{
 "title": "JuiceFS Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "name",
    "query": {
     "query": "label_values(juicefs_uptime, vol_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sort(max(juicefs_uptime{vol_name=\"$name\"}) by (instance, juicefs_version))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(juicefs_used_space{vol_name=\"$name\"})",
     "legendFormat": "Data Size"
    }
   ]
  },
  {
   "title": "Files",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(juicefs_used_inodes{vol_name=\"$name\"})",
     "legendFormat": "Files"
    }
   ]
  },
  {
   "title": "Client Sessions",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count by (juicefs_version) (juicefs_uptime{vol_name=\"$name\"})",
     "legendFormat": "{{juicefs_version}}"
    }
   ]
  },
  {
   "title": "Operations",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(juicefs_fuse_ops_durations_histogram_seconds_count{vol_name=\"$name\"}[$__rate_interval]) < 5000000000) by (instance)",
     "legendFormat": "Ops {{instance}}"
    }
   ]
  },
  {
   "title": "IO Throughput",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(juicefs_fuse_written_size_bytes_sum{vol_name=\"$name\"}[$__rate_interval]) < 5000000000) by (instance)",
     "legendFormat": "Write {{instance}}"
    },
    {
     "expr": "sum(rate(juicefs_fuse_read_size_bytes_sum{vol_name=\"$name\"}[$__rate_interval]) < 5000000000) by (instance)",
     "legendFormat": "Read {{instance}}"
    }
   ]
  },
  {
   "title": "IO Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "sum(rate(juicefs_fuse_ops_durations_histogram_seconds_sum{vol_name=\"$name\"}[$__rate_interval])) by  (instance,mp) * 1000000 / sum(rate(juicefs_fuse_ops_durations_histogram_seconds_count{vol_name=\"$name\"}[$__rate_interval])) by  (instance,mp)",
     "legendFormat": "{{instance}}:{{mp}}"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(juicefs_transaction_durations_histogram_seconds_count{vol_name=\"$name\"}[$__rate_interval])) by  (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Transaction Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "sum(rate(juicefs_transaction_durations_histogram_seconds_sum{vol_name=\"$name\"}[$__rate_interval])) by  (instance,mp) * 1000000 / sum(rate(juicefs_transaction_durations_histogram_seconds_count{vol_name=\"$name\"}[$__rate_interval])) by  (instance,mp)",
     "legendFormat": "{{instance}}:{{mp}}"
    }
   ]
  },
  {
   "title": "Transaction Restarts",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(juicefs_transaction_restart{vol_name=~\"$name\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Restarts {{instance}}"
    }
   ]
  },
  {
   "title": "Objects Requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(juicefs_object_request_durations_histogram_seconds_count{vol_name=\"$name\"}[$__rate_interval])) by  (method)",
     "legendFormat": "{{method}}"
    },
    {
     "expr": "sum(rate(juicefs_object_request_errors{vol_name=\"$name\"}[$__rate_interval])) ",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Objects Throughput",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(juicefs_object_request_data_bytes{method=\"PUT\",vol_name=\"$name\"}[$__rate_interval])) by  (instance,method)",
     "legendFormat": "{{method}} {{instance}}"
    },
    {
     "expr": "sum(rate(juicefs_object_request_data_bytes{method=\"GET\",vol_name=\"$name\"}[$__rate_interval])) by  (instance,method)",
     "legendFormat": "{{method}} {{instance}}"
    },
    {
     "expr": "sum(rate(juicefs_object_request_data_bytes{method=\"GET\",vol_name=\"$name\"}[$__rate_interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Objects Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "sum(rate(juicefs_object_request_durations_histogram_seconds_sum{vol_name=\"$name\"}[$__rate_interval])) by  (instance) * 1000000 / sum(rate(juicefs_object_request_durations_histogram_seconds_count{vol_name=\"$name\"}[$__rate_interval])) by  (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Client CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(juicefs_cpu_usage{vol_name=\"$name\"}[$__rate_interval])*100 < 1000) by (instance,mp)",
     "legendFormat": "{{instance}}:{{mp}}"
    }
   ]
  },
  {
   "title": "Client Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(juicefs_memory{vol_name=\"$name\"}) by (instance,mp)",
     "legendFormat": "{{instance}}:{{mp}}"
    }
   ]
  },
  {
   "title": "Go threads",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(juicefs_go_goroutines{vol_name=\"$name\"}) by (instance,mp)",
     "legendFormat": "{{instance}}:{{mp}}"
    }
   ]
  },
  {
   "title": "Block Cache Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(juicefs_blockcache_bytes{vol_name=\"$name\"}) by (instance,mp)",
     "legendFormat": "{{instance}}:{{mp}}"
    }
   ]
  },
  {
   "title": "Block Cache Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(juicefs_blockcache_blocks{vol_name=\"$name\"}) by (instance,mp)",
     "legendFormat": "{{instance}}:{{mp}}"
    }
   ]
  },
  {
   "title": "Block Cache Hit Ratio",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(juicefs_blockcache_hits{vol_name=\"$name\"}[$__rate_interval])) by (instance,mp) *100 / (sum(rate(juicefs_blockcache_hits{vol_name=\"$name\"}[$__rate_interval])) by (instance,mp) + sum(rate(juicefs_blockcache_miss{vol_name=\"$name\"}[$__rate_interval])) by (instance,mp))",
     "legendFormat": "Hits {{instance}}:{{mp}}"
    },
    {
     "expr": "sum(rate(juicefs_blockcache_hit_bytes{vol_name=\"$name\"}[$__rate_interval])) by (instance,mp) *100 / (sum(rate(juicefs_blockcache_hit_bytes{vol_name=\"$name\"}[$__rate_interval])) by (instance,mp) + sum(rate(juicefs_blockcache_miss_bytes{vol_name=\"$name\"}[$__rate_interval])) by (instance,mp))",
     "legendFormat": "HitBytes {{instance}}:{{mp}}"
    }
   ]
  },
  {
   "title": "Compaction",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(juicefs_compact_size_histogram_bytes_count{vol_name=\"$name\"}[$__rate_interval])) by (instance,mp)",
     "legendFormat": "{{instance}}:{{mp}}"
    }
   ]
  },
  {
   "title": "Compacted Data",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(juicefs_compact_size_histogram_bytes_sum{vol_name=\"$name\"}[$__rate_interval])) by (instance,mp)",
     "legendFormat": "{{instance}}:{{mp}}"
    }
   ]
  },
  {
   "title": "Open File Handlers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(juicefs_fuse_open_handlers{vol_name=\"$name\"}) by (instance,mp)",
     "legendFormat": "{{instance}}:{{mp}}"
    }
   ]
  },
  {
   "title": "Juicefs Staging Blocks",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "juicefs_staging_blocks{vol_name=\"$name\"}",
     "legendFormat": "{{instance}}:{{mp}}"
    }
   ]
  },
  {
   "title": "Juicefs Staging Block Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "juicefs_staging_block_bytes{vol_name=\"$name\"}",
     "legendFormat": "{{instance}}:{{mp}}"
    }
   ]
  },
  {
   "title": "Juicefs Staging Block Delay",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(juicefs_staging_block_delay_seconds{vol_name=\"$name\"}[$__rate_interval])) by (instance,mp) / sum(rate(juicefs_object_request_durations_histogram_seconds_count{vol_name=\"$name\"}[$__rate_interval])) by (instance,mp) ",
     "legendFormat": "{{instance}}:{{mp}}"
    }
   ]
  }
 ]
}