apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: "observed-genesis"
  instance: "observed"
  service: "cast-info-service"
  system: "media"
spec:
  replace_scope: "service"
  points:
    - capability: "pod_kill"
      target:
        app: "cast-info-service"
        namespace: "media"
    - capability: "pod_failure"
      target:
        app: "cast-info-service"
        namespace: "media"
    - capability: "container_kill"
      target:
        app: "cast-info-service"
        container: "cast-info-service"
        namespace: "media"
    - capability: "cpu_stress"
      target:
        app: "cast-info-service"
        container: "cast-info-service"
        namespace: "media"
    - capability: "time_skew"
      target:
        app: "cast-info-service"
        container: "cast-info-service"
        namespace: "media"
    - capability: "http_request_delay"
      target:
        app: "cast-info-service"
        method: "POST"
        namespace: "media"
        path: "/PageService/ReadPage"
        server_address: "cast-info-service"
    - capability: "http_request_abort"
      target:
        app: "cast-info-service"
        method: "POST"
        namespace: "media"
        path: "/PageService/ReadPage"
        server_address: "cast-info-service"
    - capability: "http_request_delay"
      target:
        app: "cast-info-service"
        method: "POST"
        namespace: "media"
        path: "/CastInfoService/ReadCastInfo"
        server_address: "cast-info-service"
    - capability: "http_request_abort"
      target:
        app: "cast-info-service"
        method: "POST"
        namespace: "media"
        path: "/CastInfoService/ReadCastInfo"
        server_address: "cast-info-service"
    - capability: "dns_error"
      target:
        app: "cast-info-service"
        domain_patterns:
          - "movie-info-service"
        namespace: "media"
    - capability: "dns_random"
      target:
        app: "cast-info-service"
        domain_patterns:
          - "movie-info-service"
        namespace: "media"
    - capability: "network_delay"
      target:
        namespace: "media"
        source_app: "cast-info-service"
        span_names:
          - "ReadMovieInfo"
        target_service: "movie-info-service"
    - capability: "network_loss"
      target:
        namespace: "media"
        source_app: "cast-info-service"
        span_names:
          - "ReadMovieInfo"
        target_service: "movie-info-service"
    - capability: "network_duplicate"
      target:
        namespace: "media"
        source_app: "cast-info-service"
        span_names:
          - "ReadMovieInfo"
        target_service: "movie-info-service"
    - capability: "network_corrupt"
      target:
        namespace: "media"
        source_app: "cast-info-service"
        span_names:
          - "ReadMovieInfo"
        target_service: "movie-info-service"
    - capability: "network_bandwidth"
      target:
        namespace: "media"
        source_app: "cast-info-service"
        span_names:
          - "ReadMovieInfo"
        target_service: "movie-info-service"
    - capability: "network_partition"
      target:
        namespace: "media"
        source_app: "cast-info-service"
        span_names:
          - "ReadMovieInfo"
        target_service: "movie-info-service"
    - capability: "dns_error"
      target:
        app: "cast-info-service"
        domain_patterns:
          - "plot-service"
        namespace: "media"
    - capability: "dns_random"
      target:
        app: "cast-info-service"
        domain_patterns:
          - "plot-service"
        namespace: "media"
    - capability: "network_delay"
      target:
        namespace: "media"
        source_app: "cast-info-service"
        span_names:
          - "ReadPlot"
        target_service: "plot-service"
    - capability: "network_loss"
      target:
        namespace: "media"
        source_app: "cast-info-service"
        span_names:
          - "ReadPlot"
        target_service: "plot-service"
    - capability: "network_duplicate"
      target:
        namespace: "media"
        source_app: "cast-info-service"
        span_names:
          - "ReadPlot"
        target_service: "plot-service"
    - capability: "network_corrupt"
      target:
        namespace: "media"
        source_app: "cast-info-service"
        span_names:
          - "ReadPlot"
        target_service: "plot-service"
    - capability: "network_bandwidth"
      target:
        namespace: "media"
        source_app: "cast-info-service"
        span_names:
          - "ReadPlot"
        target_service: "plot-service"
    - capability: "network_partition"
      target:
        namespace: "media"
        source_app: "cast-info-service"
        span_names:
          - "ReadPlot"
        target_service: "plot-service"
    - capability: "dns_error"
      target:
        app: "cast-info-service"
        domain_patterns:
          - "movie-review-service"
        namespace: "media"
    - capability: "dns_random"
      target:
        app: "cast-info-service"
        domain_patterns:
          - "movie-review-service"
        namespace: "media"
    - capability: "network_delay"
      target:
        namespace: "media"
        source_app: "cast-info-service"
        span_names:
          - "ReadMovieReviews"
        target_service: "movie-review-service"
    - capability: "network_loss"
      target:
        namespace: "media"
        source_app: "cast-info-service"
        span_names:
          - "ReadMovieReviews"
        target_service: "movie-review-service"
    - capability: "network_duplicate"
      target:
        namespace: "media"
        source_app: "cast-info-service"
        span_names:
          - "ReadMovieReviews"
        target_service: "movie-review-service"
    - capability: "network_corrupt"
      target:
        namespace: "media"
        source_app: "cast-info-service"
        span_names:
          - "ReadMovieReviews"
        target_service: "movie-review-service"
    - capability: "network_bandwidth"
      target:
        namespace: "media"
        source_app: "cast-info-service"
        span_names:
          - "ReadMovieReviews"
        target_service: "movie-review-service"
    - capability: "network_partition"
      target:
        namespace: "media"
        source_app: "cast-info-service"
        span_names:
          - "ReadMovieReviews"
        target_service: "movie-review-service"
