version: 1
metadata:
  name: aegis OIDC provider
entries:
  - model: authentik_providers_oauth2.scopemapping
    id: aegis-claims
    attrs:
      name: "aegis-claims"
      scope_name: "aegis"
      expression: |
        user = request.user
        attrs = user.attributes
        groups = [g.name for g in user.ak_groups.all()]
        return {
            "aegis_user_id": attrs.get("aegis_user_id", 0),
            "groups": groups,
        }
