apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: "seed-genesis"
  instance: "seed"
  service: "catalog"
  system: "sockshop"
spec:
  replace_scope: "service"
  points:
    - capability: "container_kill"
      target:
        app: "catalog"
        container: "catalog"
        namespace: "sock-shop"
    - capability: "cpu_stress"
      target:
        app: "catalog"
        container: "catalog"
        namespace: "sock-shop"
    - capability: "http_request_abort"
      target:
        app: "catalog"
        method: "GET"
        namespace: "sock-shop"
        path: "/"
        port: 8079
    - capability: "http_request_delay"
      target:
        app: "catalog"
        method: "GET"
        namespace: "sock-shop"
        path: "/"
        port: 8079
    - capability: "jvm_method_latency"
      target:
        app: "catalog"
        class: "com.oracle.coherence.examples.sockshop.helidon.catalog.Application"
        method: "main"
        namespace: "sock-shop"
    - capability: "jvm_method_latency"
      target:
        app: "catalog"
        class: "com.oracle.coherence.examples.sockshop.helidon.catalog.CatalogResource.Count"
        method: "Count"
        namespace: "sock-shop"
    - capability: "jvm_method_latency"
      target:
        app: "catalog"
        class: "com.oracle.coherence.examples.sockshop.helidon.catalog.CatalogResource"
        method: "getImage"
        namespace: "sock-shop"
    - capability: "jvm_method_latency"
      target:
        app: "catalog"
        class: "com.oracle.coherence.examples.sockshop.helidon.catalog.CatalogResource"
        method: "getSock"
        namespace: "sock-shop"
    - capability: "jvm_method_latency"
      target:
        app: "catalog"
        class: "com.oracle.coherence.examples.sockshop.helidon.catalog.CatalogResource"
        method: "getSockCount"
        namespace: "sock-shop"
    - capability: "jvm_method_latency"
      target:
        app: "catalog"
        class: "com.oracle.coherence.examples.sockshop.helidon.catalog.CatalogResource"
        method: "getSocks"
        namespace: "sock-shop"
    - capability: "jvm_method_latency"
      target:
        app: "catalog"
        class: "com.oracle.coherence.examples.sockshop.helidon.catalog.CatalogResourceIT"
        method: "setup"
        namespace: "sock-shop"
    - capability: "jvm_method_latency"
      target:
        app: "catalog"
        class: "com.oracle.coherence.examples.sockshop.helidon.catalog.CatalogResourceIT"
        method: "startServer"
        namespace: "sock-shop"
    - capability: "jvm_method_latency"
      target:
        app: "catalog"
        class: "com.oracle.coherence.examples.sockshop.helidon.catalog.CatalogResourceIT"
        method: "stopServer"
        namespace: "sock-shop"
    - capability: "jvm_method_latency"
      target:
        app: "catalog"
        class: "com.oracle.coherence.examples.sockshop.helidon.catalog.CatalogResourceIT"
        method: "testGetById"
        namespace: "sock-shop"
    - capability: "jvm_method_latency"
      target:
        app: "catalog"
        class: "com.oracle.coherence.examples.sockshop.helidon.catalog.CatalogResourceIT"
        method: "testGetByMissingId"
        namespace: "sock-shop"
    - capability: "jvm_method_latency"
      target:
        app: "catalog"
        class: "com.oracle.coherence.examples.sockshop.helidon.catalog.CatalogResourceIT"
        method: "testGetImage"
        namespace: "sock-shop"
    - capability: "jvm_method_latency"
      target:
        app: "catalog"
        class: "com.oracle.coherence.examples.sockshop.helidon.catalog.CatalogResourceIT"
        method: "testGetMissingImage"
        namespace: "sock-shop"
    - capability: "jvm_method_latency"
      target:
        app: "catalog"
        class: "com.oracle.coherence.examples.sockshop.helidon.catalog.CatalogResourceIT"
        method: "testGetTags"
        namespace: "sock-shop"
    - capability: "jvm_method_latency"
      target:
        app: "catalog"
        class: "com.oracle.coherence.examples.sockshop.helidon.catalog.CatalogResourceIT"
        method: "testQueryPaging"
        namespace: "sock-shop"
    - capability: "jvm_method_latency"
      target:
        app: "catalog"
        class: "com.oracle.coherence.examples.sockshop.helidon.catalog.CatalogResourceIT"
        method: "testQueryWithFilter"
        namespace: "sock-shop"
    - capability: "jvm_method_latency"
      target:
        app: "catalog"
        class: "com.oracle.coherence.examples.sockshop.helidon.catalog.CatalogResourceIT"
        method: "testQueryWithoutFilter"
        namespace: "sock-shop"
    - capability: "jvm_method_latency"
      target:
        app: "catalog"
        class: "com.oracle.coherence.examples.sockshop.helidon.catalog.CatalogResourceIT"
        method: "testSockCountWithFilter"
        namespace: "sock-shop"
    - capability: "jvm_method_latency"
      target:
        app: "catalog"
        class: "com.oracle.coherence.examples.sockshop.helidon.catalog.CatalogResourceIT"
        method: "testSockCountWithoutFilter"
        namespace: "sock-shop"
    - capability: "jvm_method_latency"
      target:
        app: "catalog"
        class: "com.oracle.coherence.examples.sockshop.helidon.catalog.CoherenceCatalogRepository"
        method: "CoherenceCatalogRepository"
        namespace: "sock-shop"
    - capability: "jvm_method_latency"
      target:
        app: "catalog"
        class: "com.oracle.coherence.examples.sockshop.helidon.catalog.CoherenceCatalogRepository"
        method: "createTagsFilter"
        namespace: "sock-shop"
    - capability: "jvm_method_latency"
      target:
        app: "catalog"
        class: "com.oracle.coherence.examples.sockshop.helidon.catalog.CoherenceCatalogRepository"
        method: "getActualTypeArguments"
        namespace: "sock-shop"
    - capability: "jvm_method_latency"
      target:
        app: "catalog"
        class: "com.oracle.coherence.examples.sockshop.helidon.catalog.CoherenceCatalogRepository"
        method: "getOwnerType"
        namespace: "sock-shop"
    - capability: "jvm_method_latency"
      target:
        app: "catalog"
        class: "com.oracle.coherence.examples.sockshop.helidon.catalog.CoherenceCatalogRepository"
        method: "getRawType"
        namespace: "sock-shop"
    - capability: "jvm_method_latency"
      target:
        app: "catalog"
        class: "com.oracle.coherence.examples.sockshop.helidon.catalog.CoherenceCatalogRepository"
        method: "getSock"
        namespace: "sock-shop"
    - capability: "jvm_method_latency"
      target:
        app: "catalog"
        class: "com.oracle.coherence.examples.sockshop.helidon.catalog.CoherenceCatalogRepository"
        method: "getSockCount"
        namespace: "sock-shop"
    - capability: "jvm_method_latency"
      target:
        app: "catalog"
        class: "com.oracle.coherence.examples.sockshop.helidon.catalog.CoherenceCatalogRepository"
        method: "getSocks"
        namespace: "sock-shop"
    - capability: "jvm_method_latency"
      target:
        app: "catalog"
        class: "com.oracle.coherence.examples.sockshop.helidon.catalog.CoherenceCatalogRepository"
        method: "getTags"
        namespace: "sock-shop"
    - capability: "jvm_method_latency"
      target:
        app: "catalog"
        class: "com.oracle.coherence.examples.sockshop.helidon.catalog.CoherenceCatalogRepository"
        method: "init"
        namespace: "sock-shop"
    - capability: "jvm_method_latency"
      target:
        app: "catalog"
        class: "com.oracle.coherence.examples.sockshop.helidon.catalog.CoherenceCatalogRepository"
        method: "loadData"
        namespace: "sock-shop"
    - capability: "jvm_method_latency"
      target:
        app: "catalog"
        class: "com.oracle.coherence.examples.sockshop.helidon.catalog.CoherenceCatalogRepository"
        method: "loadSocksFromJson"
        namespace: "sock-shop"
    - capability: "jvm_method_latency"
      target:
        app: "catalog"
        class: "com.oracle.coherence.examples.sockshop.helidon.catalog.CoherenceCatalogRepositoryIT"
        method: "getCatalogRepository"
        namespace: "sock-shop"
    - capability: "jvm_method_latency"
      target:
        app: "catalog"
        class: "com.oracle.coherence.examples.sockshop.helidon.catalog.CoherenceCatalogRepositoryIT"
        method: "startServer"
        namespace: "sock-shop"
    - capability: "jvm_method_latency"
      target:
        app: "catalog"
        class: "com.oracle.coherence.examples.sockshop.helidon.catalog.CoherenceCatalogRepositoryIT"
        method: "stopServer"
        namespace: "sock-shop"
    - capability: "jvm_method_latency"
      target:
        app: "catalog"
        class: "com.oracle.coherence.examples.sockshop.helidon.catalog.CorsFilter"
        method: "filter"
        namespace: "sock-shop"
    - capability: "jvm_method_latency"
      target:
        app: "catalog"
        class: "com.oracle.coherence.examples.sockshop.helidon.catalog.MetricsIT"
        method: "setup"
        namespace: "sock-shop"
    - capability: "jvm_method_latency"
      target:
        app: "catalog"
        class: "com.oracle.coherence.examples.sockshop.helidon.catalog.MetricsIT"
        method: "startServer"
        namespace: "sock-shop"
    - capability: "jvm_method_latency"
      target:
        app: "catalog"
        class: "com.oracle.coherence.examples.sockshop.helidon.catalog.MetricsIT"
        method: "stopServer"
        namespace: "sock-shop"
    - capability: "jvm_method_latency"
      target:
        app: "catalog"
        class: "com.oracle.coherence.examples.sockshop.helidon.catalog.MetricsIT"
        method: "testAddItem"
        namespace: "sock-shop"
    - capability: "jvm_method_latency"
      target:
        app: "catalog"
        class: "com.oracle.coherence.examples.sockshop.helidon.catalog.OpenTelemetryMdcTurboFilter"
        method: "decide"
        namespace: "sock-shop"
    - capability: "jvm_method_latency"
      target:
        app: "catalog"
        class: "com.oracle.coherence.examples.sockshop.helidon.catalog.TagsResource.Tags"
        method: "Tags"
        namespace: "sock-shop"
    - capability: "jvm_method_latency"
      target:
        app: "catalog"
        class: "com.oracle.coherence.examples.sockshop.helidon.catalog.TagsResource"
        method: "getTags"
        namespace: "sock-shop"
    - capability: "memory_stress"
      target:
        app: "catalog"
        container: "catalog"
        namespace: "sock-shop"
    - capability: "pod_failure"
      target:
        app: "catalog"
        namespace: "sock-shop"
    - capability: "pod_kill"
      target:
        app: "catalog"
        namespace: "sock-shop"
    - capability: "time_skew"
      target:
        app: "catalog"
        container: "catalog"
        namespace: "sock-shop"
