apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: "seed-genesis"
  instance: "seed"
  service: "front-end"
  system: "sockshop"
spec:
  replace_scope: "service"
  points:
    - capability: "container_kill"
      target:
        app: "front-end"
        container: "front-end"
        namespace: "sockshop"
    - capability: "cpu_stress"
      target:
        app: "front-end"
        container: "front-end"
        namespace: "sockshop"
    - capability: "http_request_abort"
      target:
        app: "front-end"
        method: "DELETE"
        namespace: "sockshop"
        path: "/cart"
        port: 8079
    - capability: "http_request_abort"
      target:
        app: "front-end"
        method: "DELETE"
        namespace: "sockshop"
        path: "/carts/*"
        port: 80
    - capability: "http_request_abort"
      target:
        app: "front-end"
        method: "GET"
        namespace: "sockshop"
        path: "/"
        port: 8079
    - capability: "http_request_abort"
      target:
        app: "front-end"
        method: "GET"
        namespace: "sockshop"
        path: "/basket.html"
        port: 8079
    - capability: "http_request_abort"
      target:
        app: "front-end"
        method: "GET"
        namespace: "sockshop"
        path: "/cart"
        port: 8079
    - capability: "http_request_abort"
      target:
        app: "front-end"
        method: "GET"
        namespace: "sockshop"
        path: "/carts/*/items"
        port: 80
    - capability: "http_request_abort"
      target:
        app: "front-end"
        method: "GET"
        namespace: "sockshop"
        path: "/carts/*/merge"
        port: 80
    - capability: "http_request_abort"
      target:
        app: "front-end"
        method: "GET"
        namespace: "sockshop"
        path: "/catalogue*"
        port: 80
    - capability: "http_request_abort"
      target:
        app: "front-end"
        method: "GET"
        namespace: "sockshop"
        path: "/catalogue/*"
        port: 80
    - capability: "http_request_abort"
      target:
        app: "front-end"
        method: "GET"
        namespace: "sockshop"
        path: "/catalogue/images*"
        port: 80
    - capability: "http_request_abort"
      target:
        app: "front-end"
        method: "GET"
        namespace: "sockshop"
        path: "/catalogue/images/WAT.jpg"
        port: 80
    - capability: "http_request_abort"
      target:
        app: "front-end"
        method: "GET"
        namespace: "sockshop"
        path: "/catalogue/images/bit_of_leg_1.jpeg"
        port: 80
    - capability: "http_request_abort"
      target:
        app: "front-end"
        method: "GET"
        namespace: "sockshop"
        path: "/catalogue/images/catsocks.jpg"
        port: 80
    - capability: "http_request_abort"
      target:
        app: "front-end"
        method: "GET"
        namespace: "sockshop"
        path: "/catalogue/images/classic.jpg"
        port: 80
    - capability: "http_request_abort"
      target:
        app: "front-end"
        method: "GET"
        namespace: "sockshop"
        path: "/catalogue/images/colourful_socks.jpg"
        port: 80
    - capability: "http_request_abort"
      target:
        app: "front-end"
        method: "GET"
        namespace: "sockshop"
        path: "/catalogue/images/cross_1.jpeg"
        port: 80
    - capability: "http_request_abort"
      target:
        app: "front-end"
        method: "GET"
        namespace: "sockshop"
        path: "/catalogue/images/holy_1.jpeg"
        port: 80
    - capability: "http_request_abort"
      target:
        app: "front-end"
        method: "GET"
        namespace: "sockshop"
        path: "/catalogue/images/puma_1.jpeg"
        port: 80
    - capability: "http_request_abort"
      target:
        app: "front-end"
        method: "GET"
        namespace: "sockshop"
        path: "/catalogue/images/youtube_1.jpeg"
        port: 80
    - capability: "http_request_abort"
      target:
        app: "front-end"
        method: "GET"
        namespace: "sockshop"
        path: "/catalogue"
        port: 80
    - capability: "http_request_abort"
      target:
        app: "front-end"
        method: "GET"
        namespace: "sockshop"
        path: "/category.html"
        port: 8079
    - capability: "http_request_abort"
      target:
        app: "front-end"
        method: "GET"
        namespace: "sockshop"
        path: "/customers/*/addresses"
        port: 8079
    - capability: "http_request_abort"
      target:
        app: "front-end"
        method: "GET"
        namespace: "sockshop"
        path: "/customers/*/cards"
        port: 8079
    - capability: "http_request_abort"
      target:
        app: "front-end"
        method: "GET"
        namespace: "sockshop"
        path: "/customers/*"
        port: 8079
    - capability: "http_request_abort"
      target:
        app: "front-end"
        method: "GET"
        namespace: "sockshop"
        path: "/detail.html"
        port: 8079
    - capability: "http_request_abort"
      target:
        app: "front-end"
        method: "GET"
        namespace: "sockshop"
        path: "/login"
        port: 8079
    - capability: "http_request_abort"
      target:
        app: "front-end"
        method: "POST"
        namespace: "sockshop"
        path: "/addresses"
        port: 8079
    - capability: "http_request_abort"
      target:
        app: "front-end"
        method: "POST"
        namespace: "sockshop"
        path: "/cards"
        port: 8079
    - capability: "http_request_abort"
      target:
        app: "front-end"
        method: "POST"
        namespace: "sockshop"
        path: "/cart"
        port: 8079
    - capability: "http_request_abort"
      target:
        app: "front-end"
        method: "POST"
        namespace: "sockshop"
        path: "/carts/*/items"
        port: 80
    - capability: "http_request_abort"
      target:
        app: "front-end"
        method: "POST"
        namespace: "sockshop"
        path: "/orders"
        port: 80
    - capability: "http_request_delay"
      target:
        app: "front-end"
        method: "DELETE"
        namespace: "sockshop"
        path: "/cart"
        port: 8079
    - capability: "http_request_delay"
      target:
        app: "front-end"
        method: "DELETE"
        namespace: "sockshop"
        path: "/carts/*"
        port: 80
    - capability: "http_request_delay"
      target:
        app: "front-end"
        method: "GET"
        namespace: "sockshop"
        path: "/"
        port: 8079
    - capability: "http_request_delay"
      target:
        app: "front-end"
        method: "GET"
        namespace: "sockshop"
        path: "/basket.html"
        port: 8079
    - capability: "http_request_delay"
      target:
        app: "front-end"
        method: "GET"
        namespace: "sockshop"
        path: "/cart"
        port: 8079
    - capability: "http_request_delay"
      target:
        app: "front-end"
        method: "GET"
        namespace: "sockshop"
        path: "/carts/*/items"
        port: 80
    - capability: "http_request_delay"
      target:
        app: "front-end"
        method: "GET"
        namespace: "sockshop"
        path: "/carts/*/merge"
        port: 80
    - capability: "http_request_delay"
      target:
        app: "front-end"
        method: "GET"
        namespace: "sockshop"
        path: "/catalogue*"
        port: 80
    - capability: "http_request_delay"
      target:
        app: "front-end"
        method: "GET"
        namespace: "sockshop"
        path: "/catalogue/*"
        port: 80
    - capability: "http_request_delay"
      target:
        app: "front-end"
        method: "GET"
        namespace: "sockshop"
        path: "/catalogue/images*"
        port: 80
    - capability: "http_request_delay"
      target:
        app: "front-end"
        method: "GET"
        namespace: "sockshop"
        path: "/catalogue/images/WAT.jpg"
        port: 80
    - capability: "http_request_delay"
      target:
        app: "front-end"
        method: "GET"
        namespace: "sockshop"
        path: "/catalogue/images/bit_of_leg_1.jpeg"
        port: 80
    - capability: "http_request_delay"
      target:
        app: "front-end"
        method: "GET"
        namespace: "sockshop"
        path: "/catalogue/images/catsocks.jpg"
        port: 80
    - capability: "http_request_delay"
      target:
        app: "front-end"
        method: "GET"
        namespace: "sockshop"
        path: "/catalogue/images/classic.jpg"
        port: 80
    - capability: "http_request_delay"
      target:
        app: "front-end"
        method: "GET"
        namespace: "sockshop"
        path: "/catalogue/images/colourful_socks.jpg"
        port: 80
    - capability: "http_request_delay"
      target:
        app: "front-end"
        method: "GET"
        namespace: "sockshop"
        path: "/catalogue/images/cross_1.jpeg"
        port: 80
    - capability: "http_request_delay"
      target:
        app: "front-end"
        method: "GET"
        namespace: "sockshop"
        path: "/catalogue/images/holy_1.jpeg"
        port: 80
    - capability: "http_request_delay"
      target:
        app: "front-end"
        method: "GET"
        namespace: "sockshop"
        path: "/catalogue/images/puma_1.jpeg"
        port: 80
    - capability: "http_request_delay"
      target:
        app: "front-end"
        method: "GET"
        namespace: "sockshop"
        path: "/catalogue/images/youtube_1.jpeg"
        port: 80
    - capability: "http_request_delay"
      target:
        app: "front-end"
        method: "GET"
        namespace: "sockshop"
        path: "/catalogue"
        port: 80
    - capability: "http_request_delay"
      target:
        app: "front-end"
        method: "GET"
        namespace: "sockshop"
        path: "/category.html"
        port: 8079
    - capability: "http_request_delay"
      target:
        app: "front-end"
        method: "GET"
        namespace: "sockshop"
        path: "/customers/*/addresses"
        port: 8079
    - capability: "http_request_delay"
      target:
        app: "front-end"
        method: "GET"
        namespace: "sockshop"
        path: "/customers/*/cards"
        port: 8079
    - capability: "http_request_delay"
      target:
        app: "front-end"
        method: "GET"
        namespace: "sockshop"
        path: "/customers/*"
        port: 8079
    - capability: "http_request_delay"
      target:
        app: "front-end"
        method: "GET"
        namespace: "sockshop"
        path: "/detail.html"
        port: 8079
    - capability: "http_request_delay"
      target:
        app: "front-end"
        method: "GET"
        namespace: "sockshop"
        path: "/login"
        port: 8079
    - capability: "http_request_delay"
      target:
        app: "front-end"
        method: "POST"
        namespace: "sockshop"
        path: "/addresses"
        port: 8079
    - capability: "http_request_delay"
      target:
        app: "front-end"
        method: "POST"
        namespace: "sockshop"
        path: "/cards"
        port: 8079
    - capability: "http_request_delay"
      target:
        app: "front-end"
        method: "POST"
        namespace: "sockshop"
        path: "/cart"
        port: 8079
    - capability: "http_request_delay"
      target:
        app: "front-end"
        method: "POST"
        namespace: "sockshop"
        path: "/carts/*/items"
        port: 80
    - capability: "http_request_delay"
      target:
        app: "front-end"
        method: "POST"
        namespace: "sockshop"
        path: "/orders"
        port: 80
    - capability: "memory_stress"
      target:
        app: "front-end"
        container: "front-end"
        namespace: "sockshop"
    - capability: "pod_failure"
      target:
        app: "front-end"
        namespace: "sockshop"
    - capability: "pod_kill"
      target:
        app: "front-end"
        namespace: "sockshop"
    - capability: "time_skew"
      target:
        app: "front-end"
        container: "front-end"
        namespace: "sockshop"
