apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: seed-genesis
  instance: seed
  service: orders
  system: sockshop
spec:
  points:
  - capability: http_request_replace_method
    target:
      app: orders
      method: GET
      namespace: sockshop
      path: /
      port: 8079
  - capability: http_request_replace_path
    target:
      app: orders
      method: GET
      namespace: sockshop
      path: /
      port: 8079
  - capability: http_response_abort
    target:
      app: orders
      method: GET
      namespace: sockshop
      path: /
      port: 8079
  - capability: http_response_delay
    target:
      app: orders
      method: GET
      namespace: sockshop
      path: /
      port: 8079
  - capability: http_response_patch_body
    target:
      app: orders
      method: GET
      namespace: sockshop
      path: /
      port: 8079
  - capability: http_response_replace_body
    target:
      app: orders
      method: GET
      namespace: sockshop
      path: /
      port: 8079
  - capability: http_response_replace_code
    target:
      app: orders
      method: GET
      namespace: sockshop
      path: /
      port: 8079
  replace_scope: service
