apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: "seed-genesis"
  instance: "seed"
  service: "shipping"
  system: "sockshop"
spec:
  replace_scope: "service"
  points:
    - capability: "container_kill"
      target:
        app: "shipping"
        container: "shipping"
        namespace: "sock-shop"
    - capability: "cpu_stress"
      target:
        app: "shipping"
        container: "shipping"
        namespace: "sock-shop"
    - capability: "http_request_abort"
      target:
        app: "shipping"
        method: "GET"
        namespace: "sock-shop"
        path: "/"
        port: 8079
    - capability: "http_request_delay"
      target:
        app: "shipping"
        method: "GET"
        namespace: "sock-shop"
        path: "/"
        port: 8079
    - capability: "jvm_method_latency"
      target:
        app: "shipping"
        class: "com.oracle.coherence.examples.sockshop.helidon.shipping.Address"
        method: "Address"
        namespace: "sock-shop"
    - capability: "jvm_method_latency"
      target:
        app: "shipping"
        class: "com.oracle.coherence.examples.sockshop.helidon.shipping.Application"
        method: "main"
        namespace: "sock-shop"
    - capability: "jvm_method_latency"
      target:
        app: "shipping"
        class: "com.oracle.coherence.examples.sockshop.helidon.shipping.CoherenceShipmentRepository"
        method: "CoherenceShipmentRepository"
        namespace: "sock-shop"
    - capability: "jvm_method_latency"
      target:
        app: "shipping"
        class: "com.oracle.coherence.examples.sockshop.helidon.shipping.CoherenceShipmentRepository"
        method: "getShipment"
        namespace: "sock-shop"
    - capability: "jvm_method_latency"
      target:
        app: "shipping"
        class: "com.oracle.coherence.examples.sockshop.helidon.shipping.CoherenceShipmentRepository"
        method: "saveShipment"
        namespace: "sock-shop"
    - capability: "jvm_method_latency"
      target:
        app: "shipping"
        class: "com.oracle.coherence.examples.sockshop.helidon.shipping.CoherenceShipmentRepositoryIT"
        method: "getShipmentRepository"
        namespace: "sock-shop"
    - capability: "jvm_method_latency"
      target:
        app: "shipping"
        class: "com.oracle.coherence.examples.sockshop.helidon.shipping.CoherenceShipmentRepositoryIT"
        method: "startServer"
        namespace: "sock-shop"
    - capability: "jvm_method_latency"
      target:
        app: "shipping"
        class: "com.oracle.coherence.examples.sockshop.helidon.shipping.CoherenceShipmentRepositoryIT"
        method: "stopServer"
        namespace: "sock-shop"
    - capability: "jvm_method_latency"
      target:
        app: "shipping"
        class: "com.oracle.coherence.examples.sockshop.helidon.shipping.CorsFilter"
        method: "filter"
        namespace: "sock-shop"
    - capability: "jvm_method_latency"
      target:
        app: "shipping"
        class: "com.oracle.coherence.examples.sockshop.helidon.shipping.JsonbMarshaller.Supplier"
        method: "get"
        namespace: "sock-shop"
    - capability: "jvm_method_latency"
      target:
        app: "shipping"
        class: "com.oracle.coherence.examples.sockshop.helidon.shipping.JsonbMarshaller"
        method: "JsonbMarshaller"
        namespace: "sock-shop"
    - capability: "jvm_method_latency"
      target:
        app: "shipping"
        class: "com.oracle.coherence.examples.sockshop.helidon.shipping.JsonbMarshaller"
        method: "parse"
        namespace: "sock-shop"
    - capability: "jvm_method_latency"
      target:
        app: "shipping"
        class: "com.oracle.coherence.examples.sockshop.helidon.shipping.JsonbMarshaller"
        method: "stream"
        namespace: "sock-shop"
    - capability: "jvm_method_latency"
      target:
        app: "shipping"
        class: "com.oracle.coherence.examples.sockshop.helidon.shipping.MetricsIT"
        method: "setup"
        namespace: "sock-shop"
    - capability: "jvm_method_latency"
      target:
        app: "shipping"
        class: "com.oracle.coherence.examples.sockshop.helidon.shipping.MetricsIT"
        method: "startServer"
        namespace: "sock-shop"
    - capability: "jvm_method_latency"
      target:
        app: "shipping"
        class: "com.oracle.coherence.examples.sockshop.helidon.shipping.MetricsIT"
        method: "stopServer"
        namespace: "sock-shop"
    - capability: "jvm_method_latency"
      target:
        app: "shipping"
        class: "com.oracle.coherence.examples.sockshop.helidon.shipping.MetricsIT"
        method: "testFedEx"
        namespace: "sock-shop"
    - capability: "jvm_method_latency"
      target:
        app: "shipping"
        class: "com.oracle.coherence.examples.sockshop.helidon.shipping.OpenTelemetryMdcTurboFilter"
        method: "decide"
        namespace: "sock-shop"
    - capability: "jvm_method_latency"
      target:
        app: "shipping"
        class: "com.oracle.coherence.examples.sockshop.helidon.shipping.Shipment"
        method: "Shipment"
        namespace: "sock-shop"
    - capability: "jvm_method_latency"
      target:
        app: "shipping"
        class: "com.oracle.coherence.examples.sockshop.helidon.shipping.ShippingRequest"
        method: "ShippingRequest"
        namespace: "sock-shop"
    - capability: "jvm_method_latency"
      target:
        app: "shipping"
        class: "com.oracle.coherence.examples.sockshop.helidon.shipping.ShippingResource"
        method: "contains"
        namespace: "sock-shop"
    - capability: "jvm_method_latency"
      target:
        app: "shipping"
        class: "com.oracle.coherence.examples.sockshop.helidon.shipping.ShippingResource"
        method: "get"
        namespace: "sock-shop"
    - capability: "jvm_method_latency"
      target:
        app: "shipping"
        class: "com.oracle.coherence.examples.sockshop.helidon.shipping.ShippingResource"
        method: "getAll"
        namespace: "sock-shop"
    - capability: "jvm_method_latency"
      target:
        app: "shipping"
        class: "com.oracle.coherence.examples.sockshop.helidon.shipping.ShippingResource"
        method: "getShipmentByOrderId"
        namespace: "sock-shop"
    - capability: "jvm_method_latency"
      target:
        app: "shipping"
        class: "com.oracle.coherence.examples.sockshop.helidon.shipping.ShippingResource"
        method: "keys"
        namespace: "sock-shop"
    - capability: "jvm_method_latency"
      target:
        app: "shipping"
        class: "com.oracle.coherence.examples.sockshop.helidon.shipping.ShippingResource"
        method: "ship"
        namespace: "sock-shop"
    - capability: "jvm_method_latency"
      target:
        app: "shipping"
        class: "com.oracle.coherence.examples.sockshop.helidon.shipping.ShippingResourceIT"
        method: "setup"
        namespace: "sock-shop"
    - capability: "jvm_method_latency"
      target:
        app: "shipping"
        class: "com.oracle.coherence.examples.sockshop.helidon.shipping.ShippingResourceIT"
        method: "startServer"
        namespace: "sock-shop"
    - capability: "jvm_method_latency"
      target:
        app: "shipping"
        class: "com.oracle.coherence.examples.sockshop.helidon.shipping.ShippingResourceIT"
        method: "stopServer"
        namespace: "sock-shop"
    - capability: "jvm_method_latency"
      target:
        app: "shipping"
        class: "com.oracle.coherence.examples.sockshop.helidon.shipping.ShippingResourceIT"
        method: "testFedEx"
        namespace: "sock-shop"
    - capability: "jvm_method_latency"
      target:
        app: "shipping"
        class: "com.oracle.coherence.examples.sockshop.helidon.shipping.ShippingResourceIT"
        method: "testGetShipmentByOrder"
        namespace: "sock-shop"
    - capability: "jvm_method_latency"
      target:
        app: "shipping"
        class: "com.oracle.coherence.examples.sockshop.helidon.shipping.ShippingResourceIT"
        method: "testUPS"
        namespace: "sock-shop"
    - capability: "jvm_method_latency"
      target:
        app: "shipping"
        class: "com.oracle.coherence.examples.sockshop.helidon.shipping.ShippingResourceIT"
        method: "testUSPS"
        namespace: "sock-shop"
    - capability: "jvm_method_latency"
      target:
        app: "shipping"
        class: "com.oracle.coherence.examples.sockshop.helidon.shipping.TestCoherenceShipmentRepository"
        method: "TestCoherenceShipmentRepository"
        namespace: "sock-shop"
    - capability: "jvm_method_latency"
      target:
        app: "shipping"
        class: "com.oracle.coherence.examples.sockshop.helidon.shipping.TestCoherenceShipmentRepository"
        method: "clear"
        namespace: "sock-shop"
    - capability: "jvm_method_latency"
      target:
        app: "shipping"
        class: "com.oracle.coherence.examples.sockshop.helidon.shipping.TestDataFactory"
        method: "address"
        namespace: "sock-shop"
    - capability: "jvm_method_latency"
      target:
        app: "shipping"
        class: "com.oracle.coherence.examples.sockshop.helidon.shipping.TestDataFactory"
        method: "shipment"
        namespace: "sock-shop"
    - capability: "jvm_method_latency"
      target:
        app: "shipping"
        class: "com.oracle.coherence.examples.sockshop.helidon.shipping.TestDataFactory"
        method: "shippingRequest"
        namespace: "sock-shop"
    - capability: "memory_stress"
      target:
        app: "shipping"
        container: "shipping"
        namespace: "sock-shop"
    - capability: "pod_failure"
      target:
        app: "shipping"
        namespace: "sock-shop"
    - capability: "pod_kill"
      target:
        app: "shipping"
        namespace: "sock-shop"
    - capability: "time_skew"
      target:
        app: "shipping"
        container: "shipping"
        namespace: "sock-shop"
