apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: seed-genesis
  instance: seed
  service: shipping
  system: sockshop
spec:
  points:
  - capability: dns_error
    target:
      app: shipping
      domain_patterns:
      - front-end
      namespace: sockshop
  - capability: dns_random
    target:
      app: shipping
      domain_patterns:
      - front-end
      namespace: sockshop
  replace_scope: service
