apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: seed-genesis
  instance: seed
  service: adservice
  system: ob
spec:
  points:
  - capability: jvm_cpu_stress
    target:
      app: adservice
      class: hipstershop.AdService.AdServiceImpl
      method: getAds
      namespace: ob
  - capability: jvm_cpu_stress
    target:
      app: adservice
      class: hipstershop.AdService
      method: blockUntilShutdown
      namespace: ob
  - capability: jvm_cpu_stress
    target:
      app: adservice
      class: hipstershop.AdService
      method: createAdsMap
      namespace: ob
  - capability: jvm_cpu_stress
    target:
      app: adservice
      class: hipstershop.AdService
      method: getAdsByCategory
      namespace: ob
  - capability: jvm_cpu_stress
    target:
      app: adservice
      class: hipstershop.AdService
      method: getInstance
      namespace: ob
  - capability: jvm_cpu_stress
    target:
      app: adservice
      class: hipstershop.AdService
      method: getRandomAds
      namespace: ob
  - capability: jvm_cpu_stress
    target:
      app: adservice
      class: hipstershop.AdService
      method: initStats
      namespace: ob
  - capability: jvm_cpu_stress
    target:
      app: adservice
      class: hipstershop.AdService
      method: initTracing
      namespace: ob
  - capability: jvm_cpu_stress
    target:
      app: adservice
      class: hipstershop.AdService
      method: main
      namespace: ob
  - capability: jvm_cpu_stress
    target:
      app: adservice
      class: hipstershop.AdService
      method: start
      namespace: ob
  - capability: jvm_cpu_stress
    target:
      app: adservice
      class: hipstershop.AdService
      method: stop
      namespace: ob
  - capability: jvm_cpu_stress
    target:
      app: adservice
      class: hipstershop.AdServiceClient
      method: AdServiceClient
      namespace: ob
  - capability: jvm_cpu_stress
    target:
      app: adservice
      class: hipstershop.AdServiceClient
      method: AdServiceClient
      namespace: ob
  - capability: jvm_cpu_stress
    target:
      app: adservice
      class: hipstershop.AdServiceClient
      method: getAds
      namespace: ob
  - capability: jvm_cpu_stress
    target:
      app: adservice
      class: hipstershop.AdServiceClient
      method: getPortOrDefaultFromArgs
      namespace: ob
  - capability: jvm_cpu_stress
    target:
      app: adservice
      class: hipstershop.AdServiceClient
      method: getStringOrDefaultFromArgs
      namespace: ob
  - capability: jvm_cpu_stress
    target:
      app: adservice
      class: hipstershop.AdServiceClient
      method: main
      namespace: ob
  - capability: jvm_cpu_stress
    target:
      app: adservice
      class: hipstershop.AdServiceClient
      method: shutdown
      namespace: ob
  - capability: jvm_memory_stress
    target:
      app: adservice
      class: hipstershop.AdService.AdServiceImpl
      method: getAds
      namespace: ob
  - capability: jvm_memory_stress
    target:
      app: adservice
      class: hipstershop.AdService
      method: blockUntilShutdown
      namespace: ob
  - capability: jvm_memory_stress
    target:
      app: adservice
      class: hipstershop.AdService
      method: createAdsMap
      namespace: ob
  - capability: jvm_memory_stress
    target:
      app: adservice
      class: hipstershop.AdService
      method: getAdsByCategory
      namespace: ob
  - capability: jvm_memory_stress
    target:
      app: adservice
      class: hipstershop.AdService
      method: getInstance
      namespace: ob
  - capability: jvm_memory_stress
    target:
      app: adservice
      class: hipstershop.AdService
      method: getRandomAds
      namespace: ob
  - capability: jvm_memory_stress
    target:
      app: adservice
      class: hipstershop.AdService
      method: initStats
      namespace: ob
  - capability: jvm_memory_stress
    target:
      app: adservice
      class: hipstershop.AdService
      method: initTracing
      namespace: ob
  - capability: jvm_memory_stress
    target:
      app: adservice
      class: hipstershop.AdService
      method: main
      namespace: ob
  - capability: jvm_memory_stress
    target:
      app: adservice
      class: hipstershop.AdService
      method: start
      namespace: ob
  - capability: jvm_memory_stress
    target:
      app: adservice
      class: hipstershop.AdService
      method: stop
      namespace: ob
  - capability: jvm_memory_stress
    target:
      app: adservice
      class: hipstershop.AdServiceClient
      method: AdServiceClient
      namespace: ob
  - capability: jvm_memory_stress
    target:
      app: adservice
      class: hipstershop.AdServiceClient
      method: AdServiceClient
      namespace: ob
  - capability: jvm_memory_stress
    target:
      app: adservice
      class: hipstershop.AdServiceClient
      method: getAds
      namespace: ob
  - capability: jvm_memory_stress
    target:
      app: adservice
      class: hipstershop.AdServiceClient
      method: getPortOrDefaultFromArgs
      namespace: ob
  - capability: jvm_memory_stress
    target:
      app: adservice
      class: hipstershop.AdServiceClient
      method: getStringOrDefaultFromArgs
      namespace: ob
  - capability: jvm_memory_stress
    target:
      app: adservice
      class: hipstershop.AdServiceClient
      method: main
      namespace: ob
  - capability: jvm_memory_stress
    target:
      app: adservice
      class: hipstershop.AdServiceClient
      method: shutdown
      namespace: ob
  - capability: jvm_method_exception
    target:
      app: adservice
      class: hipstershop.AdService.AdServiceImpl
      method: getAds
      namespace: ob
  - capability: jvm_method_exception
    target:
      app: adservice
      class: hipstershop.AdService
      method: blockUntilShutdown
      namespace: ob
  - capability: jvm_method_exception
    target:
      app: adservice
      class: hipstershop.AdService
      method: createAdsMap
      namespace: ob
  - capability: jvm_method_exception
    target:
      app: adservice
      class: hipstershop.AdService
      method: getAdsByCategory
      namespace: ob
  - capability: jvm_method_exception
    target:
      app: adservice
      class: hipstershop.AdService
      method: getInstance
      namespace: ob
  - capability: jvm_method_exception
    target:
      app: adservice
      class: hipstershop.AdService
      method: getRandomAds
      namespace: ob
  - capability: jvm_method_exception
    target:
      app: adservice
      class: hipstershop.AdService
      method: initStats
      namespace: ob
  - capability: jvm_method_exception
    target:
      app: adservice
      class: hipstershop.AdService
      method: initTracing
      namespace: ob
  - capability: jvm_method_exception
    target:
      app: adservice
      class: hipstershop.AdService
      method: main
      namespace: ob
  - capability: jvm_method_exception
    target:
      app: adservice
      class: hipstershop.AdService
      method: start
      namespace: ob
  - capability: jvm_method_exception
    target:
      app: adservice
      class: hipstershop.AdService
      method: stop
      namespace: ob
  - capability: jvm_method_exception
    target:
      app: adservice
      class: hipstershop.AdServiceClient
      method: AdServiceClient
      namespace: ob
  - capability: jvm_method_exception
    target:
      app: adservice
      class: hipstershop.AdServiceClient
      method: AdServiceClient
      namespace: ob
  - capability: jvm_method_exception
    target:
      app: adservice
      class: hipstershop.AdServiceClient
      method: getAds
      namespace: ob
  - capability: jvm_method_exception
    target:
      app: adservice
      class: hipstershop.AdServiceClient
      method: getPortOrDefaultFromArgs
      namespace: ob
  - capability: jvm_method_exception
    target:
      app: adservice
      class: hipstershop.AdServiceClient
      method: getStringOrDefaultFromArgs
      namespace: ob
  - capability: jvm_method_exception
    target:
      app: adservice
      class: hipstershop.AdServiceClient
      method: main
      namespace: ob
  - capability: jvm_method_exception
    target:
      app: adservice
      class: hipstershop.AdServiceClient
      method: shutdown
      namespace: ob
  - capability: jvm_method_return
    target:
      app: adservice
      class: hipstershop.AdService.AdServiceImpl
      method: getAds
      namespace: ob
  - capability: jvm_method_return
    target:
      app: adservice
      class: hipstershop.AdService
      method: blockUntilShutdown
      namespace: ob
  - capability: jvm_method_return
    target:
      app: adservice
      class: hipstershop.AdService
      method: createAdsMap
      namespace: ob
  - capability: jvm_method_return
    target:
      app: adservice
      class: hipstershop.AdService
      method: getAdsByCategory
      namespace: ob
  - capability: jvm_method_return
    target:
      app: adservice
      class: hipstershop.AdService
      method: getInstance
      namespace: ob
  - capability: jvm_method_return
    target:
      app: adservice
      class: hipstershop.AdService
      method: getRandomAds
      namespace: ob
  - capability: jvm_method_return
    target:
      app: adservice
      class: hipstershop.AdService
      method: initStats
      namespace: ob
  - capability: jvm_method_return
    target:
      app: adservice
      class: hipstershop.AdService
      method: initTracing
      namespace: ob
  - capability: jvm_method_return
    target:
      app: adservice
      class: hipstershop.AdService
      method: main
      namespace: ob
  - capability: jvm_method_return
    target:
      app: adservice
      class: hipstershop.AdService
      method: start
      namespace: ob
  - capability: jvm_method_return
    target:
      app: adservice
      class: hipstershop.AdService
      method: stop
      namespace: ob
  - capability: jvm_method_return
    target:
      app: adservice
      class: hipstershop.AdServiceClient
      method: AdServiceClient
      namespace: ob
  - capability: jvm_method_return
    target:
      app: adservice
      class: hipstershop.AdServiceClient
      method: AdServiceClient
      namespace: ob
  - capability: jvm_method_return
    target:
      app: adservice
      class: hipstershop.AdServiceClient
      method: getAds
      namespace: ob
  - capability: jvm_method_return
    target:
      app: adservice
      class: hipstershop.AdServiceClient
      method: getPortOrDefaultFromArgs
      namespace: ob
  - capability: jvm_method_return
    target:
      app: adservice
      class: hipstershop.AdServiceClient
      method: getStringOrDefaultFromArgs
      namespace: ob
  - capability: jvm_method_return
    target:
      app: adservice
      class: hipstershop.AdServiceClient
      method: main
      namespace: ob
  - capability: jvm_method_return
    target:
      app: adservice
      class: hipstershop.AdServiceClient
      method: shutdown
      namespace: ob
  replace_scope: service
