apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: "seed-genesis"
  instance: "seed"
  service: "emailservice"
  system: "ob"
spec:
  replace_scope: "service"
  points:
    - capability: "container_kill"
      target:
        app: "emailservice"
        container: "emailservice"
        namespace: "ob"
    - capability: "cpu_stress"
      target:
        app: "emailservice"
        container: "emailservice"
        namespace: "ob"
    - capability: "http_request_abort"
      target:
        app: "emailservice"
        method: "POST"
        namespace: "ob"
        path: "/hipstershop.EmailService/SendOrderConfirmation"
        port: 5000
        server_address: "emailservice"
        span_name: "/hipstershop.EmailService/SendOrderConfirmation"
    - capability: "http_request_delay"
      target:
        app: "emailservice"
        method: "POST"
        namespace: "ob"
        path: "/hipstershop.EmailService/SendOrderConfirmation"
        port: 5000
        server_address: "emailservice"
        span_name: "/hipstershop.EmailService/SendOrderConfirmation"
    - capability: "memory_stress"
      target:
        app: "emailservice"
        container: "emailservice"
        namespace: "ob"
    - capability: "pod_failure"
      target:
        app: "emailservice"
        namespace: "ob"
    - capability: "pod_kill"
      target:
        app: "emailservice"
        namespace: "ob"
    - capability: "time_skew"
      target:
        app: "emailservice"
        container: "emailservice"
        namespace: "ob"
