apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: "seed-genesis"
  instance: "seed"
  service: "productcatalogservice"
  system: "ob"
spec:
  replace_scope: "service"
  points:
    - capability: "container_kill"
      target:
        app: "productcatalogservice"
        container: "productcatalogservice"
        namespace: "online-boutique"
    - capability: "cpu_stress"
      target:
        app: "productcatalogservice"
        container: "productcatalogservice"
        namespace: "online-boutique"
    - capability: "http_request_abort"
      target:
        app: "productcatalogservice"
        method: "POST"
        namespace: "online-boutique"
        path: "/hipstershop.ProductCatalogService/GetProduct"
        port: 3550
    - capability: "http_request_abort"
      target:
        app: "productcatalogservice"
        method: "POST"
        namespace: "online-boutique"
        path: "/hipstershop.ProductCatalogService/ListProducts"
        port: 3550
    - capability: "http_request_delay"
      target:
        app: "productcatalogservice"
        method: "POST"
        namespace: "online-boutique"
        path: "/hipstershop.ProductCatalogService/GetProduct"
        port: 3550
    - capability: "http_request_delay"
      target:
        app: "productcatalogservice"
        method: "POST"
        namespace: "online-boutique"
        path: "/hipstershop.ProductCatalogService/ListProducts"
        port: 3550
    - capability: "memory_stress"
      target:
        app: "productcatalogservice"
        container: "productcatalogservice"
        namespace: "online-boutique"
    - capability: "pod_failure"
      target:
        app: "productcatalogservice"
        namespace: "online-boutique"
    - capability: "pod_kill"
      target:
        app: "productcatalogservice"
        namespace: "online-boutique"
    - capability: "time_skew"
      target:
        app: "productcatalogservice"
        container: "productcatalogservice"
        namespace: "online-boutique"
