apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: "seed-genesis"
  instance: "seed"
  service: "recommendationservice"
  system: "ob"
spec:
  replace_scope: "service"
  points:
    - capability: "network_bandwidth"
      target:
        namespace: "ob"
        source_app: "recommendationservice"
        target_service: "productcatalogservice"
    - capability: "network_corrupt"
      target:
        namespace: "ob"
        source_app: "recommendationservice"
        target_service: "productcatalogservice"
    - capability: "network_delay"
      target:
        namespace: "ob"
        source_app: "recommendationservice"
        target_service: "productcatalogservice"
    - capability: "network_duplicate"
      target:
        namespace: "ob"
        source_app: "recommendationservice"
        target_service: "productcatalogservice"
    - capability: "network_loss"
      target:
        namespace: "ob"
        source_app: "recommendationservice"
        target_service: "productcatalogservice"
    - capability: "network_partition"
      target:
        namespace: "ob"
        source_app: "recommendationservice"
        target_service: "productcatalogservice"
