// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/runtime/v1/runtime.proto

package runtimev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_proto_runtime_v1_runtime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runtime_v1_runtime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_proto_runtime_v1_runtime_proto_rawDescGZIP(), []int{0}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	AppId         string                 `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	TimestampUnix int64                  `protobuf:"varint,4,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_proto_runtime_v1_runtime_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runtime_v1_runtime_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_proto_runtime_v1_runtime_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *PingResponse) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *PingResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PingResponse) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

type RuntimeStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeStatusRequest) Reset() {
	*x = RuntimeStatusRequest{}
	mi := &file_proto_runtime_v1_runtime_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeStatusRequest) ProtoMessage() {}

func (x *RuntimeStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runtime_v1_runtime_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeStatusRequest.ProtoReflect.Descriptor instead.
func (*RuntimeStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_runtime_v1_runtime_proto_rawDescGZIP(), []int{2}
}

type RuntimeStatusResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Service           string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Mode              string                 `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`
	AppId             string                 `protobuf:"bytes,3,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	StartedAtUnix     int64                  `protobuf:"varint,4,opt,name=started_at_unix,json=startedAtUnix,proto3" json:"started_at_unix,omitempty"`
	UptimeSeconds     int64                  `protobuf:"varint,5,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	DbAvailable       bool                   `protobuf:"varint,10,opt,name=db_available,json=dbAvailable,proto3" json:"db_available,omitempty"`
	DbHealthy         bool                   `protobuf:"varint,11,opt,name=db_healthy,json=dbHealthy,proto3" json:"db_healthy,omitempty"`
	DbError           string                 `protobuf:"bytes,12,opt,name=db_error,json=dbError,proto3" json:"db_error,omitempty"`
	RedisAvailable    bool                   `protobuf:"varint,20,opt,name=redis_available,json=redisAvailable,proto3" json:"redis_available,omitempty"`
	RedisHealthy      bool                   `protobuf:"varint,21,opt,name=redis_healthy,json=redisHealthy,proto3" json:"redis_healthy,omitempty"`
	RedisError        string                 `protobuf:"bytes,22,opt,name=redis_error,json=redisError,proto3" json:"redis_error,omitempty"`
	K8SAvailable      bool                   `protobuf:"varint,30,opt,name=k8s_available,json=k8sAvailable,proto3" json:"k8s_available,omitempty"`
	K8SHealthy        bool                   `protobuf:"varint,31,opt,name=k8s_healthy,json=k8sHealthy,proto3" json:"k8s_healthy,omitempty"`
	K8SError          string                 `protobuf:"bytes,32,opt,name=k8s_error,json=k8sError,proto3" json:"k8s_error,omitempty"`
	BuildkitAvailable bool                   `protobuf:"varint,40,opt,name=buildkit_available,json=buildkitAvailable,proto3" json:"buildkit_available,omitempty"`
	BuildkitHealthy   bool                   `protobuf:"varint,41,opt,name=buildkit_healthy,json=buildkitHealthy,proto3" json:"buildkit_healthy,omitempty"`
	BuildkitError     string                 `protobuf:"bytes,42,opt,name=buildkit_error,json=buildkitError,proto3" json:"buildkit_error,omitempty"`
	HelmAvailable     bool                   `protobuf:"varint,50,opt,name=helm_available,json=helmAvailable,proto3" json:"helm_available,omitempty"`
	HelmHealthy       bool                   `protobuf:"varint,51,opt,name=helm_healthy,json=helmHealthy,proto3" json:"helm_healthy,omitempty"`
	HelmError         string                 `protobuf:"bytes,52,opt,name=helm_error,json=helmError,proto3" json:"helm_error,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RuntimeStatusResponse) Reset() {
	*x = RuntimeStatusResponse{}
	mi := &file_proto_runtime_v1_runtime_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeStatusResponse) ProtoMessage() {}

func (x *RuntimeStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runtime_v1_runtime_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeStatusResponse.ProtoReflect.Descriptor instead.
func (*RuntimeStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_runtime_v1_runtime_proto_rawDescGZIP(), []int{3}
}

func (x *RuntimeStatusResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *RuntimeStatusResponse) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *RuntimeStatusResponse) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *RuntimeStatusResponse) GetStartedAtUnix() int64 {
	if x != nil {
		return x.StartedAtUnix
	}
	return 0
}

func (x *RuntimeStatusResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *RuntimeStatusResponse) GetDbAvailable() bool {
	if x != nil {
		return x.DbAvailable
	}
	return false
}

func (x *RuntimeStatusResponse) GetDbHealthy() bool {
	if x != nil {
		return x.DbHealthy
	}
	return false
}

func (x *RuntimeStatusResponse) GetDbError() string {
	if x != nil {
		return x.DbError
	}
	return ""
}

func (x *RuntimeStatusResponse) GetRedisAvailable() bool {
	if x != nil {
		return x.RedisAvailable
	}
	return false
}

func (x *RuntimeStatusResponse) GetRedisHealthy() bool {
	if x != nil {
		return x.RedisHealthy
	}
	return false
}

func (x *RuntimeStatusResponse) GetRedisError() string {
	if x != nil {
		return x.RedisError
	}
	return ""
}

func (x *RuntimeStatusResponse) GetK8SAvailable() bool {
	if x != nil {
		return x.K8SAvailable
	}
	return false
}

func (x *RuntimeStatusResponse) GetK8SHealthy() bool {
	if x != nil {
		return x.K8SHealthy
	}
	return false
}

func (x *RuntimeStatusResponse) GetK8SError() string {
	if x != nil {
		return x.K8SError
	}
	return ""
}

func (x *RuntimeStatusResponse) GetBuildkitAvailable() bool {
	if x != nil {
		return x.BuildkitAvailable
	}
	return false
}

func (x *RuntimeStatusResponse) GetBuildkitHealthy() bool {
	if x != nil {
		return x.BuildkitHealthy
	}
	return false
}

func (x *RuntimeStatusResponse) GetBuildkitError() string {
	if x != nil {
		return x.BuildkitError
	}
	return ""
}

func (x *RuntimeStatusResponse) GetHelmAvailable() bool {
	if x != nil {
		return x.HelmAvailable
	}
	return false
}

func (x *RuntimeStatusResponse) GetHelmHealthy() bool {
	if x != nil {
		return x.HelmHealthy
	}
	return false
}

func (x *RuntimeStatusResponse) GetHelmError() string {
	if x != nil {
		return x.HelmError
	}
	return ""
}

type QueueStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueStatusRequest) Reset() {
	*x = QueueStatusRequest{}
	mi := &file_proto_runtime_v1_runtime_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueStatusRequest) ProtoMessage() {}

func (x *QueueStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runtime_v1_runtime_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueStatusRequest.ProtoReflect.Descriptor instead.
func (*QueueStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_runtime_v1_runtime_proto_rawDescGZIP(), []int{4}
}

type QueueStatusResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ReadyCount       int64                  `protobuf:"varint,1,opt,name=ready_count,json=readyCount,proto3" json:"ready_count,omitempty"`
	DelayedCount     int64                  `protobuf:"varint,2,opt,name=delayed_count,json=delayedCount,proto3" json:"delayed_count,omitempty"`
	DeadCount        int64                  `protobuf:"varint,3,opt,name=dead_count,json=deadCount,proto3" json:"dead_count,omitempty"`
	IndexedCount     int64                  `protobuf:"varint,4,opt,name=indexed_count,json=indexedCount,proto3" json:"indexed_count,omitempty"`
	ConcurrencyCount int64                  `protobuf:"varint,5,opt,name=concurrency_count,json=concurrencyCount,proto3" json:"concurrency_count,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *QueueStatusResponse) Reset() {
	*x = QueueStatusResponse{}
	mi := &file_proto_runtime_v1_runtime_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueStatusResponse) ProtoMessage() {}

func (x *QueueStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runtime_v1_runtime_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueStatusResponse.ProtoReflect.Descriptor instead.
func (*QueueStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_runtime_v1_runtime_proto_rawDescGZIP(), []int{5}
}

func (x *QueueStatusResponse) GetReadyCount() int64 {
	if x != nil {
		return x.ReadyCount
	}
	return 0
}

func (x *QueueStatusResponse) GetDelayedCount() int64 {
	if x != nil {
		return x.DelayedCount
	}
	return 0
}

func (x *QueueStatusResponse) GetDeadCount() int64 {
	if x != nil {
		return x.DeadCount
	}
	return 0
}

func (x *QueueStatusResponse) GetIndexedCount() int64 {
	if x != nil {
		return x.IndexedCount
	}
	return 0
}

func (x *QueueStatusResponse) GetConcurrencyCount() int64 {
	if x != nil {
		return x.ConcurrencyCount
	}
	return 0
}

type LimiterStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LimiterStatusRequest) Reset() {
	*x = LimiterStatusRequest{}
	mi := &file_proto_runtime_v1_runtime_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LimiterStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LimiterStatusRequest) ProtoMessage() {}

func (x *LimiterStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runtime_v1_runtime_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LimiterStatusRequest.ProtoReflect.Descriptor instead.
func (*LimiterStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_runtime_v1_runtime_proto_rawDescGZIP(), []int{6}
}

type LimiterStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*LimiterStatus       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LimiterStatusResponse) Reset() {
	*x = LimiterStatusResponse{}
	mi := &file_proto_runtime_v1_runtime_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LimiterStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LimiterStatusResponse) ProtoMessage() {}

func (x *LimiterStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runtime_v1_runtime_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LimiterStatusResponse.ProtoReflect.Descriptor instead.
func (*LimiterStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_runtime_v1_runtime_proto_rawDescGZIP(), []int{7}
}

func (x *LimiterStatusResponse) GetItems() []*LimiterStatus {
	if x != nil {
		return x.Items
	}
	return nil
}

type LimiterStatus struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ServiceName        string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	BucketKey          string                 `protobuf:"bytes,2,opt,name=bucket_key,json=bucketKey,proto3" json:"bucket_key,omitempty"`
	MaxTokens          int64                  `protobuf:"varint,3,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	WaitTimeoutSeconds int64                  `protobuf:"varint,4,opt,name=wait_timeout_seconds,json=waitTimeoutSeconds,proto3" json:"wait_timeout_seconds,omitempty"`
	InUseTokens        int64                  `protobuf:"varint,5,opt,name=in_use_tokens,json=inUseTokens,proto3" json:"in_use_tokens,omitempty"`
	Error              string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *LimiterStatus) Reset() {
	*x = LimiterStatus{}
	mi := &file_proto_runtime_v1_runtime_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LimiterStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LimiterStatus) ProtoMessage() {}

func (x *LimiterStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runtime_v1_runtime_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LimiterStatus.ProtoReflect.Descriptor instead.
func (*LimiterStatus) Descriptor() ([]byte, []int) {
	return file_proto_runtime_v1_runtime_proto_rawDescGZIP(), []int{8}
}

func (x *LimiterStatus) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *LimiterStatus) GetBucketKey() string {
	if x != nil {
		return x.BucketKey
	}
	return ""
}

func (x *LimiterStatus) GetMaxTokens() int64 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *LimiterStatus) GetWaitTimeoutSeconds() int64 {
	if x != nil {
		return x.WaitTimeoutSeconds
	}
	return 0
}

func (x *LimiterStatus) GetInUseTokens() int64 {
	if x != nil {
		return x.InUseTokens
	}
	return 0
}

func (x *LimiterStatus) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StructResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *structpb.Struct       `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StructResponse) Reset() {
	*x = StructResponse{}
	mi := &file_proto_runtime_v1_runtime_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StructResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StructResponse) ProtoMessage() {}

func (x *StructResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runtime_v1_runtime_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StructResponse.ProtoReflect.Descriptor instead.
func (*StructResponse) Descriptor() ([]byte, []int) {
	return file_proto_runtime_v1_runtime_proto_rawDescGZIP(), []int{9}
}

func (x *StructResponse) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_proto_runtime_v1_runtime_proto protoreflect.FileDescriptor

const file_proto_runtime_v1_runtime_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/runtime/v1/runtime.proto\x12\n" +
	"runtime.v1\x1a\x1cgoogle/protobuf/struct.proto\"\r\n" +
	"\vPingRequest\"~\n" +
	"\fPingResponse\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\tR\x05appId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12%\n" +
	"\x0etimestamp_unix\x18\x04 \x01(\x03R\rtimestampUnix\"\x16\n" +
	"\x14RuntimeStatusRequest\"\xc4\x05\n" +
	"\x15RuntimeStatusResponse\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\x12\x15\n" +
	"\x06app_id\x18\x03 \x01(\tR\x05appId\x12&\n" +
	"\x0fstarted_at_unix\x18\x04 \x01(\x03R\rstartedAtUnix\x12%\n" +
	"\x0euptime_seconds\x18\x05 \x01(\x03R\ruptimeSeconds\x12!\n" +
	"\fdb_available\x18\n" +
	" \x01(\bR\vdbAvailable\x12\x1d\n" +
	"\n" +
	"db_healthy\x18\v \x01(\bR\tdbHealthy\x12\x19\n" +
	"\bdb_error\x18\f \x01(\tR\adbError\x12'\n" +
	"\x0fredis_available\x18\x14 \x01(\bR\x0eredisAvailable\x12#\n" +
	"\rredis_healthy\x18\x15 \x01(\bR\fredisHealthy\x12\x1f\n" +
	"\vredis_error\x18\x16 \x01(\tR\n" +
	"redisError\x12#\n" +
	"\rk8s_available\x18\x1e \x01(\bR\fk8sAvailable\x12\x1f\n" +
	"\vk8s_healthy\x18\x1f \x01(\bR\n" +
	"k8sHealthy\x12\x1b\n" +
	"\tk8s_error\x18  \x01(\tR\bk8sError\x12-\n" +
	"\x12buildkit_available\x18( \x01(\bR\x11buildkitAvailable\x12)\n" +
	"\x10buildkit_healthy\x18) \x01(\bR\x0fbuildkitHealthy\x12%\n" +
	"\x0ebuildkit_error\x18* \x01(\tR\rbuildkitError\x12%\n" +
	"\x0ehelm_available\x182 \x01(\bR\rhelmAvailable\x12!\n" +
	"\fhelm_healthy\x183 \x01(\bR\vhelmHealthy\x12\x1d\n" +
	"\n" +
	"helm_error\x184 \x01(\tR\thelmError\"\x14\n" +
	"\x12QueueStatusRequest\"\xcc\x01\n" +
	"\x13QueueStatusResponse\x12\x1f\n" +
	"\vready_count\x18\x01 \x01(\x03R\n" +
	"readyCount\x12#\n" +
	"\rdelayed_count\x18\x02 \x01(\x03R\fdelayedCount\x12\x1d\n" +
	"\n" +
	"dead_count\x18\x03 \x01(\x03R\tdeadCount\x12#\n" +
	"\rindexed_count\x18\x04 \x01(\x03R\findexedCount\x12+\n" +
	"\x11concurrency_count\x18\x05 \x01(\x03R\x10concurrencyCount\"\x16\n" +
	"\x14LimiterStatusRequest\"H\n" +
	"\x15LimiterStatusResponse\x12/\n" +
	"\x05items\x18\x01 \x03(\v2\x19.runtime.v1.LimiterStatusR\x05items\"\xdc\x01\n" +
	"\rLimiterStatus\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x1d\n" +
	"\n" +
	"bucket_key\x18\x02 \x01(\tR\tbucketKey\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x03 \x01(\x03R\tmaxTokens\x120\n" +
	"\x14wait_timeout_seconds\x18\x04 \x01(\x03R\x12waitTimeoutSeconds\x12\"\n" +
	"\rin_use_tokens\x18\x05 \x01(\x03R\vinUseTokens\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"=\n" +
	"\x0eStructResponse\x12+\n" +
	"\x04data\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x04data2\xe1\x03\n" +
	"\x0eRuntimeService\x129\n" +
	"\x04Ping\x12\x17.runtime.v1.PingRequest\x1a\x18.runtime.v1.PingResponse\x12W\n" +
	"\x10GetRuntimeStatus\x12 .runtime.v1.RuntimeStatusRequest\x1a!.runtime.v1.RuntimeStatusResponse\x12Q\n" +
	"\x0eGetQueueStatus\x12\x1e.runtime.v1.QueueStatusRequest\x1a\x1f.runtime.v1.QueueStatusResponse\x12W\n" +
	"\x10GetLimiterStatus\x12 .runtime.v1.LimiterStatusRequest\x1a!.runtime.v1.LimiterStatusResponse\x12H\n" +
	"\x11GetNamespaceLocks\x12\x17.runtime.v1.PingRequest\x1a\x1a.runtime.v1.StructResponse\x12E\n" +
	"\x0eGetQueuedTasks\x12\x17.runtime.v1.PingRequest\x1a\x1a.runtime.v1.StructResponseB\"Z aegis/proto/runtime/v1;runtimev1b\x06proto3"

var (
	file_proto_runtime_v1_runtime_proto_rawDescOnce sync.Once
	file_proto_runtime_v1_runtime_proto_rawDescData []byte
)

func file_proto_runtime_v1_runtime_proto_rawDescGZIP() []byte {
	file_proto_runtime_v1_runtime_proto_rawDescOnce.Do(func() {
		file_proto_runtime_v1_runtime_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_runtime_v1_runtime_proto_rawDesc), len(file_proto_runtime_v1_runtime_proto_rawDesc)))
	})
	return file_proto_runtime_v1_runtime_proto_rawDescData
}

var file_proto_runtime_v1_runtime_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_runtime_v1_runtime_proto_goTypes = []any{
	(*PingRequest)(nil),           // 0: runtime.v1.PingRequest
	(*PingResponse)(nil),          // 1: runtime.v1.PingResponse
	(*RuntimeStatusRequest)(nil),  // 2: runtime.v1.RuntimeStatusRequest
	(*RuntimeStatusResponse)(nil), // 3: runtime.v1.RuntimeStatusResponse
	(*QueueStatusRequest)(nil),    // 4: runtime.v1.QueueStatusRequest
	(*QueueStatusResponse)(nil),   // 5: runtime.v1.QueueStatusResponse
	(*LimiterStatusRequest)(nil),  // 6: runtime.v1.LimiterStatusRequest
	(*LimiterStatusResponse)(nil), // 7: runtime.v1.LimiterStatusResponse
	(*LimiterStatus)(nil),         // 8: runtime.v1.LimiterStatus
	(*StructResponse)(nil),        // 9: runtime.v1.StructResponse
	(*structpb.Struct)(nil),       // 10: google.protobuf.Struct
}
var file_proto_runtime_v1_runtime_proto_depIdxs = []int32{
	8,  // 0: runtime.v1.LimiterStatusResponse.items:type_name -> runtime.v1.LimiterStatus
	10, // 1: runtime.v1.StructResponse.data:type_name -> google.protobuf.Struct
	0,  // 2: runtime.v1.RuntimeService.Ping:input_type -> runtime.v1.PingRequest
	2,  // 3: runtime.v1.RuntimeService.GetRuntimeStatus:input_type -> runtime.v1.RuntimeStatusRequest
	4,  // 4: runtime.v1.RuntimeService.GetQueueStatus:input_type -> runtime.v1.QueueStatusRequest
	6,  // 5: runtime.v1.RuntimeService.GetLimiterStatus:input_type -> runtime.v1.LimiterStatusRequest
	0,  // 6: runtime.v1.RuntimeService.GetNamespaceLocks:input_type -> runtime.v1.PingRequest
	0,  // 7: runtime.v1.RuntimeService.GetQueuedTasks:input_type -> runtime.v1.PingRequest
	1,  // 8: runtime.v1.RuntimeService.Ping:output_type -> runtime.v1.PingResponse
	3,  // 9: runtime.v1.RuntimeService.GetRuntimeStatus:output_type -> runtime.v1.RuntimeStatusResponse
	5,  // 10: runtime.v1.RuntimeService.GetQueueStatus:output_type -> runtime.v1.QueueStatusResponse
	7,  // 11: runtime.v1.RuntimeService.GetLimiterStatus:output_type -> runtime.v1.LimiterStatusResponse
	9,  // 12: runtime.v1.RuntimeService.GetNamespaceLocks:output_type -> runtime.v1.StructResponse
	9,  // 13: runtime.v1.RuntimeService.GetQueuedTasks:output_type -> runtime.v1.StructResponse
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_runtime_v1_runtime_proto_init() }
func file_proto_runtime_v1_runtime_proto_init() {
	if File_proto_runtime_v1_runtime_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_runtime_v1_runtime_proto_rawDesc), len(file_proto_runtime_v1_runtime_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_runtime_v1_runtime_proto_goTypes,
		DependencyIndexes: file_proto_runtime_v1_runtime_proto_depIdxs,
		MessageInfos:      file_proto_runtime_v1_runtime_proto_msgTypes,
	}.Build()
	File_proto_runtime_v1_runtime_proto = out.File
	file_proto_runtime_v1_runtime_proto_goTypes = nil
	file_proto_runtime_v1_runtime_proto_depIdxs = nil
}
