global:
  image:
    repository: pair-diag-cn-guangzhou.cr.volces.com/pair
    tag: "v1.2.9"
  security:
    allowInsecureImages: true

mysql:
  image:
    repository: pair-diag-cn-guangzhou.cr.volces.com/pair/mysql

rabbitmq:
  image:
    registry: pair-cn-shanghai.cr.volces.com
    repository: opspai/rabbitmq

loadgenerator:
  image:
    repository: pair-diag-cn-guangzhou.cr.volces.com/pair/loadgenerator
    tag: "023"
  initContainer:
    image: pair-diag-cn-guangzhou.cr.volces.com/pair/netshoot:v0.14
