name = "AegisLab"
version = "1.0.0"

port = 8082
workspace = "/home/nn/workspace/AegisLab"

[system]
timezone = "Asia/Shanghai"

[initialization]
data_path = "/home/nn/workspace/AegisLab/data/initial_data/staging"

[database.mysql]
host = "localhost"
port = "3306"
user = "root"
password = "yourpassword"
db = "rcabench"

[jaeger]
endpoint = "localhost:4318"

[redis]
host = "localhost:6379"

[etcd]
endpoints = ["localhost:2379"]
username = ""
password = ""

[k8s]
namespace = "exp"

[k8s.service]
internal_url = "http://10.10.10.161:8082"

[k8s.init_container]
busybox_image = "10.10.10.240/library/busybox:1.35"

[k8s.job.service_account]
name = "rcabench-sa"

[k8s.job.volume_mount.dataset]
name = "dataset"
mount_path = "/data"
source_type = "pvc"
claim_name = "rcabench-juicefs-dataset"

[k8s.job.volume_mount.experiment_storage]
name = "experiment-storage"
mount_path = "/experiment_storage"
source_type = "pvc"
claim_name = "rcabench-juicefs-experiment-storage"

[jfs]
container_path = "/home/nn/workspace/AegisLab/containers"
dataset_path = "/mnt/jfs/rcabench_dataset"
experiment_storage_path = "/mnt/jfs/experiment_storage"

[buildkit]
address = "localhost:1234"

[clients.orchestrator]
target = "localhost:9092"

[clients.resource]
target = "localhost:9093"

[clients.runtime]
target = "localhost:9094"

[clients.system]
target = "localhost:9095"

[orchestrator.grpc]
addr = ":9092"

[resource.grpc]
addr = ":9093"

[runtime_worker.grpc]
addr = ":9094"

[system.grpc]
addr = ":9095"

[loki]
address = "http://10.10.10.161:3100"
timeout = "10s"
max_entries = 5000

[otlp_receiver]
port = 4319
max_request_size = 5242880
