apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: "observed-genesis"
  instance: "observed"
  service: "movie-id-service"
  system: "media"
spec:
  replace_scope: "service"
  points:
    - capability: "pod_kill"
      target:
        app: "movie-id-service"
        namespace: "media"
    - capability: "pod_failure"
      target:
        app: "movie-id-service"
        namespace: "media"
    - capability: "container_kill"
      target:
        app: "movie-id-service"
        container: "movie-id-service"
        namespace: "media"
    - capability: "cpu_stress"
      target:
        app: "movie-id-service"
        container: "movie-id-service"
        namespace: "media"
    - capability: "time_skew"
      target:
        app: "movie-id-service"
        container: "movie-id-service"
        namespace: "media"
    - capability: "dns_error"
      target:
        app: "movie-id-service"
        domain_patterns:
          - "compose-review-service"
        namespace: "media"
    - capability: "dns_random"
      target:
        app: "movie-id-service"
        domain_patterns:
          - "compose-review-service"
        namespace: "media"
    - capability: "network_delay"
      target:
        namespace: "media"
        source_app: "movie-id-service"
        span_names:
          - "UploadMovieId"
        target_service: "compose-review-service"
    - capability: "network_loss"
      target:
        namespace: "media"
        source_app: "movie-id-service"
        span_names:
          - "UploadMovieId"
        target_service: "compose-review-service"
    - capability: "network_duplicate"
      target:
        namespace: "media"
        source_app: "movie-id-service"
        span_names:
          - "UploadMovieId"
        target_service: "compose-review-service"
    - capability: "network_corrupt"
      target:
        namespace: "media"
        source_app: "movie-id-service"
        span_names:
          - "UploadMovieId"
        target_service: "compose-review-service"
    - capability: "network_bandwidth"
      target:
        namespace: "media"
        source_app: "movie-id-service"
        span_names:
          - "UploadMovieId"
        target_service: "compose-review-service"
    - capability: "network_partition"
      target:
        namespace: "media"
        source_app: "movie-id-service"
        span_names:
          - "UploadMovieId"
        target_service: "compose-review-service"
    - capability: "dns_error"
      target:
        app: "movie-id-service"
        domain_patterns:
          - "rating-service"
        namespace: "media"
    - capability: "dns_random"
      target:
        app: "movie-id-service"
        domain_patterns:
          - "rating-service"
        namespace: "media"
    - capability: "network_delay"
      target:
        namespace: "media"
        source_app: "movie-id-service"
        span_names:
          - "UploadRating"
        target_service: "rating-service"
    - capability: "network_loss"
      target:
        namespace: "media"
        source_app: "movie-id-service"
        span_names:
          - "UploadRating"
        target_service: "rating-service"
    - capability: "network_duplicate"
      target:
        namespace: "media"
        source_app: "movie-id-service"
        span_names:
          - "UploadRating"
        target_service: "rating-service"
    - capability: "network_corrupt"
      target:
        namespace: "media"
        source_app: "movie-id-service"
        span_names:
          - "UploadRating"
        target_service: "rating-service"
    - capability: "network_bandwidth"
      target:
        namespace: "media"
        source_app: "movie-id-service"
        span_names:
          - "UploadRating"
        target_service: "rating-service"
    - capability: "network_partition"
      target:
        namespace: "media"
        source_app: "movie-id-service"
        span_names:
          - "UploadRating"
        target_service: "rating-service"
