apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: "seed-genesis"
  instance: "seed"
  service: "movie-id-service"
  system: "media"
spec:
  replace_scope: "service"
  points:
    - capability: "container_kill"
      target:
        app: "movie-id-service"
        container: "movie-id-service"
        namespace: "media"
    - capability: "cpu_stress"
      target:
        app: "movie-id-service"
        container: "movie-id-service"
        namespace: "media"
    - capability: "memory_stress"
      target:
        app: "movie-id-service"
        container: "movie-id-service"
        namespace: "media"
    - capability: "pod_failure"
      target:
        app: "movie-id-service"
        namespace: "media"
    - capability: "pod_kill"
      target:
        app: "movie-id-service"
        namespace: "media"
    - capability: "time_skew"
      target:
        app: "movie-id-service"
        container: "movie-id-service"
        namespace: "media"
