apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: "seed-genesis"
  instance: "seed"
  service: "nginx-web-server"
  system: "media"
spec:
  replace_scope: "service"
  points:
    - capability: "container_kill"
      target:
        app: "nginx-web-server"
        container: "nginx-web-server"
        namespace: "media"
    - capability: "cpu_stress"
      target:
        app: "nginx-web-server"
        container: "nginx-web-server"
        namespace: "media"
    - capability: "http_request_abort"
      target:
        app: "nginx-web-server"
        method: "GET"
        namespace: "media"
        path: "/wrk2-api/movie/read-info"
        port: 9090
        server_address: "movie-info-service"
        span_name: "/wrk2-api/movie/read-info"
    - capability: "http_request_abort"
      target:
        app: "nginx-web-server"
        method: "GET"
        namespace: "media"
        path: "/wrk2-api/movie/read-page"
        port: 9090
        server_address: "page-service"
        span_name: "/wrk2-api/movie/read-page"
    - capability: "http_request_abort"
      target:
        app: "nginx-web-server"
        method: "POST"
        namespace: "media"
        path: "/wrk2-api/cast-info/write"
        port: 9090
        server_address: "cast-info-service"
        span_name: "/wrk2-api/cast-info/write"
    - capability: "http_request_abort"
      target:
        app: "nginx-web-server"
        method: "POST"
        namespace: "media"
        path: "/wrk2-api/movie-info/write"
        port: 9090
        server_address: "movie-info-service"
        span_name: "/wrk2-api/movie-info/write"
    - capability: "http_request_abort"
      target:
        app: "nginx-web-server"
        method: "POST"
        namespace: "media"
        path: "/wrk2-api/movie/register"
        port: 9090
        server_address: "compose-review-service"
        span_name: "/wrk2-api/movie/register"
    - capability: "http_request_abort"
      target:
        app: "nginx-web-server"
        method: "POST"
        namespace: "media"
        path: "/wrk2-api/plot/write"
        port: 9090
        server_address: "plot-service"
        span_name: "/wrk2-api/plot/write"
    - capability: "http_request_abort"
      target:
        app: "nginx-web-server"
        method: "POST"
        namespace: "media"
        path: "/wrk2-api/review/compose"
        port: 9090
        server_address: "compose-review-service"
        span_name: "/wrk2-api/review/compose"
    - capability: "http_request_abort"
      target:
        app: "nginx-web-server"
        method: "POST"
        namespace: "media"
        path: "/wrk2-api/user/register"
        port: 9090
        server_address: "user-service"
        span_name: "/wrk2-api/user/register"
    - capability: "http_request_delay"
      target:
        app: "nginx-web-server"
        method: "GET"
        namespace: "media"
        path: "/wrk2-api/movie/read-info"
        port: 9090
        server_address: "movie-info-service"
        span_name: "/wrk2-api/movie/read-info"
    - capability: "http_request_delay"
      target:
        app: "nginx-web-server"
        method: "GET"
        namespace: "media"
        path: "/wrk2-api/movie/read-page"
        port: 9090
        server_address: "page-service"
        span_name: "/wrk2-api/movie/read-page"
    - capability: "http_request_delay"
      target:
        app: "nginx-web-server"
        method: "POST"
        namespace: "media"
        path: "/wrk2-api/cast-info/write"
        port: 9090
        server_address: "cast-info-service"
        span_name: "/wrk2-api/cast-info/write"
    - capability: "http_request_delay"
      target:
        app: "nginx-web-server"
        method: "POST"
        namespace: "media"
        path: "/wrk2-api/movie-info/write"
        port: 9090
        server_address: "movie-info-service"
        span_name: "/wrk2-api/movie-info/write"
    - capability: "http_request_delay"
      target:
        app: "nginx-web-server"
        method: "POST"
        namespace: "media"
        path: "/wrk2-api/movie/register"
        port: 9090
        server_address: "compose-review-service"
        span_name: "/wrk2-api/movie/register"
    - capability: "http_request_delay"
      target:
        app: "nginx-web-server"
        method: "POST"
        namespace: "media"
        path: "/wrk2-api/plot/write"
        port: 9090
        server_address: "plot-service"
        span_name: "/wrk2-api/plot/write"
    - capability: "http_request_delay"
      target:
        app: "nginx-web-server"
        method: "POST"
        namespace: "media"
        path: "/wrk2-api/review/compose"
        port: 9090
        server_address: "compose-review-service"
        span_name: "/wrk2-api/review/compose"
    - capability: "http_request_delay"
      target:
        app: "nginx-web-server"
        method: "POST"
        namespace: "media"
        path: "/wrk2-api/user/register"
        port: 9090
        server_address: "user-service"
        span_name: "/wrk2-api/user/register"
    - capability: "pod_failure"
      target:
        app: "nginx-web-server"
        namespace: "media"
    - capability: "pod_kill"
      target:
        app: "nginx-web-server"
        namespace: "media"
    - capability: "time_skew"
      target:
        app: "nginx-web-server"
        container: "nginx-web-server"
        namespace: "media"
