apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: seed-genesis
  instance: seed
  service: nginx-web-server
  system: media
spec:
  points:
  - capability: http_request_replace_method
    target:
      app: nginx-web-server
      method: GET
      namespace: media
      path: /wrk2-api/movie/read-info
      port: 9090
  - capability: http_request_replace_method
    target:
      app: nginx-web-server
      method: GET
      namespace: media
      path: /wrk2-api/movie/read-page
      port: 9090
  - capability: http_request_replace_method
    target:
      app: nginx-web-server
      method: POST
      namespace: media
      path: /wrk2-api/cast-info/write
      port: 9090
  - capability: http_request_replace_method
    target:
      app: nginx-web-server
      method: POST
      namespace: media
      path: /wrk2-api/movie-info/write
      port: 9090
  - capability: http_request_replace_method
    target:
      app: nginx-web-server
      method: POST
      namespace: media
      path: /wrk2-api/movie/register
      port: 9090
  - capability: http_request_replace_method
    target:
      app: nginx-web-server
      method: POST
      namespace: media
      path: /wrk2-api/plot/write
      port: 9090
  - capability: http_request_replace_method
    target:
      app: nginx-web-server
      method: POST
      namespace: media
      path: /wrk2-api/review/compose
      port: 9090
  - capability: http_request_replace_method
    target:
      app: nginx-web-server
      method: POST
      namespace: media
      path: /wrk2-api/user/register
      port: 9090
  - capability: http_request_replace_path
    target:
      app: nginx-web-server
      method: GET
      namespace: media
      path: /wrk2-api/movie/read-info
      port: 9090
  - capability: http_request_replace_path
    target:
      app: nginx-web-server
      method: GET
      namespace: media
      path: /wrk2-api/movie/read-page
      port: 9090
  - capability: http_request_replace_path
    target:
      app: nginx-web-server
      method: POST
      namespace: media
      path: /wrk2-api/cast-info/write
      port: 9090
  - capability: http_request_replace_path
    target:
      app: nginx-web-server
      method: POST
      namespace: media
      path: /wrk2-api/movie-info/write
      port: 9090
  - capability: http_request_replace_path
    target:
      app: nginx-web-server
      method: POST
      namespace: media
      path: /wrk2-api/movie/register
      port: 9090
  - capability: http_request_replace_path
    target:
      app: nginx-web-server
      method: POST
      namespace: media
      path: /wrk2-api/plot/write
      port: 9090
  - capability: http_request_replace_path
    target:
      app: nginx-web-server
      method: POST
      namespace: media
      path: /wrk2-api/review/compose
      port: 9090
  - capability: http_request_replace_path
    target:
      app: nginx-web-server
      method: POST
      namespace: media
      path: /wrk2-api/user/register
      port: 9090
  - capability: http_response_abort
    target:
      app: nginx-web-server
      method: GET
      namespace: media
      path: /wrk2-api/movie/read-info
      port: 9090
  - capability: http_response_abort
    target:
      app: nginx-web-server
      method: GET
      namespace: media
      path: /wrk2-api/movie/read-page
      port: 9090
  - capability: http_response_abort
    target:
      app: nginx-web-server
      method: POST
      namespace: media
      path: /wrk2-api/cast-info/write
      port: 9090
  - capability: http_response_abort
    target:
      app: nginx-web-server
      method: POST
      namespace: media
      path: /wrk2-api/movie-info/write
      port: 9090
  - capability: http_response_abort
    target:
      app: nginx-web-server
      method: POST
      namespace: media
      path: /wrk2-api/movie/register
      port: 9090
  - capability: http_response_abort
    target:
      app: nginx-web-server
      method: POST
      namespace: media
      path: /wrk2-api/plot/write
      port: 9090
  - capability: http_response_abort
    target:
      app: nginx-web-server
      method: POST
      namespace: media
      path: /wrk2-api/review/compose
      port: 9090
  - capability: http_response_abort
    target:
      app: nginx-web-server
      method: POST
      namespace: media
      path: /wrk2-api/user/register
      port: 9090
  - capability: http_response_delay
    target:
      app: nginx-web-server
      method: GET
      namespace: media
      path: /wrk2-api/movie/read-info
      port: 9090
  - capability: http_response_delay
    target:
      app: nginx-web-server
      method: GET
      namespace: media
      path: /wrk2-api/movie/read-page
      port: 9090
  - capability: http_response_delay
    target:
      app: nginx-web-server
      method: POST
      namespace: media
      path: /wrk2-api/cast-info/write
      port: 9090
  - capability: http_response_delay
    target:
      app: nginx-web-server
      method: POST
      namespace: media
      path: /wrk2-api/movie-info/write
      port: 9090
  - capability: http_response_delay
    target:
      app: nginx-web-server
      method: POST
      namespace: media
      path: /wrk2-api/movie/register
      port: 9090
  - capability: http_response_delay
    target:
      app: nginx-web-server
      method: POST
      namespace: media
      path: /wrk2-api/plot/write
      port: 9090
  - capability: http_response_delay
    target:
      app: nginx-web-server
      method: POST
      namespace: media
      path: /wrk2-api/review/compose
      port: 9090
  - capability: http_response_delay
    target:
      app: nginx-web-server
      method: POST
      namespace: media
      path: /wrk2-api/user/register
      port: 9090
  - capability: http_response_patch_body
    target:
      app: nginx-web-server
      method: GET
      namespace: media
      path: /wrk2-api/movie/read-info
      port: 9090
  - capability: http_response_patch_body
    target:
      app: nginx-web-server
      method: GET
      namespace: media
      path: /wrk2-api/movie/read-page
      port: 9090
  - capability: http_response_patch_body
    target:
      app: nginx-web-server
      method: POST
      namespace: media
      path: /wrk2-api/cast-info/write
      port: 9090
  - capability: http_response_patch_body
    target:
      app: nginx-web-server
      method: POST
      namespace: media
      path: /wrk2-api/movie-info/write
      port: 9090
  - capability: http_response_patch_body
    target:
      app: nginx-web-server
      method: POST
      namespace: media
      path: /wrk2-api/movie/register
      port: 9090
  - capability: http_response_patch_body
    target:
      app: nginx-web-server
      method: POST
      namespace: media
      path: /wrk2-api/plot/write
      port: 9090
  - capability: http_response_patch_body
    target:
      app: nginx-web-server
      method: POST
      namespace: media
      path: /wrk2-api/review/compose
      port: 9090
  - capability: http_response_patch_body
    target:
      app: nginx-web-server
      method: POST
      namespace: media
      path: /wrk2-api/user/register
      port: 9090
  - capability: http_response_replace_body
    target:
      app: nginx-web-server
      method: GET
      namespace: media
      path: /wrk2-api/movie/read-info
      port: 9090
  - capability: http_response_replace_body
    target:
      app: nginx-web-server
      method: GET
      namespace: media
      path: /wrk2-api/movie/read-page
      port: 9090
  - capability: http_response_replace_body
    target:
      app: nginx-web-server
      method: POST
      namespace: media
      path: /wrk2-api/cast-info/write
      port: 9090
  - capability: http_response_replace_body
    target:
      app: nginx-web-server
      method: POST
      namespace: media
      path: /wrk2-api/movie-info/write
      port: 9090
  - capability: http_response_replace_body
    target:
      app: nginx-web-server
      method: POST
      namespace: media
      path: /wrk2-api/movie/register
      port: 9090
  - capability: http_response_replace_body
    target:
      app: nginx-web-server
      method: POST
      namespace: media
      path: /wrk2-api/plot/write
      port: 9090
  - capability: http_response_replace_body
    target:
      app: nginx-web-server
      method: POST
      namespace: media
      path: /wrk2-api/review/compose
      port: 9090
  - capability: http_response_replace_body
    target:
      app: nginx-web-server
      method: POST
      namespace: media
      path: /wrk2-api/user/register
      port: 9090
  - capability: http_response_replace_code
    target:
      app: nginx-web-server
      method: GET
      namespace: media
      path: /wrk2-api/movie/read-info
      port: 9090
  - capability: http_response_replace_code
    target:
      app: nginx-web-server
      method: GET
      namespace: media
      path: /wrk2-api/movie/read-page
      port: 9090
  - capability: http_response_replace_code
    target:
      app: nginx-web-server
      method: POST
      namespace: media
      path: /wrk2-api/cast-info/write
      port: 9090
  - capability: http_response_replace_code
    target:
      app: nginx-web-server
      method: POST
      namespace: media
      path: /wrk2-api/movie-info/write
      port: 9090
  - capability: http_response_replace_code
    target:
      app: nginx-web-server
      method: POST
      namespace: media
      path: /wrk2-api/movie/register
      port: 9090
  - capability: http_response_replace_code
    target:
      app: nginx-web-server
      method: POST
      namespace: media
      path: /wrk2-api/plot/write
      port: 9090
  - capability: http_response_replace_code
    target:
      app: nginx-web-server
      method: POST
      namespace: media
      path: /wrk2-api/review/compose
      port: 9090
  - capability: http_response_replace_code
    target:
      app: nginx-web-server
      method: POST
      namespace: media
      path: /wrk2-api/user/register
      port: 9090
  replace_scope: service
