apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: "seed-genesis"
  instance: "seed"
  service: "rating-service"
  system: "media"
spec:
  replace_scope: "service"
  points:
    - capability: "container_kill"
      target:
        app: "rating-service"
        container: "rating-service"
        namespace: "media"
    - capability: "cpu_stress"
      target:
        app: "rating-service"
        container: "rating-service"
        namespace: "media"
    - capability: "pod_failure"
      target:
        app: "rating-service"
        namespace: "media"
    - capability: "pod_kill"
      target:
        app: "rating-service"
        namespace: "media"
    - capability: "time_skew"
      target:
        app: "rating-service"
        container: "rating-service"
        namespace: "media"
