apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: "seed-genesis"
  instance: "seed"
  service: "text-service"
  system: "media"
spec:
  replace_scope: "service"
  points:
    - capability: "container_kill"
      target:
        app: "text-service"
        container: "text-service"
        namespace: "media"
    - capability: "cpu_stress"
      target:
        app: "text-service"
        container: "text-service"
        namespace: "media"
    - capability: "http_request_abort"
      target:
        app: "text-service"
        method: "POST"
        namespace: "media"
        path: "/TextService/UploadText"
        port: 9090
        server_address: "text-service"
        span_name: "UploadText"
    - capability: "http_request_delay"
      target:
        app: "text-service"
        method: "POST"
        namespace: "media"
        path: "/TextService/UploadText"
        port: 9090
        server_address: "text-service"
        span_name: "UploadText"
    - capability: "memory_stress"
      target:
        app: "text-service"
        container: "text-service"
        namespace: "media"
    - capability: "pod_failure"
      target:
        app: "text-service"
        namespace: "media"
    - capability: "pod_kill"
      target:
        app: "text-service"
        namespace: "media"
    - capability: "time_skew"
      target:
        app: "text-service"
        container: "text-service"
        namespace: "media"
