apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: "seed-genesis"
  instance: "seed"
  service: "user-review-service"
  system: "media"
spec:
  replace_scope: "service"
  points:
    - capability: "container_kill"
      target:
        app: "user-review-service"
        container: "user-review-service"
        namespace: "media"
    - capability: "cpu_stress"
      target:
        app: "user-review-service"
        container: "user-review-service"
        namespace: "media"
    - capability: "http_request_abort"
      target:
        app: "user-review-service"
        method: "POST"
        namespace: "media"
        path: "/UserReviewService/UploadUserReview"
        port: 9090
        server_address: "user-review-service"
        span_name: "UploadUserReview"
    - capability: "http_request_delay"
      target:
        app: "user-review-service"
        method: "POST"
        namespace: "media"
        path: "/UserReviewService/UploadUserReview"
        port: 9090
        server_address: "user-review-service"
        span_name: "UploadUserReview"
    - capability: "memory_stress"
      target:
        app: "user-review-service"
        container: "user-review-service"
        namespace: "media"
    - capability: "pod_failure"
      target:
        app: "user-review-service"
        namespace: "media"
    - capability: "pod_kill"
      target:
        app: "user-review-service"
        namespace: "media"
    - capability: "time_skew"
      target:
        app: "user-review-service"
        container: "user-review-service"
        namespace: "media"
