apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: "seed-genesis"
  instance: "seed"
  service: "webui"
  system: "teastore"
spec:
  replace_scope: "service"
  points:
    - capability: "network_bandwidth"
      target:
        namespace: "teastore"
        source_app: "webui"
        target_service: "registry"
    - capability: "network_corrupt"
      target:
        namespace: "teastore"
        source_app: "webui"
        target_service: "registry"
    - capability: "network_delay"
      target:
        namespace: "teastore"
        source_app: "webui"
        target_service: "registry"
    - capability: "network_duplicate"
      target:
        namespace: "teastore"
        source_app: "webui"
        target_service: "registry"
    - capability: "network_loss"
      target:
        namespace: "teastore"
        source_app: "webui"
        target_service: "registry"
    - capability: "network_partition"
      target:
        namespace: "teastore"
        source_app: "webui"
        target_service: "registry"
