apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: "seed-genesis"
  instance: "seed"
  service: "webui"
  system: "teastore"
spec:
  replace_scope: "service"
  points:
    - capability: "dns_error"
      target:
        app: "webui"
        domain_patterns:
          - "teastore-registry"
        namespace: "teastore"
    - capability: "dns_random"
      target:
        app: "webui"
        domain_patterns:
          - "teastore-registry"
        namespace: "teastore"
