apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: seed-genesis
  instance: seed
  service: teastore-auth
  system: teastore
spec:
  points:
  - capability: http_request_replace_method
    target:
      app: teastore-auth
      method: GET
      namespace: teastore
      path: /tools.descartes.teastore.registry/rest/services/tools.descartes.teastore.persistence/
      port: 8080
      server_address: teastore-registry
      span_name: GET
  - capability: http_request_replace_method
    target:
      app: teastore-auth
      method: POST
      namespace: teastore
      path: /tools.descartes.teastore.auth/rest/cart/add/*
      port: 8080
      server_address: teastore-auth
      span_name: POST /tools.descartes.teastore.auth/rest/cart/add/{pid}
  - capability: http_request_replace_method
    target:
      app: teastore-auth
      method: POST
      namespace: teastore
      path: /tools.descartes.teastore.auth/rest/useractions/isloggedin
      port: 8080
      server_address: teastore-auth
      span_name: POST /tools.descartes.teastore.auth/rest/useractions/isloggedin
  - capability: http_request_replace_method
    target:
      app: teastore-auth
      method: POST
      namespace: teastore
      path: /tools.descartes.teastore.auth/rest/useractions/login
      port: 8080
      server_address: teastore-auth
      span_name: POST /tools.descartes.teastore.auth/rest/useractions/login
  - capability: http_request_replace_method
    target:
      app: teastore-auth
      method: POST
      namespace: teastore
      path: /tools.descartes.teastore.auth/rest/useractions/logout
      port: 8080
      server_address: teastore-auth
      span_name: POST /tools.descartes.teastore.auth/rest/useractions/logout
  - capability: http_request_replace_method
    target:
      app: teastore-auth
      method: PUT
      namespace: teastore
      path: /tools.descartes.teastore.registry/rest/services/tools.descartes.teastore.auth/teastore-auth-0.teastore-auth
      port: 8080
      server_address: teastore-registry
      span_name: PUT
  - capability: http_request_replace_path
    target:
      app: teastore-auth
      method: GET
      namespace: teastore
      path: /tools.descartes.teastore.registry/rest/services/tools.descartes.teastore.persistence/
      port: 8080
      server_address: teastore-registry
      span_name: GET
  - capability: http_request_replace_path
    target:
      app: teastore-auth
      method: POST
      namespace: teastore
      path: /tools.descartes.teastore.auth/rest/cart/add/*
      port: 8080
      server_address: teastore-auth
      span_name: POST /tools.descartes.teastore.auth/rest/cart/add/{pid}
  - capability: http_request_replace_path
    target:
      app: teastore-auth
      method: POST
      namespace: teastore
      path: /tools.descartes.teastore.auth/rest/useractions/isloggedin
      port: 8080
      server_address: teastore-auth
      span_name: POST /tools.descartes.teastore.auth/rest/useractions/isloggedin
  - capability: http_request_replace_path
    target:
      app: teastore-auth
      method: POST
      namespace: teastore
      path: /tools.descartes.teastore.auth/rest/useractions/login
      port: 8080
      server_address: teastore-auth
      span_name: POST /tools.descartes.teastore.auth/rest/useractions/login
  - capability: http_request_replace_path
    target:
      app: teastore-auth
      method: POST
      namespace: teastore
      path: /tools.descartes.teastore.auth/rest/useractions/logout
      port: 8080
      server_address: teastore-auth
      span_name: POST /tools.descartes.teastore.auth/rest/useractions/logout
  - capability: http_request_replace_path
    target:
      app: teastore-auth
      method: PUT
      namespace: teastore
      path: /tools.descartes.teastore.registry/rest/services/tools.descartes.teastore.auth/teastore-auth-0.teastore-auth
      port: 8080
      server_address: teastore-registry
      span_name: PUT
  - capability: http_response_abort
    target:
      app: teastore-auth
      method: GET
      namespace: teastore
      path: /tools.descartes.teastore.registry/rest/services/tools.descartes.teastore.persistence/
      port: 8080
      server_address: teastore-registry
      span_name: GET
  - capability: http_response_abort
    target:
      app: teastore-auth
      method: POST
      namespace: teastore
      path: /tools.descartes.teastore.auth/rest/cart/add/*
      port: 8080
      server_address: teastore-auth
      span_name: POST /tools.descartes.teastore.auth/rest/cart/add/{pid}
  - capability: http_response_abort
    target:
      app: teastore-auth
      method: POST
      namespace: teastore
      path: /tools.descartes.teastore.auth/rest/useractions/isloggedin
      port: 8080
      server_address: teastore-auth
      span_name: POST /tools.descartes.teastore.auth/rest/useractions/isloggedin
  - capability: http_response_abort
    target:
      app: teastore-auth
      method: POST
      namespace: teastore
      path: /tools.descartes.teastore.auth/rest/useractions/login
      port: 8080
      server_address: teastore-auth
      span_name: POST /tools.descartes.teastore.auth/rest/useractions/login
  - capability: http_response_abort
    target:
      app: teastore-auth
      method: POST
      namespace: teastore
      path: /tools.descartes.teastore.auth/rest/useractions/logout
      port: 8080
      server_address: teastore-auth
      span_name: POST /tools.descartes.teastore.auth/rest/useractions/logout
  - capability: http_response_abort
    target:
      app: teastore-auth
      method: PUT
      namespace: teastore
      path: /tools.descartes.teastore.registry/rest/services/tools.descartes.teastore.auth/teastore-auth-0.teastore-auth
      port: 8080
      server_address: teastore-registry
      span_name: PUT
  - capability: http_response_delay
    target:
      app: teastore-auth
      method: GET
      namespace: teastore
      path: /tools.descartes.teastore.registry/rest/services/tools.descartes.teastore.persistence/
      port: 8080
      server_address: teastore-registry
      span_name: GET
  - capability: http_response_delay
    target:
      app: teastore-auth
      method: POST
      namespace: teastore
      path: /tools.descartes.teastore.auth/rest/cart/add/*
      port: 8080
      server_address: teastore-auth
      span_name: POST /tools.descartes.teastore.auth/rest/cart/add/{pid}
  - capability: http_response_delay
    target:
      app: teastore-auth
      method: POST
      namespace: teastore
      path: /tools.descartes.teastore.auth/rest/useractions/isloggedin
      port: 8080
      server_address: teastore-auth
      span_name: POST /tools.descartes.teastore.auth/rest/useractions/isloggedin
  - capability: http_response_delay
    target:
      app: teastore-auth
      method: POST
      namespace: teastore
      path: /tools.descartes.teastore.auth/rest/useractions/login
      port: 8080
      server_address: teastore-auth
      span_name: POST /tools.descartes.teastore.auth/rest/useractions/login
  - capability: http_response_delay
    target:
      app: teastore-auth
      method: POST
      namespace: teastore
      path: /tools.descartes.teastore.auth/rest/useractions/logout
      port: 8080
      server_address: teastore-auth
      span_name: POST /tools.descartes.teastore.auth/rest/useractions/logout
  - capability: http_response_delay
    target:
      app: teastore-auth
      method: PUT
      namespace: teastore
      path: /tools.descartes.teastore.registry/rest/services/tools.descartes.teastore.auth/teastore-auth-0.teastore-auth
      port: 8080
      server_address: teastore-registry
      span_name: PUT
  - capability: http_response_patch_body
    target:
      app: teastore-auth
      method: GET
      namespace: teastore
      path: /tools.descartes.teastore.registry/rest/services/tools.descartes.teastore.persistence/
      port: 8080
      server_address: teastore-registry
      span_name: GET
  - capability: http_response_patch_body
    target:
      app: teastore-auth
      method: POST
      namespace: teastore
      path: /tools.descartes.teastore.auth/rest/cart/add/*
      port: 8080
      server_address: teastore-auth
      span_name: POST /tools.descartes.teastore.auth/rest/cart/add/{pid}
  - capability: http_response_patch_body
    target:
      app: teastore-auth
      method: POST
      namespace: teastore
      path: /tools.descartes.teastore.auth/rest/useractions/isloggedin
      port: 8080
      server_address: teastore-auth
      span_name: POST /tools.descartes.teastore.auth/rest/useractions/isloggedin
  - capability: http_response_patch_body
    target:
      app: teastore-auth
      method: POST
      namespace: teastore
      path: /tools.descartes.teastore.auth/rest/useractions/login
      port: 8080
      server_address: teastore-auth
      span_name: POST /tools.descartes.teastore.auth/rest/useractions/login
  - capability: http_response_patch_body
    target:
      app: teastore-auth
      method: POST
      namespace: teastore
      path: /tools.descartes.teastore.auth/rest/useractions/logout
      port: 8080
      server_address: teastore-auth
      span_name: POST /tools.descartes.teastore.auth/rest/useractions/logout
  - capability: http_response_patch_body
    target:
      app: teastore-auth
      method: PUT
      namespace: teastore
      path: /tools.descartes.teastore.registry/rest/services/tools.descartes.teastore.auth/teastore-auth-0.teastore-auth
      port: 8080
      server_address: teastore-registry
      span_name: PUT
  - capability: http_response_replace_body
    target:
      app: teastore-auth
      method: GET
      namespace: teastore
      path: /tools.descartes.teastore.registry/rest/services/tools.descartes.teastore.persistence/
      port: 8080
      server_address: teastore-registry
      span_name: GET
  - capability: http_response_replace_body
    target:
      app: teastore-auth
      method: POST
      namespace: teastore
      path: /tools.descartes.teastore.auth/rest/cart/add/*
      port: 8080
      server_address: teastore-auth
      span_name: POST /tools.descartes.teastore.auth/rest/cart/add/{pid}
  - capability: http_response_replace_body
    target:
      app: teastore-auth
      method: POST
      namespace: teastore
      path: /tools.descartes.teastore.auth/rest/useractions/isloggedin
      port: 8080
      server_address: teastore-auth
      span_name: POST /tools.descartes.teastore.auth/rest/useractions/isloggedin
  - capability: http_response_replace_body
    target:
      app: teastore-auth
      method: POST
      namespace: teastore
      path: /tools.descartes.teastore.auth/rest/useractions/login
      port: 8080
      server_address: teastore-auth
      span_name: POST /tools.descartes.teastore.auth/rest/useractions/login
  - capability: http_response_replace_body
    target:
      app: teastore-auth
      method: POST
      namespace: teastore
      path: /tools.descartes.teastore.auth/rest/useractions/logout
      port: 8080
      server_address: teastore-auth
      span_name: POST /tools.descartes.teastore.auth/rest/useractions/logout
  - capability: http_response_replace_body
    target:
      app: teastore-auth
      method: PUT
      namespace: teastore
      path: /tools.descartes.teastore.registry/rest/services/tools.descartes.teastore.auth/teastore-auth-0.teastore-auth
      port: 8080
      server_address: teastore-registry
      span_name: PUT
  - capability: http_response_replace_code
    target:
      app: teastore-auth
      method: GET
      namespace: teastore
      path: /tools.descartes.teastore.registry/rest/services/tools.descartes.teastore.persistence/
      port: 8080
      server_address: teastore-registry
      span_name: GET
  - capability: http_response_replace_code
    target:
      app: teastore-auth
      method: POST
      namespace: teastore
      path: /tools.descartes.teastore.auth/rest/cart/add/*
      port: 8080
      server_address: teastore-auth
      span_name: POST /tools.descartes.teastore.auth/rest/cart/add/{pid}
  - capability: http_response_replace_code
    target:
      app: teastore-auth
      method: POST
      namespace: teastore
      path: /tools.descartes.teastore.auth/rest/useractions/isloggedin
      port: 8080
      server_address: teastore-auth
      span_name: POST /tools.descartes.teastore.auth/rest/useractions/isloggedin
  - capability: http_response_replace_code
    target:
      app: teastore-auth
      method: POST
      namespace: teastore
      path: /tools.descartes.teastore.auth/rest/useractions/login
      port: 8080
      server_address: teastore-auth
      span_name: POST /tools.descartes.teastore.auth/rest/useractions/login
  - capability: http_response_replace_code
    target:
      app: teastore-auth
      method: POST
      namespace: teastore
      path: /tools.descartes.teastore.auth/rest/useractions/logout
      port: 8080
      server_address: teastore-auth
      span_name: POST /tools.descartes.teastore.auth/rest/useractions/logout
  - capability: http_response_replace_code
    target:
      app: teastore-auth
      method: PUT
      namespace: teastore
      path: /tools.descartes.teastore.registry/rest/services/tools.descartes.teastore.auth/teastore-auth-0.teastore-auth
      port: 8080
      server_address: teastore-registry
      span_name: PUT
  replace_scope: service
