apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: seed-genesis
  instance: seed
  service: teastore-webui
  system: teastore
spec:
  points:
  - capability: http_request_replace_method
    target:
      app: teastore-webui
      method: GET
      namespace: teastore
      path: /tools.descartes.teastore.registry/rest/services/tools.descartes.teastore.auth/
      port: 8080
  - capability: http_request_replace_method
    target:
      app: teastore-webui
      method: GET
      namespace: teastore
      path: /tools.descartes.teastore.registry/rest/services/tools.descartes.teastore.image/
      port: 8080
  - capability: http_request_replace_method
    target:
      app: teastore-webui
      method: GET
      namespace: teastore
      path: /tools.descartes.teastore.registry/rest/services/tools.descartes.teastore.persistence/
      port: 8080
  - capability: http_request_replace_method
    target:
      app: teastore-webui
      method: GET
      namespace: teastore
      path: /tools.descartes.teastore.registry/rest/services/tools.descartes.teastore.recommender/
      port: 8080
  - capability: http_request_replace_method
    target:
      app: teastore-webui
      method: PUT
      namespace: teastore
      path: /tools.descartes.teastore.registry/rest/services/tools.descartes.teastore.webui/teastore-webui-0.teastore-webui
      port: 8080
  - capability: http_request_replace_path
    target:
      app: teastore-webui
      method: GET
      namespace: teastore
      path: /tools.descartes.teastore.registry/rest/services/tools.descartes.teastore.auth/
      port: 8080
  - capability: http_request_replace_path
    target:
      app: teastore-webui
      method: GET
      namespace: teastore
      path: /tools.descartes.teastore.registry/rest/services/tools.descartes.teastore.image/
      port: 8080
  - capability: http_request_replace_path
    target:
      app: teastore-webui
      method: GET
      namespace: teastore
      path: /tools.descartes.teastore.registry/rest/services/tools.descartes.teastore.persistence/
      port: 8080
  - capability: http_request_replace_path
    target:
      app: teastore-webui
      method: GET
      namespace: teastore
      path: /tools.descartes.teastore.registry/rest/services/tools.descartes.teastore.recommender/
      port: 8080
  - capability: http_request_replace_path
    target:
      app: teastore-webui
      method: PUT
      namespace: teastore
      path: /tools.descartes.teastore.registry/rest/services/tools.descartes.teastore.webui/teastore-webui-0.teastore-webui
      port: 8080
  - capability: http_response_abort
    target:
      app: teastore-webui
      method: GET
      namespace: teastore
      path: /tools.descartes.teastore.registry/rest/services/tools.descartes.teastore.auth/
      port: 8080
  - capability: http_response_abort
    target:
      app: teastore-webui
      method: GET
      namespace: teastore
      path: /tools.descartes.teastore.registry/rest/services/tools.descartes.teastore.image/
      port: 8080
  - capability: http_response_abort
    target:
      app: teastore-webui
      method: GET
      namespace: teastore
      path: /tools.descartes.teastore.registry/rest/services/tools.descartes.teastore.persistence/
      port: 8080
  - capability: http_response_abort
    target:
      app: teastore-webui
      method: GET
      namespace: teastore
      path: /tools.descartes.teastore.registry/rest/services/tools.descartes.teastore.recommender/
      port: 8080
  - capability: http_response_abort
    target:
      app: teastore-webui
      method: PUT
      namespace: teastore
      path: /tools.descartes.teastore.registry/rest/services/tools.descartes.teastore.webui/teastore-webui-0.teastore-webui
      port: 8080
  - capability: http_response_delay
    target:
      app: teastore-webui
      method: GET
      namespace: teastore
      path: /tools.descartes.teastore.registry/rest/services/tools.descartes.teastore.auth/
      port: 8080
  - capability: http_response_delay
    target:
      app: teastore-webui
      method: GET
      namespace: teastore
      path: /tools.descartes.teastore.registry/rest/services/tools.descartes.teastore.image/
      port: 8080
  - capability: http_response_delay
    target:
      app: teastore-webui
      method: GET
      namespace: teastore
      path: /tools.descartes.teastore.registry/rest/services/tools.descartes.teastore.persistence/
      port: 8080
  - capability: http_response_delay
    target:
      app: teastore-webui
      method: GET
      namespace: teastore
      path: /tools.descartes.teastore.registry/rest/services/tools.descartes.teastore.recommender/
      port: 8080
  - capability: http_response_delay
    target:
      app: teastore-webui
      method: PUT
      namespace: teastore
      path: /tools.descartes.teastore.registry/rest/services/tools.descartes.teastore.webui/teastore-webui-0.teastore-webui
      port: 8080
  - capability: http_response_patch_body
    target:
      app: teastore-webui
      method: GET
      namespace: teastore
      path: /tools.descartes.teastore.registry/rest/services/tools.descartes.teastore.auth/
      port: 8080
  - capability: http_response_patch_body
    target:
      app: teastore-webui
      method: GET
      namespace: teastore
      path: /tools.descartes.teastore.registry/rest/services/tools.descartes.teastore.image/
      port: 8080
  - capability: http_response_patch_body
    target:
      app: teastore-webui
      method: GET
      namespace: teastore
      path: /tools.descartes.teastore.registry/rest/services/tools.descartes.teastore.persistence/
      port: 8080
  - capability: http_response_patch_body
    target:
      app: teastore-webui
      method: GET
      namespace: teastore
      path: /tools.descartes.teastore.registry/rest/services/tools.descartes.teastore.recommender/
      port: 8080
  - capability: http_response_patch_body
    target:
      app: teastore-webui
      method: PUT
      namespace: teastore
      path: /tools.descartes.teastore.registry/rest/services/tools.descartes.teastore.webui/teastore-webui-0.teastore-webui
      port: 8080
  - capability: http_response_replace_body
    target:
      app: teastore-webui
      method: GET
      namespace: teastore
      path: /tools.descartes.teastore.registry/rest/services/tools.descartes.teastore.auth/
      port: 8080
  - capability: http_response_replace_body
    target:
      app: teastore-webui
      method: GET
      namespace: teastore
      path: /tools.descartes.teastore.registry/rest/services/tools.descartes.teastore.image/
      port: 8080
  - capability: http_response_replace_body
    target:
      app: teastore-webui
      method: GET
      namespace: teastore
      path: /tools.descartes.teastore.registry/rest/services/tools.descartes.teastore.persistence/
      port: 8080
  - capability: http_response_replace_body
    target:
      app: teastore-webui
      method: GET
      namespace: teastore
      path: /tools.descartes.teastore.registry/rest/services/tools.descartes.teastore.recommender/
      port: 8080
  - capability: http_response_replace_body
    target:
      app: teastore-webui
      method: PUT
      namespace: teastore
      path: /tools.descartes.teastore.registry/rest/services/tools.descartes.teastore.webui/teastore-webui-0.teastore-webui
      port: 8080
  - capability: http_response_replace_code
    target:
      app: teastore-webui
      method: GET
      namespace: teastore
      path: /tools.descartes.teastore.registry/rest/services/tools.descartes.teastore.auth/
      port: 8080
  - capability: http_response_replace_code
    target:
      app: teastore-webui
      method: GET
      namespace: teastore
      path: /tools.descartes.teastore.registry/rest/services/tools.descartes.teastore.image/
      port: 8080
  - capability: http_response_replace_code
    target:
      app: teastore-webui
      method: GET
      namespace: teastore
      path: /tools.descartes.teastore.registry/rest/services/tools.descartes.teastore.persistence/
      port: 8080
  - capability: http_response_replace_code
    target:
      app: teastore-webui
      method: GET
      namespace: teastore
      path: /tools.descartes.teastore.registry/rest/services/tools.descartes.teastore.recommender/
      port: 8080
  - capability: http_response_replace_code
    target:
      app: teastore-webui
      method: PUT
      namespace: teastore
      path: /tools.descartes.teastore.registry/rest/services/tools.descartes.teastore.webui/teastore-webui-0.teastore-webui
      port: 8080
  replace_scope: service
