apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: "observed-genesis"
  instance: "observed"
  service: "teastore-recommender"
  system: "teastore"
spec:
  replace_scope: "service"
  points:
    - capability: "pod_kill"
      target:
        app: "teastore-recommender"
        namespace: "teastore"
    - capability: "pod_failure"
      target:
        app: "teastore-recommender"
        namespace: "teastore"
    - capability: "container_kill"
      target:
        app: "teastore-recommender"
        container: "recommender"
        namespace: "teastore"
    - capability: "cpu_stress"
      target:
        app: "teastore-recommender"
        container: "recommender"
        namespace: "teastore"
    - capability: "time_skew"
      target:
        app: "teastore-recommender"
        container: "recommender"
        namespace: "teastore"
    - capability: "http_request_delay"
      target:
        app: "teastore-recommender"
        method: "POST"
        namespace: "teastore"
        path: "/tools.descartes.teastore.recommender/rest/recommend"
        port: 8080
        server_address: "teastore-recommender"
        span_name: "POST /tools.descartes.teastore.recommender/rest/recommend"
    - capability: "http_request_abort"
      target:
        app: "teastore-recommender"
        method: "POST"
        namespace: "teastore"
        path: "/tools.descartes.teastore.recommender/rest/recommend"
        port: 8080
        server_address: "teastore-recommender"
        span_name: "POST /tools.descartes.teastore.recommender/rest/recommend"
    - capability: "http_response_abort"
      target:
        app: "teastore-recommender"
        method: "POST"
        namespace: "teastore"
        path: "/tools.descartes.teastore.recommender/rest/recommend"
        port: 8080
    - capability: "http_response_delay"
      target:
        app: "teastore-recommender"
        method: "POST"
        namespace: "teastore"
        path: "/tools.descartes.teastore.recommender/rest/recommend"
        port: 8080
    - capability: "http_response_replace_code"
      target:
        app: "teastore-recommender"
        method: "POST"
        namespace: "teastore"
        path: "/tools.descartes.teastore.recommender/rest/recommend"
        port: 8080
    - capability: "http_response_patch_body"
      target:
        app: "teastore-recommender"
        method: "POST"
        namespace: "teastore"
        path: "/tools.descartes.teastore.recommender/rest/recommend"
        port: 8080
    - capability: "http_response_replace_body"
      target:
        app: "teastore-recommender"
        method: "POST"
        namespace: "teastore"
        path: "/tools.descartes.teastore.recommender/rest/recommend"
        port: 8080
    - capability: "http_request_replace_method"
      target:
        app: "teastore-recommender"
        method: "POST"
        namespace: "teastore"
        path: "/tools.descartes.teastore.recommender/rest/recommend"
        port: 8080
    - capability: "http_request_replace_path"
      target:
        app: "teastore-recommender"
        method: "POST"
        namespace: "teastore"
        path: "/tools.descartes.teastore.recommender/rest/recommend"
        port: 8080
    - capability: "dns_error"
      target:
        app: "teastore-recommender"
        domain_patterns:
          - "teastore-registry"
        namespace: "teastore"
    - capability: "dns_random"
      target:
        app: "teastore-recommender"
        domain_patterns:
          - "teastore-registry"
        namespace: "teastore"
    - capability: "network_delay"
      target:
        namespace: "teastore"
        source_app: "teastore-recommender"
        span_names:
          - "GET /rest/services/{name}"
          - "PUT /rest/services/{name}/{location}"
        target_service: "teastore-registry"
    - capability: "network_loss"
      target:
        namespace: "teastore"
        source_app: "teastore-recommender"
        span_names:
          - "GET /rest/services/{name}"
          - "PUT /rest/services/{name}/{location}"
        target_service: "teastore-registry"
    - capability: "network_duplicate"
      target:
        namespace: "teastore"
        source_app: "teastore-recommender"
        span_names:
          - "GET /rest/services/{name}"
          - "PUT /rest/services/{name}/{location}"
        target_service: "teastore-registry"
    - capability: "network_corrupt"
      target:
        namespace: "teastore"
        source_app: "teastore-recommender"
        span_names:
          - "GET /rest/services/{name}"
          - "PUT /rest/services/{name}/{location}"
        target_service: "teastore-registry"
    - capability: "network_bandwidth"
      target:
        namespace: "teastore"
        source_app: "teastore-recommender"
        span_names:
          - "GET /rest/services/{name}"
          - "PUT /rest/services/{name}/{location}"
        target_service: "teastore-registry"
    - capability: "network_partition"
      target:
        namespace: "teastore"
        source_app: "teastore-recommender"
        span_names:
          - "GET /rest/services/{name}"
          - "PUT /rest/services/{name}/{location}"
        target_service: "teastore-registry"
