#!/usr/bin/env python3
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
SRC_ROOT = REPO_ROOT / 'src'
MODULE_ROOT = SRC_ROOT / 'module'
OUTPUT = SRC_ROOT / 'app' / 'http_modules_gen.go'

# Modules owned by the standalone aegis-sso process; not loaded by the
# AegisLab backend HTTP graph. See docs/sso-extraction-design.md §7.
SSO_OWNED_MODULES = {'user', 'auth', 'rbac', 'sso', 'ssoclient'}


def discover_modules() -> list[str]:
    modules: list[str] = []
    for entry in sorted(MODULE_ROOT.iterdir()):
        if not entry.is_dir():
            continue
        if entry.name in SSO_OWNED_MODULES:
            continue
        if (entry / 'module.go').exists():
            modules.append(entry.name)
    return modules


def generate(modules: list[str]) -> str:
    imports = '\n'.join(f'\t{name} "aegis/module/{name}"' for name in modules)
    options = '\n'.join(f'\t\t{name}.Module,' for name in modules)
    names = '\n'.join(f'\t\t"{name}",' for name in modules)
    return f'''// Code generated by scripts/generate_http_modules.py; DO NOT EDIT.\npackage app\n\nimport (\n{imports}\n\t"aegis/router"\n\t"go.uber.org/fx"\n)\n\nfunc producerHTTPModules() []fx.Option {{\n\treturn []fx.Option{{\n{options}\n\t\trouter.Module,\n\t}}\n}}\n\nfunc producerHTTPModuleNames() []string {{\n\treturn []string{{\n{names}\n\t}}\n}}\n'''


def main() -> None:
    OUTPUT.write_text(generate(discover_modules()))


if __name__ == '__main__':
    main()
