apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: "seed-genesis"
  instance: "seed"
  service: "ts-admin-travel-service"
  system: "ts"
spec:
  replace_scope: "service"
  points:
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-admin-travel-service"
        class: "admintravel.AdminTravelApplication"
        method: "main"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-admin-travel-service"
        class: "admintravel.controller.AdminTravelController"
        method: "addTravel"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-admin-travel-service"
        class: "admintravel.controller.AdminTravelController"
        method: "deleteTravel"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-admin-travel-service"
        class: "admintravel.controller.AdminTravelController"
        method: "getAllTravels"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-admin-travel-service"
        class: "admintravel.controller.AdminTravelController"
        method: "home"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-admin-travel-service"
        class: "admintravel.controller.AdminTravelController"
        method: "updateTravel"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-admin-travel-service"
        class: "admintravel.service.AdminTravelServiceImpl"
        method: "addTravel"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-admin-travel-service"
        class: "admintravel.service.AdminTravelServiceImpl"
        method: "checkStationsExists"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-admin-travel-service"
        class: "admintravel.service.AdminTravelServiceImpl"
        method: "checkTravelInfo"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-admin-travel-service"
        class: "admintravel.service.AdminTravelServiceImpl"
        method: "deleteTravel"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-admin-travel-service"
        class: "admintravel.service.AdminTravelServiceImpl"
        method: "getAllTravels"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-admin-travel-service"
        class: "admintravel.service.AdminTravelServiceImpl"
        method: "getRouteByRouteId"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-admin-travel-service"
        class: "admintravel.service.AdminTravelServiceImpl"
        method: "getServiceUrl"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-admin-travel-service"
        class: "admintravel.service.AdminTravelServiceImpl"
        method: "queryTrainTypeByName"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-admin-travel-service"
        class: "admintravel.service.AdminTravelServiceImpl"
        method: "updateTravel"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-admin-travel-service"
        class: "admintravel.AdminTravelApplication"
        method: "main"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-admin-travel-service"
        class: "admintravel.controller.AdminTravelController"
        method: "addTravel"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-admin-travel-service"
        class: "admintravel.controller.AdminTravelController"
        method: "deleteTravel"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-admin-travel-service"
        class: "admintravel.controller.AdminTravelController"
        method: "getAllTravels"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-admin-travel-service"
        class: "admintravel.controller.AdminTravelController"
        method: "home"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-admin-travel-service"
        class: "admintravel.controller.AdminTravelController"
        method: "updateTravel"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-admin-travel-service"
        class: "admintravel.service.AdminTravelServiceImpl"
        method: "addTravel"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-admin-travel-service"
        class: "admintravel.service.AdminTravelServiceImpl"
        method: "checkStationsExists"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-admin-travel-service"
        class: "admintravel.service.AdminTravelServiceImpl"
        method: "checkTravelInfo"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-admin-travel-service"
        class: "admintravel.service.AdminTravelServiceImpl"
        method: "deleteTravel"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-admin-travel-service"
        class: "admintravel.service.AdminTravelServiceImpl"
        method: "getAllTravels"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-admin-travel-service"
        class: "admintravel.service.AdminTravelServiceImpl"
        method: "getRouteByRouteId"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-admin-travel-service"
        class: "admintravel.service.AdminTravelServiceImpl"
        method: "getServiceUrl"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-admin-travel-service"
        class: "admintravel.service.AdminTravelServiceImpl"
        method: "queryTrainTypeByName"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-admin-travel-service"
        class: "admintravel.service.AdminTravelServiceImpl"
        method: "updateTravel"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-admin-travel-service"
        class: "admintravel.AdminTravelApplication"
        method: "main"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-admin-travel-service"
        class: "admintravel.controller.AdminTravelController"
        method: "addTravel"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-admin-travel-service"
        class: "admintravel.controller.AdminTravelController"
        method: "deleteTravel"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-admin-travel-service"
        class: "admintravel.controller.AdminTravelController"
        method: "getAllTravels"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-admin-travel-service"
        class: "admintravel.controller.AdminTravelController"
        method: "home"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-admin-travel-service"
        class: "admintravel.controller.AdminTravelController"
        method: "updateTravel"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-admin-travel-service"
        class: "admintravel.service.AdminTravelServiceImpl"
        method: "addTravel"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-admin-travel-service"
        class: "admintravel.service.AdminTravelServiceImpl"
        method: "checkStationsExists"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-admin-travel-service"
        class: "admintravel.service.AdminTravelServiceImpl"
        method: "checkTravelInfo"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-admin-travel-service"
        class: "admintravel.service.AdminTravelServiceImpl"
        method: "deleteTravel"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-admin-travel-service"
        class: "admintravel.service.AdminTravelServiceImpl"
        method: "getAllTravels"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-admin-travel-service"
        class: "admintravel.service.AdminTravelServiceImpl"
        method: "getRouteByRouteId"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-admin-travel-service"
        class: "admintravel.service.AdminTravelServiceImpl"
        method: "getServiceUrl"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-admin-travel-service"
        class: "admintravel.service.AdminTravelServiceImpl"
        method: "queryTrainTypeByName"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-admin-travel-service"
        class: "admintravel.service.AdminTravelServiceImpl"
        method: "updateTravel"
        namespace: "ts"
