apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: "observed-genesis"
  instance: "observed"
  service: "ts-consign-price-service"
  system: "ts"
spec:
  replace_scope: "service"
  points:
    - capability: "pod_kill"
      target:
        app: "ts-consign-price-service"
        namespace: "ts"
    - capability: "pod_failure"
      target:
        app: "ts-consign-price-service"
        namespace: "ts"
    - capability: "container_kill"
      target:
        app: "ts-consign-price-service"
        container: "ts-consign-price-service"
        namespace: "ts"
    - capability: "cpu_stress"
      target:
        app: "ts-consign-price-service"
        container: "ts-consign-price-service"
        namespace: "ts"
    - capability: "time_skew"
      target:
        app: "ts-consign-price-service"
        container: "ts-consign-price-service"
        namespace: "ts"
    - capability: "http_request_delay"
      target:
        app: "ts-consign-price-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/consignpriceservice/consignprice/{weight}/{isWithinRegion}"
        port: 8080
        server_address: "ts-consign-price-service"
        span_name: "GET /api/v1/consignpriceservice/consignprice/{weight}/{isWithinRegion}"
    - capability: "http_request_abort"
      target:
        app: "ts-consign-price-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/consignpriceservice/consignprice/{weight}/{isWithinRegion}"
        port: 8080
        server_address: "ts-consign-price-service"
        span_name: "GET /api/v1/consignpriceservice/consignprice/{weight}/{isWithinRegion}"
    - capability: "http_response_abort"
      target:
        app: "ts-consign-price-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/consignpriceservice/consignprice/{weight}/{isWithinRegion}"
        port: 8080
    - capability: "http_response_delay"
      target:
        app: "ts-consign-price-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/consignpriceservice/consignprice/{weight}/{isWithinRegion}"
        port: 8080
    - capability: "http_response_replace_code"
      target:
        app: "ts-consign-price-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/consignpriceservice/consignprice/{weight}/{isWithinRegion}"
        port: 8080
    - capability: "http_response_patch_body"
      target:
        app: "ts-consign-price-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/consignpriceservice/consignprice/{weight}/{isWithinRegion}"
        port: 8080
    - capability: "http_response_replace_body"
      target:
        app: "ts-consign-price-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/consignpriceservice/consignprice/{weight}/{isWithinRegion}"
        port: 8080
    - capability: "http_request_replace_method"
      target:
        app: "ts-consign-price-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/consignpriceservice/consignprice/{weight}/{isWithinRegion}"
        port: 8080
    - capability: "http_request_replace_path"
      target:
        app: "ts-consign-price-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/consignpriceservice/consignprice/{weight}/{isWithinRegion}"
        port: 8080
    - capability: "network_delay"
      target:
        namespace: "ts"
        source_app: "ts-consign-price-service"
        target_service: "mysql"
    - capability: "network_loss"
      target:
        namespace: "ts"
        source_app: "ts-consign-price-service"
        target_service: "mysql"
    - capability: "network_duplicate"
      target:
        namespace: "ts"
        source_app: "ts-consign-price-service"
        target_service: "mysql"
    - capability: "network_corrupt"
      target:
        namespace: "ts"
        source_app: "ts-consign-price-service"
        target_service: "mysql"
    - capability: "network_bandwidth"
      target:
        namespace: "ts"
        source_app: "ts-consign-price-service"
        target_service: "mysql"
    - capability: "network_partition"
      target:
        namespace: "ts"
        source_app: "ts-consign-price-service"
        target_service: "mysql"
    - capability: "jvm_mysql_latency"
      target:
        app: "ts-consign-price-service"
        db_name: "ts"
        namespace: "ts"
        sql_type: "select"
        table: "consign_price"
    - capability: "jvm_mysql_exception"
      target:
        app: "ts-consign-price-service"
        db_name: "ts"
        namespace: "ts"
        sql_type: "select"
        table: "consign_price"
