apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: "observed-genesis"
  instance: "observed"
  service: "ts-execute-service"
  system: "ts"
spec:
  replace_scope: "service"
  points:
    - capability: "pod_kill"
      target:
        app: "ts-execute-service"
        namespace: "ts"
    - capability: "pod_failure"
      target:
        app: "ts-execute-service"
        namespace: "ts"
    - capability: "container_kill"
      target:
        app: "ts-execute-service"
        container: "ts-execute-service"
        namespace: "ts"
    - capability: "cpu_stress"
      target:
        app: "ts-execute-service"
        container: "ts-execute-service"
        namespace: "ts"
    - capability: "time_skew"
      target:
        app: "ts-execute-service"
        container: "ts-execute-service"
        namespace: "ts"
    - capability: "http_request_delay"
      target:
        app: "ts-execute-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/executeservice/execute/collected/{orderId}"
        port: 8080
        server_address: "ts-execute-service"
        span_name: "GET /api/v1/executeservice/execute/collected/{orderId}"
    - capability: "http_request_abort"
      target:
        app: "ts-execute-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/executeservice/execute/collected/{orderId}"
        port: 8080
        server_address: "ts-execute-service"
        span_name: "GET /api/v1/executeservice/execute/collected/{orderId}"
    - capability: "http_response_abort"
      target:
        app: "ts-execute-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/executeservice/execute/collected/{orderId}"
        port: 8080
    - capability: "http_response_delay"
      target:
        app: "ts-execute-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/executeservice/execute/collected/{orderId}"
        port: 8080
    - capability: "http_response_replace_code"
      target:
        app: "ts-execute-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/executeservice/execute/collected/{orderId}"
        port: 8080
    - capability: "http_response_patch_body"
      target:
        app: "ts-execute-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/executeservice/execute/collected/{orderId}"
        port: 8080
    - capability: "http_response_replace_body"
      target:
        app: "ts-execute-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/executeservice/execute/collected/{orderId}"
        port: 8080
    - capability: "http_request_replace_method"
      target:
        app: "ts-execute-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/executeservice/execute/collected/{orderId}"
        port: 8080
    - capability: "http_request_replace_path"
      target:
        app: "ts-execute-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/executeservice/execute/collected/{orderId}"
        port: 8080
    - capability: "http_request_delay"
      target:
        app: "ts-execute-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/executeservice/execute/execute/{orderId}"
        port: 8080
        server_address: "ts-execute-service"
        span_name: "GET /api/v1/executeservice/execute/execute/{orderId}"
    - capability: "http_request_abort"
      target:
        app: "ts-execute-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/executeservice/execute/execute/{orderId}"
        port: 8080
        server_address: "ts-execute-service"
        span_name: "GET /api/v1/executeservice/execute/execute/{orderId}"
    - capability: "http_response_abort"
      target:
        app: "ts-execute-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/executeservice/execute/execute/{orderId}"
        port: 8080
    - capability: "http_response_delay"
      target:
        app: "ts-execute-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/executeservice/execute/execute/{orderId}"
        port: 8080
    - capability: "http_response_replace_code"
      target:
        app: "ts-execute-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/executeservice/execute/execute/{orderId}"
        port: 8080
    - capability: "http_response_patch_body"
      target:
        app: "ts-execute-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/executeservice/execute/execute/{orderId}"
        port: 8080
    - capability: "http_response_replace_body"
      target:
        app: "ts-execute-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/executeservice/execute/execute/{orderId}"
        port: 8080
    - capability: "http_request_replace_method"
      target:
        app: "ts-execute-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/executeservice/execute/execute/{orderId}"
        port: 8080
    - capability: "http_request_replace_path"
      target:
        app: "ts-execute-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/executeservice/execute/execute/{orderId}"
        port: 8080
    - capability: "dns_error"
      target:
        app: "ts-execute-service"
        domain_patterns:
          - "ts-order-other-service"
        namespace: "ts"
    - capability: "dns_random"
      target:
        app: "ts-execute-service"
        domain_patterns:
          - "ts-order-other-service"
        namespace: "ts"
    - capability: "network_delay"
      target:
        namespace: "ts"
        source_app: "ts-execute-service"
        span_names:
          - "GET /api/v1/orderOtherService/orderOther/status/{orderId}/{status}"
          - "GET /api/v1/orderOtherService/orderOther/{orderId}"
        target_service: "ts-order-other-service"
    - capability: "network_loss"
      target:
        namespace: "ts"
        source_app: "ts-execute-service"
        span_names:
          - "GET /api/v1/orderOtherService/orderOther/status/{orderId}/{status}"
          - "GET /api/v1/orderOtherService/orderOther/{orderId}"
        target_service: "ts-order-other-service"
    - capability: "network_duplicate"
      target:
        namespace: "ts"
        source_app: "ts-execute-service"
        span_names:
          - "GET /api/v1/orderOtherService/orderOther/status/{orderId}/{status}"
          - "GET /api/v1/orderOtherService/orderOther/{orderId}"
        target_service: "ts-order-other-service"
    - capability: "network_corrupt"
      target:
        namespace: "ts"
        source_app: "ts-execute-service"
        span_names:
          - "GET /api/v1/orderOtherService/orderOther/status/{orderId}/{status}"
          - "GET /api/v1/orderOtherService/orderOther/{orderId}"
        target_service: "ts-order-other-service"
    - capability: "network_bandwidth"
      target:
        namespace: "ts"
        source_app: "ts-execute-service"
        span_names:
          - "GET /api/v1/orderOtherService/orderOther/status/{orderId}/{status}"
          - "GET /api/v1/orderOtherService/orderOther/{orderId}"
        target_service: "ts-order-other-service"
    - capability: "network_partition"
      target:
        namespace: "ts"
        source_app: "ts-execute-service"
        span_names:
          - "GET /api/v1/orderOtherService/orderOther/status/{orderId}/{status}"
          - "GET /api/v1/orderOtherService/orderOther/{orderId}"
        target_service: "ts-order-other-service"
    - capability: "dns_error"
      target:
        app: "ts-execute-service"
        domain_patterns:
          - "ts-order-service"
        namespace: "ts"
    - capability: "dns_random"
      target:
        app: "ts-execute-service"
        domain_patterns:
          - "ts-order-service"
        namespace: "ts"
    - capability: "network_delay"
      target:
        namespace: "ts"
        source_app: "ts-execute-service"
        span_names:
          - "GET /api/v1/orderservice/order/{orderId}"
        target_service: "ts-order-service"
    - capability: "network_loss"
      target:
        namespace: "ts"
        source_app: "ts-execute-service"
        span_names:
          - "GET /api/v1/orderservice/order/{orderId}"
        target_service: "ts-order-service"
    - capability: "network_duplicate"
      target:
        namespace: "ts"
        source_app: "ts-execute-service"
        span_names:
          - "GET /api/v1/orderservice/order/{orderId}"
        target_service: "ts-order-service"
    - capability: "network_corrupt"
      target:
        namespace: "ts"
        source_app: "ts-execute-service"
        span_names:
          - "GET /api/v1/orderservice/order/{orderId}"
        target_service: "ts-order-service"
    - capability: "network_bandwidth"
      target:
        namespace: "ts"
        source_app: "ts-execute-service"
        span_names:
          - "GET /api/v1/orderservice/order/{orderId}"
        target_service: "ts-order-service"
    - capability: "network_partition"
      target:
        namespace: "ts"
        source_app: "ts-execute-service"
        span_names:
          - "GET /api/v1/orderservice/order/{orderId}"
        target_service: "ts-order-service"
