apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: "observed-genesis"
  instance: "observed"
  service: "ts-notification-service"
  system: "ts"
spec:
  replace_scope: "service"
  points:
    - capability: "pod_kill"
      target:
        app: "ts-notification-service"
        namespace: "ts"
    - capability: "pod_failure"
      target:
        app: "ts-notification-service"
        namespace: "ts"
    - capability: "container_kill"
      target:
        app: "ts-notification-service"
        container: "ts-notification-service"
        namespace: "ts"
    - capability: "cpu_stress"
      target:
        app: "ts-notification-service"
        container: "ts-notification-service"
        namespace: "ts"
    - capability: "time_skew"
      target:
        app: "ts-notification-service"
        container: "ts-notification-service"
        namespace: "ts"
