apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: "seed-genesis"
  instance: "seed"
  service: "ts-wait-order-service"
  system: "ts"
spec:
  replace_scope: "service"
  points:
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.WaitOrderApplication"
        method: "main"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.controller.WaitListOrderController"
        method: "createNewOrder"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.controller.WaitListOrderController"
        method: "getAllOrders"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.controller.WaitListOrderController"
        method: "getWaitListOrders"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.controller.WaitListOrderController"
        method: "home"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.entity.WaitListOrder"
        method: "WaitListOrder"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.entity.WaitListOrder"
        method: "getCreatedTime"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.entity.WaitListOrder"
        method: "getTravelTime"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.entity.WaitListOrder"
        method: "getWaitUtilTime"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.entity.WaitListOrder"
        method: "hashCode"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.entity.WaitListOrder"
        method: "setCreatedTime"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.entity.WaitListOrder"
        method: "setTravelTime"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.entity.WaitListOrder"
        method: "setWaitUntilTime"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.entity.WaitListOrderVO"
        method: "getDate"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.entity.WaitListOrderVO"
        method: "setDate"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.service.Impl.WaitListOrderServiceImpl"
        method: "WaitListOrderExist"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.service.Impl.WaitListOrderServiceImpl"
        method: "create"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.service.Impl.WaitListOrderServiceImpl"
        method: "findOrderById"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.service.Impl.WaitListOrderServiceImpl"
        method: "getAllOrders"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.service.Impl.WaitListOrderServiceImpl"
        method: "getAllWaitListOrders"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.service.Impl.WaitListOrderServiceImpl"
        method: "modifyWaitListOrderStatus"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.service.Impl.WaitListOrderServiceImpl"
        method: "saveNewOrder"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.service.Impl.WaitListOrderServiceImpl"
        method: "triggerThread"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.service.Impl.WaitListOrderServiceImpl"
        method: "updateOrder"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.utils.PollThread"
        method: "PollThread"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.utils.PollThread"
        method: "doPreserve"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.utils.PollThread"
        method: "getServiceUrl"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.utils.PollThread"
        method: "run"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.WaitOrderApplication"
        method: "main"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.controller.WaitListOrderController"
        method: "createNewOrder"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.controller.WaitListOrderController"
        method: "getAllOrders"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.controller.WaitListOrderController"
        method: "getWaitListOrders"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.controller.WaitListOrderController"
        method: "home"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.entity.WaitListOrder"
        method: "WaitListOrder"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.entity.WaitListOrder"
        method: "getCreatedTime"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.entity.WaitListOrder"
        method: "getTravelTime"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.entity.WaitListOrder"
        method: "getWaitUtilTime"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.entity.WaitListOrder"
        method: "hashCode"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.entity.WaitListOrder"
        method: "setCreatedTime"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.entity.WaitListOrder"
        method: "setTravelTime"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.entity.WaitListOrder"
        method: "setWaitUntilTime"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.entity.WaitListOrderVO"
        method: "getDate"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.entity.WaitListOrderVO"
        method: "setDate"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.service.Impl.WaitListOrderServiceImpl"
        method: "WaitListOrderExist"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.service.Impl.WaitListOrderServiceImpl"
        method: "create"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.service.Impl.WaitListOrderServiceImpl"
        method: "findOrderById"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.service.Impl.WaitListOrderServiceImpl"
        method: "getAllOrders"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.service.Impl.WaitListOrderServiceImpl"
        method: "getAllWaitListOrders"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.service.Impl.WaitListOrderServiceImpl"
        method: "modifyWaitListOrderStatus"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.service.Impl.WaitListOrderServiceImpl"
        method: "saveNewOrder"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.service.Impl.WaitListOrderServiceImpl"
        method: "triggerThread"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.service.Impl.WaitListOrderServiceImpl"
        method: "updateOrder"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.utils.PollThread"
        method: "PollThread"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.utils.PollThread"
        method: "doPreserve"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.utils.PollThread"
        method: "getServiceUrl"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.utils.PollThread"
        method: "run"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.WaitOrderApplication"
        method: "main"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.controller.WaitListOrderController"
        method: "createNewOrder"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.controller.WaitListOrderController"
        method: "getAllOrders"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.controller.WaitListOrderController"
        method: "getWaitListOrders"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.controller.WaitListOrderController"
        method: "home"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.entity.WaitListOrder"
        method: "WaitListOrder"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.entity.WaitListOrder"
        method: "getCreatedTime"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.entity.WaitListOrder"
        method: "getTravelTime"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.entity.WaitListOrder"
        method: "getWaitUtilTime"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.entity.WaitListOrder"
        method: "hashCode"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.entity.WaitListOrder"
        method: "setCreatedTime"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.entity.WaitListOrder"
        method: "setTravelTime"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.entity.WaitListOrder"
        method: "setWaitUntilTime"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.entity.WaitListOrderVO"
        method: "getDate"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.entity.WaitListOrderVO"
        method: "setDate"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.service.Impl.WaitListOrderServiceImpl"
        method: "WaitListOrderExist"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.service.Impl.WaitListOrderServiceImpl"
        method: "create"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.service.Impl.WaitListOrderServiceImpl"
        method: "findOrderById"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.service.Impl.WaitListOrderServiceImpl"
        method: "getAllOrders"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.service.Impl.WaitListOrderServiceImpl"
        method: "getAllWaitListOrders"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.service.Impl.WaitListOrderServiceImpl"
        method: "modifyWaitListOrderStatus"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.service.Impl.WaitListOrderServiceImpl"
        method: "saveNewOrder"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.service.Impl.WaitListOrderServiceImpl"
        method: "triggerThread"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.service.Impl.WaitListOrderServiceImpl"
        method: "updateOrder"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.utils.PollThread"
        method: "PollThread"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.utils.PollThread"
        method: "doPreserve"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.utils.PollThread"
        method: "getServiceUrl"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-wait-order-service"
        class: "waitorder.utils.PollThread"
        method: "run"
        namespace: "ts"
