/*
RCABench API

RCABench - A comprehensive root cause analysis benchmarking platform for microservices

API version: 1.0.0
Contact: team@rcabench.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
)

// checks if the DtoListRespLabelLabelResp type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DtoListRespLabelLabelResp{}

// DtoListRespLabelLabelResp struct for DtoListRespLabelLabelResp
type DtoListRespLabelLabelResp struct {
	Items                []LabelLabelResp   `json:"items,omitempty"`
	Pagination           *DtoPaginationInfo `json:"pagination,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _DtoListRespLabelLabelResp DtoListRespLabelLabelResp

// NewDtoListRespLabelLabelResp instantiates a new DtoListRespLabelLabelResp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDtoListRespLabelLabelResp() *DtoListRespLabelLabelResp {
	this := DtoListRespLabelLabelResp{}
	return &this
}

// NewDtoListRespLabelLabelRespWithDefaults instantiates a new DtoListRespLabelLabelResp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDtoListRespLabelLabelRespWithDefaults() *DtoListRespLabelLabelResp {
	this := DtoListRespLabelLabelResp{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *DtoListRespLabelLabelResp) GetItems() []LabelLabelResp {
	if o == nil || IsNil(o.Items) {
		var ret []LabelLabelResp
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoListRespLabelLabelResp) GetItemsOk() ([]LabelLabelResp, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *DtoListRespLabelLabelResp) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []LabelLabelResp and assigns it to the Items field.
func (o *DtoListRespLabelLabelResp) SetItems(v []LabelLabelResp) {
	o.Items = v
}

// GetPagination returns the Pagination field value if set, zero value otherwise.
func (o *DtoListRespLabelLabelResp) GetPagination() DtoPaginationInfo {
	if o == nil || IsNil(o.Pagination) {
		var ret DtoPaginationInfo
		return ret
	}
	return *o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoListRespLabelLabelResp) GetPaginationOk() (*DtoPaginationInfo, bool) {
	if o == nil || IsNil(o.Pagination) {
		return nil, false
	}
	return o.Pagination, true
}

// HasPagination returns a boolean if a field has been set.
func (o *DtoListRespLabelLabelResp) HasPagination() bool {
	if o != nil && !IsNil(o.Pagination) {
		return true
	}

	return false
}

// SetPagination gets a reference to the given DtoPaginationInfo and assigns it to the Pagination field.
func (o *DtoListRespLabelLabelResp) SetPagination(v DtoPaginationInfo) {
	o.Pagination = &v
}

func (o DtoListRespLabelLabelResp) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DtoListRespLabelLabelResp) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	if !IsNil(o.Pagination) {
		toSerialize["pagination"] = o.Pagination
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DtoListRespLabelLabelResp) UnmarshalJSON(data []byte) (err error) {
	varDtoListRespLabelLabelResp := _DtoListRespLabelLabelResp{}

	err = json.Unmarshal(data, &varDtoListRespLabelLabelResp)

	if err != nil {
		return err
	}

	*o = DtoListRespLabelLabelResp(varDtoListRespLabelLabelResp)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "items")
		delete(additionalProperties, "pagination")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDtoListRespLabelLabelResp struct {
	value *DtoListRespLabelLabelResp
	isSet bool
}

func (v NullableDtoListRespLabelLabelResp) Get() *DtoListRespLabelLabelResp {
	return v.value
}

func (v *NullableDtoListRespLabelLabelResp) Set(val *DtoListRespLabelLabelResp) {
	v.value = val
	v.isSet = true
}

func (v NullableDtoListRespLabelLabelResp) IsSet() bool {
	return v.isSet
}

func (v *NullableDtoListRespLabelLabelResp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDtoListRespLabelLabelResp(val *DtoListRespLabelLabelResp) *NullableDtoListRespLabelLabelResp {
	return &NullableDtoListRespLabelLabelResp{value: val, isSet: true}
}

func (v NullableDtoListRespLabelLabelResp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDtoListRespLabelLabelResp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
