/*
RCABench API

RCABench - A comprehensive root cause analysis benchmarking platform for microservices

API version: 1.0.0
Contact: team@rcabench.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
)

// checks if the DtoListRespTeamTeamResp type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DtoListRespTeamTeamResp{}

// DtoListRespTeamTeamResp struct for DtoListRespTeamTeamResp
type DtoListRespTeamTeamResp struct {
	Items                []TeamTeamResp     `json:"items,omitempty"`
	Pagination           *DtoPaginationInfo `json:"pagination,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _DtoListRespTeamTeamResp DtoListRespTeamTeamResp

// NewDtoListRespTeamTeamResp instantiates a new DtoListRespTeamTeamResp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDtoListRespTeamTeamResp() *DtoListRespTeamTeamResp {
	this := DtoListRespTeamTeamResp{}
	return &this
}

// NewDtoListRespTeamTeamRespWithDefaults instantiates a new DtoListRespTeamTeamResp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDtoListRespTeamTeamRespWithDefaults() *DtoListRespTeamTeamResp {
	this := DtoListRespTeamTeamResp{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *DtoListRespTeamTeamResp) GetItems() []TeamTeamResp {
	if o == nil || IsNil(o.Items) {
		var ret []TeamTeamResp
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoListRespTeamTeamResp) GetItemsOk() ([]TeamTeamResp, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *DtoListRespTeamTeamResp) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []TeamTeamResp and assigns it to the Items field.
func (o *DtoListRespTeamTeamResp) SetItems(v []TeamTeamResp) {
	o.Items = v
}

// GetPagination returns the Pagination field value if set, zero value otherwise.
func (o *DtoListRespTeamTeamResp) GetPagination() DtoPaginationInfo {
	if o == nil || IsNil(o.Pagination) {
		var ret DtoPaginationInfo
		return ret
	}
	return *o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoListRespTeamTeamResp) GetPaginationOk() (*DtoPaginationInfo, bool) {
	if o == nil || IsNil(o.Pagination) {
		return nil, false
	}
	return o.Pagination, true
}

// HasPagination returns a boolean if a field has been set.
func (o *DtoListRespTeamTeamResp) HasPagination() bool {
	if o != nil && !IsNil(o.Pagination) {
		return true
	}

	return false
}

// SetPagination gets a reference to the given DtoPaginationInfo and assigns it to the Pagination field.
func (o *DtoListRespTeamTeamResp) SetPagination(v DtoPaginationInfo) {
	o.Pagination = &v
}

func (o DtoListRespTeamTeamResp) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DtoListRespTeamTeamResp) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	if !IsNil(o.Pagination) {
		toSerialize["pagination"] = o.Pagination
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DtoListRespTeamTeamResp) UnmarshalJSON(data []byte) (err error) {
	varDtoListRespTeamTeamResp := _DtoListRespTeamTeamResp{}

	err = json.Unmarshal(data, &varDtoListRespTeamTeamResp)

	if err != nil {
		return err
	}

	*o = DtoListRespTeamTeamResp(varDtoListRespTeamTeamResp)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "items")
		delete(additionalProperties, "pagination")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDtoListRespTeamTeamResp struct {
	value *DtoListRespTeamTeamResp
	isSet bool
}

func (v NullableDtoListRespTeamTeamResp) Get() *DtoListRespTeamTeamResp {
	return v.value
}

func (v *NullableDtoListRespTeamTeamResp) Set(val *DtoListRespTeamTeamResp) {
	v.value = val
	v.isSet = true
}

func (v NullableDtoListRespTeamTeamResp) IsSet() bool {
	return v.isSet
}

func (v *NullableDtoListRespTeamTeamResp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDtoListRespTeamTeamResp(val *DtoListRespTeamTeamResp) *NullableDtoListRespTeamTeamResp {
	return &NullableDtoListRespTeamTeamResp{value: val, isSet: true}
}

func (v NullableDtoListRespTeamTeamResp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDtoListRespTeamTeamResp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
