/*
RCABench API

RCABench - A comprehensive root cause analysis benchmarking platform for microservices

API version: 1.0.0
Contact: team@rcabench.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
)

// checks if the DtoListRespTeamTeamProjectItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DtoListRespTeamTeamProjectItem{}

// DtoListRespTeamTeamProjectItem struct for DtoListRespTeamTeamProjectItem
type DtoListRespTeamTeamProjectItem struct {
	Items                []TeamTeamProjectItem `json:"items,omitempty"`
	Pagination           *DtoPaginationInfo    `json:"pagination,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _DtoListRespTeamTeamProjectItem DtoListRespTeamTeamProjectItem

// NewDtoListRespTeamTeamProjectItem instantiates a new DtoListRespTeamTeamProjectItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDtoListRespTeamTeamProjectItem() *DtoListRespTeamTeamProjectItem {
	this := DtoListRespTeamTeamProjectItem{}
	return &this
}

// NewDtoListRespTeamTeamProjectItemWithDefaults instantiates a new DtoListRespTeamTeamProjectItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDtoListRespTeamTeamProjectItemWithDefaults() *DtoListRespTeamTeamProjectItem {
	this := DtoListRespTeamTeamProjectItem{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *DtoListRespTeamTeamProjectItem) GetItems() []TeamTeamProjectItem {
	if o == nil || IsNil(o.Items) {
		var ret []TeamTeamProjectItem
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoListRespTeamTeamProjectItem) GetItemsOk() ([]TeamTeamProjectItem, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *DtoListRespTeamTeamProjectItem) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []TeamTeamProjectItem and assigns it to the Items field.
func (o *DtoListRespTeamTeamProjectItem) SetItems(v []TeamTeamProjectItem) {
	o.Items = v
}

// GetPagination returns the Pagination field value if set, zero value otherwise.
func (o *DtoListRespTeamTeamProjectItem) GetPagination() DtoPaginationInfo {
	if o == nil || IsNil(o.Pagination) {
		var ret DtoPaginationInfo
		return ret
	}
	return *o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoListRespTeamTeamProjectItem) GetPaginationOk() (*DtoPaginationInfo, bool) {
	if o == nil || IsNil(o.Pagination) {
		return nil, false
	}
	return o.Pagination, true
}

// HasPagination returns a boolean if a field has been set.
func (o *DtoListRespTeamTeamProjectItem) HasPagination() bool {
	if o != nil && !IsNil(o.Pagination) {
		return true
	}

	return false
}

// SetPagination gets a reference to the given DtoPaginationInfo and assigns it to the Pagination field.
func (o *DtoListRespTeamTeamProjectItem) SetPagination(v DtoPaginationInfo) {
	o.Pagination = &v
}

func (o DtoListRespTeamTeamProjectItem) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DtoListRespTeamTeamProjectItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	if !IsNil(o.Pagination) {
		toSerialize["pagination"] = o.Pagination
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DtoListRespTeamTeamProjectItem) UnmarshalJSON(data []byte) (err error) {
	varDtoListRespTeamTeamProjectItem := _DtoListRespTeamTeamProjectItem{}

	err = json.Unmarshal(data, &varDtoListRespTeamTeamProjectItem)

	if err != nil {
		return err
	}

	*o = DtoListRespTeamTeamProjectItem(varDtoListRespTeamTeamProjectItem)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "items")
		delete(additionalProperties, "pagination")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDtoListRespTeamTeamProjectItem struct {
	value *DtoListRespTeamTeamProjectItem
	isSet bool
}

func (v NullableDtoListRespTeamTeamProjectItem) Get() *DtoListRespTeamTeamProjectItem {
	return v.value
}

func (v *NullableDtoListRespTeamTeamProjectItem) Set(val *DtoListRespTeamTeamProjectItem) {
	v.value = val
	v.isSet = true
}

func (v NullableDtoListRespTeamTeamProjectItem) IsSet() bool {
	return v.isSet
}

func (v *NullableDtoListRespTeamTeamProjectItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDtoListRespTeamTeamProjectItem(val *DtoListRespTeamTeamProjectItem) *NullableDtoListRespTeamTeamProjectItem {
	return &NullableDtoListRespTeamTeamProjectItem{value: val, isSet: true}
}

func (v NullableDtoListRespTeamTeamProjectItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDtoListRespTeamTeamProjectItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
