/*
RCABench API

RCABench - A comprehensive root cause analysis benchmarking platform for microservices

API version: 1.0.0
Contact: team@rcabench.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
)

// checks if the ShareLinkView type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ShareLinkView{}

// ShareLinkView struct for ShareLinkView
type ShareLinkView struct {
	Bucket               *string `json:"bucket,omitempty"`
	ContentType          *string `json:"content_type,omitempty"`
	CreatedAt            *string `json:"created_at,omitempty"`
	ExpiresAt            *string `json:"expires_at,omitempty"`
	MaxViews             *int32  `json:"max_views,omitempty"`
	OriginalFilename     *string `json:"original_filename,omitempty"`
	OwnerUserId          *int32  `json:"owner_user_id,omitempty"`
	ShareUrl             *string `json:"share_url,omitempty"`
	ShortCode            *string `json:"short_code,omitempty"`
	SizeBytes            *int32  `json:"size_bytes,omitempty"`
	Status               *int32  `json:"status,omitempty"`
	ViewCount            *int32  `json:"view_count,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ShareLinkView ShareLinkView

// NewShareLinkView instantiates a new ShareLinkView object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewShareLinkView() *ShareLinkView {
	this := ShareLinkView{}
	return &this
}

// NewShareLinkViewWithDefaults instantiates a new ShareLinkView object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewShareLinkViewWithDefaults() *ShareLinkView {
	this := ShareLinkView{}
	return &this
}

// GetBucket returns the Bucket field value if set, zero value otherwise.
func (o *ShareLinkView) GetBucket() string {
	if o == nil || IsNil(o.Bucket) {
		var ret string
		return ret
	}
	return *o.Bucket
}

// GetBucketOk returns a tuple with the Bucket field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShareLinkView) GetBucketOk() (*string, bool) {
	if o == nil || IsNil(o.Bucket) {
		return nil, false
	}
	return o.Bucket, true
}

// HasBucket returns a boolean if a field has been set.
func (o *ShareLinkView) HasBucket() bool {
	if o != nil && !IsNil(o.Bucket) {
		return true
	}

	return false
}

// SetBucket gets a reference to the given string and assigns it to the Bucket field.
func (o *ShareLinkView) SetBucket(v string) {
	o.Bucket = &v
}

// GetContentType returns the ContentType field value if set, zero value otherwise.
func (o *ShareLinkView) GetContentType() string {
	if o == nil || IsNil(o.ContentType) {
		var ret string
		return ret
	}
	return *o.ContentType
}

// GetContentTypeOk returns a tuple with the ContentType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShareLinkView) GetContentTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ContentType) {
		return nil, false
	}
	return o.ContentType, true
}

// HasContentType returns a boolean if a field has been set.
func (o *ShareLinkView) HasContentType() bool {
	if o != nil && !IsNil(o.ContentType) {
		return true
	}

	return false
}

// SetContentType gets a reference to the given string and assigns it to the ContentType field.
func (o *ShareLinkView) SetContentType(v string) {
	o.ContentType = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *ShareLinkView) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShareLinkView) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *ShareLinkView) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *ShareLinkView) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetExpiresAt returns the ExpiresAt field value if set, zero value otherwise.
func (o *ShareLinkView) GetExpiresAt() string {
	if o == nil || IsNil(o.ExpiresAt) {
		var ret string
		return ret
	}
	return *o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShareLinkView) GetExpiresAtOk() (*string, bool) {
	if o == nil || IsNil(o.ExpiresAt) {
		return nil, false
	}
	return o.ExpiresAt, true
}

// HasExpiresAt returns a boolean if a field has been set.
func (o *ShareLinkView) HasExpiresAt() bool {
	if o != nil && !IsNil(o.ExpiresAt) {
		return true
	}

	return false
}

// SetExpiresAt gets a reference to the given string and assigns it to the ExpiresAt field.
func (o *ShareLinkView) SetExpiresAt(v string) {
	o.ExpiresAt = &v
}

// GetMaxViews returns the MaxViews field value if set, zero value otherwise.
func (o *ShareLinkView) GetMaxViews() int32 {
	if o == nil || IsNil(o.MaxViews) {
		var ret int32
		return ret
	}
	return *o.MaxViews
}

// GetMaxViewsOk returns a tuple with the MaxViews field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShareLinkView) GetMaxViewsOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxViews) {
		return nil, false
	}
	return o.MaxViews, true
}

// HasMaxViews returns a boolean if a field has been set.
func (o *ShareLinkView) HasMaxViews() bool {
	if o != nil && !IsNil(o.MaxViews) {
		return true
	}

	return false
}

// SetMaxViews gets a reference to the given int32 and assigns it to the MaxViews field.
func (o *ShareLinkView) SetMaxViews(v int32) {
	o.MaxViews = &v
}

// GetOriginalFilename returns the OriginalFilename field value if set, zero value otherwise.
func (o *ShareLinkView) GetOriginalFilename() string {
	if o == nil || IsNil(o.OriginalFilename) {
		var ret string
		return ret
	}
	return *o.OriginalFilename
}

// GetOriginalFilenameOk returns a tuple with the OriginalFilename field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShareLinkView) GetOriginalFilenameOk() (*string, bool) {
	if o == nil || IsNil(o.OriginalFilename) {
		return nil, false
	}
	return o.OriginalFilename, true
}

// HasOriginalFilename returns a boolean if a field has been set.
func (o *ShareLinkView) HasOriginalFilename() bool {
	if o != nil && !IsNil(o.OriginalFilename) {
		return true
	}

	return false
}

// SetOriginalFilename gets a reference to the given string and assigns it to the OriginalFilename field.
func (o *ShareLinkView) SetOriginalFilename(v string) {
	o.OriginalFilename = &v
}

// GetOwnerUserId returns the OwnerUserId field value if set, zero value otherwise.
func (o *ShareLinkView) GetOwnerUserId() int32 {
	if o == nil || IsNil(o.OwnerUserId) {
		var ret int32
		return ret
	}
	return *o.OwnerUserId
}

// GetOwnerUserIdOk returns a tuple with the OwnerUserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShareLinkView) GetOwnerUserIdOk() (*int32, bool) {
	if o == nil || IsNil(o.OwnerUserId) {
		return nil, false
	}
	return o.OwnerUserId, true
}

// HasOwnerUserId returns a boolean if a field has been set.
func (o *ShareLinkView) HasOwnerUserId() bool {
	if o != nil && !IsNil(o.OwnerUserId) {
		return true
	}

	return false
}

// SetOwnerUserId gets a reference to the given int32 and assigns it to the OwnerUserId field.
func (o *ShareLinkView) SetOwnerUserId(v int32) {
	o.OwnerUserId = &v
}

// GetShareUrl returns the ShareUrl field value if set, zero value otherwise.
func (o *ShareLinkView) GetShareUrl() string {
	if o == nil || IsNil(o.ShareUrl) {
		var ret string
		return ret
	}
	return *o.ShareUrl
}

// GetShareUrlOk returns a tuple with the ShareUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShareLinkView) GetShareUrlOk() (*string, bool) {
	if o == nil || IsNil(o.ShareUrl) {
		return nil, false
	}
	return o.ShareUrl, true
}

// HasShareUrl returns a boolean if a field has been set.
func (o *ShareLinkView) HasShareUrl() bool {
	if o != nil && !IsNil(o.ShareUrl) {
		return true
	}

	return false
}

// SetShareUrl gets a reference to the given string and assigns it to the ShareUrl field.
func (o *ShareLinkView) SetShareUrl(v string) {
	o.ShareUrl = &v
}

// GetShortCode returns the ShortCode field value if set, zero value otherwise.
func (o *ShareLinkView) GetShortCode() string {
	if o == nil || IsNil(o.ShortCode) {
		var ret string
		return ret
	}
	return *o.ShortCode
}

// GetShortCodeOk returns a tuple with the ShortCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShareLinkView) GetShortCodeOk() (*string, bool) {
	if o == nil || IsNil(o.ShortCode) {
		return nil, false
	}
	return o.ShortCode, true
}

// HasShortCode returns a boolean if a field has been set.
func (o *ShareLinkView) HasShortCode() bool {
	if o != nil && !IsNil(o.ShortCode) {
		return true
	}

	return false
}

// SetShortCode gets a reference to the given string and assigns it to the ShortCode field.
func (o *ShareLinkView) SetShortCode(v string) {
	o.ShortCode = &v
}

// GetSizeBytes returns the SizeBytes field value if set, zero value otherwise.
func (o *ShareLinkView) GetSizeBytes() int32 {
	if o == nil || IsNil(o.SizeBytes) {
		var ret int32
		return ret
	}
	return *o.SizeBytes
}

// GetSizeBytesOk returns a tuple with the SizeBytes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShareLinkView) GetSizeBytesOk() (*int32, bool) {
	if o == nil || IsNil(o.SizeBytes) {
		return nil, false
	}
	return o.SizeBytes, true
}

// HasSizeBytes returns a boolean if a field has been set.
func (o *ShareLinkView) HasSizeBytes() bool {
	if o != nil && !IsNil(o.SizeBytes) {
		return true
	}

	return false
}

// SetSizeBytes gets a reference to the given int32 and assigns it to the SizeBytes field.
func (o *ShareLinkView) SetSizeBytes(v int32) {
	o.SizeBytes = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ShareLinkView) GetStatus() int32 {
	if o == nil || IsNil(o.Status) {
		var ret int32
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShareLinkView) GetStatusOk() (*int32, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ShareLinkView) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given int32 and assigns it to the Status field.
func (o *ShareLinkView) SetStatus(v int32) {
	o.Status = &v
}

// GetViewCount returns the ViewCount field value if set, zero value otherwise.
func (o *ShareLinkView) GetViewCount() int32 {
	if o == nil || IsNil(o.ViewCount) {
		var ret int32
		return ret
	}
	return *o.ViewCount
}

// GetViewCountOk returns a tuple with the ViewCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShareLinkView) GetViewCountOk() (*int32, bool) {
	if o == nil || IsNil(o.ViewCount) {
		return nil, false
	}
	return o.ViewCount, true
}

// HasViewCount returns a boolean if a field has been set.
func (o *ShareLinkView) HasViewCount() bool {
	if o != nil && !IsNil(o.ViewCount) {
		return true
	}

	return false
}

// SetViewCount gets a reference to the given int32 and assigns it to the ViewCount field.
func (o *ShareLinkView) SetViewCount(v int32) {
	o.ViewCount = &v
}

func (o ShareLinkView) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ShareLinkView) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Bucket) {
		toSerialize["bucket"] = o.Bucket
	}
	if !IsNil(o.ContentType) {
		toSerialize["content_type"] = o.ContentType
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.ExpiresAt) {
		toSerialize["expires_at"] = o.ExpiresAt
	}
	if !IsNil(o.MaxViews) {
		toSerialize["max_views"] = o.MaxViews
	}
	if !IsNil(o.OriginalFilename) {
		toSerialize["original_filename"] = o.OriginalFilename
	}
	if !IsNil(o.OwnerUserId) {
		toSerialize["owner_user_id"] = o.OwnerUserId
	}
	if !IsNil(o.ShareUrl) {
		toSerialize["share_url"] = o.ShareUrl
	}
	if !IsNil(o.ShortCode) {
		toSerialize["short_code"] = o.ShortCode
	}
	if !IsNil(o.SizeBytes) {
		toSerialize["size_bytes"] = o.SizeBytes
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.ViewCount) {
		toSerialize["view_count"] = o.ViewCount
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ShareLinkView) UnmarshalJSON(data []byte) (err error) {
	varShareLinkView := _ShareLinkView{}

	err = json.Unmarshal(data, &varShareLinkView)

	if err != nil {
		return err
	}

	*o = ShareLinkView(varShareLinkView)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "bucket")
		delete(additionalProperties, "content_type")
		delete(additionalProperties, "created_at")
		delete(additionalProperties, "expires_at")
		delete(additionalProperties, "max_views")
		delete(additionalProperties, "original_filename")
		delete(additionalProperties, "owner_user_id")
		delete(additionalProperties, "share_url")
		delete(additionalProperties, "short_code")
		delete(additionalProperties, "size_bytes")
		delete(additionalProperties, "status")
		delete(additionalProperties, "view_count")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableShareLinkView struct {
	value *ShareLinkView
	isSet bool
}

func (v NullableShareLinkView) Get() *ShareLinkView {
	return v.value
}

func (v *NullableShareLinkView) Set(val *ShareLinkView) {
	v.value = val
	v.isSet = true
}

func (v NullableShareLinkView) IsSet() bool {
	return v.isSet
}

func (v *NullableShareLinkView) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableShareLinkView(val *ShareLinkView) *NullableShareLinkView {
	return &NullableShareLinkView{value: val, isSet: true}
}

func (v NullableShareLinkView) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableShareLinkView) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
