/*
RCABench API

RCABench - A comprehensive root cause analysis benchmarking platform for microservices

API version: 1.0.0
Contact: team@rcabench.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"fmt"
)

// checks if the BlobCreateBucketReq type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BlobCreateBucketReq{}

// BlobCreateBucketReq struct for BlobCreateBucketReq
type BlobCreateBucketReq struct {
	AccessKeyEnv         *string  `json:"access_key_env,omitempty"`
	Bucket               *string  `json:"bucket,omitempty"`
	ContentTypes         []string `json:"content_types,omitempty"`
	Driver               string   `json:"driver"`
	Endpoint             *string  `json:"endpoint,omitempty"`
	MaxObjectBytes       *int32   `json:"max_object_bytes,omitempty"`
	Name                 string   `json:"name"`
	PathStyle            *bool    `json:"path_style,omitempty"`
	PublicEndpoint       *string  `json:"public_endpoint,omitempty"`
	PublicRead           *bool    `json:"public_read,omitempty"`
	ReadRoles            []string `json:"read_roles,omitempty"`
	Region               *string  `json:"region,omitempty"`
	RetentionDays        *int32   `json:"retention_days,omitempty"`
	Root                 *string  `json:"root,omitempty"`
	SecretKeyEnv         *string  `json:"secret_key_env,omitempty"`
	UseSsl               *bool    `json:"use_ssl,omitempty"`
	WriteRoles           []string `json:"write_roles,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _BlobCreateBucketReq BlobCreateBucketReq

// NewBlobCreateBucketReq instantiates a new BlobCreateBucketReq object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBlobCreateBucketReq(driver string, name string) *BlobCreateBucketReq {
	this := BlobCreateBucketReq{}
	this.Driver = driver
	this.Name = name
	return &this
}

// NewBlobCreateBucketReqWithDefaults instantiates a new BlobCreateBucketReq object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBlobCreateBucketReqWithDefaults() *BlobCreateBucketReq {
	this := BlobCreateBucketReq{}
	return &this
}

// GetAccessKeyEnv returns the AccessKeyEnv field value if set, zero value otherwise.
func (o *BlobCreateBucketReq) GetAccessKeyEnv() string {
	if o == nil || IsNil(o.AccessKeyEnv) {
		var ret string
		return ret
	}
	return *o.AccessKeyEnv
}

// GetAccessKeyEnvOk returns a tuple with the AccessKeyEnv field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlobCreateBucketReq) GetAccessKeyEnvOk() (*string, bool) {
	if o == nil || IsNil(o.AccessKeyEnv) {
		return nil, false
	}
	return o.AccessKeyEnv, true
}

// HasAccessKeyEnv returns a boolean if a field has been set.
func (o *BlobCreateBucketReq) HasAccessKeyEnv() bool {
	if o != nil && !IsNil(o.AccessKeyEnv) {
		return true
	}

	return false
}

// SetAccessKeyEnv gets a reference to the given string and assigns it to the AccessKeyEnv field.
func (o *BlobCreateBucketReq) SetAccessKeyEnv(v string) {
	o.AccessKeyEnv = &v
}

// GetBucket returns the Bucket field value if set, zero value otherwise.
func (o *BlobCreateBucketReq) GetBucket() string {
	if o == nil || IsNil(o.Bucket) {
		var ret string
		return ret
	}
	return *o.Bucket
}

// GetBucketOk returns a tuple with the Bucket field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlobCreateBucketReq) GetBucketOk() (*string, bool) {
	if o == nil || IsNil(o.Bucket) {
		return nil, false
	}
	return o.Bucket, true
}

// HasBucket returns a boolean if a field has been set.
func (o *BlobCreateBucketReq) HasBucket() bool {
	if o != nil && !IsNil(o.Bucket) {
		return true
	}

	return false
}

// SetBucket gets a reference to the given string and assigns it to the Bucket field.
func (o *BlobCreateBucketReq) SetBucket(v string) {
	o.Bucket = &v
}

// GetContentTypes returns the ContentTypes field value if set, zero value otherwise.
func (o *BlobCreateBucketReq) GetContentTypes() []string {
	if o == nil || IsNil(o.ContentTypes) {
		var ret []string
		return ret
	}
	return o.ContentTypes
}

// GetContentTypesOk returns a tuple with the ContentTypes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlobCreateBucketReq) GetContentTypesOk() ([]string, bool) {
	if o == nil || IsNil(o.ContentTypes) {
		return nil, false
	}
	return o.ContentTypes, true
}

// HasContentTypes returns a boolean if a field has been set.
func (o *BlobCreateBucketReq) HasContentTypes() bool {
	if o != nil && !IsNil(o.ContentTypes) {
		return true
	}

	return false
}

// SetContentTypes gets a reference to the given []string and assigns it to the ContentTypes field.
func (o *BlobCreateBucketReq) SetContentTypes(v []string) {
	o.ContentTypes = v
}

// GetDriver returns the Driver field value
func (o *BlobCreateBucketReq) GetDriver() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Driver
}

// GetDriverOk returns a tuple with the Driver field value
// and a boolean to check if the value has been set.
func (o *BlobCreateBucketReq) GetDriverOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Driver, true
}

// SetDriver sets field value
func (o *BlobCreateBucketReq) SetDriver(v string) {
	o.Driver = v
}

// GetEndpoint returns the Endpoint field value if set, zero value otherwise.
func (o *BlobCreateBucketReq) GetEndpoint() string {
	if o == nil || IsNil(o.Endpoint) {
		var ret string
		return ret
	}
	return *o.Endpoint
}

// GetEndpointOk returns a tuple with the Endpoint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlobCreateBucketReq) GetEndpointOk() (*string, bool) {
	if o == nil || IsNil(o.Endpoint) {
		return nil, false
	}
	return o.Endpoint, true
}

// HasEndpoint returns a boolean if a field has been set.
func (o *BlobCreateBucketReq) HasEndpoint() bool {
	if o != nil && !IsNil(o.Endpoint) {
		return true
	}

	return false
}

// SetEndpoint gets a reference to the given string and assigns it to the Endpoint field.
func (o *BlobCreateBucketReq) SetEndpoint(v string) {
	o.Endpoint = &v
}

// GetMaxObjectBytes returns the MaxObjectBytes field value if set, zero value otherwise.
func (o *BlobCreateBucketReq) GetMaxObjectBytes() int32 {
	if o == nil || IsNil(o.MaxObjectBytes) {
		var ret int32
		return ret
	}
	return *o.MaxObjectBytes
}

// GetMaxObjectBytesOk returns a tuple with the MaxObjectBytes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlobCreateBucketReq) GetMaxObjectBytesOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxObjectBytes) {
		return nil, false
	}
	return o.MaxObjectBytes, true
}

// HasMaxObjectBytes returns a boolean if a field has been set.
func (o *BlobCreateBucketReq) HasMaxObjectBytes() bool {
	if o != nil && !IsNil(o.MaxObjectBytes) {
		return true
	}

	return false
}

// SetMaxObjectBytes gets a reference to the given int32 and assigns it to the MaxObjectBytes field.
func (o *BlobCreateBucketReq) SetMaxObjectBytes(v int32) {
	o.MaxObjectBytes = &v
}

// GetName returns the Name field value
func (o *BlobCreateBucketReq) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *BlobCreateBucketReq) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *BlobCreateBucketReq) SetName(v string) {
	o.Name = v
}

// GetPathStyle returns the PathStyle field value if set, zero value otherwise.
func (o *BlobCreateBucketReq) GetPathStyle() bool {
	if o == nil || IsNil(o.PathStyle) {
		var ret bool
		return ret
	}
	return *o.PathStyle
}

// GetPathStyleOk returns a tuple with the PathStyle field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlobCreateBucketReq) GetPathStyleOk() (*bool, bool) {
	if o == nil || IsNil(o.PathStyle) {
		return nil, false
	}
	return o.PathStyle, true
}

// HasPathStyle returns a boolean if a field has been set.
func (o *BlobCreateBucketReq) HasPathStyle() bool {
	if o != nil && !IsNil(o.PathStyle) {
		return true
	}

	return false
}

// SetPathStyle gets a reference to the given bool and assigns it to the PathStyle field.
func (o *BlobCreateBucketReq) SetPathStyle(v bool) {
	o.PathStyle = &v
}

// GetPublicEndpoint returns the PublicEndpoint field value if set, zero value otherwise.
func (o *BlobCreateBucketReq) GetPublicEndpoint() string {
	if o == nil || IsNil(o.PublicEndpoint) {
		var ret string
		return ret
	}
	return *o.PublicEndpoint
}

// GetPublicEndpointOk returns a tuple with the PublicEndpoint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlobCreateBucketReq) GetPublicEndpointOk() (*string, bool) {
	if o == nil || IsNil(o.PublicEndpoint) {
		return nil, false
	}
	return o.PublicEndpoint, true
}

// HasPublicEndpoint returns a boolean if a field has been set.
func (o *BlobCreateBucketReq) HasPublicEndpoint() bool {
	if o != nil && !IsNil(o.PublicEndpoint) {
		return true
	}

	return false
}

// SetPublicEndpoint gets a reference to the given string and assigns it to the PublicEndpoint field.
func (o *BlobCreateBucketReq) SetPublicEndpoint(v string) {
	o.PublicEndpoint = &v
}

// GetPublicRead returns the PublicRead field value if set, zero value otherwise.
func (o *BlobCreateBucketReq) GetPublicRead() bool {
	if o == nil || IsNil(o.PublicRead) {
		var ret bool
		return ret
	}
	return *o.PublicRead
}

// GetPublicReadOk returns a tuple with the PublicRead field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlobCreateBucketReq) GetPublicReadOk() (*bool, bool) {
	if o == nil || IsNil(o.PublicRead) {
		return nil, false
	}
	return o.PublicRead, true
}

// HasPublicRead returns a boolean if a field has been set.
func (o *BlobCreateBucketReq) HasPublicRead() bool {
	if o != nil && !IsNil(o.PublicRead) {
		return true
	}

	return false
}

// SetPublicRead gets a reference to the given bool and assigns it to the PublicRead field.
func (o *BlobCreateBucketReq) SetPublicRead(v bool) {
	o.PublicRead = &v
}

// GetReadRoles returns the ReadRoles field value if set, zero value otherwise.
func (o *BlobCreateBucketReq) GetReadRoles() []string {
	if o == nil || IsNil(o.ReadRoles) {
		var ret []string
		return ret
	}
	return o.ReadRoles
}

// GetReadRolesOk returns a tuple with the ReadRoles field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlobCreateBucketReq) GetReadRolesOk() ([]string, bool) {
	if o == nil || IsNil(o.ReadRoles) {
		return nil, false
	}
	return o.ReadRoles, true
}

// HasReadRoles returns a boolean if a field has been set.
func (o *BlobCreateBucketReq) HasReadRoles() bool {
	if o != nil && !IsNil(o.ReadRoles) {
		return true
	}

	return false
}

// SetReadRoles gets a reference to the given []string and assigns it to the ReadRoles field.
func (o *BlobCreateBucketReq) SetReadRoles(v []string) {
	o.ReadRoles = v
}

// GetRegion returns the Region field value if set, zero value otherwise.
func (o *BlobCreateBucketReq) GetRegion() string {
	if o == nil || IsNil(o.Region) {
		var ret string
		return ret
	}
	return *o.Region
}

// GetRegionOk returns a tuple with the Region field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlobCreateBucketReq) GetRegionOk() (*string, bool) {
	if o == nil || IsNil(o.Region) {
		return nil, false
	}
	return o.Region, true
}

// HasRegion returns a boolean if a field has been set.
func (o *BlobCreateBucketReq) HasRegion() bool {
	if o != nil && !IsNil(o.Region) {
		return true
	}

	return false
}

// SetRegion gets a reference to the given string and assigns it to the Region field.
func (o *BlobCreateBucketReq) SetRegion(v string) {
	o.Region = &v
}

// GetRetentionDays returns the RetentionDays field value if set, zero value otherwise.
func (o *BlobCreateBucketReq) GetRetentionDays() int32 {
	if o == nil || IsNil(o.RetentionDays) {
		var ret int32
		return ret
	}
	return *o.RetentionDays
}

// GetRetentionDaysOk returns a tuple with the RetentionDays field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlobCreateBucketReq) GetRetentionDaysOk() (*int32, bool) {
	if o == nil || IsNil(o.RetentionDays) {
		return nil, false
	}
	return o.RetentionDays, true
}

// HasRetentionDays returns a boolean if a field has been set.
func (o *BlobCreateBucketReq) HasRetentionDays() bool {
	if o != nil && !IsNil(o.RetentionDays) {
		return true
	}

	return false
}

// SetRetentionDays gets a reference to the given int32 and assigns it to the RetentionDays field.
func (o *BlobCreateBucketReq) SetRetentionDays(v int32) {
	o.RetentionDays = &v
}

// GetRoot returns the Root field value if set, zero value otherwise.
func (o *BlobCreateBucketReq) GetRoot() string {
	if o == nil || IsNil(o.Root) {
		var ret string
		return ret
	}
	return *o.Root
}

// GetRootOk returns a tuple with the Root field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlobCreateBucketReq) GetRootOk() (*string, bool) {
	if o == nil || IsNil(o.Root) {
		return nil, false
	}
	return o.Root, true
}

// HasRoot returns a boolean if a field has been set.
func (o *BlobCreateBucketReq) HasRoot() bool {
	if o != nil && !IsNil(o.Root) {
		return true
	}

	return false
}

// SetRoot gets a reference to the given string and assigns it to the Root field.
func (o *BlobCreateBucketReq) SetRoot(v string) {
	o.Root = &v
}

// GetSecretKeyEnv returns the SecretKeyEnv field value if set, zero value otherwise.
func (o *BlobCreateBucketReq) GetSecretKeyEnv() string {
	if o == nil || IsNil(o.SecretKeyEnv) {
		var ret string
		return ret
	}
	return *o.SecretKeyEnv
}

// GetSecretKeyEnvOk returns a tuple with the SecretKeyEnv field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlobCreateBucketReq) GetSecretKeyEnvOk() (*string, bool) {
	if o == nil || IsNil(o.SecretKeyEnv) {
		return nil, false
	}
	return o.SecretKeyEnv, true
}

// HasSecretKeyEnv returns a boolean if a field has been set.
func (o *BlobCreateBucketReq) HasSecretKeyEnv() bool {
	if o != nil && !IsNil(o.SecretKeyEnv) {
		return true
	}

	return false
}

// SetSecretKeyEnv gets a reference to the given string and assigns it to the SecretKeyEnv field.
func (o *BlobCreateBucketReq) SetSecretKeyEnv(v string) {
	o.SecretKeyEnv = &v
}

// GetUseSsl returns the UseSsl field value if set, zero value otherwise.
func (o *BlobCreateBucketReq) GetUseSsl() bool {
	if o == nil || IsNil(o.UseSsl) {
		var ret bool
		return ret
	}
	return *o.UseSsl
}

// GetUseSslOk returns a tuple with the UseSsl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlobCreateBucketReq) GetUseSslOk() (*bool, bool) {
	if o == nil || IsNil(o.UseSsl) {
		return nil, false
	}
	return o.UseSsl, true
}

// HasUseSsl returns a boolean if a field has been set.
func (o *BlobCreateBucketReq) HasUseSsl() bool {
	if o != nil && !IsNil(o.UseSsl) {
		return true
	}

	return false
}

// SetUseSsl gets a reference to the given bool and assigns it to the UseSsl field.
func (o *BlobCreateBucketReq) SetUseSsl(v bool) {
	o.UseSsl = &v
}

// GetWriteRoles returns the WriteRoles field value if set, zero value otherwise.
func (o *BlobCreateBucketReq) GetWriteRoles() []string {
	if o == nil || IsNil(o.WriteRoles) {
		var ret []string
		return ret
	}
	return o.WriteRoles
}

// GetWriteRolesOk returns a tuple with the WriteRoles field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlobCreateBucketReq) GetWriteRolesOk() ([]string, bool) {
	if o == nil || IsNil(o.WriteRoles) {
		return nil, false
	}
	return o.WriteRoles, true
}

// HasWriteRoles returns a boolean if a field has been set.
func (o *BlobCreateBucketReq) HasWriteRoles() bool {
	if o != nil && !IsNil(o.WriteRoles) {
		return true
	}

	return false
}

// SetWriteRoles gets a reference to the given []string and assigns it to the WriteRoles field.
func (o *BlobCreateBucketReq) SetWriteRoles(v []string) {
	o.WriteRoles = v
}

func (o BlobCreateBucketReq) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BlobCreateBucketReq) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AccessKeyEnv) {
		toSerialize["access_key_env"] = o.AccessKeyEnv
	}
	if !IsNil(o.Bucket) {
		toSerialize["bucket"] = o.Bucket
	}
	if !IsNil(o.ContentTypes) {
		toSerialize["content_types"] = o.ContentTypes
	}
	toSerialize["driver"] = o.Driver
	if !IsNil(o.Endpoint) {
		toSerialize["endpoint"] = o.Endpoint
	}
	if !IsNil(o.MaxObjectBytes) {
		toSerialize["max_object_bytes"] = o.MaxObjectBytes
	}
	toSerialize["name"] = o.Name
	if !IsNil(o.PathStyle) {
		toSerialize["path_style"] = o.PathStyle
	}
	if !IsNil(o.PublicEndpoint) {
		toSerialize["public_endpoint"] = o.PublicEndpoint
	}
	if !IsNil(o.PublicRead) {
		toSerialize["public_read"] = o.PublicRead
	}
	if !IsNil(o.ReadRoles) {
		toSerialize["read_roles"] = o.ReadRoles
	}
	if !IsNil(o.Region) {
		toSerialize["region"] = o.Region
	}
	if !IsNil(o.RetentionDays) {
		toSerialize["retention_days"] = o.RetentionDays
	}
	if !IsNil(o.Root) {
		toSerialize["root"] = o.Root
	}
	if !IsNil(o.SecretKeyEnv) {
		toSerialize["secret_key_env"] = o.SecretKeyEnv
	}
	if !IsNil(o.UseSsl) {
		toSerialize["use_ssl"] = o.UseSsl
	}
	if !IsNil(o.WriteRoles) {
		toSerialize["write_roles"] = o.WriteRoles
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BlobCreateBucketReq) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"driver",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBlobCreateBucketReq := _BlobCreateBucketReq{}

	err = json.Unmarshal(data, &varBlobCreateBucketReq)

	if err != nil {
		return err
	}

	*o = BlobCreateBucketReq(varBlobCreateBucketReq)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "access_key_env")
		delete(additionalProperties, "bucket")
		delete(additionalProperties, "content_types")
		delete(additionalProperties, "driver")
		delete(additionalProperties, "endpoint")
		delete(additionalProperties, "max_object_bytes")
		delete(additionalProperties, "name")
		delete(additionalProperties, "path_style")
		delete(additionalProperties, "public_endpoint")
		delete(additionalProperties, "public_read")
		delete(additionalProperties, "read_roles")
		delete(additionalProperties, "region")
		delete(additionalProperties, "retention_days")
		delete(additionalProperties, "root")
		delete(additionalProperties, "secret_key_env")
		delete(additionalProperties, "use_ssl")
		delete(additionalProperties, "write_roles")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBlobCreateBucketReq struct {
	value *BlobCreateBucketReq
	isSet bool
}

func (v NullableBlobCreateBucketReq) Get() *BlobCreateBucketReq {
	return v.value
}

func (v *NullableBlobCreateBucketReq) Set(val *BlobCreateBucketReq) {
	v.value = val
	v.isSet = true
}

func (v NullableBlobCreateBucketReq) IsSet() bool {
	return v.isSet
}

func (v *NullableBlobCreateBucketReq) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBlobCreateBucketReq(val *BlobCreateBucketReq) *NullableBlobCreateBucketReq {
	return &NullableBlobCreateBucketReq{value: val, isSet: true}
}

func (v NullableBlobCreateBucketReq) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBlobCreateBucketReq) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
