/*
RCABench API

RCABench - A comprehensive root cause analysis benchmarking platform for microservices

API version: 1.0.0
Contact: team@rcabench.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
)

// checks if the RatelimiterRateLimiterHolder type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RatelimiterRateLimiterHolder{}

// RatelimiterRateLimiterHolder struct for RatelimiterRateLimiterHolder
type RatelimiterRateLimiterHolder struct {
	IsTerminal           *bool   `json:"is_terminal,omitempty"`
	TaskId               *string `json:"task_id,omitempty"`
	TaskState            *string `json:"task_state,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _RatelimiterRateLimiterHolder RatelimiterRateLimiterHolder

// NewRatelimiterRateLimiterHolder instantiates a new RatelimiterRateLimiterHolder object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRatelimiterRateLimiterHolder() *RatelimiterRateLimiterHolder {
	this := RatelimiterRateLimiterHolder{}
	return &this
}

// NewRatelimiterRateLimiterHolderWithDefaults instantiates a new RatelimiterRateLimiterHolder object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRatelimiterRateLimiterHolderWithDefaults() *RatelimiterRateLimiterHolder {
	this := RatelimiterRateLimiterHolder{}
	return &this
}

// GetIsTerminal returns the IsTerminal field value if set, zero value otherwise.
func (o *RatelimiterRateLimiterHolder) GetIsTerminal() bool {
	if o == nil || IsNil(o.IsTerminal) {
		var ret bool
		return ret
	}
	return *o.IsTerminal
}

// GetIsTerminalOk returns a tuple with the IsTerminal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RatelimiterRateLimiterHolder) GetIsTerminalOk() (*bool, bool) {
	if o == nil || IsNil(o.IsTerminal) {
		return nil, false
	}
	return o.IsTerminal, true
}

// HasIsTerminal returns a boolean if a field has been set.
func (o *RatelimiterRateLimiterHolder) HasIsTerminal() bool {
	if o != nil && !IsNil(o.IsTerminal) {
		return true
	}

	return false
}

// SetIsTerminal gets a reference to the given bool and assigns it to the IsTerminal field.
func (o *RatelimiterRateLimiterHolder) SetIsTerminal(v bool) {
	o.IsTerminal = &v
}

// GetTaskId returns the TaskId field value if set, zero value otherwise.
func (o *RatelimiterRateLimiterHolder) GetTaskId() string {
	if o == nil || IsNil(o.TaskId) {
		var ret string
		return ret
	}
	return *o.TaskId
}

// GetTaskIdOk returns a tuple with the TaskId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RatelimiterRateLimiterHolder) GetTaskIdOk() (*string, bool) {
	if o == nil || IsNil(o.TaskId) {
		return nil, false
	}
	return o.TaskId, true
}

// HasTaskId returns a boolean if a field has been set.
func (o *RatelimiterRateLimiterHolder) HasTaskId() bool {
	if o != nil && !IsNil(o.TaskId) {
		return true
	}

	return false
}

// SetTaskId gets a reference to the given string and assigns it to the TaskId field.
func (o *RatelimiterRateLimiterHolder) SetTaskId(v string) {
	o.TaskId = &v
}

// GetTaskState returns the TaskState field value if set, zero value otherwise.
func (o *RatelimiterRateLimiterHolder) GetTaskState() string {
	if o == nil || IsNil(o.TaskState) {
		var ret string
		return ret
	}
	return *o.TaskState
}

// GetTaskStateOk returns a tuple with the TaskState field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RatelimiterRateLimiterHolder) GetTaskStateOk() (*string, bool) {
	if o == nil || IsNil(o.TaskState) {
		return nil, false
	}
	return o.TaskState, true
}

// HasTaskState returns a boolean if a field has been set.
func (o *RatelimiterRateLimiterHolder) HasTaskState() bool {
	if o != nil && !IsNil(o.TaskState) {
		return true
	}

	return false
}

// SetTaskState gets a reference to the given string and assigns it to the TaskState field.
func (o *RatelimiterRateLimiterHolder) SetTaskState(v string) {
	o.TaskState = &v
}

func (o RatelimiterRateLimiterHolder) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RatelimiterRateLimiterHolder) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.IsTerminal) {
		toSerialize["is_terminal"] = o.IsTerminal
	}
	if !IsNil(o.TaskId) {
		toSerialize["task_id"] = o.TaskId
	}
	if !IsNil(o.TaskState) {
		toSerialize["task_state"] = o.TaskState
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RatelimiterRateLimiterHolder) UnmarshalJSON(data []byte) (err error) {
	varRatelimiterRateLimiterHolder := _RatelimiterRateLimiterHolder{}

	err = json.Unmarshal(data, &varRatelimiterRateLimiterHolder)

	if err != nil {
		return err
	}

	*o = RatelimiterRateLimiterHolder(varRatelimiterRateLimiterHolder)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "is_terminal")
		delete(additionalProperties, "task_id")
		delete(additionalProperties, "task_state")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRatelimiterRateLimiterHolder struct {
	value *RatelimiterRateLimiterHolder
	isSet bool
}

func (v NullableRatelimiterRateLimiterHolder) Get() *RatelimiterRateLimiterHolder {
	return v.value
}

func (v *NullableRatelimiterRateLimiterHolder) Set(val *RatelimiterRateLimiterHolder) {
	v.value = val
	v.isSet = true
}

func (v NullableRatelimiterRateLimiterHolder) IsSet() bool {
	return v.isSet
}

func (v *NullableRatelimiterRateLimiterHolder) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRatelimiterRateLimiterHolder(val *RatelimiterRateLimiterHolder) *NullableRatelimiterRateLimiterHolder {
	return &NullableRatelimiterRateLimiterHolder{value: val, isSet: true}
}

func (v NullableRatelimiterRateLimiterHolder) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRatelimiterRateLimiterHolder) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
