/*
RCABench API

RCABench - A comprehensive root cause analysis benchmarking platform for microservices

API version: 1.0.0
Contact: team@rcabench.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
)

// checks if the PagesListResp type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PagesListResp{}

// PagesListResp struct for PagesListResp
type PagesListResp struct {
	Items                []PagesPageSiteResponse `json:"items,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PagesListResp PagesListResp

// NewPagesListResp instantiates a new PagesListResp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPagesListResp() *PagesListResp {
	this := PagesListResp{}
	return &this
}

// NewPagesListRespWithDefaults instantiates a new PagesListResp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPagesListRespWithDefaults() *PagesListResp {
	this := PagesListResp{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *PagesListResp) GetItems() []PagesPageSiteResponse {
	if o == nil || IsNil(o.Items) {
		var ret []PagesPageSiteResponse
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PagesListResp) GetItemsOk() ([]PagesPageSiteResponse, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *PagesListResp) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []PagesPageSiteResponse and assigns it to the Items field.
func (o *PagesListResp) SetItems(v []PagesPageSiteResponse) {
	o.Items = v
}

func (o PagesListResp) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PagesListResp) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PagesListResp) UnmarshalJSON(data []byte) (err error) {
	varPagesListResp := _PagesListResp{}

	err = json.Unmarshal(data, &varPagesListResp)

	if err != nil {
		return err
	}

	*o = PagesListResp(varPagesListResp)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "items")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePagesListResp struct {
	value *PagesListResp
	isSet bool
}

func (v NullablePagesListResp) Get() *PagesListResp {
	return v.value
}

func (v *NullablePagesListResp) Set(val *PagesListResp) {
	v.value = val
	v.isSet = true
}

func (v NullablePagesListResp) IsSet() bool {
	return v.isSet
}

func (v *NullablePagesListResp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePagesListResp(val *PagesListResp) *NullablePagesListResp {
	return &NullablePagesListResp{value: val, isSet: true}
}

func (v NullablePagesListResp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePagesListResp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
