/*
RCABench API

RCABench - A comprehensive root cause analysis benchmarking platform for microservices

API version: 1.0.0
Contact: team@rcabench.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
)

// checks if the ChaosNode type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChaosNode{}

// ChaosNode struct for ChaosNode
type ChaosNode struct {
	Children             *map[string]ChaosNode `json:"children,omitempty"`
	Description          *string               `json:"description,omitempty"`
	Name                 *string               `json:"name,omitempty"`
	Range                []int32               `json:"range,omitempty"`
	Value                *int32                `json:"value,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ChaosNode ChaosNode

// NewChaosNode instantiates a new ChaosNode object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChaosNode() *ChaosNode {
	this := ChaosNode{}
	return &this
}

// NewChaosNodeWithDefaults instantiates a new ChaosNode object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChaosNodeWithDefaults() *ChaosNode {
	this := ChaosNode{}
	return &this
}

// GetChildren returns the Children field value if set, zero value otherwise.
func (o *ChaosNode) GetChildren() map[string]ChaosNode {
	if o == nil || IsNil(o.Children) {
		var ret map[string]ChaosNode
		return ret
	}
	return *o.Children
}

// GetChildrenOk returns a tuple with the Children field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChaosNode) GetChildrenOk() (*map[string]ChaosNode, bool) {
	if o == nil || IsNil(o.Children) {
		return nil, false
	}
	return o.Children, true
}

// HasChildren returns a boolean if a field has been set.
func (o *ChaosNode) HasChildren() bool {
	if o != nil && !IsNil(o.Children) {
		return true
	}

	return false
}

// SetChildren gets a reference to the given map[string]ChaosNode and assigns it to the Children field.
func (o *ChaosNode) SetChildren(v map[string]ChaosNode) {
	o.Children = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ChaosNode) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChaosNode) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ChaosNode) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ChaosNode) SetDescription(v string) {
	o.Description = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ChaosNode) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChaosNode) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ChaosNode) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ChaosNode) SetName(v string) {
	o.Name = &v
}

// GetRange returns the Range field value if set, zero value otherwise.
func (o *ChaosNode) GetRange() []int32 {
	if o == nil || IsNil(o.Range) {
		var ret []int32
		return ret
	}
	return o.Range
}

// GetRangeOk returns a tuple with the Range field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChaosNode) GetRangeOk() ([]int32, bool) {
	if o == nil || IsNil(o.Range) {
		return nil, false
	}
	return o.Range, true
}

// HasRange returns a boolean if a field has been set.
func (o *ChaosNode) HasRange() bool {
	if o != nil && !IsNil(o.Range) {
		return true
	}

	return false
}

// SetRange gets a reference to the given []int32 and assigns it to the Range field.
func (o *ChaosNode) SetRange(v []int32) {
	o.Range = v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *ChaosNode) GetValue() int32 {
	if o == nil || IsNil(o.Value) {
		var ret int32
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChaosNode) GetValueOk() (*int32, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *ChaosNode) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given int32 and assigns it to the Value field.
func (o *ChaosNode) SetValue(v int32) {
	o.Value = &v
}

func (o ChaosNode) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChaosNode) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Children) {
		toSerialize["children"] = o.Children
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Range) {
		toSerialize["range"] = o.Range
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ChaosNode) UnmarshalJSON(data []byte) (err error) {
	varChaosNode := _ChaosNode{}

	err = json.Unmarshal(data, &varChaosNode)

	if err != nil {
		return err
	}

	*o = ChaosNode(varChaosNode)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "children")
		delete(additionalProperties, "description")
		delete(additionalProperties, "name")
		delete(additionalProperties, "range")
		delete(additionalProperties, "value")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableChaosNode struct {
	value *ChaosNode
	isSet bool
}

func (v NullableChaosNode) Get() *ChaosNode {
	return v.value
}

func (v *NullableChaosNode) Set(val *ChaosNode) {
	v.value = val
	v.isSet = true
}

func (v NullableChaosNode) IsSet() bool {
	return v.isSet
}

func (v *NullableChaosNode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChaosNode(val *ChaosNode) *NullableChaosNode {
	return &NullableChaosNode{value: val, isSet: true}
}

func (v NullableChaosNode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChaosNode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
