/*
RCABench API

RCABench - A comprehensive root cause analysis benchmarking platform for microservices

API version: 1.0.0
Contact: team@rcabench.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
)

// checks if the DtoGenericResponseSystemListNamespaceLockResp type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DtoGenericResponseSystemListNamespaceLockResp{}

// DtoGenericResponseSystemListNamespaceLockResp struct for DtoGenericResponseSystemListNamespaceLockResp
type DtoGenericResponseSystemListNamespaceLockResp struct {
	// Status code
	Code *int32 `json:"code,omitempty"`
	// Generic type data
	Data *SystemListNamespaceLockResp `json:"data,omitempty"`
	// Response message
	Message *string `json:"message,omitempty"`
	// Response generation time
	Timestamp            *int32 `json:"timestamp,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _DtoGenericResponseSystemListNamespaceLockResp DtoGenericResponseSystemListNamespaceLockResp

// NewDtoGenericResponseSystemListNamespaceLockResp instantiates a new DtoGenericResponseSystemListNamespaceLockResp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDtoGenericResponseSystemListNamespaceLockResp() *DtoGenericResponseSystemListNamespaceLockResp {
	this := DtoGenericResponseSystemListNamespaceLockResp{}
	return &this
}

// NewDtoGenericResponseSystemListNamespaceLockRespWithDefaults instantiates a new DtoGenericResponseSystemListNamespaceLockResp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDtoGenericResponseSystemListNamespaceLockRespWithDefaults() *DtoGenericResponseSystemListNamespaceLockResp {
	this := DtoGenericResponseSystemListNamespaceLockResp{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *DtoGenericResponseSystemListNamespaceLockResp) GetCode() int32 {
	if o == nil || IsNil(o.Code) {
		var ret int32
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoGenericResponseSystemListNamespaceLockResp) GetCodeOk() (*int32, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *DtoGenericResponseSystemListNamespaceLockResp) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given int32 and assigns it to the Code field.
func (o *DtoGenericResponseSystemListNamespaceLockResp) SetCode(v int32) {
	o.Code = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *DtoGenericResponseSystemListNamespaceLockResp) GetData() SystemListNamespaceLockResp {
	if o == nil || IsNil(o.Data) {
		var ret SystemListNamespaceLockResp
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoGenericResponseSystemListNamespaceLockResp) GetDataOk() (*SystemListNamespaceLockResp, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *DtoGenericResponseSystemListNamespaceLockResp) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given SystemListNamespaceLockResp and assigns it to the Data field.
func (o *DtoGenericResponseSystemListNamespaceLockResp) SetData(v SystemListNamespaceLockResp) {
	o.Data = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *DtoGenericResponseSystemListNamespaceLockResp) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoGenericResponseSystemListNamespaceLockResp) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *DtoGenericResponseSystemListNamespaceLockResp) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *DtoGenericResponseSystemListNamespaceLockResp) SetMessage(v string) {
	o.Message = &v
}

// GetTimestamp returns the Timestamp field value if set, zero value otherwise.
func (o *DtoGenericResponseSystemListNamespaceLockResp) GetTimestamp() int32 {
	if o == nil || IsNil(o.Timestamp) {
		var ret int32
		return ret
	}
	return *o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoGenericResponseSystemListNamespaceLockResp) GetTimestampOk() (*int32, bool) {
	if o == nil || IsNil(o.Timestamp) {
		return nil, false
	}
	return o.Timestamp, true
}

// HasTimestamp returns a boolean if a field has been set.
func (o *DtoGenericResponseSystemListNamespaceLockResp) HasTimestamp() bool {
	if o != nil && !IsNil(o.Timestamp) {
		return true
	}

	return false
}

// SetTimestamp gets a reference to the given int32 and assigns it to the Timestamp field.
func (o *DtoGenericResponseSystemListNamespaceLockResp) SetTimestamp(v int32) {
	o.Timestamp = &v
}

func (o DtoGenericResponseSystemListNamespaceLockResp) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DtoGenericResponseSystemListNamespaceLockResp) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Timestamp) {
		toSerialize["timestamp"] = o.Timestamp
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DtoGenericResponseSystemListNamespaceLockResp) UnmarshalJSON(data []byte) (err error) {
	varDtoGenericResponseSystemListNamespaceLockResp := _DtoGenericResponseSystemListNamespaceLockResp{}

	err = json.Unmarshal(data, &varDtoGenericResponseSystemListNamespaceLockResp)

	if err != nil {
		return err
	}

	*o = DtoGenericResponseSystemListNamespaceLockResp(varDtoGenericResponseSystemListNamespaceLockResp)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "code")
		delete(additionalProperties, "data")
		delete(additionalProperties, "message")
		delete(additionalProperties, "timestamp")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDtoGenericResponseSystemListNamespaceLockResp struct {
	value *DtoGenericResponseSystemListNamespaceLockResp
	isSet bool
}

func (v NullableDtoGenericResponseSystemListNamespaceLockResp) Get() *DtoGenericResponseSystemListNamespaceLockResp {
	return v.value
}

func (v *NullableDtoGenericResponseSystemListNamespaceLockResp) Set(val *DtoGenericResponseSystemListNamespaceLockResp) {
	v.value = val
	v.isSet = true
}

func (v NullableDtoGenericResponseSystemListNamespaceLockResp) IsSet() bool {
	return v.isSet
}

func (v *NullableDtoGenericResponseSystemListNamespaceLockResp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDtoGenericResponseSystemListNamespaceLockResp(val *DtoGenericResponseSystemListNamespaceLockResp) *NullableDtoGenericResponseSystemListNamespaceLockResp {
	return &NullableDtoGenericResponseSystemListNamespaceLockResp{value: val, isSet: true}
}

func (v NullableDtoGenericResponseSystemListNamespaceLockResp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDtoGenericResponseSystemListNamespaceLockResp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
