/*
RCABench API

RCABench - A comprehensive root cause analysis benchmarking platform for microservices

API version: 1.0.0
Contact: team@rcabench.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
)

// checks if the InjectionGuidedSpec type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InjectionGuidedSpec{}

// InjectionGuidedSpec struct for InjectionGuidedSpec
type InjectionGuidedSpec struct {
	App                  *string `json:"app,omitempty"`
	BodyType             *string `json:"body_type,omitempty"`
	Buffer               *int32  `json:"buffer,omitempty"`
	ChaosType            *string `json:"chaos_type,omitempty"`
	Class                *string `json:"class,omitempty"`
	Container            *string `json:"container,omitempty"`
	Correlation          *int32  `json:"correlation,omitempty"`
	Corrupt              *int32  `json:"corrupt,omitempty"`
	CpuCount             *int32  `json:"cpu_count,omitempty"`
	CpuLoad              *int32  `json:"cpu_load,omitempty"`
	CpuWorker            *int32  `json:"cpu_worker,omitempty"`
	Database             *string `json:"database,omitempty"`
	DelayDuration        *int32  `json:"delay_duration,omitempty"`
	Direction            *string `json:"direction,omitempty"`
	Domain               *string `json:"domain,omitempty"`
	Duplicate            *int32  `json:"duplicate,omitempty"`
	Duration             *int32  `json:"duration,omitempty"`
	ExceptionOpt         *string `json:"exception_opt,omitempty"`
	HttpMethod           *string `json:"http_method,omitempty"`
	Jitter               *int32  `json:"jitter,omitempty"`
	Latency              *int32  `json:"latency,omitempty"`
	LatencyDuration      *int32  `json:"latency_duration,omitempty"`
	LatencyMs            *int32  `json:"latency_ms,omitempty"`
	Limit                *int32  `json:"limit,omitempty"`
	Loss                 *int32  `json:"loss,omitempty"`
	MemType              *string `json:"mem_type,omitempty"`
	MemWorker            *int32  `json:"mem_worker,omitempty"`
	MemorySize           *int32  `json:"memory_size,omitempty"`
	Method               *string `json:"method,omitempty"`
	MutatorConfig        *string `json:"mutator_config,omitempty"`
	Namespace            *string `json:"namespace,omitempty"`
	Operation            *string `json:"operation,omitempty"`
	Rate                 *int32  `json:"rate,omitempty"`
	ReplaceMethod        *string `json:"replace_method,omitempty"`
	ReturnType           *string `json:"return_type,omitempty"`
	ReturnValueOpt       *string `json:"return_value_opt,omitempty"`
	Route                *string `json:"route,omitempty"`
	StatusCode           *int32  `json:"status_code,omitempty"`
	System               *string `json:"system,omitempty"`
	SystemType           *string `json:"system_type,omitempty"`
	Table                *string `json:"table,omitempty"`
	TargetService        *string `json:"target_service,omitempty"`
	TimeOffset           *int32  `json:"time_offset,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _InjectionGuidedSpec InjectionGuidedSpec

// NewInjectionGuidedSpec instantiates a new InjectionGuidedSpec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInjectionGuidedSpec() *InjectionGuidedSpec {
	this := InjectionGuidedSpec{}
	return &this
}

// NewInjectionGuidedSpecWithDefaults instantiates a new InjectionGuidedSpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInjectionGuidedSpecWithDefaults() *InjectionGuidedSpec {
	this := InjectionGuidedSpec{}
	return &this
}

// GetApp returns the App field value if set, zero value otherwise.
func (o *InjectionGuidedSpec) GetApp() string {
	if o == nil || IsNil(o.App) {
		var ret string
		return ret
	}
	return *o.App
}

// GetAppOk returns a tuple with the App field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InjectionGuidedSpec) GetAppOk() (*string, bool) {
	if o == nil || IsNil(o.App) {
		return nil, false
	}
	return o.App, true
}

// HasApp returns a boolean if a field has been set.
func (o *InjectionGuidedSpec) HasApp() bool {
	if o != nil && !IsNil(o.App) {
		return true
	}

	return false
}

// SetApp gets a reference to the given string and assigns it to the App field.
func (o *InjectionGuidedSpec) SetApp(v string) {
	o.App = &v
}

// GetBodyType returns the BodyType field value if set, zero value otherwise.
func (o *InjectionGuidedSpec) GetBodyType() string {
	if o == nil || IsNil(o.BodyType) {
		var ret string
		return ret
	}
	return *o.BodyType
}

// GetBodyTypeOk returns a tuple with the BodyType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InjectionGuidedSpec) GetBodyTypeOk() (*string, bool) {
	if o == nil || IsNil(o.BodyType) {
		return nil, false
	}
	return o.BodyType, true
}

// HasBodyType returns a boolean if a field has been set.
func (o *InjectionGuidedSpec) HasBodyType() bool {
	if o != nil && !IsNil(o.BodyType) {
		return true
	}

	return false
}

// SetBodyType gets a reference to the given string and assigns it to the BodyType field.
func (o *InjectionGuidedSpec) SetBodyType(v string) {
	o.BodyType = &v
}

// GetBuffer returns the Buffer field value if set, zero value otherwise.
func (o *InjectionGuidedSpec) GetBuffer() int32 {
	if o == nil || IsNil(o.Buffer) {
		var ret int32
		return ret
	}
	return *o.Buffer
}

// GetBufferOk returns a tuple with the Buffer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InjectionGuidedSpec) GetBufferOk() (*int32, bool) {
	if o == nil || IsNil(o.Buffer) {
		return nil, false
	}
	return o.Buffer, true
}

// HasBuffer returns a boolean if a field has been set.
func (o *InjectionGuidedSpec) HasBuffer() bool {
	if o != nil && !IsNil(o.Buffer) {
		return true
	}

	return false
}

// SetBuffer gets a reference to the given int32 and assigns it to the Buffer field.
func (o *InjectionGuidedSpec) SetBuffer(v int32) {
	o.Buffer = &v
}

// GetChaosType returns the ChaosType field value if set, zero value otherwise.
func (o *InjectionGuidedSpec) GetChaosType() string {
	if o == nil || IsNil(o.ChaosType) {
		var ret string
		return ret
	}
	return *o.ChaosType
}

// GetChaosTypeOk returns a tuple with the ChaosType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InjectionGuidedSpec) GetChaosTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ChaosType) {
		return nil, false
	}
	return o.ChaosType, true
}

// HasChaosType returns a boolean if a field has been set.
func (o *InjectionGuidedSpec) HasChaosType() bool {
	if o != nil && !IsNil(o.ChaosType) {
		return true
	}

	return false
}

// SetChaosType gets a reference to the given string and assigns it to the ChaosType field.
func (o *InjectionGuidedSpec) SetChaosType(v string) {
	o.ChaosType = &v
}

// GetClass returns the Class field value if set, zero value otherwise.
func (o *InjectionGuidedSpec) GetClass() string {
	if o == nil || IsNil(o.Class) {
		var ret string
		return ret
	}
	return *o.Class
}

// GetClassOk returns a tuple with the Class field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InjectionGuidedSpec) GetClassOk() (*string, bool) {
	if o == nil || IsNil(o.Class) {
		return nil, false
	}
	return o.Class, true
}

// HasClass returns a boolean if a field has been set.
func (o *InjectionGuidedSpec) HasClass() bool {
	if o != nil && !IsNil(o.Class) {
		return true
	}

	return false
}

// SetClass gets a reference to the given string and assigns it to the Class field.
func (o *InjectionGuidedSpec) SetClass(v string) {
	o.Class = &v
}

// GetContainer returns the Container field value if set, zero value otherwise.
func (o *InjectionGuidedSpec) GetContainer() string {
	if o == nil || IsNil(o.Container) {
		var ret string
		return ret
	}
	return *o.Container
}

// GetContainerOk returns a tuple with the Container field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InjectionGuidedSpec) GetContainerOk() (*string, bool) {
	if o == nil || IsNil(o.Container) {
		return nil, false
	}
	return o.Container, true
}

// HasContainer returns a boolean if a field has been set.
func (o *InjectionGuidedSpec) HasContainer() bool {
	if o != nil && !IsNil(o.Container) {
		return true
	}

	return false
}

// SetContainer gets a reference to the given string and assigns it to the Container field.
func (o *InjectionGuidedSpec) SetContainer(v string) {
	o.Container = &v
}

// GetCorrelation returns the Correlation field value if set, zero value otherwise.
func (o *InjectionGuidedSpec) GetCorrelation() int32 {
	if o == nil || IsNil(o.Correlation) {
		var ret int32
		return ret
	}
	return *o.Correlation
}

// GetCorrelationOk returns a tuple with the Correlation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InjectionGuidedSpec) GetCorrelationOk() (*int32, bool) {
	if o == nil || IsNil(o.Correlation) {
		return nil, false
	}
	return o.Correlation, true
}

// HasCorrelation returns a boolean if a field has been set.
func (o *InjectionGuidedSpec) HasCorrelation() bool {
	if o != nil && !IsNil(o.Correlation) {
		return true
	}

	return false
}

// SetCorrelation gets a reference to the given int32 and assigns it to the Correlation field.
func (o *InjectionGuidedSpec) SetCorrelation(v int32) {
	o.Correlation = &v
}

// GetCorrupt returns the Corrupt field value if set, zero value otherwise.
func (o *InjectionGuidedSpec) GetCorrupt() int32 {
	if o == nil || IsNil(o.Corrupt) {
		var ret int32
		return ret
	}
	return *o.Corrupt
}

// GetCorruptOk returns a tuple with the Corrupt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InjectionGuidedSpec) GetCorruptOk() (*int32, bool) {
	if o == nil || IsNil(o.Corrupt) {
		return nil, false
	}
	return o.Corrupt, true
}

// HasCorrupt returns a boolean if a field has been set.
func (o *InjectionGuidedSpec) HasCorrupt() bool {
	if o != nil && !IsNil(o.Corrupt) {
		return true
	}

	return false
}

// SetCorrupt gets a reference to the given int32 and assigns it to the Corrupt field.
func (o *InjectionGuidedSpec) SetCorrupt(v int32) {
	o.Corrupt = &v
}

// GetCpuCount returns the CpuCount field value if set, zero value otherwise.
func (o *InjectionGuidedSpec) GetCpuCount() int32 {
	if o == nil || IsNil(o.CpuCount) {
		var ret int32
		return ret
	}
	return *o.CpuCount
}

// GetCpuCountOk returns a tuple with the CpuCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InjectionGuidedSpec) GetCpuCountOk() (*int32, bool) {
	if o == nil || IsNil(o.CpuCount) {
		return nil, false
	}
	return o.CpuCount, true
}

// HasCpuCount returns a boolean if a field has been set.
func (o *InjectionGuidedSpec) HasCpuCount() bool {
	if o != nil && !IsNil(o.CpuCount) {
		return true
	}

	return false
}

// SetCpuCount gets a reference to the given int32 and assigns it to the CpuCount field.
func (o *InjectionGuidedSpec) SetCpuCount(v int32) {
	o.CpuCount = &v
}

// GetCpuLoad returns the CpuLoad field value if set, zero value otherwise.
func (o *InjectionGuidedSpec) GetCpuLoad() int32 {
	if o == nil || IsNil(o.CpuLoad) {
		var ret int32
		return ret
	}
	return *o.CpuLoad
}

// GetCpuLoadOk returns a tuple with the CpuLoad field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InjectionGuidedSpec) GetCpuLoadOk() (*int32, bool) {
	if o == nil || IsNil(o.CpuLoad) {
		return nil, false
	}
	return o.CpuLoad, true
}

// HasCpuLoad returns a boolean if a field has been set.
func (o *InjectionGuidedSpec) HasCpuLoad() bool {
	if o != nil && !IsNil(o.CpuLoad) {
		return true
	}

	return false
}

// SetCpuLoad gets a reference to the given int32 and assigns it to the CpuLoad field.
func (o *InjectionGuidedSpec) SetCpuLoad(v int32) {
	o.CpuLoad = &v
}

// GetCpuWorker returns the CpuWorker field value if set, zero value otherwise.
func (o *InjectionGuidedSpec) GetCpuWorker() int32 {
	if o == nil || IsNil(o.CpuWorker) {
		var ret int32
		return ret
	}
	return *o.CpuWorker
}

// GetCpuWorkerOk returns a tuple with the CpuWorker field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InjectionGuidedSpec) GetCpuWorkerOk() (*int32, bool) {
	if o == nil || IsNil(o.CpuWorker) {
		return nil, false
	}
	return o.CpuWorker, true
}

// HasCpuWorker returns a boolean if a field has been set.
func (o *InjectionGuidedSpec) HasCpuWorker() bool {
	if o != nil && !IsNil(o.CpuWorker) {
		return true
	}

	return false
}

// SetCpuWorker gets a reference to the given int32 and assigns it to the CpuWorker field.
func (o *InjectionGuidedSpec) SetCpuWorker(v int32) {
	o.CpuWorker = &v
}

// GetDatabase returns the Database field value if set, zero value otherwise.
func (o *InjectionGuidedSpec) GetDatabase() string {
	if o == nil || IsNil(o.Database) {
		var ret string
		return ret
	}
	return *o.Database
}

// GetDatabaseOk returns a tuple with the Database field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InjectionGuidedSpec) GetDatabaseOk() (*string, bool) {
	if o == nil || IsNil(o.Database) {
		return nil, false
	}
	return o.Database, true
}

// HasDatabase returns a boolean if a field has been set.
func (o *InjectionGuidedSpec) HasDatabase() bool {
	if o != nil && !IsNil(o.Database) {
		return true
	}

	return false
}

// SetDatabase gets a reference to the given string and assigns it to the Database field.
func (o *InjectionGuidedSpec) SetDatabase(v string) {
	o.Database = &v
}

// GetDelayDuration returns the DelayDuration field value if set, zero value otherwise.
func (o *InjectionGuidedSpec) GetDelayDuration() int32 {
	if o == nil || IsNil(o.DelayDuration) {
		var ret int32
		return ret
	}
	return *o.DelayDuration
}

// GetDelayDurationOk returns a tuple with the DelayDuration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InjectionGuidedSpec) GetDelayDurationOk() (*int32, bool) {
	if o == nil || IsNil(o.DelayDuration) {
		return nil, false
	}
	return o.DelayDuration, true
}

// HasDelayDuration returns a boolean if a field has been set.
func (o *InjectionGuidedSpec) HasDelayDuration() bool {
	if o != nil && !IsNil(o.DelayDuration) {
		return true
	}

	return false
}

// SetDelayDuration gets a reference to the given int32 and assigns it to the DelayDuration field.
func (o *InjectionGuidedSpec) SetDelayDuration(v int32) {
	o.DelayDuration = &v
}

// GetDirection returns the Direction field value if set, zero value otherwise.
func (o *InjectionGuidedSpec) GetDirection() string {
	if o == nil || IsNil(o.Direction) {
		var ret string
		return ret
	}
	return *o.Direction
}

// GetDirectionOk returns a tuple with the Direction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InjectionGuidedSpec) GetDirectionOk() (*string, bool) {
	if o == nil || IsNil(o.Direction) {
		return nil, false
	}
	return o.Direction, true
}

// HasDirection returns a boolean if a field has been set.
func (o *InjectionGuidedSpec) HasDirection() bool {
	if o != nil && !IsNil(o.Direction) {
		return true
	}

	return false
}

// SetDirection gets a reference to the given string and assigns it to the Direction field.
func (o *InjectionGuidedSpec) SetDirection(v string) {
	o.Direction = &v
}

// GetDomain returns the Domain field value if set, zero value otherwise.
func (o *InjectionGuidedSpec) GetDomain() string {
	if o == nil || IsNil(o.Domain) {
		var ret string
		return ret
	}
	return *o.Domain
}

// GetDomainOk returns a tuple with the Domain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InjectionGuidedSpec) GetDomainOk() (*string, bool) {
	if o == nil || IsNil(o.Domain) {
		return nil, false
	}
	return o.Domain, true
}

// HasDomain returns a boolean if a field has been set.
func (o *InjectionGuidedSpec) HasDomain() bool {
	if o != nil && !IsNil(o.Domain) {
		return true
	}

	return false
}

// SetDomain gets a reference to the given string and assigns it to the Domain field.
func (o *InjectionGuidedSpec) SetDomain(v string) {
	o.Domain = &v
}

// GetDuplicate returns the Duplicate field value if set, zero value otherwise.
func (o *InjectionGuidedSpec) GetDuplicate() int32 {
	if o == nil || IsNil(o.Duplicate) {
		var ret int32
		return ret
	}
	return *o.Duplicate
}

// GetDuplicateOk returns a tuple with the Duplicate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InjectionGuidedSpec) GetDuplicateOk() (*int32, bool) {
	if o == nil || IsNil(o.Duplicate) {
		return nil, false
	}
	return o.Duplicate, true
}

// HasDuplicate returns a boolean if a field has been set.
func (o *InjectionGuidedSpec) HasDuplicate() bool {
	if o != nil && !IsNil(o.Duplicate) {
		return true
	}

	return false
}

// SetDuplicate gets a reference to the given int32 and assigns it to the Duplicate field.
func (o *InjectionGuidedSpec) SetDuplicate(v int32) {
	o.Duplicate = &v
}

// GetDuration returns the Duration field value if set, zero value otherwise.
func (o *InjectionGuidedSpec) GetDuration() int32 {
	if o == nil || IsNil(o.Duration) {
		var ret int32
		return ret
	}
	return *o.Duration
}

// GetDurationOk returns a tuple with the Duration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InjectionGuidedSpec) GetDurationOk() (*int32, bool) {
	if o == nil || IsNil(o.Duration) {
		return nil, false
	}
	return o.Duration, true
}

// HasDuration returns a boolean if a field has been set.
func (o *InjectionGuidedSpec) HasDuration() bool {
	if o != nil && !IsNil(o.Duration) {
		return true
	}

	return false
}

// SetDuration gets a reference to the given int32 and assigns it to the Duration field.
func (o *InjectionGuidedSpec) SetDuration(v int32) {
	o.Duration = &v
}

// GetExceptionOpt returns the ExceptionOpt field value if set, zero value otherwise.
func (o *InjectionGuidedSpec) GetExceptionOpt() string {
	if o == nil || IsNil(o.ExceptionOpt) {
		var ret string
		return ret
	}
	return *o.ExceptionOpt
}

// GetExceptionOptOk returns a tuple with the ExceptionOpt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InjectionGuidedSpec) GetExceptionOptOk() (*string, bool) {
	if o == nil || IsNil(o.ExceptionOpt) {
		return nil, false
	}
	return o.ExceptionOpt, true
}

// HasExceptionOpt returns a boolean if a field has been set.
func (o *InjectionGuidedSpec) HasExceptionOpt() bool {
	if o != nil && !IsNil(o.ExceptionOpt) {
		return true
	}

	return false
}

// SetExceptionOpt gets a reference to the given string and assigns it to the ExceptionOpt field.
func (o *InjectionGuidedSpec) SetExceptionOpt(v string) {
	o.ExceptionOpt = &v
}

// GetHttpMethod returns the HttpMethod field value if set, zero value otherwise.
func (o *InjectionGuidedSpec) GetHttpMethod() string {
	if o == nil || IsNil(o.HttpMethod) {
		var ret string
		return ret
	}
	return *o.HttpMethod
}

// GetHttpMethodOk returns a tuple with the HttpMethod field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InjectionGuidedSpec) GetHttpMethodOk() (*string, bool) {
	if o == nil || IsNil(o.HttpMethod) {
		return nil, false
	}
	return o.HttpMethod, true
}

// HasHttpMethod returns a boolean if a field has been set.
func (o *InjectionGuidedSpec) HasHttpMethod() bool {
	if o != nil && !IsNil(o.HttpMethod) {
		return true
	}

	return false
}

// SetHttpMethod gets a reference to the given string and assigns it to the HttpMethod field.
func (o *InjectionGuidedSpec) SetHttpMethod(v string) {
	o.HttpMethod = &v
}

// GetJitter returns the Jitter field value if set, zero value otherwise.
func (o *InjectionGuidedSpec) GetJitter() int32 {
	if o == nil || IsNil(o.Jitter) {
		var ret int32
		return ret
	}
	return *o.Jitter
}

// GetJitterOk returns a tuple with the Jitter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InjectionGuidedSpec) GetJitterOk() (*int32, bool) {
	if o == nil || IsNil(o.Jitter) {
		return nil, false
	}
	return o.Jitter, true
}

// HasJitter returns a boolean if a field has been set.
func (o *InjectionGuidedSpec) HasJitter() bool {
	if o != nil && !IsNil(o.Jitter) {
		return true
	}

	return false
}

// SetJitter gets a reference to the given int32 and assigns it to the Jitter field.
func (o *InjectionGuidedSpec) SetJitter(v int32) {
	o.Jitter = &v
}

// GetLatency returns the Latency field value if set, zero value otherwise.
func (o *InjectionGuidedSpec) GetLatency() int32 {
	if o == nil || IsNil(o.Latency) {
		var ret int32
		return ret
	}
	return *o.Latency
}

// GetLatencyOk returns a tuple with the Latency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InjectionGuidedSpec) GetLatencyOk() (*int32, bool) {
	if o == nil || IsNil(o.Latency) {
		return nil, false
	}
	return o.Latency, true
}

// HasLatency returns a boolean if a field has been set.
func (o *InjectionGuidedSpec) HasLatency() bool {
	if o != nil && !IsNil(o.Latency) {
		return true
	}

	return false
}

// SetLatency gets a reference to the given int32 and assigns it to the Latency field.
func (o *InjectionGuidedSpec) SetLatency(v int32) {
	o.Latency = &v
}

// GetLatencyDuration returns the LatencyDuration field value if set, zero value otherwise.
func (o *InjectionGuidedSpec) GetLatencyDuration() int32 {
	if o == nil || IsNil(o.LatencyDuration) {
		var ret int32
		return ret
	}
	return *o.LatencyDuration
}

// GetLatencyDurationOk returns a tuple with the LatencyDuration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InjectionGuidedSpec) GetLatencyDurationOk() (*int32, bool) {
	if o == nil || IsNil(o.LatencyDuration) {
		return nil, false
	}
	return o.LatencyDuration, true
}

// HasLatencyDuration returns a boolean if a field has been set.
func (o *InjectionGuidedSpec) HasLatencyDuration() bool {
	if o != nil && !IsNil(o.LatencyDuration) {
		return true
	}

	return false
}

// SetLatencyDuration gets a reference to the given int32 and assigns it to the LatencyDuration field.
func (o *InjectionGuidedSpec) SetLatencyDuration(v int32) {
	o.LatencyDuration = &v
}

// GetLatencyMs returns the LatencyMs field value if set, zero value otherwise.
func (o *InjectionGuidedSpec) GetLatencyMs() int32 {
	if o == nil || IsNil(o.LatencyMs) {
		var ret int32
		return ret
	}
	return *o.LatencyMs
}

// GetLatencyMsOk returns a tuple with the LatencyMs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InjectionGuidedSpec) GetLatencyMsOk() (*int32, bool) {
	if o == nil || IsNil(o.LatencyMs) {
		return nil, false
	}
	return o.LatencyMs, true
}

// HasLatencyMs returns a boolean if a field has been set.
func (o *InjectionGuidedSpec) HasLatencyMs() bool {
	if o != nil && !IsNil(o.LatencyMs) {
		return true
	}

	return false
}

// SetLatencyMs gets a reference to the given int32 and assigns it to the LatencyMs field.
func (o *InjectionGuidedSpec) SetLatencyMs(v int32) {
	o.LatencyMs = &v
}

// GetLimit returns the Limit field value if set, zero value otherwise.
func (o *InjectionGuidedSpec) GetLimit() int32 {
	if o == nil || IsNil(o.Limit) {
		var ret int32
		return ret
	}
	return *o.Limit
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InjectionGuidedSpec) GetLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.Limit) {
		return nil, false
	}
	return o.Limit, true
}

// HasLimit returns a boolean if a field has been set.
func (o *InjectionGuidedSpec) HasLimit() bool {
	if o != nil && !IsNil(o.Limit) {
		return true
	}

	return false
}

// SetLimit gets a reference to the given int32 and assigns it to the Limit field.
func (o *InjectionGuidedSpec) SetLimit(v int32) {
	o.Limit = &v
}

// GetLoss returns the Loss field value if set, zero value otherwise.
func (o *InjectionGuidedSpec) GetLoss() int32 {
	if o == nil || IsNil(o.Loss) {
		var ret int32
		return ret
	}
	return *o.Loss
}

// GetLossOk returns a tuple with the Loss field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InjectionGuidedSpec) GetLossOk() (*int32, bool) {
	if o == nil || IsNil(o.Loss) {
		return nil, false
	}
	return o.Loss, true
}

// HasLoss returns a boolean if a field has been set.
func (o *InjectionGuidedSpec) HasLoss() bool {
	if o != nil && !IsNil(o.Loss) {
		return true
	}

	return false
}

// SetLoss gets a reference to the given int32 and assigns it to the Loss field.
func (o *InjectionGuidedSpec) SetLoss(v int32) {
	o.Loss = &v
}

// GetMemType returns the MemType field value if set, zero value otherwise.
func (o *InjectionGuidedSpec) GetMemType() string {
	if o == nil || IsNil(o.MemType) {
		var ret string
		return ret
	}
	return *o.MemType
}

// GetMemTypeOk returns a tuple with the MemType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InjectionGuidedSpec) GetMemTypeOk() (*string, bool) {
	if o == nil || IsNil(o.MemType) {
		return nil, false
	}
	return o.MemType, true
}

// HasMemType returns a boolean if a field has been set.
func (o *InjectionGuidedSpec) HasMemType() bool {
	if o != nil && !IsNil(o.MemType) {
		return true
	}

	return false
}

// SetMemType gets a reference to the given string and assigns it to the MemType field.
func (o *InjectionGuidedSpec) SetMemType(v string) {
	o.MemType = &v
}

// GetMemWorker returns the MemWorker field value if set, zero value otherwise.
func (o *InjectionGuidedSpec) GetMemWorker() int32 {
	if o == nil || IsNil(o.MemWorker) {
		var ret int32
		return ret
	}
	return *o.MemWorker
}

// GetMemWorkerOk returns a tuple with the MemWorker field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InjectionGuidedSpec) GetMemWorkerOk() (*int32, bool) {
	if o == nil || IsNil(o.MemWorker) {
		return nil, false
	}
	return o.MemWorker, true
}

// HasMemWorker returns a boolean if a field has been set.
func (o *InjectionGuidedSpec) HasMemWorker() bool {
	if o != nil && !IsNil(o.MemWorker) {
		return true
	}

	return false
}

// SetMemWorker gets a reference to the given int32 and assigns it to the MemWorker field.
func (o *InjectionGuidedSpec) SetMemWorker(v int32) {
	o.MemWorker = &v
}

// GetMemorySize returns the MemorySize field value if set, zero value otherwise.
func (o *InjectionGuidedSpec) GetMemorySize() int32 {
	if o == nil || IsNil(o.MemorySize) {
		var ret int32
		return ret
	}
	return *o.MemorySize
}

// GetMemorySizeOk returns a tuple with the MemorySize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InjectionGuidedSpec) GetMemorySizeOk() (*int32, bool) {
	if o == nil || IsNil(o.MemorySize) {
		return nil, false
	}
	return o.MemorySize, true
}

// HasMemorySize returns a boolean if a field has been set.
func (o *InjectionGuidedSpec) HasMemorySize() bool {
	if o != nil && !IsNil(o.MemorySize) {
		return true
	}

	return false
}

// SetMemorySize gets a reference to the given int32 and assigns it to the MemorySize field.
func (o *InjectionGuidedSpec) SetMemorySize(v int32) {
	o.MemorySize = &v
}

// GetMethod returns the Method field value if set, zero value otherwise.
func (o *InjectionGuidedSpec) GetMethod() string {
	if o == nil || IsNil(o.Method) {
		var ret string
		return ret
	}
	return *o.Method
}

// GetMethodOk returns a tuple with the Method field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InjectionGuidedSpec) GetMethodOk() (*string, bool) {
	if o == nil || IsNil(o.Method) {
		return nil, false
	}
	return o.Method, true
}

// HasMethod returns a boolean if a field has been set.
func (o *InjectionGuidedSpec) HasMethod() bool {
	if o != nil && !IsNil(o.Method) {
		return true
	}

	return false
}

// SetMethod gets a reference to the given string and assigns it to the Method field.
func (o *InjectionGuidedSpec) SetMethod(v string) {
	o.Method = &v
}

// GetMutatorConfig returns the MutatorConfig field value if set, zero value otherwise.
func (o *InjectionGuidedSpec) GetMutatorConfig() string {
	if o == nil || IsNil(o.MutatorConfig) {
		var ret string
		return ret
	}
	return *o.MutatorConfig
}

// GetMutatorConfigOk returns a tuple with the MutatorConfig field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InjectionGuidedSpec) GetMutatorConfigOk() (*string, bool) {
	if o == nil || IsNil(o.MutatorConfig) {
		return nil, false
	}
	return o.MutatorConfig, true
}

// HasMutatorConfig returns a boolean if a field has been set.
func (o *InjectionGuidedSpec) HasMutatorConfig() bool {
	if o != nil && !IsNil(o.MutatorConfig) {
		return true
	}

	return false
}

// SetMutatorConfig gets a reference to the given string and assigns it to the MutatorConfig field.
func (o *InjectionGuidedSpec) SetMutatorConfig(v string) {
	o.MutatorConfig = &v
}

// GetNamespace returns the Namespace field value if set, zero value otherwise.
func (o *InjectionGuidedSpec) GetNamespace() string {
	if o == nil || IsNil(o.Namespace) {
		var ret string
		return ret
	}
	return *o.Namespace
}

// GetNamespaceOk returns a tuple with the Namespace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InjectionGuidedSpec) GetNamespaceOk() (*string, bool) {
	if o == nil || IsNil(o.Namespace) {
		return nil, false
	}
	return o.Namespace, true
}

// HasNamespace returns a boolean if a field has been set.
func (o *InjectionGuidedSpec) HasNamespace() bool {
	if o != nil && !IsNil(o.Namespace) {
		return true
	}

	return false
}

// SetNamespace gets a reference to the given string and assigns it to the Namespace field.
func (o *InjectionGuidedSpec) SetNamespace(v string) {
	o.Namespace = &v
}

// GetOperation returns the Operation field value if set, zero value otherwise.
func (o *InjectionGuidedSpec) GetOperation() string {
	if o == nil || IsNil(o.Operation) {
		var ret string
		return ret
	}
	return *o.Operation
}

// GetOperationOk returns a tuple with the Operation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InjectionGuidedSpec) GetOperationOk() (*string, bool) {
	if o == nil || IsNil(o.Operation) {
		return nil, false
	}
	return o.Operation, true
}

// HasOperation returns a boolean if a field has been set.
func (o *InjectionGuidedSpec) HasOperation() bool {
	if o != nil && !IsNil(o.Operation) {
		return true
	}

	return false
}

// SetOperation gets a reference to the given string and assigns it to the Operation field.
func (o *InjectionGuidedSpec) SetOperation(v string) {
	o.Operation = &v
}

// GetRate returns the Rate field value if set, zero value otherwise.
func (o *InjectionGuidedSpec) GetRate() int32 {
	if o == nil || IsNil(o.Rate) {
		var ret int32
		return ret
	}
	return *o.Rate
}

// GetRateOk returns a tuple with the Rate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InjectionGuidedSpec) GetRateOk() (*int32, bool) {
	if o == nil || IsNil(o.Rate) {
		return nil, false
	}
	return o.Rate, true
}

// HasRate returns a boolean if a field has been set.
func (o *InjectionGuidedSpec) HasRate() bool {
	if o != nil && !IsNil(o.Rate) {
		return true
	}

	return false
}

// SetRate gets a reference to the given int32 and assigns it to the Rate field.
func (o *InjectionGuidedSpec) SetRate(v int32) {
	o.Rate = &v
}

// GetReplaceMethod returns the ReplaceMethod field value if set, zero value otherwise.
func (o *InjectionGuidedSpec) GetReplaceMethod() string {
	if o == nil || IsNil(o.ReplaceMethod) {
		var ret string
		return ret
	}
	return *o.ReplaceMethod
}

// GetReplaceMethodOk returns a tuple with the ReplaceMethod field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InjectionGuidedSpec) GetReplaceMethodOk() (*string, bool) {
	if o == nil || IsNil(o.ReplaceMethod) {
		return nil, false
	}
	return o.ReplaceMethod, true
}

// HasReplaceMethod returns a boolean if a field has been set.
func (o *InjectionGuidedSpec) HasReplaceMethod() bool {
	if o != nil && !IsNil(o.ReplaceMethod) {
		return true
	}

	return false
}

// SetReplaceMethod gets a reference to the given string and assigns it to the ReplaceMethod field.
func (o *InjectionGuidedSpec) SetReplaceMethod(v string) {
	o.ReplaceMethod = &v
}

// GetReturnType returns the ReturnType field value if set, zero value otherwise.
func (o *InjectionGuidedSpec) GetReturnType() string {
	if o == nil || IsNil(o.ReturnType) {
		var ret string
		return ret
	}
	return *o.ReturnType
}

// GetReturnTypeOk returns a tuple with the ReturnType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InjectionGuidedSpec) GetReturnTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ReturnType) {
		return nil, false
	}
	return o.ReturnType, true
}

// HasReturnType returns a boolean if a field has been set.
func (o *InjectionGuidedSpec) HasReturnType() bool {
	if o != nil && !IsNil(o.ReturnType) {
		return true
	}

	return false
}

// SetReturnType gets a reference to the given string and assigns it to the ReturnType field.
func (o *InjectionGuidedSpec) SetReturnType(v string) {
	o.ReturnType = &v
}

// GetReturnValueOpt returns the ReturnValueOpt field value if set, zero value otherwise.
func (o *InjectionGuidedSpec) GetReturnValueOpt() string {
	if o == nil || IsNil(o.ReturnValueOpt) {
		var ret string
		return ret
	}
	return *o.ReturnValueOpt
}

// GetReturnValueOptOk returns a tuple with the ReturnValueOpt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InjectionGuidedSpec) GetReturnValueOptOk() (*string, bool) {
	if o == nil || IsNil(o.ReturnValueOpt) {
		return nil, false
	}
	return o.ReturnValueOpt, true
}

// HasReturnValueOpt returns a boolean if a field has been set.
func (o *InjectionGuidedSpec) HasReturnValueOpt() bool {
	if o != nil && !IsNil(o.ReturnValueOpt) {
		return true
	}

	return false
}

// SetReturnValueOpt gets a reference to the given string and assigns it to the ReturnValueOpt field.
func (o *InjectionGuidedSpec) SetReturnValueOpt(v string) {
	o.ReturnValueOpt = &v
}

// GetRoute returns the Route field value if set, zero value otherwise.
func (o *InjectionGuidedSpec) GetRoute() string {
	if o == nil || IsNil(o.Route) {
		var ret string
		return ret
	}
	return *o.Route
}

// GetRouteOk returns a tuple with the Route field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InjectionGuidedSpec) GetRouteOk() (*string, bool) {
	if o == nil || IsNil(o.Route) {
		return nil, false
	}
	return o.Route, true
}

// HasRoute returns a boolean if a field has been set.
func (o *InjectionGuidedSpec) HasRoute() bool {
	if o != nil && !IsNil(o.Route) {
		return true
	}

	return false
}

// SetRoute gets a reference to the given string and assigns it to the Route field.
func (o *InjectionGuidedSpec) SetRoute(v string) {
	o.Route = &v
}

// GetStatusCode returns the StatusCode field value if set, zero value otherwise.
func (o *InjectionGuidedSpec) GetStatusCode() int32 {
	if o == nil || IsNil(o.StatusCode) {
		var ret int32
		return ret
	}
	return *o.StatusCode
}

// GetStatusCodeOk returns a tuple with the StatusCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InjectionGuidedSpec) GetStatusCodeOk() (*int32, bool) {
	if o == nil || IsNil(o.StatusCode) {
		return nil, false
	}
	return o.StatusCode, true
}

// HasStatusCode returns a boolean if a field has been set.
func (o *InjectionGuidedSpec) HasStatusCode() bool {
	if o != nil && !IsNil(o.StatusCode) {
		return true
	}

	return false
}

// SetStatusCode gets a reference to the given int32 and assigns it to the StatusCode field.
func (o *InjectionGuidedSpec) SetStatusCode(v int32) {
	o.StatusCode = &v
}

// GetSystem returns the System field value if set, zero value otherwise.
func (o *InjectionGuidedSpec) GetSystem() string {
	if o == nil || IsNil(o.System) {
		var ret string
		return ret
	}
	return *o.System
}

// GetSystemOk returns a tuple with the System field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InjectionGuidedSpec) GetSystemOk() (*string, bool) {
	if o == nil || IsNil(o.System) {
		return nil, false
	}
	return o.System, true
}

// HasSystem returns a boolean if a field has been set.
func (o *InjectionGuidedSpec) HasSystem() bool {
	if o != nil && !IsNil(o.System) {
		return true
	}

	return false
}

// SetSystem gets a reference to the given string and assigns it to the System field.
func (o *InjectionGuidedSpec) SetSystem(v string) {
	o.System = &v
}

// GetSystemType returns the SystemType field value if set, zero value otherwise.
func (o *InjectionGuidedSpec) GetSystemType() string {
	if o == nil || IsNil(o.SystemType) {
		var ret string
		return ret
	}
	return *o.SystemType
}

// GetSystemTypeOk returns a tuple with the SystemType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InjectionGuidedSpec) GetSystemTypeOk() (*string, bool) {
	if o == nil || IsNil(o.SystemType) {
		return nil, false
	}
	return o.SystemType, true
}

// HasSystemType returns a boolean if a field has been set.
func (o *InjectionGuidedSpec) HasSystemType() bool {
	if o != nil && !IsNil(o.SystemType) {
		return true
	}

	return false
}

// SetSystemType gets a reference to the given string and assigns it to the SystemType field.
func (o *InjectionGuidedSpec) SetSystemType(v string) {
	o.SystemType = &v
}

// GetTable returns the Table field value if set, zero value otherwise.
func (o *InjectionGuidedSpec) GetTable() string {
	if o == nil || IsNil(o.Table) {
		var ret string
		return ret
	}
	return *o.Table
}

// GetTableOk returns a tuple with the Table field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InjectionGuidedSpec) GetTableOk() (*string, bool) {
	if o == nil || IsNil(o.Table) {
		return nil, false
	}
	return o.Table, true
}

// HasTable returns a boolean if a field has been set.
func (o *InjectionGuidedSpec) HasTable() bool {
	if o != nil && !IsNil(o.Table) {
		return true
	}

	return false
}

// SetTable gets a reference to the given string and assigns it to the Table field.
func (o *InjectionGuidedSpec) SetTable(v string) {
	o.Table = &v
}

// GetTargetService returns the TargetService field value if set, zero value otherwise.
func (o *InjectionGuidedSpec) GetTargetService() string {
	if o == nil || IsNil(o.TargetService) {
		var ret string
		return ret
	}
	return *o.TargetService
}

// GetTargetServiceOk returns a tuple with the TargetService field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InjectionGuidedSpec) GetTargetServiceOk() (*string, bool) {
	if o == nil || IsNil(o.TargetService) {
		return nil, false
	}
	return o.TargetService, true
}

// HasTargetService returns a boolean if a field has been set.
func (o *InjectionGuidedSpec) HasTargetService() bool {
	if o != nil && !IsNil(o.TargetService) {
		return true
	}

	return false
}

// SetTargetService gets a reference to the given string and assigns it to the TargetService field.
func (o *InjectionGuidedSpec) SetTargetService(v string) {
	o.TargetService = &v
}

// GetTimeOffset returns the TimeOffset field value if set, zero value otherwise.
func (o *InjectionGuidedSpec) GetTimeOffset() int32 {
	if o == nil || IsNil(o.TimeOffset) {
		var ret int32
		return ret
	}
	return *o.TimeOffset
}

// GetTimeOffsetOk returns a tuple with the TimeOffset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InjectionGuidedSpec) GetTimeOffsetOk() (*int32, bool) {
	if o == nil || IsNil(o.TimeOffset) {
		return nil, false
	}
	return o.TimeOffset, true
}

// HasTimeOffset returns a boolean if a field has been set.
func (o *InjectionGuidedSpec) HasTimeOffset() bool {
	if o != nil && !IsNil(o.TimeOffset) {
		return true
	}

	return false
}

// SetTimeOffset gets a reference to the given int32 and assigns it to the TimeOffset field.
func (o *InjectionGuidedSpec) SetTimeOffset(v int32) {
	o.TimeOffset = &v
}

func (o InjectionGuidedSpec) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InjectionGuidedSpec) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.App) {
		toSerialize["app"] = o.App
	}
	if !IsNil(o.BodyType) {
		toSerialize["body_type"] = o.BodyType
	}
	if !IsNil(o.Buffer) {
		toSerialize["buffer"] = o.Buffer
	}
	if !IsNil(o.ChaosType) {
		toSerialize["chaos_type"] = o.ChaosType
	}
	if !IsNil(o.Class) {
		toSerialize["class"] = o.Class
	}
	if !IsNil(o.Container) {
		toSerialize["container"] = o.Container
	}
	if !IsNil(o.Correlation) {
		toSerialize["correlation"] = o.Correlation
	}
	if !IsNil(o.Corrupt) {
		toSerialize["corrupt"] = o.Corrupt
	}
	if !IsNil(o.CpuCount) {
		toSerialize["cpu_count"] = o.CpuCount
	}
	if !IsNil(o.CpuLoad) {
		toSerialize["cpu_load"] = o.CpuLoad
	}
	if !IsNil(o.CpuWorker) {
		toSerialize["cpu_worker"] = o.CpuWorker
	}
	if !IsNil(o.Database) {
		toSerialize["database"] = o.Database
	}
	if !IsNil(o.DelayDuration) {
		toSerialize["delay_duration"] = o.DelayDuration
	}
	if !IsNil(o.Direction) {
		toSerialize["direction"] = o.Direction
	}
	if !IsNil(o.Domain) {
		toSerialize["domain"] = o.Domain
	}
	if !IsNil(o.Duplicate) {
		toSerialize["duplicate"] = o.Duplicate
	}
	if !IsNil(o.Duration) {
		toSerialize["duration"] = o.Duration
	}
	if !IsNil(o.ExceptionOpt) {
		toSerialize["exception_opt"] = o.ExceptionOpt
	}
	if !IsNil(o.HttpMethod) {
		toSerialize["http_method"] = o.HttpMethod
	}
	if !IsNil(o.Jitter) {
		toSerialize["jitter"] = o.Jitter
	}
	if !IsNil(o.Latency) {
		toSerialize["latency"] = o.Latency
	}
	if !IsNil(o.LatencyDuration) {
		toSerialize["latency_duration"] = o.LatencyDuration
	}
	if !IsNil(o.LatencyMs) {
		toSerialize["latency_ms"] = o.LatencyMs
	}
	if !IsNil(o.Limit) {
		toSerialize["limit"] = o.Limit
	}
	if !IsNil(o.Loss) {
		toSerialize["loss"] = o.Loss
	}
	if !IsNil(o.MemType) {
		toSerialize["mem_type"] = o.MemType
	}
	if !IsNil(o.MemWorker) {
		toSerialize["mem_worker"] = o.MemWorker
	}
	if !IsNil(o.MemorySize) {
		toSerialize["memory_size"] = o.MemorySize
	}
	if !IsNil(o.Method) {
		toSerialize["method"] = o.Method
	}
	if !IsNil(o.MutatorConfig) {
		toSerialize["mutator_config"] = o.MutatorConfig
	}
	if !IsNil(o.Namespace) {
		toSerialize["namespace"] = o.Namespace
	}
	if !IsNil(o.Operation) {
		toSerialize["operation"] = o.Operation
	}
	if !IsNil(o.Rate) {
		toSerialize["rate"] = o.Rate
	}
	if !IsNil(o.ReplaceMethod) {
		toSerialize["replace_method"] = o.ReplaceMethod
	}
	if !IsNil(o.ReturnType) {
		toSerialize["return_type"] = o.ReturnType
	}
	if !IsNil(o.ReturnValueOpt) {
		toSerialize["return_value_opt"] = o.ReturnValueOpt
	}
	if !IsNil(o.Route) {
		toSerialize["route"] = o.Route
	}
	if !IsNil(o.StatusCode) {
		toSerialize["status_code"] = o.StatusCode
	}
	if !IsNil(o.System) {
		toSerialize["system"] = o.System
	}
	if !IsNil(o.SystemType) {
		toSerialize["system_type"] = o.SystemType
	}
	if !IsNil(o.Table) {
		toSerialize["table"] = o.Table
	}
	if !IsNil(o.TargetService) {
		toSerialize["target_service"] = o.TargetService
	}
	if !IsNil(o.TimeOffset) {
		toSerialize["time_offset"] = o.TimeOffset
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *InjectionGuidedSpec) UnmarshalJSON(data []byte) (err error) {
	varInjectionGuidedSpec := _InjectionGuidedSpec{}

	err = json.Unmarshal(data, &varInjectionGuidedSpec)

	if err != nil {
		return err
	}

	*o = InjectionGuidedSpec(varInjectionGuidedSpec)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "app")
		delete(additionalProperties, "body_type")
		delete(additionalProperties, "buffer")
		delete(additionalProperties, "chaos_type")
		delete(additionalProperties, "class")
		delete(additionalProperties, "container")
		delete(additionalProperties, "correlation")
		delete(additionalProperties, "corrupt")
		delete(additionalProperties, "cpu_count")
		delete(additionalProperties, "cpu_load")
		delete(additionalProperties, "cpu_worker")
		delete(additionalProperties, "database")
		delete(additionalProperties, "delay_duration")
		delete(additionalProperties, "direction")
		delete(additionalProperties, "domain")
		delete(additionalProperties, "duplicate")
		delete(additionalProperties, "duration")
		delete(additionalProperties, "exception_opt")
		delete(additionalProperties, "http_method")
		delete(additionalProperties, "jitter")
		delete(additionalProperties, "latency")
		delete(additionalProperties, "latency_duration")
		delete(additionalProperties, "latency_ms")
		delete(additionalProperties, "limit")
		delete(additionalProperties, "loss")
		delete(additionalProperties, "mem_type")
		delete(additionalProperties, "mem_worker")
		delete(additionalProperties, "memory_size")
		delete(additionalProperties, "method")
		delete(additionalProperties, "mutator_config")
		delete(additionalProperties, "namespace")
		delete(additionalProperties, "operation")
		delete(additionalProperties, "rate")
		delete(additionalProperties, "replace_method")
		delete(additionalProperties, "return_type")
		delete(additionalProperties, "return_value_opt")
		delete(additionalProperties, "route")
		delete(additionalProperties, "status_code")
		delete(additionalProperties, "system")
		delete(additionalProperties, "system_type")
		delete(additionalProperties, "table")
		delete(additionalProperties, "target_service")
		delete(additionalProperties, "time_offset")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableInjectionGuidedSpec struct {
	value *InjectionGuidedSpec
	isSet bool
}

func (v NullableInjectionGuidedSpec) Get() *InjectionGuidedSpec {
	return v.value
}

func (v *NullableInjectionGuidedSpec) Set(val *InjectionGuidedSpec) {
	v.value = val
	v.isSet = true
}

func (v NullableInjectionGuidedSpec) IsSet() bool {
	return v.isSet
}

func (v *NullableInjectionGuidedSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInjectionGuidedSpec(val *InjectionGuidedSpec) *NullableInjectionGuidedSpec {
	return &NullableInjectionGuidedSpec{value: val, isSet: true}
}

func (v NullableInjectionGuidedSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInjectionGuidedSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
