/*
RCABench API

RCABench - A comprehensive root cause analysis benchmarking platform for microservices

API version: 1.0.0
Contact: team@rcabench.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"fmt"
)

// checks if the TeamCreateTeamReq type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TeamCreateTeamReq{}

// TeamCreateTeamReq struct for TeamCreateTeamReq
type TeamCreateTeamReq struct {
	Description          *string `json:"description,omitempty"`
	IsPublic             *bool   `json:"is_public,omitempty"`
	Name                 string  `json:"name"`
	AdditionalProperties map[string]interface{}
}

type _TeamCreateTeamReq TeamCreateTeamReq

// NewTeamCreateTeamReq instantiates a new TeamCreateTeamReq object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTeamCreateTeamReq(name string) *TeamCreateTeamReq {
	this := TeamCreateTeamReq{}
	this.Name = name
	return &this
}

// NewTeamCreateTeamReqWithDefaults instantiates a new TeamCreateTeamReq object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTeamCreateTeamReqWithDefaults() *TeamCreateTeamReq {
	this := TeamCreateTeamReq{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *TeamCreateTeamReq) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TeamCreateTeamReq) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *TeamCreateTeamReq) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *TeamCreateTeamReq) SetDescription(v string) {
	o.Description = &v
}

// GetIsPublic returns the IsPublic field value if set, zero value otherwise.
func (o *TeamCreateTeamReq) GetIsPublic() bool {
	if o == nil || IsNil(o.IsPublic) {
		var ret bool
		return ret
	}
	return *o.IsPublic
}

// GetIsPublicOk returns a tuple with the IsPublic field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TeamCreateTeamReq) GetIsPublicOk() (*bool, bool) {
	if o == nil || IsNil(o.IsPublic) {
		return nil, false
	}
	return o.IsPublic, true
}

// HasIsPublic returns a boolean if a field has been set.
func (o *TeamCreateTeamReq) HasIsPublic() bool {
	if o != nil && !IsNil(o.IsPublic) {
		return true
	}

	return false
}

// SetIsPublic gets a reference to the given bool and assigns it to the IsPublic field.
func (o *TeamCreateTeamReq) SetIsPublic(v bool) {
	o.IsPublic = &v
}

// GetName returns the Name field value
func (o *TeamCreateTeamReq) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *TeamCreateTeamReq) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *TeamCreateTeamReq) SetName(v string) {
	o.Name = v
}

func (o TeamCreateTeamReq) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TeamCreateTeamReq) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.IsPublic) {
		toSerialize["is_public"] = o.IsPublic
	}
	toSerialize["name"] = o.Name

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *TeamCreateTeamReq) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTeamCreateTeamReq := _TeamCreateTeamReq{}

	err = json.Unmarshal(data, &varTeamCreateTeamReq)

	if err != nil {
		return err
	}

	*o = TeamCreateTeamReq(varTeamCreateTeamReq)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "description")
		delete(additionalProperties, "is_public")
		delete(additionalProperties, "name")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableTeamCreateTeamReq struct {
	value *TeamCreateTeamReq
	isSet bool
}

func (v NullableTeamCreateTeamReq) Get() *TeamCreateTeamReq {
	return v.value
}

func (v *NullableTeamCreateTeamReq) Set(val *TeamCreateTeamReq) {
	v.value = val
	v.isSet = true
}

func (v NullableTeamCreateTeamReq) IsSet() bool {
	return v.isSet
}

func (v *NullableTeamCreateTeamReq) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTeamCreateTeamReq(val *TeamCreateTeamReq) *NullableTeamCreateTeamReq {
	return &NullableTeamCreateTeamReq{value: val, isSet: true}
}

func (v NullableTeamCreateTeamReq) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTeamCreateTeamReq) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
