/*
RCABench API

RCABench - A comprehensive root cause analysis benchmarking platform for microservices

API version: 1.0.0
Contact: team@rcabench.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
)

// checks if the DtoGenericResponseInjectionDatapackFilesResp type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DtoGenericResponseInjectionDatapackFilesResp{}

// DtoGenericResponseInjectionDatapackFilesResp struct for DtoGenericResponseInjectionDatapackFilesResp
type DtoGenericResponseInjectionDatapackFilesResp struct {
	// Status code
	Code *int32 `json:"code,omitempty"`
	// Generic type data
	Data *InjectionDatapackFilesResp `json:"data,omitempty"`
	// Response message
	Message *string `json:"message,omitempty"`
	// Response generation time
	Timestamp            *int32 `json:"timestamp,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _DtoGenericResponseInjectionDatapackFilesResp DtoGenericResponseInjectionDatapackFilesResp

// NewDtoGenericResponseInjectionDatapackFilesResp instantiates a new DtoGenericResponseInjectionDatapackFilesResp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDtoGenericResponseInjectionDatapackFilesResp() *DtoGenericResponseInjectionDatapackFilesResp {
	this := DtoGenericResponseInjectionDatapackFilesResp{}
	return &this
}

// NewDtoGenericResponseInjectionDatapackFilesRespWithDefaults instantiates a new DtoGenericResponseInjectionDatapackFilesResp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDtoGenericResponseInjectionDatapackFilesRespWithDefaults() *DtoGenericResponseInjectionDatapackFilesResp {
	this := DtoGenericResponseInjectionDatapackFilesResp{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *DtoGenericResponseInjectionDatapackFilesResp) GetCode() int32 {
	if o == nil || IsNil(o.Code) {
		var ret int32
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoGenericResponseInjectionDatapackFilesResp) GetCodeOk() (*int32, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *DtoGenericResponseInjectionDatapackFilesResp) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given int32 and assigns it to the Code field.
func (o *DtoGenericResponseInjectionDatapackFilesResp) SetCode(v int32) {
	o.Code = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *DtoGenericResponseInjectionDatapackFilesResp) GetData() InjectionDatapackFilesResp {
	if o == nil || IsNil(o.Data) {
		var ret InjectionDatapackFilesResp
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoGenericResponseInjectionDatapackFilesResp) GetDataOk() (*InjectionDatapackFilesResp, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *DtoGenericResponseInjectionDatapackFilesResp) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given InjectionDatapackFilesResp and assigns it to the Data field.
func (o *DtoGenericResponseInjectionDatapackFilesResp) SetData(v InjectionDatapackFilesResp) {
	o.Data = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *DtoGenericResponseInjectionDatapackFilesResp) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoGenericResponseInjectionDatapackFilesResp) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *DtoGenericResponseInjectionDatapackFilesResp) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *DtoGenericResponseInjectionDatapackFilesResp) SetMessage(v string) {
	o.Message = &v
}

// GetTimestamp returns the Timestamp field value if set, zero value otherwise.
func (o *DtoGenericResponseInjectionDatapackFilesResp) GetTimestamp() int32 {
	if o == nil || IsNil(o.Timestamp) {
		var ret int32
		return ret
	}
	return *o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoGenericResponseInjectionDatapackFilesResp) GetTimestampOk() (*int32, bool) {
	if o == nil || IsNil(o.Timestamp) {
		return nil, false
	}
	return o.Timestamp, true
}

// HasTimestamp returns a boolean if a field has been set.
func (o *DtoGenericResponseInjectionDatapackFilesResp) HasTimestamp() bool {
	if o != nil && !IsNil(o.Timestamp) {
		return true
	}

	return false
}

// SetTimestamp gets a reference to the given int32 and assigns it to the Timestamp field.
func (o *DtoGenericResponseInjectionDatapackFilesResp) SetTimestamp(v int32) {
	o.Timestamp = &v
}

func (o DtoGenericResponseInjectionDatapackFilesResp) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DtoGenericResponseInjectionDatapackFilesResp) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Timestamp) {
		toSerialize["timestamp"] = o.Timestamp
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DtoGenericResponseInjectionDatapackFilesResp) UnmarshalJSON(data []byte) (err error) {
	varDtoGenericResponseInjectionDatapackFilesResp := _DtoGenericResponseInjectionDatapackFilesResp{}

	err = json.Unmarshal(data, &varDtoGenericResponseInjectionDatapackFilesResp)

	if err != nil {
		return err
	}

	*o = DtoGenericResponseInjectionDatapackFilesResp(varDtoGenericResponseInjectionDatapackFilesResp)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "code")
		delete(additionalProperties, "data")
		delete(additionalProperties, "message")
		delete(additionalProperties, "timestamp")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDtoGenericResponseInjectionDatapackFilesResp struct {
	value *DtoGenericResponseInjectionDatapackFilesResp
	isSet bool
}

func (v NullableDtoGenericResponseInjectionDatapackFilesResp) Get() *DtoGenericResponseInjectionDatapackFilesResp {
	return v.value
}

func (v *NullableDtoGenericResponseInjectionDatapackFilesResp) Set(val *DtoGenericResponseInjectionDatapackFilesResp) {
	v.value = val
	v.isSet = true
}

func (v NullableDtoGenericResponseInjectionDatapackFilesResp) IsSet() bool {
	return v.isSet
}

func (v *NullableDtoGenericResponseInjectionDatapackFilesResp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDtoGenericResponseInjectionDatapackFilesResp(val *DtoGenericResponseInjectionDatapackFilesResp) *NullableDtoGenericResponseInjectionDatapackFilesResp {
	return &NullableDtoGenericResponseInjectionDatapackFilesResp{value: val, isSet: true}
}

func (v NullableDtoGenericResponseInjectionDatapackFilesResp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDtoGenericResponseInjectionDatapackFilesResp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
