/*
RCABench API

RCABench - A comprehensive root cause analysis benchmarking platform for microservices

API version: 1.0.0
Contact: team@rcabench.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
)

// checks if the BlobLifecycleSweepBucket type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BlobLifecycleSweepBucket{}

// BlobLifecycleSweepBucket struct for BlobLifecycleSweepBucket
type BlobLifecycleSweepBucket struct {
	Bucket               *string                  `json:"bucket,omitempty"`
	Examples             []string                 `json:"examples,omitempty"`
	Rules                []BlobLifecycleSweepRule `json:"rules,omitempty"`
	TotalKeys            *int32                   `json:"total_keys,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _BlobLifecycleSweepBucket BlobLifecycleSweepBucket

// NewBlobLifecycleSweepBucket instantiates a new BlobLifecycleSweepBucket object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBlobLifecycleSweepBucket() *BlobLifecycleSweepBucket {
	this := BlobLifecycleSweepBucket{}
	return &this
}

// NewBlobLifecycleSweepBucketWithDefaults instantiates a new BlobLifecycleSweepBucket object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBlobLifecycleSweepBucketWithDefaults() *BlobLifecycleSweepBucket {
	this := BlobLifecycleSweepBucket{}
	return &this
}

// GetBucket returns the Bucket field value if set, zero value otherwise.
func (o *BlobLifecycleSweepBucket) GetBucket() string {
	if o == nil || IsNil(o.Bucket) {
		var ret string
		return ret
	}
	return *o.Bucket
}

// GetBucketOk returns a tuple with the Bucket field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlobLifecycleSweepBucket) GetBucketOk() (*string, bool) {
	if o == nil || IsNil(o.Bucket) {
		return nil, false
	}
	return o.Bucket, true
}

// HasBucket returns a boolean if a field has been set.
func (o *BlobLifecycleSweepBucket) HasBucket() bool {
	if o != nil && !IsNil(o.Bucket) {
		return true
	}

	return false
}

// SetBucket gets a reference to the given string and assigns it to the Bucket field.
func (o *BlobLifecycleSweepBucket) SetBucket(v string) {
	o.Bucket = &v
}

// GetExamples returns the Examples field value if set, zero value otherwise.
func (o *BlobLifecycleSweepBucket) GetExamples() []string {
	if o == nil || IsNil(o.Examples) {
		var ret []string
		return ret
	}
	return o.Examples
}

// GetExamplesOk returns a tuple with the Examples field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlobLifecycleSweepBucket) GetExamplesOk() ([]string, bool) {
	if o == nil || IsNil(o.Examples) {
		return nil, false
	}
	return o.Examples, true
}

// HasExamples returns a boolean if a field has been set.
func (o *BlobLifecycleSweepBucket) HasExamples() bool {
	if o != nil && !IsNil(o.Examples) {
		return true
	}

	return false
}

// SetExamples gets a reference to the given []string and assigns it to the Examples field.
func (o *BlobLifecycleSweepBucket) SetExamples(v []string) {
	o.Examples = v
}

// GetRules returns the Rules field value if set, zero value otherwise.
func (o *BlobLifecycleSweepBucket) GetRules() []BlobLifecycleSweepRule {
	if o == nil || IsNil(o.Rules) {
		var ret []BlobLifecycleSweepRule
		return ret
	}
	return o.Rules
}

// GetRulesOk returns a tuple with the Rules field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlobLifecycleSweepBucket) GetRulesOk() ([]BlobLifecycleSweepRule, bool) {
	if o == nil || IsNil(o.Rules) {
		return nil, false
	}
	return o.Rules, true
}

// HasRules returns a boolean if a field has been set.
func (o *BlobLifecycleSweepBucket) HasRules() bool {
	if o != nil && !IsNil(o.Rules) {
		return true
	}

	return false
}

// SetRules gets a reference to the given []BlobLifecycleSweepRule and assigns it to the Rules field.
func (o *BlobLifecycleSweepBucket) SetRules(v []BlobLifecycleSweepRule) {
	o.Rules = v
}

// GetTotalKeys returns the TotalKeys field value if set, zero value otherwise.
func (o *BlobLifecycleSweepBucket) GetTotalKeys() int32 {
	if o == nil || IsNil(o.TotalKeys) {
		var ret int32
		return ret
	}
	return *o.TotalKeys
}

// GetTotalKeysOk returns a tuple with the TotalKeys field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlobLifecycleSweepBucket) GetTotalKeysOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalKeys) {
		return nil, false
	}
	return o.TotalKeys, true
}

// HasTotalKeys returns a boolean if a field has been set.
func (o *BlobLifecycleSweepBucket) HasTotalKeys() bool {
	if o != nil && !IsNil(o.TotalKeys) {
		return true
	}

	return false
}

// SetTotalKeys gets a reference to the given int32 and assigns it to the TotalKeys field.
func (o *BlobLifecycleSweepBucket) SetTotalKeys(v int32) {
	o.TotalKeys = &v
}

func (o BlobLifecycleSweepBucket) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BlobLifecycleSweepBucket) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Bucket) {
		toSerialize["bucket"] = o.Bucket
	}
	if !IsNil(o.Examples) {
		toSerialize["examples"] = o.Examples
	}
	if !IsNil(o.Rules) {
		toSerialize["rules"] = o.Rules
	}
	if !IsNil(o.TotalKeys) {
		toSerialize["total_keys"] = o.TotalKeys
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BlobLifecycleSweepBucket) UnmarshalJSON(data []byte) (err error) {
	varBlobLifecycleSweepBucket := _BlobLifecycleSweepBucket{}

	err = json.Unmarshal(data, &varBlobLifecycleSweepBucket)

	if err != nil {
		return err
	}

	*o = BlobLifecycleSweepBucket(varBlobLifecycleSweepBucket)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "bucket")
		delete(additionalProperties, "examples")
		delete(additionalProperties, "rules")
		delete(additionalProperties, "total_keys")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBlobLifecycleSweepBucket struct {
	value *BlobLifecycleSweepBucket
	isSet bool
}

func (v NullableBlobLifecycleSweepBucket) Get() *BlobLifecycleSweepBucket {
	return v.value
}

func (v *NullableBlobLifecycleSweepBucket) Set(val *BlobLifecycleSweepBucket) {
	v.value = val
	v.isSet = true
}

func (v NullableBlobLifecycleSweepBucket) IsSet() bool {
	return v.isSet
}

func (v *NullableBlobLifecycleSweepBucket) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBlobLifecycleSweepBucket(val *BlobLifecycleSweepBucket) *NullableBlobLifecycleSweepBucket {
	return &NullableBlobLifecycleSweepBucket{value: val, isSet: true}
}

func (v NullableBlobLifecycleSweepBucket) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBlobLifecycleSweepBucket) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
