/*
RCABench API

RCABench - A comprehensive root cause analysis benchmarking platform for microservices

API version: 1.0.0
Contact: team@rcabench.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"fmt"
)

// ConstsValueDataType the model 'ConstsValueDataType'
type ConstsValueDataType int32

// List of consts.ValueDataType
const (
	CONSTSVALUEDATATYPE_ValueDataTypeString ConstsValueDataType = 0
	CONSTSVALUEDATATYPE_ValueDataTypeInt    ConstsValueDataType = 1
	CONSTSVALUEDATATYPE_ValueDataTypeBool   ConstsValueDataType = 2
	CONSTSVALUEDATATYPE_ValueDataTypeFloat  ConstsValueDataType = 3
	CONSTSVALUEDATATYPE_ValueDataTypeArray  ConstsValueDataType = 4
	CONSTSVALUEDATATYPE_ValueDataTypeObject ConstsValueDataType = 5
)

// All allowed values of ConstsValueDataType enum
var AllowedConstsValueDataTypeEnumValues = []ConstsValueDataType{
	0,
	1,
	2,
	3,
	4,
	5,
}

func (v *ConstsValueDataType) UnmarshalJSON(src []byte) error {
	var value int32
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ConstsValueDataType(value)
	for _, existing := range AllowedConstsValueDataTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ConstsValueDataType", value)
}

// NewConstsValueDataTypeFromValue returns a pointer to a valid ConstsValueDataType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewConstsValueDataTypeFromValue(v int32) (*ConstsValueDataType, error) {
	ev := ConstsValueDataType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ConstsValueDataType: valid values are %v", v, AllowedConstsValueDataTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ConstsValueDataType) IsValid() bool {
	for _, existing := range AllowedConstsValueDataTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to consts.ValueDataType value
func (v ConstsValueDataType) Ptr() *ConstsValueDataType {
	return &v
}

type NullableConstsValueDataType struct {
	value *ConstsValueDataType
	isSet bool
}

func (v NullableConstsValueDataType) Get() *ConstsValueDataType {
	return v.value
}

func (v *NullableConstsValueDataType) Set(val *ConstsValueDataType) {
	v.value = val
	v.isSet = true
}

func (v NullableConstsValueDataType) IsSet() bool {
	return v.isSet
}

func (v *NullableConstsValueDataType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConstsValueDataType(val *ConstsValueDataType) *NullableConstsValueDataType {
	return &NullableConstsValueDataType{value: val, isSet: true}
}

func (v NullableConstsValueDataType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConstsValueDataType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
