/*
RCABench API

RCABench - A comprehensive root cause analysis benchmarking platform for microservices

API version: 1.0.0
Contact: team@rcabench.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"fmt"
)

// checks if the InjectionSubmitInjectionReq type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InjectionSubmitInjectionReq{}

// InjectionSubmitInjectionReq struct for InjectionSubmitInjectionReq
type InjectionSubmitInjectionReq struct {
	// RCA algorithms to execute (optional)
	Algorithms []DtoContainerSpec `json:"algorithms,omitempty"`
	// AllowBootstrap, in combination with AutoAllocate, lets the server extend the system's pool when no existing slot qualifies. The server bumps `injection.system.<system>.count` by 1, locks the new ns, and returns it as a \"fresh\" slot. RestartPedestal at runtime helm- installs into the fresh slot before the FaultInjection task runs; submit-time BuildInjection's pod listing is skipped for fresh slots since pods don't exist yet. See PR-C of #166.
	AllowBootstrap *bool `json:"allow_bootstrap,omitempty"`
	// AutoAllocate, when true, asks the server to choose a free deployed namespace from the system's pool for any guided config whose `namespace` is empty. The chosen namespace is locked at submit time (see #166) and surfaced in SubmitInjectionResp.AllocatedNamespaces. Hole-fill only — the allocator does not bootstrap fresh slots; if every 0..count-1 slot is busy or has no workload, submit fails with a pool-exhausted error and a hint to use `--install --namespace` to expand the pool. Configs that already specify a namespace continue to honor PR #164's hard-constraint path unchanged.
	AutoAllocate *bool `json:"auto_allocate,omitempty"`
	// Benchmark (detector) configuration
	Benchmark DtoContainerSpec `json:"benchmark"`
	// Labels to attach to the injection
	Labels []DtoLabelItem `json:"labels,omitempty"`
	// Pedestal (workload) configuration
	Pedestal DtoContainerSpec `json:"pedestal"`
	// Project name
	ProjectName *string `json:"project_name,omitempty"`
	// SkipRestartPedestal hints the RestartPedestal step to skip the helm install when the target release is already deployed and healthy. Namespace locking, index extraction, and the FaultInjection handoff still run as normal. Use when the caller has already installed the chart out-of-band (e.g. `aegisctl pedestal chart install` + preflight readiness wait).
	SkipRestartPedestal *bool `json:"skip_restart_pedestal,omitempty"`
	// GuidedConfig batches for fault injection
	Specs                [][]InjectionGuidedSpec `json:"specs"`
	AdditionalProperties map[string]interface{}
}

type _InjectionSubmitInjectionReq InjectionSubmitInjectionReq

// NewInjectionSubmitInjectionReq instantiates a new InjectionSubmitInjectionReq object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInjectionSubmitInjectionReq(benchmark DtoContainerSpec, pedestal DtoContainerSpec, specs [][]InjectionGuidedSpec) *InjectionSubmitInjectionReq {
	this := InjectionSubmitInjectionReq{}
	this.Benchmark = benchmark
	this.Pedestal = pedestal
	this.Specs = specs
	return &this
}

// NewInjectionSubmitInjectionReqWithDefaults instantiates a new InjectionSubmitInjectionReq object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInjectionSubmitInjectionReqWithDefaults() *InjectionSubmitInjectionReq {
	this := InjectionSubmitInjectionReq{}
	return &this
}

// GetAlgorithms returns the Algorithms field value if set, zero value otherwise.
func (o *InjectionSubmitInjectionReq) GetAlgorithms() []DtoContainerSpec {
	if o == nil || IsNil(o.Algorithms) {
		var ret []DtoContainerSpec
		return ret
	}
	return o.Algorithms
}

// GetAlgorithmsOk returns a tuple with the Algorithms field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InjectionSubmitInjectionReq) GetAlgorithmsOk() ([]DtoContainerSpec, bool) {
	if o == nil || IsNil(o.Algorithms) {
		return nil, false
	}
	return o.Algorithms, true
}

// HasAlgorithms returns a boolean if a field has been set.
func (o *InjectionSubmitInjectionReq) HasAlgorithms() bool {
	if o != nil && !IsNil(o.Algorithms) {
		return true
	}

	return false
}

// SetAlgorithms gets a reference to the given []DtoContainerSpec and assigns it to the Algorithms field.
func (o *InjectionSubmitInjectionReq) SetAlgorithms(v []DtoContainerSpec) {
	o.Algorithms = v
}

// GetAllowBootstrap returns the AllowBootstrap field value if set, zero value otherwise.
func (o *InjectionSubmitInjectionReq) GetAllowBootstrap() bool {
	if o == nil || IsNil(o.AllowBootstrap) {
		var ret bool
		return ret
	}
	return *o.AllowBootstrap
}

// GetAllowBootstrapOk returns a tuple with the AllowBootstrap field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InjectionSubmitInjectionReq) GetAllowBootstrapOk() (*bool, bool) {
	if o == nil || IsNil(o.AllowBootstrap) {
		return nil, false
	}
	return o.AllowBootstrap, true
}

// HasAllowBootstrap returns a boolean if a field has been set.
func (o *InjectionSubmitInjectionReq) HasAllowBootstrap() bool {
	if o != nil && !IsNil(o.AllowBootstrap) {
		return true
	}

	return false
}

// SetAllowBootstrap gets a reference to the given bool and assigns it to the AllowBootstrap field.
func (o *InjectionSubmitInjectionReq) SetAllowBootstrap(v bool) {
	o.AllowBootstrap = &v
}

// GetAutoAllocate returns the AutoAllocate field value if set, zero value otherwise.
func (o *InjectionSubmitInjectionReq) GetAutoAllocate() bool {
	if o == nil || IsNil(o.AutoAllocate) {
		var ret bool
		return ret
	}
	return *o.AutoAllocate
}

// GetAutoAllocateOk returns a tuple with the AutoAllocate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InjectionSubmitInjectionReq) GetAutoAllocateOk() (*bool, bool) {
	if o == nil || IsNil(o.AutoAllocate) {
		return nil, false
	}
	return o.AutoAllocate, true
}

// HasAutoAllocate returns a boolean if a field has been set.
func (o *InjectionSubmitInjectionReq) HasAutoAllocate() bool {
	if o != nil && !IsNil(o.AutoAllocate) {
		return true
	}

	return false
}

// SetAutoAllocate gets a reference to the given bool and assigns it to the AutoAllocate field.
func (o *InjectionSubmitInjectionReq) SetAutoAllocate(v bool) {
	o.AutoAllocate = &v
}

// GetBenchmark returns the Benchmark field value
func (o *InjectionSubmitInjectionReq) GetBenchmark() DtoContainerSpec {
	if o == nil {
		var ret DtoContainerSpec
		return ret
	}

	return o.Benchmark
}

// GetBenchmarkOk returns a tuple with the Benchmark field value
// and a boolean to check if the value has been set.
func (o *InjectionSubmitInjectionReq) GetBenchmarkOk() (*DtoContainerSpec, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Benchmark, true
}

// SetBenchmark sets field value
func (o *InjectionSubmitInjectionReq) SetBenchmark(v DtoContainerSpec) {
	o.Benchmark = v
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *InjectionSubmitInjectionReq) GetLabels() []DtoLabelItem {
	if o == nil || IsNil(o.Labels) {
		var ret []DtoLabelItem
		return ret
	}
	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InjectionSubmitInjectionReq) GetLabelsOk() ([]DtoLabelItem, bool) {
	if o == nil || IsNil(o.Labels) {
		return nil, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *InjectionSubmitInjectionReq) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given []DtoLabelItem and assigns it to the Labels field.
func (o *InjectionSubmitInjectionReq) SetLabels(v []DtoLabelItem) {
	o.Labels = v
}

// GetPedestal returns the Pedestal field value
func (o *InjectionSubmitInjectionReq) GetPedestal() DtoContainerSpec {
	if o == nil {
		var ret DtoContainerSpec
		return ret
	}

	return o.Pedestal
}

// GetPedestalOk returns a tuple with the Pedestal field value
// and a boolean to check if the value has been set.
func (o *InjectionSubmitInjectionReq) GetPedestalOk() (*DtoContainerSpec, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pedestal, true
}

// SetPedestal sets field value
func (o *InjectionSubmitInjectionReq) SetPedestal(v DtoContainerSpec) {
	o.Pedestal = v
}

// GetProjectName returns the ProjectName field value if set, zero value otherwise.
func (o *InjectionSubmitInjectionReq) GetProjectName() string {
	if o == nil || IsNil(o.ProjectName) {
		var ret string
		return ret
	}
	return *o.ProjectName
}

// GetProjectNameOk returns a tuple with the ProjectName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InjectionSubmitInjectionReq) GetProjectNameOk() (*string, bool) {
	if o == nil || IsNil(o.ProjectName) {
		return nil, false
	}
	return o.ProjectName, true
}

// HasProjectName returns a boolean if a field has been set.
func (o *InjectionSubmitInjectionReq) HasProjectName() bool {
	if o != nil && !IsNil(o.ProjectName) {
		return true
	}

	return false
}

// SetProjectName gets a reference to the given string and assigns it to the ProjectName field.
func (o *InjectionSubmitInjectionReq) SetProjectName(v string) {
	o.ProjectName = &v
}

// GetSkipRestartPedestal returns the SkipRestartPedestal field value if set, zero value otherwise.
func (o *InjectionSubmitInjectionReq) GetSkipRestartPedestal() bool {
	if o == nil || IsNil(o.SkipRestartPedestal) {
		var ret bool
		return ret
	}
	return *o.SkipRestartPedestal
}

// GetSkipRestartPedestalOk returns a tuple with the SkipRestartPedestal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InjectionSubmitInjectionReq) GetSkipRestartPedestalOk() (*bool, bool) {
	if o == nil || IsNil(o.SkipRestartPedestal) {
		return nil, false
	}
	return o.SkipRestartPedestal, true
}

// HasSkipRestartPedestal returns a boolean if a field has been set.
func (o *InjectionSubmitInjectionReq) HasSkipRestartPedestal() bool {
	if o != nil && !IsNil(o.SkipRestartPedestal) {
		return true
	}

	return false
}

// SetSkipRestartPedestal gets a reference to the given bool and assigns it to the SkipRestartPedestal field.
func (o *InjectionSubmitInjectionReq) SetSkipRestartPedestal(v bool) {
	o.SkipRestartPedestal = &v
}

// GetSpecs returns the Specs field value
func (o *InjectionSubmitInjectionReq) GetSpecs() [][]InjectionGuidedSpec {
	if o == nil {
		var ret [][]InjectionGuidedSpec
		return ret
	}

	return o.Specs
}

// GetSpecsOk returns a tuple with the Specs field value
// and a boolean to check if the value has been set.
func (o *InjectionSubmitInjectionReq) GetSpecsOk() ([][]InjectionGuidedSpec, bool) {
	if o == nil {
		return nil, false
	}
	return o.Specs, true
}

// SetSpecs sets field value
func (o *InjectionSubmitInjectionReq) SetSpecs(v [][]InjectionGuidedSpec) {
	o.Specs = v
}

func (o InjectionSubmitInjectionReq) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InjectionSubmitInjectionReq) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Algorithms) {
		toSerialize["algorithms"] = o.Algorithms
	}
	if !IsNil(o.AllowBootstrap) {
		toSerialize["allow_bootstrap"] = o.AllowBootstrap
	}
	if !IsNil(o.AutoAllocate) {
		toSerialize["auto_allocate"] = o.AutoAllocate
	}
	toSerialize["benchmark"] = o.Benchmark
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	toSerialize["pedestal"] = o.Pedestal
	if !IsNil(o.ProjectName) {
		toSerialize["project_name"] = o.ProjectName
	}
	if !IsNil(o.SkipRestartPedestal) {
		toSerialize["skip_restart_pedestal"] = o.SkipRestartPedestal
	}
	toSerialize["specs"] = o.Specs

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *InjectionSubmitInjectionReq) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"benchmark",
		"pedestal",
		"specs",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInjectionSubmitInjectionReq := _InjectionSubmitInjectionReq{}

	err = json.Unmarshal(data, &varInjectionSubmitInjectionReq)

	if err != nil {
		return err
	}

	*o = InjectionSubmitInjectionReq(varInjectionSubmitInjectionReq)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "algorithms")
		delete(additionalProperties, "allow_bootstrap")
		delete(additionalProperties, "auto_allocate")
		delete(additionalProperties, "benchmark")
		delete(additionalProperties, "labels")
		delete(additionalProperties, "pedestal")
		delete(additionalProperties, "project_name")
		delete(additionalProperties, "skip_restart_pedestal")
		delete(additionalProperties, "specs")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableInjectionSubmitInjectionReq struct {
	value *InjectionSubmitInjectionReq
	isSet bool
}

func (v NullableInjectionSubmitInjectionReq) Get() *InjectionSubmitInjectionReq {
	return v.value
}

func (v *NullableInjectionSubmitInjectionReq) Set(val *InjectionSubmitInjectionReq) {
	v.value = val
	v.isSet = true
}

func (v NullableInjectionSubmitInjectionReq) IsSet() bool {
	return v.isSet
}

func (v *NullableInjectionSubmitInjectionReq) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInjectionSubmitInjectionReq(val *InjectionSubmitInjectionReq) *NullableInjectionSubmitInjectionReq {
	return &NullableInjectionSubmitInjectionReq{value: val, isSet: true}
}

func (v NullableInjectionSubmitInjectionReq) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInjectionSubmitInjectionReq) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
