/*
RCABench API

RCABench - A comprehensive root cause analysis benchmarking platform for microservices

API version: 1.0.0
Contact: team@rcabench.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
)

// checks if the ChaosFieldOption type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChaosFieldOption{}

// ChaosFieldOption struct for ChaosFieldOption
type ChaosFieldOption struct {
	Description          *string                `json:"description,omitempty"`
	Label                *string                `json:"label,omitempty"`
	Metadata             map[string]interface{} `json:"metadata,omitempty"`
	Value                *string                `json:"value,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ChaosFieldOption ChaosFieldOption

// NewChaosFieldOption instantiates a new ChaosFieldOption object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChaosFieldOption() *ChaosFieldOption {
	this := ChaosFieldOption{}
	return &this
}

// NewChaosFieldOptionWithDefaults instantiates a new ChaosFieldOption object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChaosFieldOptionWithDefaults() *ChaosFieldOption {
	this := ChaosFieldOption{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ChaosFieldOption) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChaosFieldOption) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ChaosFieldOption) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ChaosFieldOption) SetDescription(v string) {
	o.Description = &v
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *ChaosFieldOption) GetLabel() string {
	if o == nil || IsNil(o.Label) {
		var ret string
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChaosFieldOption) GetLabelOk() (*string, bool) {
	if o == nil || IsNil(o.Label) {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *ChaosFieldOption) HasLabel() bool {
	if o != nil && !IsNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given string and assigns it to the Label field.
func (o *ChaosFieldOption) SetLabel(v string) {
	o.Label = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *ChaosFieldOption) GetMetadata() map[string]interface{} {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChaosFieldOption) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *ChaosFieldOption) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *ChaosFieldOption) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *ChaosFieldOption) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChaosFieldOption) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *ChaosFieldOption) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *ChaosFieldOption) SetValue(v string) {
	o.Value = &v
}

func (o ChaosFieldOption) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChaosFieldOption) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Label) {
		toSerialize["label"] = o.Label
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ChaosFieldOption) UnmarshalJSON(data []byte) (err error) {
	varChaosFieldOption := _ChaosFieldOption{}

	err = json.Unmarshal(data, &varChaosFieldOption)

	if err != nil {
		return err
	}

	*o = ChaosFieldOption(varChaosFieldOption)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "description")
		delete(additionalProperties, "label")
		delete(additionalProperties, "metadata")
		delete(additionalProperties, "value")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableChaosFieldOption struct {
	value *ChaosFieldOption
	isSet bool
}

func (v NullableChaosFieldOption) Get() *ChaosFieldOption {
	return v.value
}

func (v *NullableChaosFieldOption) Set(val *ChaosFieldOption) {
	v.value = val
	v.isSet = true
}

func (v NullableChaosFieldOption) IsSet() bool {
	return v.isSet
}

func (v *NullableChaosFieldOption) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChaosFieldOption(val *ChaosFieldOption) *NullableChaosFieldOption {
	return &NullableChaosFieldOption{value: val, isSet: true}
}

func (v NullableChaosFieldOption) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChaosFieldOption) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
