/*
RCABench API

RCABench - A comprehensive root cause analysis benchmarking platform for microservices

API version: 1.0.0
Contact: team@rcabench.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"fmt"
)

// ConstsContainerType the model 'ConstsContainerType'
type ConstsContainerType int32

// List of consts.ContainerType
const (
	CONSTSCONTAINERTYPE_ContainerTypeAlgorithm ConstsContainerType = 0
	CONSTSCONTAINERTYPE_ContainerTypeBenchmark ConstsContainerType = 1
	CONSTSCONTAINERTYPE_ContainerTypePedestal  ConstsContainerType = 2
)

// All allowed values of ConstsContainerType enum
var AllowedConstsContainerTypeEnumValues = []ConstsContainerType{
	0,
	1,
	2,
}

func (v *ConstsContainerType) UnmarshalJSON(src []byte) error {
	var value int32
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ConstsContainerType(value)
	for _, existing := range AllowedConstsContainerTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ConstsContainerType", value)
}

// NewConstsContainerTypeFromValue returns a pointer to a valid ConstsContainerType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewConstsContainerTypeFromValue(v int32) (*ConstsContainerType, error) {
	ev := ConstsContainerType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ConstsContainerType: valid values are %v", v, AllowedConstsContainerTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ConstsContainerType) IsValid() bool {
	for _, existing := range AllowedConstsContainerTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to consts.ContainerType value
func (v ConstsContainerType) Ptr() *ConstsContainerType {
	return &v
}

type NullableConstsContainerType struct {
	value *ConstsContainerType
	isSet bool
}

func (v NullableConstsContainerType) Get() *ConstsContainerType {
	return v.value
}

func (v *NullableConstsContainerType) Set(val *ConstsContainerType) {
	v.value = val
	v.isSet = true
}

func (v NullableConstsContainerType) IsSet() bool {
	return v.isSet
}

func (v *NullableConstsContainerType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConstsContainerType(val *ConstsContainerType) *NullableConstsContainerType {
	return &NullableConstsContainerType{value: val, isSet: true}
}

func (v NullableConstsContainerType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConstsContainerType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
