/*
RCABench API

RCABench - A comprehensive root cause analysis benchmarking platform for microservices

API version: 1.0.0
Contact: team@rcabench.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
)

// checks if the LabelUpdateLabelReq type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LabelUpdateLabelReq{}

// LabelUpdateLabelReq struct for LabelUpdateLabelReq
type LabelUpdateLabelReq struct {
	Color                *string           `json:"color,omitempty"`
	Description          *string           `json:"description,omitempty"`
	Status               *ConstsStatusType `json:"status,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _LabelUpdateLabelReq LabelUpdateLabelReq

// NewLabelUpdateLabelReq instantiates a new LabelUpdateLabelReq object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLabelUpdateLabelReq() *LabelUpdateLabelReq {
	this := LabelUpdateLabelReq{}
	return &this
}

// NewLabelUpdateLabelReqWithDefaults instantiates a new LabelUpdateLabelReq object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLabelUpdateLabelReqWithDefaults() *LabelUpdateLabelReq {
	this := LabelUpdateLabelReq{}
	return &this
}

// GetColor returns the Color field value if set, zero value otherwise.
func (o *LabelUpdateLabelReq) GetColor() string {
	if o == nil || IsNil(o.Color) {
		var ret string
		return ret
	}
	return *o.Color
}

// GetColorOk returns a tuple with the Color field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LabelUpdateLabelReq) GetColorOk() (*string, bool) {
	if o == nil || IsNil(o.Color) {
		return nil, false
	}
	return o.Color, true
}

// HasColor returns a boolean if a field has been set.
func (o *LabelUpdateLabelReq) HasColor() bool {
	if o != nil && !IsNil(o.Color) {
		return true
	}

	return false
}

// SetColor gets a reference to the given string and assigns it to the Color field.
func (o *LabelUpdateLabelReq) SetColor(v string) {
	o.Color = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *LabelUpdateLabelReq) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LabelUpdateLabelReq) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *LabelUpdateLabelReq) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *LabelUpdateLabelReq) SetDescription(v string) {
	o.Description = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *LabelUpdateLabelReq) GetStatus() ConstsStatusType {
	if o == nil || IsNil(o.Status) {
		var ret ConstsStatusType
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LabelUpdateLabelReq) GetStatusOk() (*ConstsStatusType, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *LabelUpdateLabelReq) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given ConstsStatusType and assigns it to the Status field.
func (o *LabelUpdateLabelReq) SetStatus(v ConstsStatusType) {
	o.Status = &v
}

func (o LabelUpdateLabelReq) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LabelUpdateLabelReq) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Color) {
		toSerialize["color"] = o.Color
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *LabelUpdateLabelReq) UnmarshalJSON(data []byte) (err error) {
	varLabelUpdateLabelReq := _LabelUpdateLabelReq{}

	err = json.Unmarshal(data, &varLabelUpdateLabelReq)

	if err != nil {
		return err
	}

	*o = LabelUpdateLabelReq(varLabelUpdateLabelReq)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "color")
		delete(additionalProperties, "description")
		delete(additionalProperties, "status")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableLabelUpdateLabelReq struct {
	value *LabelUpdateLabelReq
	isSet bool
}

func (v NullableLabelUpdateLabelReq) Get() *LabelUpdateLabelReq {
	return v.value
}

func (v *NullableLabelUpdateLabelReq) Set(val *LabelUpdateLabelReq) {
	v.value = val
	v.isSet = true
}

func (v NullableLabelUpdateLabelReq) IsSet() bool {
	return v.isSet
}

func (v *NullableLabelUpdateLabelReq) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLabelUpdateLabelReq(val *LabelUpdateLabelReq) *NullableLabelUpdateLabelReq {
	return &NullableLabelUpdateLabelReq{value: val, isSet: true}
}

func (v NullableLabelUpdateLabelReq) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLabelUpdateLabelReq) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
