/*
RCABench API

RCABench - A comprehensive root cause analysis benchmarking platform for microservices

API version: 1.0.0
Contact: team@rcabench.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
)

// checks if the InjectionDatapackTableSchema type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InjectionDatapackTableSchema{}

// InjectionDatapackTableSchema struct for InjectionDatapackTableSchema
type InjectionDatapackTableSchema struct {
	// Column metadata
	Columns []InjectionDatapackColumnSchema `json:"columns,omitempty"`
	// Source parquet relative path
	File *string `json:"file,omitempty"`
	// VIEW name, e.g. \"abnormal_traces\"
	Name *string `json:"name,omitempty"`
	// Row count, -1 if unknown
	Rows                 *int32 `json:"rows,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _InjectionDatapackTableSchema InjectionDatapackTableSchema

// NewInjectionDatapackTableSchema instantiates a new InjectionDatapackTableSchema object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInjectionDatapackTableSchema() *InjectionDatapackTableSchema {
	this := InjectionDatapackTableSchema{}
	return &this
}

// NewInjectionDatapackTableSchemaWithDefaults instantiates a new InjectionDatapackTableSchema object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInjectionDatapackTableSchemaWithDefaults() *InjectionDatapackTableSchema {
	this := InjectionDatapackTableSchema{}
	return &this
}

// GetColumns returns the Columns field value if set, zero value otherwise.
func (o *InjectionDatapackTableSchema) GetColumns() []InjectionDatapackColumnSchema {
	if o == nil || IsNil(o.Columns) {
		var ret []InjectionDatapackColumnSchema
		return ret
	}
	return o.Columns
}

// GetColumnsOk returns a tuple with the Columns field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InjectionDatapackTableSchema) GetColumnsOk() ([]InjectionDatapackColumnSchema, bool) {
	if o == nil || IsNil(o.Columns) {
		return nil, false
	}
	return o.Columns, true
}

// HasColumns returns a boolean if a field has been set.
func (o *InjectionDatapackTableSchema) HasColumns() bool {
	if o != nil && !IsNil(o.Columns) {
		return true
	}

	return false
}

// SetColumns gets a reference to the given []InjectionDatapackColumnSchema and assigns it to the Columns field.
func (o *InjectionDatapackTableSchema) SetColumns(v []InjectionDatapackColumnSchema) {
	o.Columns = v
}

// GetFile returns the File field value if set, zero value otherwise.
func (o *InjectionDatapackTableSchema) GetFile() string {
	if o == nil || IsNil(o.File) {
		var ret string
		return ret
	}
	return *o.File
}

// GetFileOk returns a tuple with the File field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InjectionDatapackTableSchema) GetFileOk() (*string, bool) {
	if o == nil || IsNil(o.File) {
		return nil, false
	}
	return o.File, true
}

// HasFile returns a boolean if a field has been set.
func (o *InjectionDatapackTableSchema) HasFile() bool {
	if o != nil && !IsNil(o.File) {
		return true
	}

	return false
}

// SetFile gets a reference to the given string and assigns it to the File field.
func (o *InjectionDatapackTableSchema) SetFile(v string) {
	o.File = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *InjectionDatapackTableSchema) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InjectionDatapackTableSchema) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *InjectionDatapackTableSchema) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *InjectionDatapackTableSchema) SetName(v string) {
	o.Name = &v
}

// GetRows returns the Rows field value if set, zero value otherwise.
func (o *InjectionDatapackTableSchema) GetRows() int32 {
	if o == nil || IsNil(o.Rows) {
		var ret int32
		return ret
	}
	return *o.Rows
}

// GetRowsOk returns a tuple with the Rows field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InjectionDatapackTableSchema) GetRowsOk() (*int32, bool) {
	if o == nil || IsNil(o.Rows) {
		return nil, false
	}
	return o.Rows, true
}

// HasRows returns a boolean if a field has been set.
func (o *InjectionDatapackTableSchema) HasRows() bool {
	if o != nil && !IsNil(o.Rows) {
		return true
	}

	return false
}

// SetRows gets a reference to the given int32 and assigns it to the Rows field.
func (o *InjectionDatapackTableSchema) SetRows(v int32) {
	o.Rows = &v
}

func (o InjectionDatapackTableSchema) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InjectionDatapackTableSchema) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Columns) {
		toSerialize["columns"] = o.Columns
	}
	if !IsNil(o.File) {
		toSerialize["file"] = o.File
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Rows) {
		toSerialize["rows"] = o.Rows
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *InjectionDatapackTableSchema) UnmarshalJSON(data []byte) (err error) {
	varInjectionDatapackTableSchema := _InjectionDatapackTableSchema{}

	err = json.Unmarshal(data, &varInjectionDatapackTableSchema)

	if err != nil {
		return err
	}

	*o = InjectionDatapackTableSchema(varInjectionDatapackTableSchema)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "columns")
		delete(additionalProperties, "file")
		delete(additionalProperties, "name")
		delete(additionalProperties, "rows")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableInjectionDatapackTableSchema struct {
	value *InjectionDatapackTableSchema
	isSet bool
}

func (v NullableInjectionDatapackTableSchema) Get() *InjectionDatapackTableSchema {
	return v.value
}

func (v *NullableInjectionDatapackTableSchema) Set(val *InjectionDatapackTableSchema) {
	v.value = val
	v.isSet = true
}

func (v NullableInjectionDatapackTableSchema) IsSet() bool {
	return v.isSet
}

func (v *NullableInjectionDatapackTableSchema) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInjectionDatapackTableSchema(val *InjectionDatapackTableSchema) *NullableInjectionDatapackTableSchema {
	return &NullableInjectionDatapackTableSchema{value: val, isSet: true}
}

func (v NullableInjectionDatapackTableSchema) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInjectionDatapackTableSchema) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
