/*
RCABench API

RCABench - A comprehensive root cause analysis benchmarking platform for microservices

API version: 1.0.0
Contact: team@rcabench.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
)

// checks if the BlobQueryRowsResp type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BlobQueryRowsResp{}

// BlobQueryRowsResp struct for BlobQueryRowsResp
type BlobQueryRowsResp struct {
	RowCount             *int32                   `json:"row_count,omitempty"`
	Rows                 []map[string]interface{} `json:"rows,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _BlobQueryRowsResp BlobQueryRowsResp

// NewBlobQueryRowsResp instantiates a new BlobQueryRowsResp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBlobQueryRowsResp() *BlobQueryRowsResp {
	this := BlobQueryRowsResp{}
	return &this
}

// NewBlobQueryRowsRespWithDefaults instantiates a new BlobQueryRowsResp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBlobQueryRowsRespWithDefaults() *BlobQueryRowsResp {
	this := BlobQueryRowsResp{}
	return &this
}

// GetRowCount returns the RowCount field value if set, zero value otherwise.
func (o *BlobQueryRowsResp) GetRowCount() int32 {
	if o == nil || IsNil(o.RowCount) {
		var ret int32
		return ret
	}
	return *o.RowCount
}

// GetRowCountOk returns a tuple with the RowCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlobQueryRowsResp) GetRowCountOk() (*int32, bool) {
	if o == nil || IsNil(o.RowCount) {
		return nil, false
	}
	return o.RowCount, true
}

// HasRowCount returns a boolean if a field has been set.
func (o *BlobQueryRowsResp) HasRowCount() bool {
	if o != nil && !IsNil(o.RowCount) {
		return true
	}

	return false
}

// SetRowCount gets a reference to the given int32 and assigns it to the RowCount field.
func (o *BlobQueryRowsResp) SetRowCount(v int32) {
	o.RowCount = &v
}

// GetRows returns the Rows field value if set, zero value otherwise.
func (o *BlobQueryRowsResp) GetRows() []map[string]interface{} {
	if o == nil || IsNil(o.Rows) {
		var ret []map[string]interface{}
		return ret
	}
	return o.Rows
}

// GetRowsOk returns a tuple with the Rows field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlobQueryRowsResp) GetRowsOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Rows) {
		return nil, false
	}
	return o.Rows, true
}

// HasRows returns a boolean if a field has been set.
func (o *BlobQueryRowsResp) HasRows() bool {
	if o != nil && !IsNil(o.Rows) {
		return true
	}

	return false
}

// SetRows gets a reference to the given []map[string]interface{} and assigns it to the Rows field.
func (o *BlobQueryRowsResp) SetRows(v []map[string]interface{}) {
	o.Rows = v
}

func (o BlobQueryRowsResp) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BlobQueryRowsResp) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.RowCount) {
		toSerialize["row_count"] = o.RowCount
	}
	if !IsNil(o.Rows) {
		toSerialize["rows"] = o.Rows
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BlobQueryRowsResp) UnmarshalJSON(data []byte) (err error) {
	varBlobQueryRowsResp := _BlobQueryRowsResp{}

	err = json.Unmarshal(data, &varBlobQueryRowsResp)

	if err != nil {
		return err
	}

	*o = BlobQueryRowsResp(varBlobQueryRowsResp)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "row_count")
		delete(additionalProperties, "rows")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBlobQueryRowsResp struct {
	value *BlobQueryRowsResp
	isSet bool
}

func (v NullableBlobQueryRowsResp) Get() *BlobQueryRowsResp {
	return v.value
}

func (v *NullableBlobQueryRowsResp) Set(val *BlobQueryRowsResp) {
	v.value = val
	v.isSet = true
}

func (v NullableBlobQueryRowsResp) IsSet() bool {
	return v.isSet
}

func (v *NullableBlobQueryRowsResp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBlobQueryRowsResp(val *BlobQueryRowsResp) *NullableBlobQueryRowsResp {
	return &NullableBlobQueryRowsResp{value: val, isSet: true}
}

func (v NullableBlobQueryRowsResp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBlobQueryRowsResp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
