/*
RCABench API

RCABench - A comprehensive root cause analysis benchmarking platform for microservices

API version: 1.0.0
Contact: team@rcabench.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"fmt"
)

// checks if the InjectionInjectionLabelOperation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InjectionInjectionLabelOperation{}

// InjectionInjectionLabelOperation struct for InjectionInjectionLabelOperation
type InjectionInjectionLabelOperation struct {
	// Labels to add to this injection
	AddLabels []DtoLabelItem `json:"add_labels,omitempty"`
	// Injection ID to manage
	InjectionId int32 `json:"injection_id"`
	// Labels to remove from this injection
	RemoveLabels         []DtoLabelItem `json:"remove_labels,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _InjectionInjectionLabelOperation InjectionInjectionLabelOperation

// NewInjectionInjectionLabelOperation instantiates a new InjectionInjectionLabelOperation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInjectionInjectionLabelOperation(injectionId int32) *InjectionInjectionLabelOperation {
	this := InjectionInjectionLabelOperation{}
	this.InjectionId = injectionId
	return &this
}

// NewInjectionInjectionLabelOperationWithDefaults instantiates a new InjectionInjectionLabelOperation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInjectionInjectionLabelOperationWithDefaults() *InjectionInjectionLabelOperation {
	this := InjectionInjectionLabelOperation{}
	return &this
}

// GetAddLabels returns the AddLabels field value if set, zero value otherwise.
func (o *InjectionInjectionLabelOperation) GetAddLabels() []DtoLabelItem {
	if o == nil || IsNil(o.AddLabels) {
		var ret []DtoLabelItem
		return ret
	}
	return o.AddLabels
}

// GetAddLabelsOk returns a tuple with the AddLabels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InjectionInjectionLabelOperation) GetAddLabelsOk() ([]DtoLabelItem, bool) {
	if o == nil || IsNil(o.AddLabels) {
		return nil, false
	}
	return o.AddLabels, true
}

// HasAddLabels returns a boolean if a field has been set.
func (o *InjectionInjectionLabelOperation) HasAddLabels() bool {
	if o != nil && !IsNil(o.AddLabels) {
		return true
	}

	return false
}

// SetAddLabels gets a reference to the given []DtoLabelItem and assigns it to the AddLabels field.
func (o *InjectionInjectionLabelOperation) SetAddLabels(v []DtoLabelItem) {
	o.AddLabels = v
}

// GetInjectionId returns the InjectionId field value
func (o *InjectionInjectionLabelOperation) GetInjectionId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.InjectionId
}

// GetInjectionIdOk returns a tuple with the InjectionId field value
// and a boolean to check if the value has been set.
func (o *InjectionInjectionLabelOperation) GetInjectionIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InjectionId, true
}

// SetInjectionId sets field value
func (o *InjectionInjectionLabelOperation) SetInjectionId(v int32) {
	o.InjectionId = v
}

// GetRemoveLabels returns the RemoveLabels field value if set, zero value otherwise.
func (o *InjectionInjectionLabelOperation) GetRemoveLabels() []DtoLabelItem {
	if o == nil || IsNil(o.RemoveLabels) {
		var ret []DtoLabelItem
		return ret
	}
	return o.RemoveLabels
}

// GetRemoveLabelsOk returns a tuple with the RemoveLabels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InjectionInjectionLabelOperation) GetRemoveLabelsOk() ([]DtoLabelItem, bool) {
	if o == nil || IsNil(o.RemoveLabels) {
		return nil, false
	}
	return o.RemoveLabels, true
}

// HasRemoveLabels returns a boolean if a field has been set.
func (o *InjectionInjectionLabelOperation) HasRemoveLabels() bool {
	if o != nil && !IsNil(o.RemoveLabels) {
		return true
	}

	return false
}

// SetRemoveLabels gets a reference to the given []DtoLabelItem and assigns it to the RemoveLabels field.
func (o *InjectionInjectionLabelOperation) SetRemoveLabels(v []DtoLabelItem) {
	o.RemoveLabels = v
}

func (o InjectionInjectionLabelOperation) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InjectionInjectionLabelOperation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AddLabels) {
		toSerialize["add_labels"] = o.AddLabels
	}
	toSerialize["injection_id"] = o.InjectionId
	if !IsNil(o.RemoveLabels) {
		toSerialize["remove_labels"] = o.RemoveLabels
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *InjectionInjectionLabelOperation) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"injection_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInjectionInjectionLabelOperation := _InjectionInjectionLabelOperation{}

	err = json.Unmarshal(data, &varInjectionInjectionLabelOperation)

	if err != nil {
		return err
	}

	*o = InjectionInjectionLabelOperation(varInjectionInjectionLabelOperation)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "add_labels")
		delete(additionalProperties, "injection_id")
		delete(additionalProperties, "remove_labels")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableInjectionInjectionLabelOperation struct {
	value *InjectionInjectionLabelOperation
	isSet bool
}

func (v NullableInjectionInjectionLabelOperation) Get() *InjectionInjectionLabelOperation {
	return v.value
}

func (v *NullableInjectionInjectionLabelOperation) Set(val *InjectionInjectionLabelOperation) {
	v.value = val
	v.isSet = true
}

func (v NullableInjectionInjectionLabelOperation) IsSet() bool {
	return v.isSet
}

func (v *NullableInjectionInjectionLabelOperation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInjectionInjectionLabelOperation(val *InjectionInjectionLabelOperation) *NullableInjectionInjectionLabelOperation {
	return &NullableInjectionInjectionLabelOperation{value: val, isSet: true}
}

func (v NullableInjectionInjectionLabelOperation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInjectionInjectionLabelOperation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
