/*
RCABench API

RCABench - A comprehensive root cause analysis benchmarking platform for microservices

API version: 1.0.0
Contact: team@rcabench.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
)

// checks if the DtoGenericResponseBlobObjectMeta type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DtoGenericResponseBlobObjectMeta{}

// DtoGenericResponseBlobObjectMeta struct for DtoGenericResponseBlobObjectMeta
type DtoGenericResponseBlobObjectMeta struct {
	// Status code
	Code *int32 `json:"code,omitempty"`
	// Generic type data
	Data *BlobObjectMeta `json:"data,omitempty"`
	// Response message
	Message *string `json:"message,omitempty"`
	// Response generation time
	Timestamp            *int32 `json:"timestamp,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _DtoGenericResponseBlobObjectMeta DtoGenericResponseBlobObjectMeta

// NewDtoGenericResponseBlobObjectMeta instantiates a new DtoGenericResponseBlobObjectMeta object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDtoGenericResponseBlobObjectMeta() *DtoGenericResponseBlobObjectMeta {
	this := DtoGenericResponseBlobObjectMeta{}
	return &this
}

// NewDtoGenericResponseBlobObjectMetaWithDefaults instantiates a new DtoGenericResponseBlobObjectMeta object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDtoGenericResponseBlobObjectMetaWithDefaults() *DtoGenericResponseBlobObjectMeta {
	this := DtoGenericResponseBlobObjectMeta{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *DtoGenericResponseBlobObjectMeta) GetCode() int32 {
	if o == nil || IsNil(o.Code) {
		var ret int32
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoGenericResponseBlobObjectMeta) GetCodeOk() (*int32, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *DtoGenericResponseBlobObjectMeta) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given int32 and assigns it to the Code field.
func (o *DtoGenericResponseBlobObjectMeta) SetCode(v int32) {
	o.Code = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *DtoGenericResponseBlobObjectMeta) GetData() BlobObjectMeta {
	if o == nil || IsNil(o.Data) {
		var ret BlobObjectMeta
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoGenericResponseBlobObjectMeta) GetDataOk() (*BlobObjectMeta, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *DtoGenericResponseBlobObjectMeta) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given BlobObjectMeta and assigns it to the Data field.
func (o *DtoGenericResponseBlobObjectMeta) SetData(v BlobObjectMeta) {
	o.Data = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *DtoGenericResponseBlobObjectMeta) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoGenericResponseBlobObjectMeta) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *DtoGenericResponseBlobObjectMeta) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *DtoGenericResponseBlobObjectMeta) SetMessage(v string) {
	o.Message = &v
}

// GetTimestamp returns the Timestamp field value if set, zero value otherwise.
func (o *DtoGenericResponseBlobObjectMeta) GetTimestamp() int32 {
	if o == nil || IsNil(o.Timestamp) {
		var ret int32
		return ret
	}
	return *o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoGenericResponseBlobObjectMeta) GetTimestampOk() (*int32, bool) {
	if o == nil || IsNil(o.Timestamp) {
		return nil, false
	}
	return o.Timestamp, true
}

// HasTimestamp returns a boolean if a field has been set.
func (o *DtoGenericResponseBlobObjectMeta) HasTimestamp() bool {
	if o != nil && !IsNil(o.Timestamp) {
		return true
	}

	return false
}

// SetTimestamp gets a reference to the given int32 and assigns it to the Timestamp field.
func (o *DtoGenericResponseBlobObjectMeta) SetTimestamp(v int32) {
	o.Timestamp = &v
}

func (o DtoGenericResponseBlobObjectMeta) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DtoGenericResponseBlobObjectMeta) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Timestamp) {
		toSerialize["timestamp"] = o.Timestamp
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DtoGenericResponseBlobObjectMeta) UnmarshalJSON(data []byte) (err error) {
	varDtoGenericResponseBlobObjectMeta := _DtoGenericResponseBlobObjectMeta{}

	err = json.Unmarshal(data, &varDtoGenericResponseBlobObjectMeta)

	if err != nil {
		return err
	}

	*o = DtoGenericResponseBlobObjectMeta(varDtoGenericResponseBlobObjectMeta)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "code")
		delete(additionalProperties, "data")
		delete(additionalProperties, "message")
		delete(additionalProperties, "timestamp")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDtoGenericResponseBlobObjectMeta struct {
	value *DtoGenericResponseBlobObjectMeta
	isSet bool
}

func (v NullableDtoGenericResponseBlobObjectMeta) Get() *DtoGenericResponseBlobObjectMeta {
	return v.value
}

func (v *NullableDtoGenericResponseBlobObjectMeta) Set(val *DtoGenericResponseBlobObjectMeta) {
	v.value = val
	v.isSet = true
}

func (v NullableDtoGenericResponseBlobObjectMeta) IsSet() bool {
	return v.isSet
}

func (v *NullableDtoGenericResponseBlobObjectMeta) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDtoGenericResponseBlobObjectMeta(val *DtoGenericResponseBlobObjectMeta) *NullableDtoGenericResponseBlobObjectMeta {
	return &NullableDtoGenericResponseBlobObjectMeta{value: val, isSet: true}
}

func (v NullableDtoGenericResponseBlobObjectMeta) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDtoGenericResponseBlobObjectMeta) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
