apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: "observed-genesis"
  instance: "observed"
  service: "unique-id-service"
  system: "sn"
spec:
  replace_scope: "service"
  points:
    - capability: "pod_kill"
      target:
        app: "unique-id-service"
        namespace: "sn"
    - capability: "pod_failure"
      target:
        app: "unique-id-service"
        namespace: "sn"
    - capability: "container_kill"
      target:
        app: "unique-id-service"
        container: "unique-id-service"
        namespace: "sn"
    - capability: "cpu_stress"
      target:
        app: "unique-id-service"
        container: "unique-id-service"
        namespace: "sn"
    - capability: "time_skew"
      target:
        app: "unique-id-service"
        container: "unique-id-service"
        namespace: "sn"
