enabled: false

externalURL: ""
providerSlug: "aegis-console"

authentik:
  global:
    env:
      - name: AUTHENTIK_BOOTSTRAP_PASSWORD
        valueFrom:
          secretKeyRef:
            name: authentik-bootstrap
            key: password
            optional: true
      - name: AUTHENTIK_BOOTSTRAP_EMAIL
        value: "admin@aegis.local"

  server:
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: "2"
        memory: 2Gi
    volumes:
      - name: aegis-blueprints
        configMap:
          name: '{{ .Release.Name }}-authentik-blueprints'
    volumeMounts:
      - name: aegis-blueprints
        mountPath: /blueprints/custom

  worker:
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: "1"
        memory: 1Gi

  postgresql:
    enabled: true
    auth:
      password: "authentik-pg-pass"

  redis:
    enabled: true
