apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: seed-genesis
  instance: seed
  service: accounting
  system: otel-demo
spec:
  points:
  - capability: dns_error
    target:
      app: accounting
      domain_patterns:
      - postgresql
      namespace: otel-demo
  - capability: dns_random
    target:
      app: accounting
      domain_patterns:
      - postgresql
      namespace: otel-demo
  replace_scope: service
