apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: seed-genesis
  instance: seed
  service: cart
  system: otel-demo
spec:
  points:
  - capability: network_bandwidth
    target:
      namespace: otel-demo
      source_app: cart
      span_names:
      - DB Access
      target_service: valkey-cart
  - capability: network_bandwidth
    target:
      namespace: otel-demo
      source_app: cart
      span_names:
      - POST
      - flagd.evaluation.v1.Service/EventStream
      target_service: flagd
  - capability: network_corrupt
    target:
      namespace: otel-demo
      source_app: cart
      span_names:
      - DB Access
      target_service: valkey-cart
  - capability: network_corrupt
    target:
      namespace: otel-demo
      source_app: cart
      span_names:
      - POST
      - flagd.evaluation.v1.Service/EventStream
      target_service: flagd
  - capability: network_delay
    target:
      namespace: otel-demo
      source_app: cart
      span_names:
      - DB Access
      target_service: valkey-cart
  - capability: network_delay
    target:
      namespace: otel-demo
      source_app: cart
      span_names:
      - POST
      - flagd.evaluation.v1.Service/EventStream
      target_service: flagd
  - capability: network_duplicate
    target:
      namespace: otel-demo
      source_app: cart
      span_names:
      - DB Access
      target_service: valkey-cart
  - capability: network_duplicate
    target:
      namespace: otel-demo
      source_app: cart
      span_names:
      - POST
      - flagd.evaluation.v1.Service/EventStream
      target_service: flagd
  - capability: network_loss
    target:
      namespace: otel-demo
      source_app: cart
      span_names:
      - DB Access
      target_service: valkey-cart
  - capability: network_loss
    target:
      namespace: otel-demo
      source_app: cart
      span_names:
      - POST
      - flagd.evaluation.v1.Service/EventStream
      target_service: flagd
  - capability: network_partition
    target:
      namespace: otel-demo
      source_app: cart
      span_names:
      - DB Access
      target_service: valkey-cart
  - capability: network_partition
    target:
      namespace: otel-demo
      source_app: cart
      span_names:
      - POST
      - flagd.evaluation.v1.Service/EventStream
      target_service: flagd
  replace_scope: service
