apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: "seed-genesis"
  instance: "seed"
  service: "cart"
  system: "otel-demo"
spec:
  replace_scope: "service"
  points:
    - capability: "container_kill"
      target:
        app: "cart"
        container: "cart"
        namespace: "otel-demo"
    - capability: "cpu_stress"
      target:
        app: "cart"
        container: "cart"
        namespace: "otel-demo"
    - capability: "http_request_abort"
      target:
        app: "cart"
        method: "POST"
        namespace: "otel-demo"
        path: "/flagd.evaluation.v1.Service/EventStream"
        port: 8013
        server_address: "flagd"
        span_name: "POST"
    - capability: "http_request_abort"
      target:
        app: "cart"
        method: "POST"
        namespace: "otel-demo"
        path: "/flagd.evaluation.v1.Service/ResolveBoolean"
        port: 8013
        server_address: "flagd"
        span_name: "POST"
    - capability: "http_request_abort"
      target:
        app: "cart"
        method: "POST"
        namespace: "otel-demo"
        path: "/oteldemo.CartService/AddItem"
        port: 8080
        server_address: "cart"
        span_name: "POST /oteldemo.CartService/AddItem"
    - capability: "http_request_abort"
      target:
        app: "cart"
        method: "POST"
        namespace: "otel-demo"
        path: "/oteldemo.CartService/EmptyCart"
        port: 8080
        server_address: "cart"
        span_name: "POST /oteldemo.CartService/EmptyCart"
    - capability: "http_request_abort"
      target:
        app: "cart"
        method: "POST"
        namespace: "otel-demo"
        path: "/oteldemo.CartService/GetCart"
        port: 8080
        server_address: "cart"
        span_name: "POST /oteldemo.CartService/GetCart"
    - capability: "http_request_delay"
      target:
        app: "cart"
        method: "POST"
        namespace: "otel-demo"
        path: "/flagd.evaluation.v1.Service/EventStream"
        port: 8013
        server_address: "flagd"
        span_name: "POST"
    - capability: "http_request_delay"
      target:
        app: "cart"
        method: "POST"
        namespace: "otel-demo"
        path: "/flagd.evaluation.v1.Service/ResolveBoolean"
        port: 8013
        server_address: "flagd"
        span_name: "POST"
    - capability: "http_request_delay"
      target:
        app: "cart"
        method: "POST"
        namespace: "otel-demo"
        path: "/oteldemo.CartService/AddItem"
        port: 8080
        server_address: "cart"
        span_name: "POST /oteldemo.CartService/AddItem"
    - capability: "http_request_delay"
      target:
        app: "cart"
        method: "POST"
        namespace: "otel-demo"
        path: "/oteldemo.CartService/EmptyCart"
        port: 8080
        server_address: "cart"
        span_name: "POST /oteldemo.CartService/EmptyCart"
    - capability: "http_request_delay"
      target:
        app: "cart"
        method: "POST"
        namespace: "otel-demo"
        path: "/oteldemo.CartService/GetCart"
        port: 8080
        server_address: "cart"
        span_name: "POST /oteldemo.CartService/GetCart"
    - capability: "memory_stress"
      target:
        app: "cart"
        container: "cart"
        namespace: "otel-demo"
    - capability: "pod_failure"
      target:
        app: "cart"
        namespace: "otel-demo"
    - capability: "pod_kill"
      target:
        app: "cart"
        namespace: "otel-demo"
    - capability: "time_skew"
      target:
        app: "cart"
        container: "cart"
        namespace: "otel-demo"
