apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: "seed-genesis"
  instance: "seed"
  service: "flagd"
  system: "otel-demo"
spec:
  replace_scope: "service"
  points:
    - capability: "container_kill"
      target:
        app: "flagd"
        container: "flagd"
        namespace: "otel-demo"
    - capability: "cpu_stress"
      target:
        app: "flagd"
        container: "flagd"
        namespace: "otel-demo"
    - capability: "http_request_abort"
      target:
        app: "flagd"
        method: "POST"
        namespace: "otel-demo"
        path: "/flagd.evaluation.v1.Service/EventStream"
        port: 8013
    - capability: "http_request_abort"
      target:
        app: "flagd"
        method: "POST"
        namespace: "otel-demo"
        path: "/flagd.evaluation.v1.Service/ResolveBoolean"
        port: 8013
    - capability: "http_request_abort"
      target:
        app: "flagd"
        method: "POST"
        namespace: "otel-demo"
        path: "/flagd.evaluation.v1.Service/ResolveInt"
        port: 8013
    - capability: "http_request_delay"
      target:
        app: "flagd"
        method: "POST"
        namespace: "otel-demo"
        path: "/flagd.evaluation.v1.Service/EventStream"
        port: 8013
    - capability: "http_request_delay"
      target:
        app: "flagd"
        method: "POST"
        namespace: "otel-demo"
        path: "/flagd.evaluation.v1.Service/ResolveBoolean"
        port: 8013
    - capability: "http_request_delay"
      target:
        app: "flagd"
        method: "POST"
        namespace: "otel-demo"
        path: "/flagd.evaluation.v1.Service/ResolveInt"
        port: 8013
    - capability: "memory_stress"
      target:
        app: "flagd"
        container: "flagd"
        namespace: "otel-demo"
    - capability: "pod_failure"
      target:
        app: "flagd"
        namespace: "otel-demo"
    - capability: "pod_kill"
      target:
        app: "flagd"
        namespace: "otel-demo"
    - capability: "time_skew"
      target:
        app: "flagd"
        container: "flagd"
        namespace: "otel-demo"
