apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: "seed-genesis"
  instance: "seed"
  service: "frontend"
  system: "otel-demo"
spec:
  replace_scope: "service"
  points:
    - capability: "container_kill"
      target:
        app: "frontend"
        container: "frontend"
        namespace: "otel-demo"
    - capability: "cpu_stress"
      target:
        app: "frontend"
        container: "frontend"
        namespace: "otel-demo"
    - capability: "http_request_abort"
      target:
        app: "frontend"
        method: "POST"
        namespace: "otel-demo"
        path: "/oteldemo.AdService/GetAds"
        port: 8080
        server_address: "ad"
        span_name: "oteldemo.AdService/GetAds"
    - capability: "http_request_abort"
      target:
        app: "frontend"
        method: "POST"
        namespace: "otel-demo"
        path: "/oteldemo.CartService/AddItem"
        port: 8080
        server_address: "cart"
        span_name: "oteldemo.CartService/AddItem"
    - capability: "http_request_abort"
      target:
        app: "frontend"
        method: "POST"
        namespace: "otel-demo"
        path: "/oteldemo.CartService/GetCart"
        port: 8080
        server_address: "cart"
        span_name: "grpc.oteldemo.CartService/GetCart"
    - capability: "http_request_abort"
      target:
        app: "frontend"
        method: "POST"
        namespace: "otel-demo"
        path: "/oteldemo.CheckoutService/PlaceOrder"
        port: 8080
        server_address: "checkout"
        span_name: "oteldemo.CheckoutService/PlaceOrder"
    - capability: "http_request_abort"
      target:
        app: "frontend"
        method: "POST"
        namespace: "otel-demo"
        path: "/oteldemo.ProductCatalogService/GetProduct"
        port: 8080
        server_address: "product-catalog"
        span_name: "oteldemo.ProductCatalogService/GetProduct"
    - capability: "http_request_abort"
      target:
        app: "frontend"
        method: "POST"
        namespace: "otel-demo"
        path: "/oteldemo.RecommendationService/ListRecommendations"
        port: 8080
        server_address: "recommendation"
        span_name: "oteldemo.RecommendationService/ListRecommendations"
    - capability: "http_request_delay"
      target:
        app: "frontend"
        method: "POST"
        namespace: "otel-demo"
        path: "/oteldemo.AdService/GetAds"
        port: 8080
        server_address: "ad"
        span_name: "oteldemo.AdService/GetAds"
    - capability: "http_request_delay"
      target:
        app: "frontend"
        method: "POST"
        namespace: "otel-demo"
        path: "/oteldemo.CartService/AddItem"
        port: 8080
        server_address: "cart"
        span_name: "oteldemo.CartService/AddItem"
    - capability: "http_request_delay"
      target:
        app: "frontend"
        method: "POST"
        namespace: "otel-demo"
        path: "/oteldemo.CartService/GetCart"
        port: 8080
        server_address: "cart"
        span_name: "grpc.oteldemo.CartService/GetCart"
    - capability: "http_request_delay"
      target:
        app: "frontend"
        method: "POST"
        namespace: "otel-demo"
        path: "/oteldemo.CheckoutService/PlaceOrder"
        port: 8080
        server_address: "checkout"
        span_name: "oteldemo.CheckoutService/PlaceOrder"
    - capability: "http_request_delay"
      target:
        app: "frontend"
        method: "POST"
        namespace: "otel-demo"
        path: "/oteldemo.ProductCatalogService/GetProduct"
        port: 8080
        server_address: "product-catalog"
        span_name: "oteldemo.ProductCatalogService/GetProduct"
    - capability: "http_request_delay"
      target:
        app: "frontend"
        method: "POST"
        namespace: "otel-demo"
        path: "/oteldemo.RecommendationService/ListRecommendations"
        port: 8080
        server_address: "recommendation"
        span_name: "oteldemo.RecommendationService/ListRecommendations"
    - capability: "memory_stress"
      target:
        app: "frontend"
        container: "frontend"
        namespace: "otel-demo"
    - capability: "pod_failure"
      target:
        app: "frontend"
        namespace: "otel-demo"
    - capability: "pod_kill"
      target:
        app: "frontend"
        namespace: "otel-demo"
    - capability: "time_skew"
      target:
        app: "frontend"
        container: "frontend"
        namespace: "otel-demo"
