apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: seed-genesis
  instance: seed
  service: frontend
  system: otel-demo
spec:
  points:
  - capability: network_bandwidth
    target:
      namespace: otel-demo
      source_app: frontend
      target_service: ad
  - capability: network_bandwidth
    target:
      namespace: otel-demo
      source_app: frontend
      target_service: cart
  - capability: network_bandwidth
    target:
      namespace: otel-demo
      source_app: frontend
      target_service: checkout
  - capability: network_bandwidth
    target:
      namespace: otel-demo
      source_app: frontend
      target_service: load-generator
  - capability: network_bandwidth
    target:
      namespace: otel-demo
      source_app: frontend
      target_service: product-catalog
  - capability: network_bandwidth
    target:
      namespace: otel-demo
      source_app: frontend
      target_service: recommendation
  - capability: network_corrupt
    target:
      namespace: otel-demo
      source_app: frontend
      target_service: ad
  - capability: network_corrupt
    target:
      namespace: otel-demo
      source_app: frontend
      target_service: cart
  - capability: network_corrupt
    target:
      namespace: otel-demo
      source_app: frontend
      target_service: checkout
  - capability: network_corrupt
    target:
      namespace: otel-demo
      source_app: frontend
      target_service: load-generator
  - capability: network_corrupt
    target:
      namespace: otel-demo
      source_app: frontend
      target_service: product-catalog
  - capability: network_corrupt
    target:
      namespace: otel-demo
      source_app: frontend
      target_service: recommendation
  - capability: network_delay
    target:
      namespace: otel-demo
      source_app: frontend
      target_service: ad
  - capability: network_delay
    target:
      namespace: otel-demo
      source_app: frontend
      target_service: cart
  - capability: network_delay
    target:
      namespace: otel-demo
      source_app: frontend
      target_service: checkout
  - capability: network_delay
    target:
      namespace: otel-demo
      source_app: frontend
      target_service: load-generator
  - capability: network_delay
    target:
      namespace: otel-demo
      source_app: frontend
      target_service: product-catalog
  - capability: network_delay
    target:
      namespace: otel-demo
      source_app: frontend
      target_service: recommendation
  - capability: network_duplicate
    target:
      namespace: otel-demo
      source_app: frontend
      target_service: ad
  - capability: network_duplicate
    target:
      namespace: otel-demo
      source_app: frontend
      target_service: cart
  - capability: network_duplicate
    target:
      namespace: otel-demo
      source_app: frontend
      target_service: checkout
  - capability: network_duplicate
    target:
      namespace: otel-demo
      source_app: frontend
      target_service: load-generator
  - capability: network_duplicate
    target:
      namespace: otel-demo
      source_app: frontend
      target_service: product-catalog
  - capability: network_duplicate
    target:
      namespace: otel-demo
      source_app: frontend
      target_service: recommendation
  - capability: network_loss
    target:
      namespace: otel-demo
      source_app: frontend
      target_service: ad
  - capability: network_loss
    target:
      namespace: otel-demo
      source_app: frontend
      target_service: cart
  - capability: network_loss
    target:
      namespace: otel-demo
      source_app: frontend
      target_service: checkout
  - capability: network_loss
    target:
      namespace: otel-demo
      source_app: frontend
      target_service: load-generator
  - capability: network_loss
    target:
      namespace: otel-demo
      source_app: frontend
      target_service: product-catalog
  - capability: network_loss
    target:
      namespace: otel-demo
      source_app: frontend
      target_service: recommendation
  - capability: network_partition
    target:
      namespace: otel-demo
      source_app: frontend
      target_service: ad
  - capability: network_partition
    target:
      namespace: otel-demo
      source_app: frontend
      target_service: cart
  - capability: network_partition
    target:
      namespace: otel-demo
      source_app: frontend
      target_service: checkout
  - capability: network_partition
    target:
      namespace: otel-demo
      source_app: frontend
      target_service: load-generator
  - capability: network_partition
    target:
      namespace: otel-demo
      source_app: frontend
      target_service: product-catalog
  - capability: network_partition
    target:
      namespace: otel-demo
      source_app: frontend
      target_service: recommendation
  replace_scope: service
