apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: "seed-genesis"
  instance: "seed"
  service: "frontend"
  system: "otel-demo"
spec:
  replace_scope: "service"
  points:
    - capability: "container_kill"
      target:
        app: "frontend"
        container: "frontend"
        namespace: "otel-demo"
    - capability: "cpu_stress"
      target:
        app: "frontend"
        container: "frontend"
        namespace: "otel-demo"
    - capability: "pod_failure"
      target:
        app: "frontend"
        namespace: "otel-demo"
    - capability: "pod_kill"
      target:
        app: "frontend"
        namespace: "otel-demo"
    - capability: "time_skew"
      target:
        app: "frontend"
        container: "frontend"
        namespace: "otel-demo"
