apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: "seed-genesis"
  instance: "seed"
  service: "image-provider"
  system: "otel-demo"
spec:
  replace_scope: "service"
  points:
    - capability: "network_bandwidth"
      target:
        namespace: "otel-demo"
        source_app: "image-provider"
        span_names:
          - "image-provider"
        target_service: "load-generator"
    - capability: "network_corrupt"
      target:
        namespace: "otel-demo"
        source_app: "image-provider"
        span_names:
          - "image-provider"
        target_service: "load-generator"
    - capability: "network_delay"
      target:
        namespace: "otel-demo"
        source_app: "image-provider"
        span_names:
          - "image-provider"
        target_service: "load-generator"
    - capability: "network_duplicate"
      target:
        namespace: "otel-demo"
        source_app: "image-provider"
        span_names:
          - "image-provider"
        target_service: "load-generator"
    - capability: "network_loss"
      target:
        namespace: "otel-demo"
        source_app: "image-provider"
        span_names:
          - "image-provider"
        target_service: "load-generator"
    - capability: "network_partition"
      target:
        namespace: "otel-demo"
        source_app: "image-provider"
        span_names:
          - "image-provider"
        target_service: "load-generator"
