apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: "observed-genesis"
  instance: "observed"
  service: "payment"
  system: "otel-demo"
spec:
  replace_scope: "service"
  points:
    - capability: "pod_kill"
      target:
        app: "payment"
        namespace: "otel-demo"
    - capability: "pod_failure"
      target:
        app: "payment"
        namespace: "otel-demo"
    - capability: "container_kill"
      target:
        app: "payment"
        container: "payment"
        namespace: "otel-demo"
    - capability: "cpu_stress"
      target:
        app: "payment"
        container: "payment"
        namespace: "otel-demo"
    - capability: "time_skew"
      target:
        app: "payment"
        container: "payment"
        namespace: "otel-demo"
    - capability: "dns_error"
      target:
        app: "payment"
        domain_patterns:
          - "flagd"
        namespace: "otel-demo"
    - capability: "dns_random"
      target:
        app: "payment"
        domain_patterns:
          - "flagd"
        namespace: "otel-demo"
    - capability: "network_delay"
      target:
        namespace: "otel-demo"
        source_app: "payment"
        span_names:
          - "flagd.evaluation.v1.Service/ResolveFloat"
        target_service: "flagd"
    - capability: "network_loss"
      target:
        namespace: "otel-demo"
        source_app: "payment"
        span_names:
          - "flagd.evaluation.v1.Service/ResolveFloat"
        target_service: "flagd"
    - capability: "network_duplicate"
      target:
        namespace: "otel-demo"
        source_app: "payment"
        span_names:
          - "flagd.evaluation.v1.Service/ResolveFloat"
        target_service: "flagd"
    - capability: "network_corrupt"
      target:
        namespace: "otel-demo"
        source_app: "payment"
        span_names:
          - "flagd.evaluation.v1.Service/ResolveFloat"
        target_service: "flagd"
    - capability: "network_bandwidth"
      target:
        namespace: "otel-demo"
        source_app: "payment"
        span_names:
          - "flagd.evaluation.v1.Service/ResolveFloat"
        target_service: "flagd"
    - capability: "network_partition"
      target:
        namespace: "otel-demo"
        source_app: "payment"
        span_names:
          - "flagd.evaluation.v1.Service/ResolveFloat"
        target_service: "flagd"
