apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: "seed-genesis"
  instance: "seed"
  service: "payment"
  system: "otel-demo"
spec:
  replace_scope: "service"
  points:
    - capability: "container_kill"
      target:
        app: "payment"
        container: "payment"
        namespace: "otel-demo"
    - capability: "cpu_stress"
      target:
        app: "payment"
        container: "payment"
        namespace: "otel-demo"
    - capability: "http_request_abort"
      target:
        app: "payment"
        method: "POST"
        namespace: "otel-demo"
        path: "/oteldemo.PaymentService/Charge"
        port: 8080
        server_address: "payment"
        span_name: "grpc.oteldemo.PaymentService/Charge"
    - capability: "http_request_delay"
      target:
        app: "payment"
        method: "POST"
        namespace: "otel-demo"
        path: "/oteldemo.PaymentService/Charge"
        port: 8080
        server_address: "payment"
        span_name: "grpc.oteldemo.PaymentService/Charge"
    - capability: "memory_stress"
      target:
        app: "payment"
        container: "payment"
        namespace: "otel-demo"
    - capability: "pod_failure"
      target:
        app: "payment"
        namespace: "otel-demo"
    - capability: "pod_kill"
      target:
        app: "payment"
        namespace: "otel-demo"
    - capability: "time_skew"
      target:
        app: "payment"
        container: "payment"
        namespace: "otel-demo"
