apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: "observed-genesis"
  instance: "observed"
  service: "product-catalog"
  system: "otel-demo"
spec:
  replace_scope: "service"
  points:
    - capability: "pod_kill"
      target:
        app: "product-catalog"
        namespace: "otel-demo"
    - capability: "pod_failure"
      target:
        app: "product-catalog"
        namespace: "otel-demo"
    - capability: "container_kill"
      target:
        app: "product-catalog"
        container: "product-catalog"
        namespace: "otel-demo"
    - capability: "cpu_stress"
      target:
        app: "product-catalog"
        container: "product-catalog"
        namespace: "otel-demo"
    - capability: "time_skew"
      target:
        app: "product-catalog"
        container: "product-catalog"
        namespace: "otel-demo"
