apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: "seed-genesis"
  instance: "seed"
  service: "product-catalog"
  system: "otel-demo"
spec:
  replace_scope: "service"
  points:
    - capability: "container_kill"
      target:
        app: "product-catalog"
        container: "product-catalog"
        namespace: "otel-demo"
    - capability: "cpu_stress"
      target:
        app: "product-catalog"
        container: "product-catalog"
        namespace: "otel-demo"
    - capability: "http_request_abort"
      target:
        app: "product-catalog"
        method: "POST"
        namespace: "otel-demo"
        path: "/oteldemo.ProductCatalogService/GetProduct"
        port: 8080
        server_address: "product-catalog"
        span_name: "oteldemo.ProductCatalogService/GetProduct"
    - capability: "http_request_abort"
      target:
        app: "product-catalog"
        method: "POST"
        namespace: "otel-demo"
        path: "/oteldemo.ProductCatalogService/ListProducts"
        port: 8080
        server_address: "product-catalog"
        span_name: "oteldemo.ProductCatalogService/ListProducts"
    - capability: "http_request_delay"
      target:
        app: "product-catalog"
        method: "POST"
        namespace: "otel-demo"
        path: "/oteldemo.ProductCatalogService/GetProduct"
        port: 8080
        server_address: "product-catalog"
        span_name: "oteldemo.ProductCatalogService/GetProduct"
    - capability: "http_request_delay"
      target:
        app: "product-catalog"
        method: "POST"
        namespace: "otel-demo"
        path: "/oteldemo.ProductCatalogService/ListProducts"
        port: 8080
        server_address: "product-catalog"
        span_name: "oteldemo.ProductCatalogService/ListProducts"
    - capability: "memory_stress"
      target:
        app: "product-catalog"
        container: "product-catalog"
        namespace: "otel-demo"
    - capability: "pod_failure"
      target:
        app: "product-catalog"
        namespace: "otel-demo"
    - capability: "pod_kill"
      target:
        app: "product-catalog"
        namespace: "otel-demo"
    - capability: "time_skew"
      target:
        app: "product-catalog"
        container: "product-catalog"
        namespace: "otel-demo"
