apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: "seed-genesis"
  instance: "seed"
  service: "quote"
  system: "otel-demo"
spec:
  replace_scope: "service"
  points:
    - capability: "container_kill"
      target:
        app: "quote"
        container: "quote"
        namespace: "otel-demo"
    - capability: "cpu_stress"
      target:
        app: "quote"
        container: "quote"
        namespace: "otel-demo"
    - capability: "http_request_abort"
      target:
        app: "quote"
        method: "POST"
        namespace: "otel-demo"
        path: "/getquote"
        port: 8080
        server_address: "quote"
        span_name: "POST /getquote"
    - capability: "http_request_delay"
      target:
        app: "quote"
        method: "POST"
        namespace: "otel-demo"
        path: "/getquote"
        port: 8080
        server_address: "quote"
        span_name: "POST /getquote"
    - capability: "memory_stress"
      target:
        app: "quote"
        container: "quote"
        namespace: "otel-demo"
    - capability: "pod_failure"
      target:
        app: "quote"
        namespace: "otel-demo"
    - capability: "pod_kill"
      target:
        app: "quote"
        namespace: "otel-demo"
    - capability: "time_skew"
      target:
        app: "quote"
        container: "quote"
        namespace: "otel-demo"
