apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: "seed-genesis"
  instance: "seed"
  service: "recommendation"
  system: "otel-demo"
spec:
  replace_scope: "service"
  points:
    - capability: "container_kill"
      target:
        app: "recommendation"
        container: "recommendation"
        namespace: "otel-demo"
    - capability: "cpu_stress"
      target:
        app: "recommendation"
        container: "recommendation"
        namespace: "otel-demo"
    - capability: "http_request_abort"
      target:
        app: "recommendation"
        method: "POST"
        namespace: "otel-demo"
        path: "/flagd.evaluation.v1.Service/EventStream"
        port: 8013
        server_address: "flagd"
        span_name: "flagd.evaluation.v1.Service/EventStream"
    - capability: "http_request_abort"
      target:
        app: "recommendation"
        method: "POST"
        namespace: "otel-demo"
        path: "/flagd.evaluation.v1.Service/ResolveBoolean"
        port: 8013
        server_address: "flagd"
        span_name: "/flagd.evaluation.v1.Service/ResolveBoolean"
    - capability: "http_request_abort"
      target:
        app: "recommendation"
        method: "POST"
        namespace: "otel-demo"
        path: "/oteldemo.ProductCatalogService/ListProducts"
        port: 8080
        server_address: "product-catalog"
        span_name: "oteldemo.ProductCatalogService/ListProducts"
    - capability: "http_request_abort"
      target:
        app: "recommendation"
        method: "POST"
        namespace: "otel-demo"
        path: "/oteldemo.RecommendationService/ListRecommendations"
        port: 8080
        server_address: "recommendation"
        span_name: "/oteldemo.RecommendationService/ListRecommendations"
    - capability: "http_request_delay"
      target:
        app: "recommendation"
        method: "POST"
        namespace: "otel-demo"
        path: "/flagd.evaluation.v1.Service/EventStream"
        port: 8013
        server_address: "flagd"
        span_name: "flagd.evaluation.v1.Service/EventStream"
    - capability: "http_request_delay"
      target:
        app: "recommendation"
        method: "POST"
        namespace: "otel-demo"
        path: "/flagd.evaluation.v1.Service/ResolveBoolean"
        port: 8013
        server_address: "flagd"
        span_name: "/flagd.evaluation.v1.Service/ResolveBoolean"
    - capability: "http_request_delay"
      target:
        app: "recommendation"
        method: "POST"
        namespace: "otel-demo"
        path: "/oteldemo.ProductCatalogService/ListProducts"
        port: 8080
        server_address: "product-catalog"
        span_name: "oteldemo.ProductCatalogService/ListProducts"
    - capability: "http_request_delay"
      target:
        app: "recommendation"
        method: "POST"
        namespace: "otel-demo"
        path: "/oteldemo.RecommendationService/ListRecommendations"
        port: 8080
        server_address: "recommendation"
        span_name: "/oteldemo.RecommendationService/ListRecommendations"
    - capability: "memory_stress"
      target:
        app: "recommendation"
        container: "recommendation"
        namespace: "otel-demo"
    - capability: "pod_failure"
      target:
        app: "recommendation"
        namespace: "otel-demo"
    - capability: "pod_kill"
      target:
        app: "recommendation"
        namespace: "otel-demo"
    - capability: "time_skew"
      target:
        app: "recommendation"
        container: "recommendation"
        namespace: "otel-demo"
