apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: "seed-genesis"
  instance: "seed"
  service: "frontend"
  system: "hs"
spec:
  replace_scope: "service"
  points:
    - capability: "container_kill"
      target:
        app: "frontend"
        container: "frontend"
        namespace: "hs"
    - capability: "cpu_stress"
      target:
        app: "frontend"
        container: "frontend"
        namespace: "hs"
    - capability: "http_request_abort"
      target:
        app: "frontend"
        method: "POST"
        namespace: "hs"
        path: "/attractions.Attractions/NearbyCinema"
        port: 8089
        server_address: "attractions"
        span_name: "attractions.Attractions/NearbyCinema"
    - capability: "http_request_abort"
      target:
        app: "frontend"
        method: "POST"
        namespace: "hs"
        path: "/attractions.Attractions/NearbyMus"
        port: 8089
        server_address: "attractions"
        span_name: "attractions.Attractions/NearbyMus"
    - capability: "http_request_abort"
      target:
        app: "frontend"
        method: "POST"
        namespace: "hs"
        path: "/attractions.Attractions/NearbyRest"
        port: 8089
        server_address: "attractions"
        span_name: "attractions.Attractions/NearbyRest"
    - capability: "http_request_abort"
      target:
        app: "frontend"
        method: "POST"
        namespace: "hs"
        path: "/profile.Profile/GetProfiles"
        port: 8081
        server_address: "profile"
        span_name: "profile.Profile/GetProfiles"
    - capability: "http_request_abort"
      target:
        app: "frontend"
        method: "POST"
        namespace: "hs"
        path: "/recommendation.Recommendation/GetRecommendations"
        port: 8085
        server_address: "recommendation"
        span_name: "recommendation.Recommendation/GetRecommendations"
    - capability: "http_request_abort"
      target:
        app: "frontend"
        method: "POST"
        namespace: "hs"
        path: "/reservation.Reservation/CheckAvailability"
        port: 8087
        server_address: "reservation"
        span_name: "reservation.Reservation/CheckAvailability"
    - capability: "http_request_abort"
      target:
        app: "frontend"
        method: "POST"
        namespace: "hs"
        path: "/reservation.Reservation/MakeReservation"
        port: 8087
        server_address: "reservation"
        span_name: "reservation.Reservation/MakeReservation"
    - capability: "http_request_abort"
      target:
        app: "frontend"
        method: "POST"
        namespace: "hs"
        path: "/search.Search/Nearby"
        port: 8082
        server_address: "search"
        span_name: "search.Search/Nearby"
    - capability: "http_request_abort"
      target:
        app: "frontend"
        method: "POST"
        namespace: "hs"
        path: "/user.User/CheckUser"
        port: 8086
        server_address: "user"
        span_name: "user.User/CheckUser"
    - capability: "http_request_delay"
      target:
        app: "frontend"
        method: "POST"
        namespace: "hs"
        path: "/attractions.Attractions/NearbyCinema"
        port: 8089
        server_address: "attractions"
        span_name: "attractions.Attractions/NearbyCinema"
    - capability: "http_request_delay"
      target:
        app: "frontend"
        method: "POST"
        namespace: "hs"
        path: "/attractions.Attractions/NearbyMus"
        port: 8089
        server_address: "attractions"
        span_name: "attractions.Attractions/NearbyMus"
    - capability: "http_request_delay"
      target:
        app: "frontend"
        method: "POST"
        namespace: "hs"
        path: "/attractions.Attractions/NearbyRest"
        port: 8089
        server_address: "attractions"
        span_name: "attractions.Attractions/NearbyRest"
    - capability: "http_request_delay"
      target:
        app: "frontend"
        method: "POST"
        namespace: "hs"
        path: "/profile.Profile/GetProfiles"
        port: 8081
        server_address: "profile"
        span_name: "profile.Profile/GetProfiles"
    - capability: "http_request_delay"
      target:
        app: "frontend"
        method: "POST"
        namespace: "hs"
        path: "/recommendation.Recommendation/GetRecommendations"
        port: 8085
        server_address: "recommendation"
        span_name: "recommendation.Recommendation/GetRecommendations"
    - capability: "http_request_delay"
      target:
        app: "frontend"
        method: "POST"
        namespace: "hs"
        path: "/reservation.Reservation/CheckAvailability"
        port: 8087
        server_address: "reservation"
        span_name: "reservation.Reservation/CheckAvailability"
    - capability: "http_request_delay"
      target:
        app: "frontend"
        method: "POST"
        namespace: "hs"
        path: "/reservation.Reservation/MakeReservation"
        port: 8087
        server_address: "reservation"
        span_name: "reservation.Reservation/MakeReservation"
    - capability: "http_request_delay"
      target:
        app: "frontend"
        method: "POST"
        namespace: "hs"
        path: "/search.Search/Nearby"
        port: 8082
        server_address: "search"
        span_name: "search.Search/Nearby"
    - capability: "http_request_delay"
      target:
        app: "frontend"
        method: "POST"
        namespace: "hs"
        path: "/user.User/CheckUser"
        port: 8086
        server_address: "user"
        span_name: "user.User/CheckUser"
    - capability: "memory_stress"
      target:
        app: "frontend"
        container: "frontend"
        namespace: "hs"
    - capability: "pod_failure"
      target:
        app: "frontend"
        namespace: "hs"
    - capability: "pod_kill"
      target:
        app: "frontend"
        namespace: "hs"
    - capability: "time_skew"
      target:
        app: "frontend"
        container: "frontend"
        namespace: "hs"
