apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: "seed-genesis"
  instance: "seed"
  service: "frontend"
  system: "hs"
spec:
  replace_scope: "service"
  points:
    - capability: "container_kill"
      target:
        app: "frontend"
        container: "frontend"
        namespace: "hotel-reservation"
    - capability: "cpu_stress"
      target:
        app: "frontend"
        container: "frontend"
        namespace: "hotel-reservation"
    - capability: "http_request_abort"
      target:
        app: "frontend"
        method: "POST"
        namespace: "hotel-reservation"
        path: "/attractions.Attractions/NearbyCinema"
        port: 8089
    - capability: "http_request_abort"
      target:
        app: "frontend"
        method: "POST"
        namespace: "hotel-reservation"
        path: "/attractions.Attractions/NearbyMus"
        port: 8089
    - capability: "http_request_abort"
      target:
        app: "frontend"
        method: "POST"
        namespace: "hotel-reservation"
        path: "/attractions.Attractions/NearbyRest"
        port: 8089
    - capability: "http_request_abort"
      target:
        app: "frontend"
        method: "POST"
        namespace: "hotel-reservation"
        path: "/profile.Profile/GetProfiles"
        port: 8081
    - capability: "http_request_abort"
      target:
        app: "frontend"
        method: "POST"
        namespace: "hotel-reservation"
        path: "/recommendation.Recommendation/GetRecommendations"
        port: 8085
    - capability: "http_request_abort"
      target:
        app: "frontend"
        method: "POST"
        namespace: "hotel-reservation"
        path: "/reservation.Reservation/CheckAvailability"
        port: 8087
    - capability: "http_request_abort"
      target:
        app: "frontend"
        method: "POST"
        namespace: "hotel-reservation"
        path: "/reservation.Reservation/MakeReservation"
        port: 8087
    - capability: "http_request_abort"
      target:
        app: "frontend"
        method: "POST"
        namespace: "hotel-reservation"
        path: "/search.Search/Nearby"
        port: 8082
    - capability: "http_request_abort"
      target:
        app: "frontend"
        method: "POST"
        namespace: "hotel-reservation"
        path: "/user.User/CheckUser"
        port: 8086
    - capability: "http_request_delay"
      target:
        app: "frontend"
        method: "POST"
        namespace: "hotel-reservation"
        path: "/attractions.Attractions/NearbyCinema"
        port: 8089
    - capability: "http_request_delay"
      target:
        app: "frontend"
        method: "POST"
        namespace: "hotel-reservation"
        path: "/attractions.Attractions/NearbyMus"
        port: 8089
    - capability: "http_request_delay"
      target:
        app: "frontend"
        method: "POST"
        namespace: "hotel-reservation"
        path: "/attractions.Attractions/NearbyRest"
        port: 8089
    - capability: "http_request_delay"
      target:
        app: "frontend"
        method: "POST"
        namespace: "hotel-reservation"
        path: "/profile.Profile/GetProfiles"
        port: 8081
    - capability: "http_request_delay"
      target:
        app: "frontend"
        method: "POST"
        namespace: "hotel-reservation"
        path: "/recommendation.Recommendation/GetRecommendations"
        port: 8085
    - capability: "http_request_delay"
      target:
        app: "frontend"
        method: "POST"
        namespace: "hotel-reservation"
        path: "/reservation.Reservation/CheckAvailability"
        port: 8087
    - capability: "http_request_delay"
      target:
        app: "frontend"
        method: "POST"
        namespace: "hotel-reservation"
        path: "/reservation.Reservation/MakeReservation"
        port: 8087
    - capability: "http_request_delay"
      target:
        app: "frontend"
        method: "POST"
        namespace: "hotel-reservation"
        path: "/search.Search/Nearby"
        port: 8082
    - capability: "http_request_delay"
      target:
        app: "frontend"
        method: "POST"
        namespace: "hotel-reservation"
        path: "/user.User/CheckUser"
        port: 8086
    - capability: "memory_stress"
      target:
        app: "frontend"
        container: "frontend"
        namespace: "hotel-reservation"
    - capability: "pod_failure"
      target:
        app: "frontend"
        namespace: "hotel-reservation"
    - capability: "pod_kill"
      target:
        app: "frontend"
        namespace: "hotel-reservation"
    - capability: "time_skew"
      target:
        app: "frontend"
        container: "frontend"
        namespace: "hotel-reservation"
