apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: "observed-genesis"
  instance: "observed"
  service: "geo"
  system: "hs"
spec:
  replace_scope: "service"
  points:
    - capability: "pod_kill"
      target:
        app: "geo"
        namespace: "hs"
    - capability: "pod_failure"
      target:
        app: "geo"
        namespace: "hs"
    - capability: "container_kill"
      target:
        app: "geo"
        container: "geo"
        namespace: "hs"
    - capability: "cpu_stress"
      target:
        app: "geo"
        container: "geo"
        namespace: "hs"
    - capability: "time_skew"
      target:
        app: "geo"
        container: "geo"
        namespace: "hs"
