apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: "seed-genesis"
  instance: "seed"
  service: "rate"
  system: "hs"
spec:
  replace_scope: "service"
  points:
    - capability: "container_kill"
      target:
        app: "rate"
        container: "rate"
        namespace: "hs"
    - capability: "cpu_stress"
      target:
        app: "rate"
        container: "rate"
        namespace: "hs"
    - capability: "pod_failure"
      target:
        app: "rate"
        namespace: "hs"
    - capability: "pod_kill"
      target:
        app: "rate"
        namespace: "hs"
    - capability: "time_skew"
      target:
        app: "rate"
        container: "rate"
        namespace: "hs"
