apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: "seed-genesis"
  instance: "seed"
  service: "rate"
  system: "hs"
spec:
  replace_scope: "service"
  points:
    - capability: "container_kill"
      target:
        app: "rate"
        container: "rate"
        namespace: "hotel-reservation"
    - capability: "cpu_stress"
      target:
        app: "rate"
        container: "rate"
        namespace: "hotel-reservation"
    - capability: "http_request_abort"
      target:
        app: "rate"
        method: "POST"
        namespace: "hotel-reservation"
        path: "/rate.Rate/GetRates"
        port: 8084
    - capability: "http_request_delay"
      target:
        app: "rate"
        method: "POST"
        namespace: "hotel-reservation"
        path: "/rate.Rate/GetRates"
        port: 8084
    - capability: "memory_stress"
      target:
        app: "rate"
        container: "rate"
        namespace: "hotel-reservation"
    - capability: "pod_failure"
      target:
        app: "rate"
        namespace: "hotel-reservation"
    - capability: "pod_kill"
      target:
        app: "rate"
        namespace: "hotel-reservation"
    - capability: "time_skew"
      target:
        app: "rate"
        container: "rate"
        namespace: "hotel-reservation"
