apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: "seed-genesis"
  instance: "seed"
  service: "reservation"
  system: "hs"
spec:
  replace_scope: "service"
  points:
    - capability: "container_kill"
      target:
        app: "reservation"
        container: "reservation"
        namespace: "hs"
    - capability: "cpu_stress"
      target:
        app: "reservation"
        container: "reservation"
        namespace: "hs"
    - capability: "http_request_abort"
      target:
        app: "reservation"
        method: "POST"
        namespace: "hs"
        path: "/reservation.Reservation/CheckAvailability"
        port: 8087
        server_address: "reservation"
        span_name: "reservation.Reservation/CheckAvailability"
    - capability: "http_request_abort"
      target:
        app: "reservation"
        method: "POST"
        namespace: "hs"
        path: "/reservation.Reservation/MakeReservation"
        port: 8087
        server_address: "reservation"
        span_name: "reservation.Reservation/MakeReservation"
    - capability: "http_request_delay"
      target:
        app: "reservation"
        method: "POST"
        namespace: "hs"
        path: "/reservation.Reservation/CheckAvailability"
        port: 8087
        server_address: "reservation"
        span_name: "reservation.Reservation/CheckAvailability"
    - capability: "http_request_delay"
      target:
        app: "reservation"
        method: "POST"
        namespace: "hs"
        path: "/reservation.Reservation/MakeReservation"
        port: 8087
        server_address: "reservation"
        span_name: "reservation.Reservation/MakeReservation"
    - capability: "memory_stress"
      target:
        app: "reservation"
        container: "reservation"
        namespace: "hs"
    - capability: "pod_failure"
      target:
        app: "reservation"
        namespace: "hs"
    - capability: "pod_kill"
      target:
        app: "reservation"
        namespace: "hs"
    - capability: "time_skew"
      target:
        app: "reservation"
        container: "reservation"
        namespace: "hs"
