apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: "observed-genesis"
  instance: "observed"
  service: "search"
  system: "hs"
spec:
  replace_scope: "service"
  points:
    - capability: "pod_kill"
      target:
        app: "search"
        namespace: "hs"
    - capability: "pod_failure"
      target:
        app: "search"
        namespace: "hs"
    - capability: "container_kill"
      target:
        app: "search"
        container: "search"
        namespace: "hs"
    - capability: "cpu_stress"
      target:
        app: "search"
        container: "search"
        namespace: "hs"
    - capability: "time_skew"
      target:
        app: "search"
        container: "search"
        namespace: "hs"
    - capability: "dns_error"
      target:
        app: "search"
        domain_patterns:
          - "geo"
        namespace: "hs"
    - capability: "dns_random"
      target:
        app: "search"
        domain_patterns:
          - "geo"
        namespace: "hs"
    - capability: "network_delay"
      target:
        namespace: "hs"
        source_app: "search"
        span_names:
          - "geo.Geo/Nearby"
        target_service: "geo"
    - capability: "network_loss"
      target:
        namespace: "hs"
        source_app: "search"
        span_names:
          - "geo.Geo/Nearby"
        target_service: "geo"
    - capability: "network_duplicate"
      target:
        namespace: "hs"
        source_app: "search"
        span_names:
          - "geo.Geo/Nearby"
        target_service: "geo"
    - capability: "network_corrupt"
      target:
        namespace: "hs"
        source_app: "search"
        span_names:
          - "geo.Geo/Nearby"
        target_service: "geo"
    - capability: "network_bandwidth"
      target:
        namespace: "hs"
        source_app: "search"
        span_names:
          - "geo.Geo/Nearby"
        target_service: "geo"
    - capability: "network_partition"
      target:
        namespace: "hs"
        source_app: "search"
        span_names:
          - "geo.Geo/Nearby"
        target_service: "geo"
    - capability: "dns_error"
      target:
        app: "search"
        domain_patterns:
          - "rate"
        namespace: "hs"
    - capability: "dns_random"
      target:
        app: "search"
        domain_patterns:
          - "rate"
        namespace: "hs"
    - capability: "network_delay"
      target:
        namespace: "hs"
        source_app: "search"
        span_names:
          - "rate.Rate/GetRates"
        target_service: "rate"
    - capability: "network_loss"
      target:
        namespace: "hs"
        source_app: "search"
        span_names:
          - "rate.Rate/GetRates"
        target_service: "rate"
    - capability: "network_duplicate"
      target:
        namespace: "hs"
        source_app: "search"
        span_names:
          - "rate.Rate/GetRates"
        target_service: "rate"
    - capability: "network_corrupt"
      target:
        namespace: "hs"
        source_app: "search"
        span_names:
          - "rate.Rate/GetRates"
        target_service: "rate"
    - capability: "network_bandwidth"
      target:
        namespace: "hs"
        source_app: "search"
        span_names:
          - "rate.Rate/GetRates"
        target_service: "rate"
    - capability: "network_partition"
      target:
        namespace: "hs"
        source_app: "search"
        span_names:
          - "rate.Rate/GetRates"
        target_service: "rate"
