apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: "seed-genesis"
  instance: "seed"
  service: "user"
  system: "hs"
spec:
  replace_scope: "service"
  points:
    - capability: "container_kill"
      target:
        app: "user"
        container: "user"
        namespace: "hs"
    - capability: "cpu_stress"
      target:
        app: "user"
        container: "user"
        namespace: "hs"
    - capability: "http_request_abort"
      target:
        app: "user"
        method: "POST"
        namespace: "hs"
        path: "/user.User/CheckUser"
        port: 8086
    - capability: "http_request_delay"
      target:
        app: "user"
        method: "POST"
        namespace: "hs"
        path: "/user.User/CheckUser"
        port: 8086
    - capability: "memory_stress"
      target:
        app: "user"
        container: "user"
        namespace: "hs"
    - capability: "pod_failure"
      target:
        app: "user"
        namespace: "hs"
    - capability: "pod_kill"
      target:
        app: "user"
        namespace: "hs"
    - capability: "time_skew"
      target:
        app: "user"
        container: "user"
        namespace: "hs"
