apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: "seed-genesis"
  instance: "seed"
  service: "nginx-thrift"
  system: "sn"
spec:
  replace_scope: "service"
  points:
    - capability: "container_kill"
      target:
        app: "nginx-thrift"
        container: "nginx-thrift"
        namespace: "sn"
    - capability: "cpu_stress"
      target:
        app: "nginx-thrift"
        container: "nginx-thrift"
        namespace: "sn"
    - capability: "http_request_abort"
      target:
        app: "nginx-thrift"
        method: "GET"
        namespace: "sn"
        path: "/wrk2-api/home-timeline/read"
        port: 9090
        server_address: "home-timeline-service"
        span_name: "/wrk2-api/home-timeline/read"
    - capability: "http_request_abort"
      target:
        app: "nginx-thrift"
        method: "GET"
        namespace: "sn"
        path: "/wrk2-api/user-timeline/read"
        port: 9090
        server_address: "user-timeline-service"
        span_name: "/wrk2-api/user-timeline/read"
    - capability: "http_request_abort"
      target:
        app: "nginx-thrift"
        method: "POST"
        namespace: "sn"
        path: "/wrk2-api/post/compose"
        port: 9090
        server_address: "compose-post-service"
        span_name: "/wrk2-api/post/compose"
    - capability: "http_request_abort"
      target:
        app: "nginx-thrift"
        method: "POST"
        namespace: "sn"
        path: "/wrk2-api/user/follow"
        port: 9090
        server_address: "social-graph-service"
        span_name: "/wrk2-api/user/follow"
    - capability: "http_request_abort"
      target:
        app: "nginx-thrift"
        method: "POST"
        namespace: "sn"
        path: "/wrk2-api/user/register"
        port: 9090
        server_address: "user-service"
        span_name: "/wrk2-api/user/register"
    - capability: "http_request_abort"
      target:
        app: "nginx-thrift"
        method: "POST"
        namespace: "sn"
        path: "/wrk2-api/user/unfollow"
        port: 9090
        server_address: "social-graph-service"
        span_name: "/wrk2-api/user/unfollow"
    - capability: "http_request_delay"
      target:
        app: "nginx-thrift"
        method: "GET"
        namespace: "sn"
        path: "/wrk2-api/home-timeline/read"
        port: 9090
        server_address: "home-timeline-service"
        span_name: "/wrk2-api/home-timeline/read"
    - capability: "http_request_delay"
      target:
        app: "nginx-thrift"
        method: "GET"
        namespace: "sn"
        path: "/wrk2-api/user-timeline/read"
        port: 9090
        server_address: "user-timeline-service"
        span_name: "/wrk2-api/user-timeline/read"
    - capability: "http_request_delay"
      target:
        app: "nginx-thrift"
        method: "POST"
        namespace: "sn"
        path: "/wrk2-api/post/compose"
        port: 9090
        server_address: "compose-post-service"
        span_name: "/wrk2-api/post/compose"
    - capability: "http_request_delay"
      target:
        app: "nginx-thrift"
        method: "POST"
        namespace: "sn"
        path: "/wrk2-api/user/follow"
        port: 9090
        server_address: "social-graph-service"
        span_name: "/wrk2-api/user/follow"
    - capability: "http_request_delay"
      target:
        app: "nginx-thrift"
        method: "POST"
        namespace: "sn"
        path: "/wrk2-api/user/register"
        port: 9090
        server_address: "user-service"
        span_name: "/wrk2-api/user/register"
    - capability: "http_request_delay"
      target:
        app: "nginx-thrift"
        method: "POST"
        namespace: "sn"
        path: "/wrk2-api/user/unfollow"
        port: 9090
        server_address: "social-graph-service"
        span_name: "/wrk2-api/user/unfollow"
    - capability: "memory_stress"
      target:
        app: "nginx-thrift"
        container: "nginx-thrift"
        namespace: "sn"
    - capability: "pod_failure"
      target:
        app: "nginx-thrift"
        namespace: "sn"
    - capability: "pod_kill"
      target:
        app: "nginx-thrift"
        namespace: "sn"
    - capability: "time_skew"
      target:
        app: "nginx-thrift"
        container: "nginx-thrift"
        namespace: "sn"
