apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: "observed-genesis"
  instance: "observed"
  service: "url-shorten-service"
  system: "sn"
spec:
  replace_scope: "service"
  points:
    - capability: "pod_kill"
      target:
        app: "url-shorten-service"
        namespace: "sn"
    - capability: "pod_failure"
      target:
        app: "url-shorten-service"
        namespace: "sn"
    - capability: "container_kill"
      target:
        app: "url-shorten-service"
        container: "url-shorten-service"
        namespace: "sn"
    - capability: "cpu_stress"
      target:
        app: "url-shorten-service"
        container: "url-shorten-service"
        namespace: "sn"
    - capability: "time_skew"
      target:
        app: "url-shorten-service"
        container: "url-shorten-service"
        namespace: "sn"
    - capability: "http_request_delay"
      target:
        app: "url-shorten-service"
        method: "POST"
        namespace: "sn"
        path: "/UrlShortenService/ComposeUrls"
        server_address: "url-shorten-service"
    - capability: "http_request_abort"
      target:
        app: "url-shorten-service"
        method: "POST"
        namespace: "sn"
        path: "/UrlShortenService/ComposeUrls"
        server_address: "url-shorten-service"
