apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: "seed-genesis"
  instance: "seed"
  service: "user-timeline-service"
  system: "sn"
spec:
  replace_scope: "service"
  points:
    - capability: "container_kill"
      target:
        app: "user-timeline-service"
        container: "user-timeline-service"
        namespace: "sn"
    - capability: "cpu_stress"
      target:
        app: "user-timeline-service"
        container: "user-timeline-service"
        namespace: "sn"
    - capability: "memory_stress"
      target:
        app: "user-timeline-service"
        container: "user-timeline-service"
        namespace: "sn"
    - capability: "pod_failure"
      target:
        app: "user-timeline-service"
        namespace: "sn"
    - capability: "pod_kill"
      target:
        app: "user-timeline-service"
        namespace: "sn"
    - capability: "time_skew"
      target:
        app: "user-timeline-service"
        container: "user-timeline-service"
        namespace: "sn"
