apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: "seed-genesis"
  instance: "seed"
  service: "user-service"
  system: "sn"
spec:
  replace_scope: "service"
  points:
    - capability: "container_kill"
      target:
        app: "user-service"
        container: "user-service"
        namespace: "sn"
    - capability: "cpu_stress"
      target:
        app: "user-service"
        container: "user-service"
        namespace: "sn"
    - capability: "http_request_abort"
      target:
        app: "user-service"
        method: "POST"
        namespace: "sn"
        path: "/UserService/RegisterUserWithId"
        port: 9090
        server_address: "user-service"
        span_name: "register_user_withid_server"
    - capability: "http_request_delay"
      target:
        app: "user-service"
        method: "POST"
        namespace: "sn"
        path: "/UserService/RegisterUserWithId"
        port: 9090
        server_address: "user-service"
        span_name: "register_user_withid_server"
    - capability: "memory_stress"
      target:
        app: "user-service"
        container: "user-service"
        namespace: "sn"
    - capability: "pod_failure"
      target:
        app: "user-service"
        namespace: "sn"
    - capability: "pod_kill"
      target:
        app: "user-service"
        namespace: "sn"
    - capability: "time_skew"
      target:
        app: "user-service"
        container: "user-service"
        namespace: "sn"
