apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: "seed-genesis"
  instance: "seed"
  service: "ts-admin-order-service"
  system: "ts"
spec:
  replace_scope: "service"
  points:
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-admin-order-service"
        class: "adminorder.AdminOrderApplication"
        method: "main"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-admin-order-service"
        class: "adminorder.controller.AdminOrderController"
        method: "addOrder"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-admin-order-service"
        class: "adminorder.controller.AdminOrderController"
        method: "deleteOrder"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-admin-order-service"
        class: "adminorder.controller.AdminOrderController"
        method: "getAllOrders"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-admin-order-service"
        class: "adminorder.controller.AdminOrderController"
        method: "home"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-admin-order-service"
        class: "adminorder.controller.AdminOrderController"
        method: "updateOrder"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-admin-order-service"
        class: "adminorder.service.AdminOrderServiceImpl"
        method: "addOrder"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-admin-order-service"
        class: "adminorder.service.AdminOrderServiceImpl"
        method: "deleteOrder"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-admin-order-service"
        class: "adminorder.service.AdminOrderServiceImpl"
        method: "getAllOrders"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-admin-order-service"
        class: "adminorder.service.AdminOrderServiceImpl"
        method: "getServiceUrl"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-admin-order-service"
        class: "adminorder.service.AdminOrderServiceImpl"
        method: "updateOrder"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-admin-order-service"
        class: "adminorder.AdminOrderApplication"
        method: "main"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-admin-order-service"
        class: "adminorder.controller.AdminOrderController"
        method: "addOrder"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-admin-order-service"
        class: "adminorder.controller.AdminOrderController"
        method: "deleteOrder"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-admin-order-service"
        class: "adminorder.controller.AdminOrderController"
        method: "getAllOrders"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-admin-order-service"
        class: "adminorder.controller.AdminOrderController"
        method: "home"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-admin-order-service"
        class: "adminorder.controller.AdminOrderController"
        method: "updateOrder"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-admin-order-service"
        class: "adminorder.service.AdminOrderServiceImpl"
        method: "addOrder"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-admin-order-service"
        class: "adminorder.service.AdminOrderServiceImpl"
        method: "deleteOrder"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-admin-order-service"
        class: "adminorder.service.AdminOrderServiceImpl"
        method: "getAllOrders"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-admin-order-service"
        class: "adminorder.service.AdminOrderServiceImpl"
        method: "getServiceUrl"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-admin-order-service"
        class: "adminorder.service.AdminOrderServiceImpl"
        method: "updateOrder"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-admin-order-service"
        class: "adminorder.AdminOrderApplication"
        method: "main"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-admin-order-service"
        class: "adminorder.controller.AdminOrderController"
        method: "addOrder"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-admin-order-service"
        class: "adminorder.controller.AdminOrderController"
        method: "deleteOrder"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-admin-order-service"
        class: "adminorder.controller.AdminOrderController"
        method: "getAllOrders"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-admin-order-service"
        class: "adminorder.controller.AdminOrderController"
        method: "home"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-admin-order-service"
        class: "adminorder.controller.AdminOrderController"
        method: "updateOrder"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-admin-order-service"
        class: "adminorder.service.AdminOrderServiceImpl"
        method: "addOrder"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-admin-order-service"
        class: "adminorder.service.AdminOrderServiceImpl"
        method: "deleteOrder"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-admin-order-service"
        class: "adminorder.service.AdminOrderServiceImpl"
        method: "getAllOrders"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-admin-order-service"
        class: "adminorder.service.AdminOrderServiceImpl"
        method: "getServiceUrl"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-admin-order-service"
        class: "adminorder.service.AdminOrderServiceImpl"
        method: "updateOrder"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-admin-order-service"
        class: "adminorder.AdminOrderApplication"
        method: "main"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-admin-order-service"
        class: "adminorder.controller.AdminOrderController"
        method: "addOrder"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-admin-order-service"
        class: "adminorder.controller.AdminOrderController"
        method: "deleteOrder"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-admin-order-service"
        class: "adminorder.controller.AdminOrderController"
        method: "getAllOrders"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-admin-order-service"
        class: "adminorder.controller.AdminOrderController"
        method: "home"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-admin-order-service"
        class: "adminorder.controller.AdminOrderController"
        method: "updateOrder"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-admin-order-service"
        class: "adminorder.service.AdminOrderServiceImpl"
        method: "addOrder"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-admin-order-service"
        class: "adminorder.service.AdminOrderServiceImpl"
        method: "deleteOrder"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-admin-order-service"
        class: "adminorder.service.AdminOrderServiceImpl"
        method: "getAllOrders"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-admin-order-service"
        class: "adminorder.service.AdminOrderServiceImpl"
        method: "getServiceUrl"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-admin-order-service"
        class: "adminorder.service.AdminOrderServiceImpl"
        method: "updateOrder"
        namespace: "ts"
