apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: "seed-genesis"
  instance: "seed"
  service: "ts-assurance-service"
  system: "ts"
spec:
  replace_scope: "service"
  points:
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-assurance-service"
        class: "assurance.AssuranceApplication"
        method: "main"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-assurance-service"
        class: "assurance.controller.AssuranceController"
        method: "createNewAssurance"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-assurance-service"
        class: "assurance.controller.AssuranceController"
        method: "deleteAssurance"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-assurance-service"
        class: "assurance.controller.AssuranceController"
        method: "deleteAssuranceByOrderId"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-assurance-service"
        class: "assurance.controller.AssuranceController"
        method: "findAssuranceByOrderId"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-assurance-service"
        class: "assurance.controller.AssuranceController"
        method: "getAllAssuranceType"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-assurance-service"
        class: "assurance.controller.AssuranceController"
        method: "getAllAssurances"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-assurance-service"
        class: "assurance.controller.AssuranceController"
        method: "getAssuranceById"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-assurance-service"
        class: "assurance.controller.AssuranceController"
        method: "home"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-assurance-service"
        class: "assurance.controller.AssuranceController"
        method: "modifyAssurance"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-assurance-service"
        class: "assurance.entity.Assurance"
        method: "Assurance"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-assurance-service"
        class: "assurance.entity.PlainAssurance"
        method: "PlainAssurance"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-assurance-service"
        class: "assurance.init.InitData"
        method: "run"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-assurance-service"
        class: "assurance.service.AssuranceServiceImpl"
        method: "create"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-assurance-service"
        class: "assurance.service.AssuranceServiceImpl"
        method: "deleteById"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-assurance-service"
        class: "assurance.service.AssuranceServiceImpl"
        method: "deleteByOrderId"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-assurance-service"
        class: "assurance.service.AssuranceServiceImpl"
        method: "findAssuranceById"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-assurance-service"
        class: "assurance.service.AssuranceServiceImpl"
        method: "findAssuranceByOrderId"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-assurance-service"
        class: "assurance.service.AssuranceServiceImpl"
        method: "getAllAssuranceTypes"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-assurance-service"
        class: "assurance.service.AssuranceServiceImpl"
        method: "getAllAssurances"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-assurance-service"
        class: "assurance.service.AssuranceServiceImpl"
        method: "modify"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-assurance-service"
        class: "assurance.AssuranceApplication"
        method: "main"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-assurance-service"
        class: "assurance.controller.AssuranceController"
        method: "createNewAssurance"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-assurance-service"
        class: "assurance.controller.AssuranceController"
        method: "deleteAssurance"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-assurance-service"
        class: "assurance.controller.AssuranceController"
        method: "deleteAssuranceByOrderId"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-assurance-service"
        class: "assurance.controller.AssuranceController"
        method: "findAssuranceByOrderId"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-assurance-service"
        class: "assurance.controller.AssuranceController"
        method: "getAllAssuranceType"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-assurance-service"
        class: "assurance.controller.AssuranceController"
        method: "getAllAssurances"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-assurance-service"
        class: "assurance.controller.AssuranceController"
        method: "getAssuranceById"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-assurance-service"
        class: "assurance.controller.AssuranceController"
        method: "home"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-assurance-service"
        class: "assurance.controller.AssuranceController"
        method: "modifyAssurance"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-assurance-service"
        class: "assurance.entity.Assurance"
        method: "Assurance"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-assurance-service"
        class: "assurance.entity.PlainAssurance"
        method: "PlainAssurance"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-assurance-service"
        class: "assurance.init.InitData"
        method: "run"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-assurance-service"
        class: "assurance.service.AssuranceServiceImpl"
        method: "create"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-assurance-service"
        class: "assurance.service.AssuranceServiceImpl"
        method: "deleteById"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-assurance-service"
        class: "assurance.service.AssuranceServiceImpl"
        method: "deleteByOrderId"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-assurance-service"
        class: "assurance.service.AssuranceServiceImpl"
        method: "findAssuranceById"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-assurance-service"
        class: "assurance.service.AssuranceServiceImpl"
        method: "findAssuranceByOrderId"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-assurance-service"
        class: "assurance.service.AssuranceServiceImpl"
        method: "getAllAssuranceTypes"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-assurance-service"
        class: "assurance.service.AssuranceServiceImpl"
        method: "getAllAssurances"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-assurance-service"
        class: "assurance.service.AssuranceServiceImpl"
        method: "modify"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-assurance-service"
        class: "assurance.AssuranceApplication"
        method: "main"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-assurance-service"
        class: "assurance.controller.AssuranceController"
        method: "createNewAssurance"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-assurance-service"
        class: "assurance.controller.AssuranceController"
        method: "deleteAssurance"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-assurance-service"
        class: "assurance.controller.AssuranceController"
        method: "deleteAssuranceByOrderId"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-assurance-service"
        class: "assurance.controller.AssuranceController"
        method: "findAssuranceByOrderId"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-assurance-service"
        class: "assurance.controller.AssuranceController"
        method: "getAllAssuranceType"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-assurance-service"
        class: "assurance.controller.AssuranceController"
        method: "getAllAssurances"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-assurance-service"
        class: "assurance.controller.AssuranceController"
        method: "getAssuranceById"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-assurance-service"
        class: "assurance.controller.AssuranceController"
        method: "home"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-assurance-service"
        class: "assurance.controller.AssuranceController"
        method: "modifyAssurance"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-assurance-service"
        class: "assurance.entity.Assurance"
        method: "Assurance"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-assurance-service"
        class: "assurance.entity.PlainAssurance"
        method: "PlainAssurance"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-assurance-service"
        class: "assurance.init.InitData"
        method: "run"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-assurance-service"
        class: "assurance.service.AssuranceServiceImpl"
        method: "create"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-assurance-service"
        class: "assurance.service.AssuranceServiceImpl"
        method: "deleteById"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-assurance-service"
        class: "assurance.service.AssuranceServiceImpl"
        method: "deleteByOrderId"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-assurance-service"
        class: "assurance.service.AssuranceServiceImpl"
        method: "findAssuranceById"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-assurance-service"
        class: "assurance.service.AssuranceServiceImpl"
        method: "findAssuranceByOrderId"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-assurance-service"
        class: "assurance.service.AssuranceServiceImpl"
        method: "getAllAssuranceTypes"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-assurance-service"
        class: "assurance.service.AssuranceServiceImpl"
        method: "getAllAssurances"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-assurance-service"
        class: "assurance.service.AssuranceServiceImpl"
        method: "modify"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-assurance-service"
        class: "assurance.AssuranceApplication"
        method: "main"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-assurance-service"
        class: "assurance.controller.AssuranceController"
        method: "createNewAssurance"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-assurance-service"
        class: "assurance.controller.AssuranceController"
        method: "deleteAssurance"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-assurance-service"
        class: "assurance.controller.AssuranceController"
        method: "deleteAssuranceByOrderId"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-assurance-service"
        class: "assurance.controller.AssuranceController"
        method: "findAssuranceByOrderId"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-assurance-service"
        class: "assurance.controller.AssuranceController"
        method: "getAllAssuranceType"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-assurance-service"
        class: "assurance.controller.AssuranceController"
        method: "getAllAssurances"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-assurance-service"
        class: "assurance.controller.AssuranceController"
        method: "getAssuranceById"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-assurance-service"
        class: "assurance.controller.AssuranceController"
        method: "home"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-assurance-service"
        class: "assurance.controller.AssuranceController"
        method: "modifyAssurance"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-assurance-service"
        class: "assurance.entity.Assurance"
        method: "Assurance"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-assurance-service"
        class: "assurance.entity.PlainAssurance"
        method: "PlainAssurance"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-assurance-service"
        class: "assurance.init.InitData"
        method: "run"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-assurance-service"
        class: "assurance.service.AssuranceServiceImpl"
        method: "create"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-assurance-service"
        class: "assurance.service.AssuranceServiceImpl"
        method: "deleteById"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-assurance-service"
        class: "assurance.service.AssuranceServiceImpl"
        method: "deleteByOrderId"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-assurance-service"
        class: "assurance.service.AssuranceServiceImpl"
        method: "findAssuranceById"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-assurance-service"
        class: "assurance.service.AssuranceServiceImpl"
        method: "findAssuranceByOrderId"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-assurance-service"
        class: "assurance.service.AssuranceServiceImpl"
        method: "getAllAssuranceTypes"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-assurance-service"
        class: "assurance.service.AssuranceServiceImpl"
        method: "getAllAssurances"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-assurance-service"
        class: "assurance.service.AssuranceServiceImpl"
        method: "modify"
        namespace: "ts"
