apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: "seed-genesis"
  instance: "seed"
  service: "ts-admin-travel-service"
  system: "ts"
spec:
  replace_scope: "service"
  points:
    - capability: "network_bandwidth"
      target:
        namespace: "ts"
        source_app: "ts-admin-travel-service"
        span_names:
          - "GET"
        target_service: "ts-route-service"
    - capability: "network_bandwidth"
      target:
        namespace: "ts"
        source_app: "ts-admin-travel-service"
        span_names:
          - "GET"
        target_service: "ts-train-service"
    - capability: "network_bandwidth"
      target:
        namespace: "ts"
        source_app: "ts-admin-travel-service"
        span_names:
          - "GET"
        target_service: "ts-travel-service"
    - capability: "network_bandwidth"
      target:
        namespace: "ts"
        source_app: "ts-admin-travel-service"
        span_names:
          - "GET"
        target_service: "ts-travel2-service"
    - capability: "network_bandwidth"
      target:
        namespace: "ts"
        source_app: "ts-admin-travel-service"
        span_names:
          - "POST"
        target_service: "ts-station-service"
    - capability: "network_corrupt"
      target:
        namespace: "ts"
        source_app: "ts-admin-travel-service"
        span_names:
          - "GET"
        target_service: "ts-route-service"
    - capability: "network_corrupt"
      target:
        namespace: "ts"
        source_app: "ts-admin-travel-service"
        span_names:
          - "GET"
        target_service: "ts-train-service"
    - capability: "network_corrupt"
      target:
        namespace: "ts"
        source_app: "ts-admin-travel-service"
        span_names:
          - "GET"
        target_service: "ts-travel-service"
    - capability: "network_corrupt"
      target:
        namespace: "ts"
        source_app: "ts-admin-travel-service"
        span_names:
          - "GET"
        target_service: "ts-travel2-service"
    - capability: "network_corrupt"
      target:
        namespace: "ts"
        source_app: "ts-admin-travel-service"
        span_names:
          - "POST"
        target_service: "ts-station-service"
    - capability: "network_delay"
      target:
        namespace: "ts"
        source_app: "ts-admin-travel-service"
        span_names:
          - "GET"
        target_service: "ts-route-service"
    - capability: "network_delay"
      target:
        namespace: "ts"
        source_app: "ts-admin-travel-service"
        span_names:
          - "GET"
        target_service: "ts-train-service"
    - capability: "network_delay"
      target:
        namespace: "ts"
        source_app: "ts-admin-travel-service"
        span_names:
          - "GET"
        target_service: "ts-travel-service"
    - capability: "network_delay"
      target:
        namespace: "ts"
        source_app: "ts-admin-travel-service"
        span_names:
          - "GET"
        target_service: "ts-travel2-service"
    - capability: "network_delay"
      target:
        namespace: "ts"
        source_app: "ts-admin-travel-service"
        span_names:
          - "POST"
        target_service: "ts-station-service"
    - capability: "network_duplicate"
      target:
        namespace: "ts"
        source_app: "ts-admin-travel-service"
        span_names:
          - "GET"
        target_service: "ts-route-service"
    - capability: "network_duplicate"
      target:
        namespace: "ts"
        source_app: "ts-admin-travel-service"
        span_names:
          - "GET"
        target_service: "ts-train-service"
    - capability: "network_duplicate"
      target:
        namespace: "ts"
        source_app: "ts-admin-travel-service"
        span_names:
          - "GET"
        target_service: "ts-travel-service"
    - capability: "network_duplicate"
      target:
        namespace: "ts"
        source_app: "ts-admin-travel-service"
        span_names:
          - "GET"
        target_service: "ts-travel2-service"
    - capability: "network_duplicate"
      target:
        namespace: "ts"
        source_app: "ts-admin-travel-service"
        span_names:
          - "POST"
        target_service: "ts-station-service"
    - capability: "network_loss"
      target:
        namespace: "ts"
        source_app: "ts-admin-travel-service"
        span_names:
          - "GET"
        target_service: "ts-route-service"
    - capability: "network_loss"
      target:
        namespace: "ts"
        source_app: "ts-admin-travel-service"
        span_names:
          - "GET"
        target_service: "ts-train-service"
    - capability: "network_loss"
      target:
        namespace: "ts"
        source_app: "ts-admin-travel-service"
        span_names:
          - "GET"
        target_service: "ts-travel-service"
    - capability: "network_loss"
      target:
        namespace: "ts"
        source_app: "ts-admin-travel-service"
        span_names:
          - "GET"
        target_service: "ts-travel2-service"
    - capability: "network_loss"
      target:
        namespace: "ts"
        source_app: "ts-admin-travel-service"
        span_names:
          - "POST"
        target_service: "ts-station-service"
    - capability: "network_partition"
      target:
        namespace: "ts"
        source_app: "ts-admin-travel-service"
        span_names:
          - "GET"
        target_service: "ts-route-service"
    - capability: "network_partition"
      target:
        namespace: "ts"
        source_app: "ts-admin-travel-service"
        span_names:
          - "GET"
        target_service: "ts-train-service"
    - capability: "network_partition"
      target:
        namespace: "ts"
        source_app: "ts-admin-travel-service"
        span_names:
          - "GET"
        target_service: "ts-travel-service"
    - capability: "network_partition"
      target:
        namespace: "ts"
        source_app: "ts-admin-travel-service"
        span_names:
          - "GET"
        target_service: "ts-travel2-service"
    - capability: "network_partition"
      target:
        namespace: "ts"
        source_app: "ts-admin-travel-service"
        span_names:
          - "POST"
        target_service: "ts-station-service"
