apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: "seed-genesis"
  instance: "seed"
  service: "ts-auth-service"
  system: "ts"
spec:
  replace_scope: "service"
  points:
    - capability: "dns_error"
      target:
        app: "ts-auth-service"
        domain_patterns:
          - "mysql"
        namespace: "ts"
    - capability: "dns_error"
      target:
        app: "ts-auth-service"
        domain_patterns:
          - "ts-verification-code-service"
        namespace: "ts"
    - capability: "dns_random"
      target:
        app: "ts-auth-service"
        domain_patterns:
          - "mysql"
        namespace: "ts"
    - capability: "dns_random"
      target:
        app: "ts-auth-service"
        domain_patterns:
          - "ts-verification-code-service"
        namespace: "ts"
