apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: "seed-genesis"
  instance: "seed"
  service: "ts-admin-user-service"
  system: "ts"
spec:
  replace_scope: "service"
  points:
    - capability: "container_kill"
      target:
        app: "ts-admin-user-service"
        container: "ts-admin-user-service"
        namespace: "ts"
    - capability: "cpu_stress"
      target:
        app: "ts-admin-user-service"
        container: "ts-admin-user-service"
        namespace: "ts"
    - capability: "http_request_abort"
      target:
        app: "ts-admin-user-service"
        method: "DELETE"
        namespace: "ts"
        path: "/api/v1/userservice/users/*"
        port: 8080
        server_address: "ts-user-service"
        span_name: "DELETE"
    - capability: "http_request_abort"
      target:
        app: "ts-admin-user-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/userservice/users"
        port: 8080
        server_address: "ts-user-service"
        span_name: "GET"
    - capability: "http_request_abort"
      target:
        app: "ts-admin-user-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/userservice/users/register"
        port: 8080
        server_address: "ts-user-service"
        span_name: "POST"
    - capability: "http_request_abort"
      target:
        app: "ts-admin-user-service"
        method: "PUT"
        namespace: "ts"
        path: "/api/v1/userservice/users"
        port: 8080
        server_address: "ts-user-service"
        span_name: "PUT"
    - capability: "http_request_delay"
      target:
        app: "ts-admin-user-service"
        method: "DELETE"
        namespace: "ts"
        path: "/api/v1/userservice/users/*"
        port: 8080
        server_address: "ts-user-service"
        span_name: "DELETE"
    - capability: "http_request_delay"
      target:
        app: "ts-admin-user-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/userservice/users"
        port: 8080
        server_address: "ts-user-service"
        span_name: "GET"
    - capability: "http_request_delay"
      target:
        app: "ts-admin-user-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/userservice/users/register"
        port: 8080
        server_address: "ts-user-service"
        span_name: "POST"
    - capability: "http_request_delay"
      target:
        app: "ts-admin-user-service"
        method: "PUT"
        namespace: "ts"
        path: "/api/v1/userservice/users"
        port: 8080
        server_address: "ts-user-service"
        span_name: "PUT"
    - capability: "jvm_method_latency"
      target:
        app: "ts-admin-user-service"
        class: "adminuser.AdminUserApplication"
        method: "main"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-admin-user-service"
        class: "adminuser.controller.AdminUserController"
        method: "addUser"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-admin-user-service"
        class: "adminuser.controller.AdminUserController"
        method: "deleteUser"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-admin-user-service"
        class: "adminuser.controller.AdminUserController"
        method: "getAllUsers"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-admin-user-service"
        class: "adminuser.controller.AdminUserController"
        method: "home"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-admin-user-service"
        class: "adminuser.controller.AdminUserController"
        method: "updateUser"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-admin-user-service"
        class: "adminuser.service.AdminUserServiceImpl"
        method: "addUser"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-admin-user-service"
        class: "adminuser.service.AdminUserServiceImpl"
        method: "deleteUser"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-admin-user-service"
        class: "adminuser.service.AdminUserServiceImpl"
        method: "getAllUsers"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-admin-user-service"
        class: "adminuser.service.AdminUserServiceImpl"
        method: "getServiceUrl"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-admin-user-service"
        class: "adminuser.service.AdminUserServiceImpl"
        method: "updateUser"
        namespace: "ts"
    - capability: "memory_stress"
      target:
        app: "ts-admin-user-service"
        container: "ts-admin-user-service"
        namespace: "ts"
    - capability: "pod_failure"
      target:
        app: "ts-admin-user-service"
        namespace: "ts"
    - capability: "pod_kill"
      target:
        app: "ts-admin-user-service"
        namespace: "ts"
    - capability: "time_skew"
      target:
        app: "ts-admin-user-service"
        container: "ts-admin-user-service"
        namespace: "ts"
