apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: "seed-genesis"
  instance: "seed"
  service: "ts-basic-service"
  system: "ts"
spec:
  replace_scope: "service"
  points:
    - capability: "container_kill"
      target:
        app: "ts-basic-service"
        container: "ts-basic-service"
        namespace: "ts"
    - capability: "cpu_stress"
      target:
        app: "ts-basic-service"
        container: "ts-basic-service"
        namespace: "ts"
    - capability: "http_request_abort"
      target:
        app: "ts-basic-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/priceservice/prices/*/DongCheOne"
        port: 8080
    - capability: "http_request_abort"
      target:
        app: "ts-basic-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/priceservice/prices/*/GaoTieOne"
        port: 8080
    - capability: "http_request_abort"
      target:
        app: "ts-basic-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/priceservice/prices/*/GaoTieTwo"
        port: 8080
    - capability: "http_request_abort"
      target:
        app: "ts-basic-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/priceservice/prices/*/KuaiSu"
        port: 8080
    - capability: "http_request_abort"
      target:
        app: "ts-basic-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/priceservice/prices/*/TeKuai"
        port: 8080
    - capability: "http_request_abort"
      target:
        app: "ts-basic-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/priceservice/prices/*/ZhiDa"
        port: 8080
    - capability: "http_request_abort"
      target:
        app: "ts-basic-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/routeservice/routes/*"
        port: 8080
    - capability: "http_request_abort"
      target:
        app: "ts-basic-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/stationservice/stations/id/*"
        port: 8080
    - capability: "http_request_abort"
      target:
        app: "ts-basic-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/trainservice/trains/byName/*"
        port: 8080
    - capability: "http_request_abort"
      target:
        app: "ts-basic-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/priceservice/prices/byRouteIdsAndTrainTypes"
        port: 8080
    - capability: "http_request_abort"
      target:
        app: "ts-basic-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/routeservice/routes/*"
        port: 8080
    - capability: "http_request_abort"
      target:
        app: "ts-basic-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/routeservice/routes/byIds/"
        port: 8080
    - capability: "http_request_abort"
      target:
        app: "ts-basic-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/stationservice/stations/idlist"
        port: 8080
    - capability: "http_request_abort"
      target:
        app: "ts-basic-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/trainservice/trains/byNames"
        port: 8080
    - capability: "http_request_delay"
      target:
        app: "ts-basic-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/priceservice/prices/*/DongCheOne"
        port: 8080
    - capability: "http_request_delay"
      target:
        app: "ts-basic-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/priceservice/prices/*/GaoTieOne"
        port: 8080
    - capability: "http_request_delay"
      target:
        app: "ts-basic-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/priceservice/prices/*/GaoTieTwo"
        port: 8080
    - capability: "http_request_delay"
      target:
        app: "ts-basic-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/priceservice/prices/*/KuaiSu"
        port: 8080
    - capability: "http_request_delay"
      target:
        app: "ts-basic-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/priceservice/prices/*/TeKuai"
        port: 8080
    - capability: "http_request_delay"
      target:
        app: "ts-basic-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/priceservice/prices/*/ZhiDa"
        port: 8080
    - capability: "http_request_delay"
      target:
        app: "ts-basic-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/routeservice/routes/*"
        port: 8080
    - capability: "http_request_delay"
      target:
        app: "ts-basic-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/stationservice/stations/id/*"
        port: 8080
    - capability: "http_request_delay"
      target:
        app: "ts-basic-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/trainservice/trains/byName/*"
        port: 8080
    - capability: "http_request_delay"
      target:
        app: "ts-basic-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/priceservice/prices/byRouteIdsAndTrainTypes"
        port: 8080
    - capability: "http_request_delay"
      target:
        app: "ts-basic-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/routeservice/routes/*"
        port: 8080
    - capability: "http_request_delay"
      target:
        app: "ts-basic-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/routeservice/routes/byIds/"
        port: 8080
    - capability: "http_request_delay"
      target:
        app: "ts-basic-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/stationservice/stations/idlist"
        port: 8080
    - capability: "http_request_delay"
      target:
        app: "ts-basic-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/trainservice/trains/byNames"
        port: 8080
    - capability: "jvm_method_latency"
      target:
        app: "ts-basic-service"
        class: "fdse.microservice.BasicApplication"
        method: "main"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-basic-service"
        class: "fdse.microservice.controller.BasicController"
        method: "home"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-basic-service"
        class: "fdse.microservice.controller.BasicController"
        method: "queryForStationId"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-basic-service"
        class: "fdse.microservice.controller.BasicController"
        method: "queryForTravel"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-basic-service"
        class: "fdse.microservice.controller.BasicController"
        method: "queryForTravels"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-basic-service"
        class: "fdse.microservice.service.BasicServiceImpl"
        method: "checkStationExists"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-basic-service"
        class: "fdse.microservice.service.BasicServiceImpl"
        method: "checkStationsExists"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-basic-service"
        class: "fdse.microservice.service.BasicServiceImpl"
        method: "getRouteByRouteId"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-basic-service"
        class: "fdse.microservice.service.BasicServiceImpl"
        method: "getRoutesByRouteIds"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-basic-service"
        class: "fdse.microservice.service.BasicServiceImpl"
        method: "getServiceUrl"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-basic-service"
        class: "fdse.microservice.service.BasicServiceImpl"
        method: "queryForStationId"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-basic-service"
        class: "fdse.microservice.service.BasicServiceImpl"
        method: "queryForTravel"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-basic-service"
        class: "fdse.microservice.service.BasicServiceImpl"
        method: "queryForTravels"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-basic-service"
        class: "fdse.microservice.service.BasicServiceImpl"
        method: "queryPriceConfigByRouteIdAndTrainType"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-basic-service"
        class: "fdse.microservice.service.BasicServiceImpl"
        method: "queryPriceConfigByRouteIdsAndTrainTypes"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-basic-service"
        class: "fdse.microservice.service.BasicServiceImpl"
        method: "queryTrainTypeByName"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-basic-service"
        class: "fdse.microservice.service.BasicServiceImpl"
        method: "queryTrainTypeByNames"
        namespace: "ts"
    - capability: "memory_stress"
      target:
        app: "ts-basic-service"
        container: "ts-basic-service"
        namespace: "ts"
    - capability: "pod_failure"
      target:
        app: "ts-basic-service"
        namespace: "ts"
    - capability: "pod_kill"
      target:
        app: "ts-basic-service"
        namespace: "ts"
    - capability: "time_skew"
      target:
        app: "ts-basic-service"
        container: "ts-basic-service"
        namespace: "ts"
