apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: "observed-genesis"
  instance: "observed"
  service: "ts-basic-service"
  system: "ts"
spec:
  replace_scope: "service"
  points:
    - capability: "pod_kill"
      target:
        app: "ts-basic-service"
        namespace: "ts"
    - capability: "pod_failure"
      target:
        app: "ts-basic-service"
        namespace: "ts"
    - capability: "container_kill"
      target:
        app: "ts-basic-service"
        container: "ts-basic-service"
        namespace: "ts"
    - capability: "cpu_stress"
      target:
        app: "ts-basic-service"
        container: "ts-basic-service"
        namespace: "ts"
    - capability: "time_skew"
      target:
        app: "ts-basic-service"
        container: "ts-basic-service"
        namespace: "ts"
    - capability: "http_request_delay"
      target:
        app: "ts-basic-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/basicservice/basic/travels"
        port: 8080
        server_address: "ts-basic-service"
        span_name: "POST /api/v1/basicservice/basic/travels"
    - capability: "http_request_abort"
      target:
        app: "ts-basic-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/basicservice/basic/travels"
        port: 8080
        server_address: "ts-basic-service"
        span_name: "POST /api/v1/basicservice/basic/travels"
    - capability: "http_response_abort"
      target:
        app: "ts-basic-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/basicservice/basic/travels"
        port: 8080
    - capability: "http_response_delay"
      target:
        app: "ts-basic-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/basicservice/basic/travels"
        port: 8080
    - capability: "http_response_replace_code"
      target:
        app: "ts-basic-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/basicservice/basic/travels"
        port: 8080
    - capability: "http_response_patch_body"
      target:
        app: "ts-basic-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/basicservice/basic/travels"
        port: 8080
    - capability: "http_response_replace_body"
      target:
        app: "ts-basic-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/basicservice/basic/travels"
        port: 8080
    - capability: "http_request_replace_method"
      target:
        app: "ts-basic-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/basicservice/basic/travels"
        port: 8080
    - capability: "http_request_replace_path"
      target:
        app: "ts-basic-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/basicservice/basic/travels"
        port: 8080
    - capability: "http_request_delay"
      target:
        app: "ts-basic-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/basicservice/basic/travel"
        port: 8080
        server_address: "ts-basic-service"
        span_name: "POST /api/v1/basicservice/basic/travel"
    - capability: "http_request_abort"
      target:
        app: "ts-basic-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/basicservice/basic/travel"
        port: 8080
        server_address: "ts-basic-service"
        span_name: "POST /api/v1/basicservice/basic/travel"
    - capability: "http_response_abort"
      target:
        app: "ts-basic-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/basicservice/basic/travel"
        port: 8080
    - capability: "http_response_delay"
      target:
        app: "ts-basic-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/basicservice/basic/travel"
        port: 8080
    - capability: "http_response_replace_code"
      target:
        app: "ts-basic-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/basicservice/basic/travel"
        port: 8080
    - capability: "http_response_patch_body"
      target:
        app: "ts-basic-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/basicservice/basic/travel"
        port: 8080
    - capability: "http_response_replace_body"
      target:
        app: "ts-basic-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/basicservice/basic/travel"
        port: 8080
    - capability: "http_request_replace_method"
      target:
        app: "ts-basic-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/basicservice/basic/travel"
        port: 8080
    - capability: "http_request_replace_path"
      target:
        app: "ts-basic-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/basicservice/basic/travel"
        port: 8080
    - capability: "dns_error"
      target:
        app: "ts-basic-service"
        domain_patterns:
          - "ts-station-service"
        namespace: "ts"
    - capability: "dns_random"
      target:
        app: "ts-basic-service"
        domain_patterns:
          - "ts-station-service"
        namespace: "ts"
    - capability: "network_delay"
      target:
        namespace: "ts"
        source_app: "ts-basic-service"
        span_names:
          - "GET /api/v1/stationservice/stations/id/{stationNameForId}"
          - "POST /api/v1/stationservice/stations/idlist"
        target_service: "ts-station-service"
    - capability: "network_loss"
      target:
        namespace: "ts"
        source_app: "ts-basic-service"
        span_names:
          - "GET /api/v1/stationservice/stations/id/{stationNameForId}"
          - "POST /api/v1/stationservice/stations/idlist"
        target_service: "ts-station-service"
    - capability: "network_duplicate"
      target:
        namespace: "ts"
        source_app: "ts-basic-service"
        span_names:
          - "GET /api/v1/stationservice/stations/id/{stationNameForId}"
          - "POST /api/v1/stationservice/stations/idlist"
        target_service: "ts-station-service"
    - capability: "network_corrupt"
      target:
        namespace: "ts"
        source_app: "ts-basic-service"
        span_names:
          - "GET /api/v1/stationservice/stations/id/{stationNameForId}"
          - "POST /api/v1/stationservice/stations/idlist"
        target_service: "ts-station-service"
    - capability: "network_bandwidth"
      target:
        namespace: "ts"
        source_app: "ts-basic-service"
        span_names:
          - "GET /api/v1/stationservice/stations/id/{stationNameForId}"
          - "POST /api/v1/stationservice/stations/idlist"
        target_service: "ts-station-service"
    - capability: "network_partition"
      target:
        namespace: "ts"
        source_app: "ts-basic-service"
        span_names:
          - "GET /api/v1/stationservice/stations/id/{stationNameForId}"
          - "POST /api/v1/stationservice/stations/idlist"
        target_service: "ts-station-service"
    - capability: "dns_error"
      target:
        app: "ts-basic-service"
        domain_patterns:
          - "ts-route-service"
        namespace: "ts"
    - capability: "dns_random"
      target:
        app: "ts-basic-service"
        domain_patterns:
          - "ts-route-service"
        namespace: "ts"
    - capability: "network_delay"
      target:
        namespace: "ts"
        source_app: "ts-basic-service"
        span_names:
          - "GET /api/v1/routeservice/routes/{routeId}"
          - "POST /api/v1/routeservice/routes/byIds"
        target_service: "ts-route-service"
    - capability: "network_loss"
      target:
        namespace: "ts"
        source_app: "ts-basic-service"
        span_names:
          - "GET /api/v1/routeservice/routes/{routeId}"
          - "POST /api/v1/routeservice/routes/byIds"
        target_service: "ts-route-service"
    - capability: "network_duplicate"
      target:
        namespace: "ts"
        source_app: "ts-basic-service"
        span_names:
          - "GET /api/v1/routeservice/routes/{routeId}"
          - "POST /api/v1/routeservice/routes/byIds"
        target_service: "ts-route-service"
    - capability: "network_corrupt"
      target:
        namespace: "ts"
        source_app: "ts-basic-service"
        span_names:
          - "GET /api/v1/routeservice/routes/{routeId}"
          - "POST /api/v1/routeservice/routes/byIds"
        target_service: "ts-route-service"
    - capability: "network_bandwidth"
      target:
        namespace: "ts"
        source_app: "ts-basic-service"
        span_names:
          - "GET /api/v1/routeservice/routes/{routeId}"
          - "POST /api/v1/routeservice/routes/byIds"
        target_service: "ts-route-service"
    - capability: "network_partition"
      target:
        namespace: "ts"
        source_app: "ts-basic-service"
        span_names:
          - "GET /api/v1/routeservice/routes/{routeId}"
          - "POST /api/v1/routeservice/routes/byIds"
        target_service: "ts-route-service"
    - capability: "dns_error"
      target:
        app: "ts-basic-service"
        domain_patterns:
          - "ts-train-service"
        namespace: "ts"
    - capability: "dns_random"
      target:
        app: "ts-basic-service"
        domain_patterns:
          - "ts-train-service"
        namespace: "ts"
    - capability: "network_delay"
      target:
        namespace: "ts"
        source_app: "ts-basic-service"
        span_names:
          - "GET /api/v1/trainservice/trains/byName/{name}"
          - "POST /api/v1/trainservice/trains/byNames"
        target_service: "ts-train-service"
    - capability: "network_loss"
      target:
        namespace: "ts"
        source_app: "ts-basic-service"
        span_names:
          - "GET /api/v1/trainservice/trains/byName/{name}"
          - "POST /api/v1/trainservice/trains/byNames"
        target_service: "ts-train-service"
    - capability: "network_duplicate"
      target:
        namespace: "ts"
        source_app: "ts-basic-service"
        span_names:
          - "GET /api/v1/trainservice/trains/byName/{name}"
          - "POST /api/v1/trainservice/trains/byNames"
        target_service: "ts-train-service"
    - capability: "network_corrupt"
      target:
        namespace: "ts"
        source_app: "ts-basic-service"
        span_names:
          - "GET /api/v1/trainservice/trains/byName/{name}"
          - "POST /api/v1/trainservice/trains/byNames"
        target_service: "ts-train-service"
    - capability: "network_bandwidth"
      target:
        namespace: "ts"
        source_app: "ts-basic-service"
        span_names:
          - "GET /api/v1/trainservice/trains/byName/{name}"
          - "POST /api/v1/trainservice/trains/byNames"
        target_service: "ts-train-service"
    - capability: "network_partition"
      target:
        namespace: "ts"
        source_app: "ts-basic-service"
        span_names:
          - "GET /api/v1/trainservice/trains/byName/{name}"
          - "POST /api/v1/trainservice/trains/byNames"
        target_service: "ts-train-service"
    - capability: "dns_error"
      target:
        app: "ts-basic-service"
        domain_patterns:
          - "ts-price-service"
        namespace: "ts"
    - capability: "dns_random"
      target:
        app: "ts-basic-service"
        domain_patterns:
          - "ts-price-service"
        namespace: "ts"
    - capability: "network_delay"
      target:
        namespace: "ts"
        source_app: "ts-basic-service"
        span_names:
          - "GET /api/v1/priceservice/prices/{routeId}/{trainType}"
          - "POST /api/v1/priceservice/prices/byRouteIdsAndTrainTypes"
        target_service: "ts-price-service"
    - capability: "network_loss"
      target:
        namespace: "ts"
        source_app: "ts-basic-service"
        span_names:
          - "GET /api/v1/priceservice/prices/{routeId}/{trainType}"
          - "POST /api/v1/priceservice/prices/byRouteIdsAndTrainTypes"
        target_service: "ts-price-service"
    - capability: "network_duplicate"
      target:
        namespace: "ts"
        source_app: "ts-basic-service"
        span_names:
          - "GET /api/v1/priceservice/prices/{routeId}/{trainType}"
          - "POST /api/v1/priceservice/prices/byRouteIdsAndTrainTypes"
        target_service: "ts-price-service"
    - capability: "network_corrupt"
      target:
        namespace: "ts"
        source_app: "ts-basic-service"
        span_names:
          - "GET /api/v1/priceservice/prices/{routeId}/{trainType}"
          - "POST /api/v1/priceservice/prices/byRouteIdsAndTrainTypes"
        target_service: "ts-price-service"
    - capability: "network_bandwidth"
      target:
        namespace: "ts"
        source_app: "ts-basic-service"
        span_names:
          - "GET /api/v1/priceservice/prices/{routeId}/{trainType}"
          - "POST /api/v1/priceservice/prices/byRouteIdsAndTrainTypes"
        target_service: "ts-price-service"
    - capability: "network_partition"
      target:
        namespace: "ts"
        source_app: "ts-basic-service"
        span_names:
          - "GET /api/v1/priceservice/prices/{routeId}/{trainType}"
          - "POST /api/v1/priceservice/prices/byRouteIdsAndTrainTypes"
        target_service: "ts-price-service"
