apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: seed-genesis
  instance: seed
  service: ts-contacts-service
  system: ts
spec:
  points:
  - capability: jvm_cpu_stress
    target:
      app: ts-contacts-service
      class: contacts.ContactsApplication
      method: main
      namespace: ts
  - capability: jvm_cpu_stress
    target:
      app: ts-contacts-service
      class: contacts.controller.ContactsController
      method: createNewContacts
      namespace: ts
  - capability: jvm_cpu_stress
    target:
      app: ts-contacts-service
      class: contacts.controller.ContactsController
      method: createNewContactsAdmin
      namespace: ts
  - capability: jvm_cpu_stress
    target:
      app: ts-contacts-service
      class: contacts.controller.ContactsController
      method: deleteContacts
      namespace: ts
  - capability: jvm_cpu_stress
    target:
      app: ts-contacts-service
      class: contacts.controller.ContactsController
      method: findContactsByAccountId
      namespace: ts
  - capability: jvm_cpu_stress
    target:
      app: ts-contacts-service
      class: contacts.controller.ContactsController
      method: getAllContacts
      namespace: ts
  - capability: jvm_cpu_stress
    target:
      app: ts-contacts-service
      class: contacts.controller.ContactsController
      method: getContactsByContactsId
      namespace: ts
  - capability: jvm_cpu_stress
    target:
      app: ts-contacts-service
      class: contacts.controller.ContactsController
      method: home
      namespace: ts
  - capability: jvm_cpu_stress
    target:
      app: ts-contacts-service
      class: contacts.controller.ContactsController
      method: modifyContacts
      namespace: ts
  - capability: jvm_cpu_stress
    target:
      app: ts-contacts-service
      class: contacts.entity.Contacts
      method: Contacts
      namespace: ts
  - capability: jvm_cpu_stress
    target:
      app: ts-contacts-service
      class: contacts.entity.Contacts
      method: equals
      namespace: ts
  - capability: jvm_cpu_stress
    target:
      app: ts-contacts-service
      class: contacts.entity.Contacts
      method: hashCode
      namespace: ts
  - capability: jvm_cpu_stress
    target:
      app: ts-contacts-service
      class: contacts.init.InitData
      method: run
      namespace: ts
  - capability: jvm_cpu_stress
    target:
      app: ts-contacts-service
      class: contacts.service.ContactsServiceImpl
      method: create
      namespace: ts
  - capability: jvm_cpu_stress
    target:
      app: ts-contacts-service
      class: contacts.service.ContactsServiceImpl
      method: createContacts
      namespace: ts
  - capability: jvm_cpu_stress
    target:
      app: ts-contacts-service
      class: contacts.service.ContactsServiceImpl
      method: delete
      namespace: ts
  - capability: jvm_cpu_stress
    target:
      app: ts-contacts-service
      class: contacts.service.ContactsServiceImpl
      method: findContactsByAccountId
      namespace: ts
  - capability: jvm_cpu_stress
    target:
      app: ts-contacts-service
      class: contacts.service.ContactsServiceImpl
      method: findContactsById
      namespace: ts
  - capability: jvm_cpu_stress
    target:
      app: ts-contacts-service
      class: contacts.service.ContactsServiceImpl
      method: getAllContacts
      namespace: ts
  - capability: jvm_cpu_stress
    target:
      app: ts-contacts-service
      class: contacts.service.ContactsServiceImpl
      method: modify
      namespace: ts
  - capability: jvm_memory_stress
    target:
      app: ts-contacts-service
      class: contacts.ContactsApplication
      method: main
      namespace: ts
  - capability: jvm_memory_stress
    target:
      app: ts-contacts-service
      class: contacts.controller.ContactsController
      method: createNewContacts
      namespace: ts
  - capability: jvm_memory_stress
    target:
      app: ts-contacts-service
      class: contacts.controller.ContactsController
      method: createNewContactsAdmin
      namespace: ts
  - capability: jvm_memory_stress
    target:
      app: ts-contacts-service
      class: contacts.controller.ContactsController
      method: deleteContacts
      namespace: ts
  - capability: jvm_memory_stress
    target:
      app: ts-contacts-service
      class: contacts.controller.ContactsController
      method: findContactsByAccountId
      namespace: ts
  - capability: jvm_memory_stress
    target:
      app: ts-contacts-service
      class: contacts.controller.ContactsController
      method: getAllContacts
      namespace: ts
  - capability: jvm_memory_stress
    target:
      app: ts-contacts-service
      class: contacts.controller.ContactsController
      method: getContactsByContactsId
      namespace: ts
  - capability: jvm_memory_stress
    target:
      app: ts-contacts-service
      class: contacts.controller.ContactsController
      method: home
      namespace: ts
  - capability: jvm_memory_stress
    target:
      app: ts-contacts-service
      class: contacts.controller.ContactsController
      method: modifyContacts
      namespace: ts
  - capability: jvm_memory_stress
    target:
      app: ts-contacts-service
      class: contacts.entity.Contacts
      method: Contacts
      namespace: ts
  - capability: jvm_memory_stress
    target:
      app: ts-contacts-service
      class: contacts.entity.Contacts
      method: equals
      namespace: ts
  - capability: jvm_memory_stress
    target:
      app: ts-contacts-service
      class: contacts.entity.Contacts
      method: hashCode
      namespace: ts
  - capability: jvm_memory_stress
    target:
      app: ts-contacts-service
      class: contacts.init.InitData
      method: run
      namespace: ts
  - capability: jvm_memory_stress
    target:
      app: ts-contacts-service
      class: contacts.service.ContactsServiceImpl
      method: create
      namespace: ts
  - capability: jvm_memory_stress
    target:
      app: ts-contacts-service
      class: contacts.service.ContactsServiceImpl
      method: createContacts
      namespace: ts
  - capability: jvm_memory_stress
    target:
      app: ts-contacts-service
      class: contacts.service.ContactsServiceImpl
      method: delete
      namespace: ts
  - capability: jvm_memory_stress
    target:
      app: ts-contacts-service
      class: contacts.service.ContactsServiceImpl
      method: findContactsByAccountId
      namespace: ts
  - capability: jvm_memory_stress
    target:
      app: ts-contacts-service
      class: contacts.service.ContactsServiceImpl
      method: findContactsById
      namespace: ts
  - capability: jvm_memory_stress
    target:
      app: ts-contacts-service
      class: contacts.service.ContactsServiceImpl
      method: getAllContacts
      namespace: ts
  - capability: jvm_memory_stress
    target:
      app: ts-contacts-service
      class: contacts.service.ContactsServiceImpl
      method: modify
      namespace: ts
  - capability: jvm_method_exception
    target:
      app: ts-contacts-service
      class: contacts.ContactsApplication
      method: main
      namespace: ts
  - capability: jvm_method_exception
    target:
      app: ts-contacts-service
      class: contacts.controller.ContactsController
      method: createNewContacts
      namespace: ts
  - capability: jvm_method_exception
    target:
      app: ts-contacts-service
      class: contacts.controller.ContactsController
      method: createNewContactsAdmin
      namespace: ts
  - capability: jvm_method_exception
    target:
      app: ts-contacts-service
      class: contacts.controller.ContactsController
      method: deleteContacts
      namespace: ts
  - capability: jvm_method_exception
    target:
      app: ts-contacts-service
      class: contacts.controller.ContactsController
      method: findContactsByAccountId
      namespace: ts
  - capability: jvm_method_exception
    target:
      app: ts-contacts-service
      class: contacts.controller.ContactsController
      method: getAllContacts
      namespace: ts
  - capability: jvm_method_exception
    target:
      app: ts-contacts-service
      class: contacts.controller.ContactsController
      method: getContactsByContactsId
      namespace: ts
  - capability: jvm_method_exception
    target:
      app: ts-contacts-service
      class: contacts.controller.ContactsController
      method: home
      namespace: ts
  - capability: jvm_method_exception
    target:
      app: ts-contacts-service
      class: contacts.controller.ContactsController
      method: modifyContacts
      namespace: ts
  - capability: jvm_method_exception
    target:
      app: ts-contacts-service
      class: contacts.entity.Contacts
      method: Contacts
      namespace: ts
  - capability: jvm_method_exception
    target:
      app: ts-contacts-service
      class: contacts.entity.Contacts
      method: equals
      namespace: ts
  - capability: jvm_method_exception
    target:
      app: ts-contacts-service
      class: contacts.entity.Contacts
      method: hashCode
      namespace: ts
  - capability: jvm_method_exception
    target:
      app: ts-contacts-service
      class: contacts.init.InitData
      method: run
      namespace: ts
  - capability: jvm_method_exception
    target:
      app: ts-contacts-service
      class: contacts.service.ContactsServiceImpl
      method: create
      namespace: ts
  - capability: jvm_method_exception
    target:
      app: ts-contacts-service
      class: contacts.service.ContactsServiceImpl
      method: createContacts
      namespace: ts
  - capability: jvm_method_exception
    target:
      app: ts-contacts-service
      class: contacts.service.ContactsServiceImpl
      method: delete
      namespace: ts
  - capability: jvm_method_exception
    target:
      app: ts-contacts-service
      class: contacts.service.ContactsServiceImpl
      method: findContactsByAccountId
      namespace: ts
  - capability: jvm_method_exception
    target:
      app: ts-contacts-service
      class: contacts.service.ContactsServiceImpl
      method: findContactsById
      namespace: ts
  - capability: jvm_method_exception
    target:
      app: ts-contacts-service
      class: contacts.service.ContactsServiceImpl
      method: getAllContacts
      namespace: ts
  - capability: jvm_method_exception
    target:
      app: ts-contacts-service
      class: contacts.service.ContactsServiceImpl
      method: modify
      namespace: ts
  - capability: jvm_method_return
    target:
      app: ts-contacts-service
      class: contacts.ContactsApplication
      method: main
      namespace: ts
  - capability: jvm_method_return
    target:
      app: ts-contacts-service
      class: contacts.controller.ContactsController
      method: createNewContacts
      namespace: ts
  - capability: jvm_method_return
    target:
      app: ts-contacts-service
      class: contacts.controller.ContactsController
      method: createNewContactsAdmin
      namespace: ts
  - capability: jvm_method_return
    target:
      app: ts-contacts-service
      class: contacts.controller.ContactsController
      method: deleteContacts
      namespace: ts
  - capability: jvm_method_return
    target:
      app: ts-contacts-service
      class: contacts.controller.ContactsController
      method: findContactsByAccountId
      namespace: ts
  - capability: jvm_method_return
    target:
      app: ts-contacts-service
      class: contacts.controller.ContactsController
      method: getAllContacts
      namespace: ts
  - capability: jvm_method_return
    target:
      app: ts-contacts-service
      class: contacts.controller.ContactsController
      method: getContactsByContactsId
      namespace: ts
  - capability: jvm_method_return
    target:
      app: ts-contacts-service
      class: contacts.controller.ContactsController
      method: home
      namespace: ts
  - capability: jvm_method_return
    target:
      app: ts-contacts-service
      class: contacts.controller.ContactsController
      method: modifyContacts
      namespace: ts
  - capability: jvm_method_return
    target:
      app: ts-contacts-service
      class: contacts.entity.Contacts
      method: Contacts
      namespace: ts
  - capability: jvm_method_return
    target:
      app: ts-contacts-service
      class: contacts.entity.Contacts
      method: equals
      namespace: ts
  - capability: jvm_method_return
    target:
      app: ts-contacts-service
      class: contacts.entity.Contacts
      method: hashCode
      namespace: ts
  - capability: jvm_method_return
    target:
      app: ts-contacts-service
      class: contacts.init.InitData
      method: run
      namespace: ts
  - capability: jvm_method_return
    target:
      app: ts-contacts-service
      class: contacts.service.ContactsServiceImpl
      method: create
      namespace: ts
  - capability: jvm_method_return
    target:
      app: ts-contacts-service
      class: contacts.service.ContactsServiceImpl
      method: createContacts
      namespace: ts
  - capability: jvm_method_return
    target:
      app: ts-contacts-service
      class: contacts.service.ContactsServiceImpl
      method: delete
      namespace: ts
  - capability: jvm_method_return
    target:
      app: ts-contacts-service
      class: contacts.service.ContactsServiceImpl
      method: findContactsByAccountId
      namespace: ts
  - capability: jvm_method_return
    target:
      app: ts-contacts-service
      class: contacts.service.ContactsServiceImpl
      method: findContactsById
      namespace: ts
  - capability: jvm_method_return
    target:
      app: ts-contacts-service
      class: contacts.service.ContactsServiceImpl
      method: getAllContacts
      namespace: ts
  - capability: jvm_method_return
    target:
      app: ts-contacts-service
      class: contacts.service.ContactsServiceImpl
      method: modify
      namespace: ts
  replace_scope: service
