apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: seed-genesis
  instance: seed
  service: ts-consign-price-service
  system: ts
spec:
  points:
  - capability: jvm_mysql_exception
    target:
      app: ts-consign-price-service
      db_name: ts
      namespace: ts
      sql_type: insert
      table: consign_price
  - capability: jvm_mysql_exception
    target:
      app: ts-consign-price-service
      db_name: ts
      namespace: ts
      sql_type: select
      table: consign_price
  - capability: jvm_mysql_exception
    target:
      app: ts-consign-price-service
      db_name: ts
      namespace: ts
      sql_type: select
      table: ts
  - capability: jvm_mysql_latency
    target:
      app: ts-consign-price-service
      db_name: ts
      namespace: ts
      sql_type: insert
      table: consign_price
  - capability: jvm_mysql_latency
    target:
      app: ts-consign-price-service
      db_name: ts
      namespace: ts
      sql_type: select
      table: consign_price
  - capability: jvm_mysql_latency
    target:
      app: ts-consign-price-service
      db_name: ts
      namespace: ts
      sql_type: select
      table: ts
  replace_scope: service
