apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: "seed-genesis"
  instance: "seed"
  service: "ts-consign-service"
  system: "ts"
spec:
  replace_scope: "service"
  points:
    - capability: "container_kill"
      target:
        app: "ts-consign-service"
        container: "ts-consign-service"
        namespace: "ts"
    - capability: "cpu_stress"
      target:
        app: "ts-consign-service"
        container: "ts-consign-service"
        namespace: "ts"
    - capability: "http_request_abort"
      target:
        app: "ts-consign-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/consignpriceservice/consignprice/*/*"
        port: 8080
        server_address: "ts-consign-price-service"
        span_name: "GET"
    - capability: "http_request_delay"
      target:
        app: "ts-consign-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/consignpriceservice/consignprice/*/*"
        port: 8080
        server_address: "ts-consign-price-service"
        span_name: "GET"
    - capability: "jvm_method_latency"
      target:
        app: "ts-consign-service"
        class: "consign.ConsignApplication"
        method: "main"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-consign-service"
        class: "consign.controller.ConsignController"
        method: "findByAccountId"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-consign-service"
        class: "consign.controller.ConsignController"
        method: "findByConsignee"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-consign-service"
        class: "consign.controller.ConsignController"
        method: "findByOrderId"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-consign-service"
        class: "consign.controller.ConsignController"
        method: "home"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-consign-service"
        class: "consign.controller.ConsignController"
        method: "insertConsign"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-consign-service"
        class: "consign.controller.ConsignController"
        method: "updateConsign"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-consign-service"
        class: "consign.entity.GetPriceDomain"
        method: "GetPriceDomain"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-consign-service"
        class: "consign.entity.InsertConsignRecordResult"
        method: "InsertConsignRecordResult"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-consign-service"
        class: "consign.init.InitData"
        method: "run"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-consign-service"
        class: "consign.service.ConsignServiceImpl"
        method: "getServiceUrl"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-consign-service"
        class: "consign.service.ConsignServiceImpl"
        method: "insertConsignRecord"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-consign-service"
        class: "consign.service.ConsignServiceImpl"
        method: "queryByAccountId"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-consign-service"
        class: "consign.service.ConsignServiceImpl"
        method: "queryByConsignee"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-consign-service"
        class: "consign.service.ConsignServiceImpl"
        method: "queryByOrderId"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-consign-service"
        class: "consign.service.ConsignServiceImpl"
        method: "updateConsignRecord"
        namespace: "ts"
    - capability: "pod_failure"
      target:
        app: "ts-consign-service"
        namespace: "ts"
    - capability: "pod_kill"
      target:
        app: "ts-consign-service"
        namespace: "ts"
    - capability: "time_skew"
      target:
        app: "ts-consign-service"
        container: "ts-consign-service"
        namespace: "ts"
