apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: "seed-genesis"
  instance: "seed"
  service: "ts-contacts-service"
  system: "ts"
spec:
  replace_scope: "service"
  points:
    - capability: "container_kill"
      target:
        app: "ts-contacts-service"
        container: "ts-contacts-service"
        namespace: "ts"
    - capability: "cpu_stress"
      target:
        app: "ts-contacts-service"
        container: "ts-contacts-service"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-contacts-service"
        class: "contacts.ContactsApplication"
        method: "main"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-contacts-service"
        class: "contacts.controller.ContactsController"
        method: "createNewContacts"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-contacts-service"
        class: "contacts.controller.ContactsController"
        method: "createNewContactsAdmin"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-contacts-service"
        class: "contacts.controller.ContactsController"
        method: "deleteContacts"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-contacts-service"
        class: "contacts.controller.ContactsController"
        method: "findContactsByAccountId"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-contacts-service"
        class: "contacts.controller.ContactsController"
        method: "getAllContacts"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-contacts-service"
        class: "contacts.controller.ContactsController"
        method: "getContactsByContactsId"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-contacts-service"
        class: "contacts.controller.ContactsController"
        method: "home"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-contacts-service"
        class: "contacts.controller.ContactsController"
        method: "modifyContacts"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-contacts-service"
        class: "contacts.entity.Contacts"
        method: "Contacts"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-contacts-service"
        class: "contacts.entity.Contacts"
        method: "equals"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-contacts-service"
        class: "contacts.entity.Contacts"
        method: "hashCode"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-contacts-service"
        class: "contacts.init.InitData"
        method: "run"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-contacts-service"
        class: "contacts.service.ContactsServiceImpl"
        method: "create"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-contacts-service"
        class: "contacts.service.ContactsServiceImpl"
        method: "createContacts"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-contacts-service"
        class: "contacts.service.ContactsServiceImpl"
        method: "delete"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-contacts-service"
        class: "contacts.service.ContactsServiceImpl"
        method: "findContactsByAccountId"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-contacts-service"
        class: "contacts.service.ContactsServiceImpl"
        method: "findContactsById"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-contacts-service"
        class: "contacts.service.ContactsServiceImpl"
        method: "getAllContacts"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-contacts-service"
        class: "contacts.service.ContactsServiceImpl"
        method: "modify"
        namespace: "ts"
    - capability: "pod_failure"
      target:
        app: "ts-contacts-service"
        namespace: "ts"
    - capability: "pod_kill"
      target:
        app: "ts-contacts-service"
        namespace: "ts"
    - capability: "time_skew"
      target:
        app: "ts-contacts-service"
        container: "ts-contacts-service"
        namespace: "ts"
