apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: "seed-genesis"
  instance: "seed"
  service: "ts-delivery-service"
  system: "ts"
spec:
  replace_scope: "service"
  points:
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-delivery-service"
        class: "delivery.DeliveryApplication"
        method: "main"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-delivery-service"
        class: "delivery.config.Queues"
        method: "emailQueue"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-delivery-service"
        class: "delivery.entity.Delivery"
        method: "Delivery"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-delivery-service"
        class: "delivery.mq.RabbitReceive"
        method: "process"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-delivery-service"
        class: "delivery.DeliveryApplication"
        method: "main"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-delivery-service"
        class: "delivery.config.Queues"
        method: "emailQueue"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-delivery-service"
        class: "delivery.entity.Delivery"
        method: "Delivery"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-delivery-service"
        class: "delivery.mq.RabbitReceive"
        method: "process"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-delivery-service"
        class: "delivery.DeliveryApplication"
        method: "main"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-delivery-service"
        class: "delivery.config.Queues"
        method: "emailQueue"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-delivery-service"
        class: "delivery.entity.Delivery"
        method: "Delivery"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-delivery-service"
        class: "delivery.mq.RabbitReceive"
        method: "process"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-delivery-service"
        class: "delivery.DeliveryApplication"
        method: "main"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-delivery-service"
        class: "delivery.config.Queues"
        method: "emailQueue"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-delivery-service"
        class: "delivery.entity.Delivery"
        method: "Delivery"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-delivery-service"
        class: "delivery.mq.RabbitReceive"
        method: "process"
        namespace: "ts"
