apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: "seed-genesis"
  instance: "seed"
  service: "ts-delivery-service"
  system: "ts"
spec:
  replace_scope: "service"
  points:
    - capability: "container_kill"
      target:
        app: "ts-delivery-service"
        container: "ts-delivery-service"
        namespace: "ts"
    - capability: "cpu_stress"
      target:
        app: "ts-delivery-service"
        container: "ts-delivery-service"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-delivery-service"
        class: "delivery.DeliveryApplication"
        method: "main"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-delivery-service"
        class: "delivery.config.Queues"
        method: "emailQueue"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-delivery-service"
        class: "delivery.entity.Delivery"
        method: "Delivery"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-delivery-service"
        class: "delivery.mq.RabbitReceive"
        method: "process"
        namespace: "ts"
    - capability: "memory_stress"
      target:
        app: "ts-delivery-service"
        container: "ts-delivery-service"
        namespace: "ts"
    - capability: "pod_failure"
      target:
        app: "ts-delivery-service"
        namespace: "ts"
    - capability: "pod_kill"
      target:
        app: "ts-delivery-service"
        namespace: "ts"
    - capability: "time_skew"
      target:
        app: "ts-delivery-service"
        container: "ts-delivery-service"
        namespace: "ts"
