apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: "seed-genesis"
  instance: "seed"
  service: "ts-execute-service"
  system: "ts"
spec:
  replace_scope: "service"
  points:
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-execute-service"
        class: "execute.ExecuteApplication"
        method: "main"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-execute-service"
        class: "execute.controller.ExecuteControlller"
        method: "collectTicket"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-execute-service"
        class: "execute.controller.ExecuteControlller"
        method: "executeTicket"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-execute-service"
        class: "execute.controller.ExecuteControlller"
        method: "home"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-execute-service"
        class: "execute.serivce.ExecuteServiceImpl"
        method: "executeOrder"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-execute-service"
        class: "execute.serivce.ExecuteServiceImpl"
        method: "executeOrderOther"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-execute-service"
        class: "execute.serivce.ExecuteServiceImpl"
        method: "getOrderByIdFromOrder"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-execute-service"
        class: "execute.serivce.ExecuteServiceImpl"
        method: "getOrderByIdFromOrderOther"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-execute-service"
        class: "execute.serivce.ExecuteServiceImpl"
        method: "getServiceUrl"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-execute-service"
        class: "execute.serivce.ExecuteServiceImpl"
        method: "ticketCollect"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-execute-service"
        class: "execute.serivce.ExecuteServiceImpl"
        method: "ticketExecute"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-execute-service"
        class: "execute.ExecuteApplication"
        method: "main"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-execute-service"
        class: "execute.controller.ExecuteControlller"
        method: "collectTicket"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-execute-service"
        class: "execute.controller.ExecuteControlller"
        method: "executeTicket"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-execute-service"
        class: "execute.controller.ExecuteControlller"
        method: "home"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-execute-service"
        class: "execute.serivce.ExecuteServiceImpl"
        method: "executeOrder"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-execute-service"
        class: "execute.serivce.ExecuteServiceImpl"
        method: "executeOrderOther"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-execute-service"
        class: "execute.serivce.ExecuteServiceImpl"
        method: "getOrderByIdFromOrder"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-execute-service"
        class: "execute.serivce.ExecuteServiceImpl"
        method: "getOrderByIdFromOrderOther"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-execute-service"
        class: "execute.serivce.ExecuteServiceImpl"
        method: "getServiceUrl"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-execute-service"
        class: "execute.serivce.ExecuteServiceImpl"
        method: "ticketCollect"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-execute-service"
        class: "execute.serivce.ExecuteServiceImpl"
        method: "ticketExecute"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-execute-service"
        class: "execute.ExecuteApplication"
        method: "main"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-execute-service"
        class: "execute.controller.ExecuteControlller"
        method: "collectTicket"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-execute-service"
        class: "execute.controller.ExecuteControlller"
        method: "executeTicket"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-execute-service"
        class: "execute.controller.ExecuteControlller"
        method: "home"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-execute-service"
        class: "execute.serivce.ExecuteServiceImpl"
        method: "executeOrder"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-execute-service"
        class: "execute.serivce.ExecuteServiceImpl"
        method: "executeOrderOther"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-execute-service"
        class: "execute.serivce.ExecuteServiceImpl"
        method: "getOrderByIdFromOrder"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-execute-service"
        class: "execute.serivce.ExecuteServiceImpl"
        method: "getOrderByIdFromOrderOther"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-execute-service"
        class: "execute.serivce.ExecuteServiceImpl"
        method: "getServiceUrl"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-execute-service"
        class: "execute.serivce.ExecuteServiceImpl"
        method: "ticketCollect"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-execute-service"
        class: "execute.serivce.ExecuteServiceImpl"
        method: "ticketExecute"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-execute-service"
        class: "execute.ExecuteApplication"
        method: "main"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-execute-service"
        class: "execute.controller.ExecuteControlller"
        method: "collectTicket"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-execute-service"
        class: "execute.controller.ExecuteControlller"
        method: "executeTicket"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-execute-service"
        class: "execute.controller.ExecuteControlller"
        method: "home"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-execute-service"
        class: "execute.serivce.ExecuteServiceImpl"
        method: "executeOrder"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-execute-service"
        class: "execute.serivce.ExecuteServiceImpl"
        method: "executeOrderOther"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-execute-service"
        class: "execute.serivce.ExecuteServiceImpl"
        method: "getOrderByIdFromOrder"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-execute-service"
        class: "execute.serivce.ExecuteServiceImpl"
        method: "getOrderByIdFromOrderOther"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-execute-service"
        class: "execute.serivce.ExecuteServiceImpl"
        method: "getServiceUrl"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-execute-service"
        class: "execute.serivce.ExecuteServiceImpl"
        method: "ticketCollect"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-execute-service"
        class: "execute.serivce.ExecuteServiceImpl"
        method: "ticketExecute"
        namespace: "ts"
