apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: "seed-genesis"
  instance: "seed"
  service: "ts-food-delivery-service"
  system: "ts"
spec:
  replace_scope: "service"
  points:
    - capability: "container_kill"
      target:
        app: "ts-food-delivery-service"
        container: "ts-food-delivery-service"
        namespace: "ts"
    - capability: "cpu_stress"
      target:
        app: "ts-food-delivery-service"
        container: "ts-food-delivery-service"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-food-delivery-service"
        class: "food_delivery.FoodDeliveryApplication"
        method: "main"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-food-delivery-service"
        class: "food_delivery.controller.FoodDeliveryController"
        method: "createFoodDeliveryOrder"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-food-delivery-service"
        class: "food_delivery.controller.FoodDeliveryController"
        method: "deleteFoodDeliveryOrder"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-food-delivery-service"
        class: "food_delivery.controller.FoodDeliveryController"
        method: "getAllFoodDeliveryOrders"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-food-delivery-service"
        class: "food_delivery.controller.FoodDeliveryController"
        method: "getFoodDeliveryOrderById"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-food-delivery-service"
        class: "food_delivery.controller.FoodDeliveryController"
        method: "getFoodDeliveryOrderByStoreId"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-food-delivery-service"
        class: "food_delivery.controller.FoodDeliveryController"
        method: "home"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-food-delivery-service"
        class: "food_delivery.controller.FoodDeliveryController"
        method: "updateDeliveryTime"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-food-delivery-service"
        class: "food_delivery.controller.FoodDeliveryController"
        method: "updateSeatNo"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-food-delivery-service"
        class: "food_delivery.controller.FoodDeliveryController"
        method: "updateTripId"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-food-delivery-service"
        class: "food_delivery.init.InitData"
        method: "run"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-food-delivery-service"
        class: "food_delivery.service.FoodDeliveryServiceImpl"
        method: "createFoodDeliveryOrder"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-food-delivery-service"
        class: "food_delivery.service.FoodDeliveryServiceImpl"
        method: "deleteFoodDeliveryOrder"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-food-delivery-service"
        class: "food_delivery.service.FoodDeliveryServiceImpl"
        method: "getAllFoodDeliveryOrders"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-food-delivery-service"
        class: "food_delivery.service.FoodDeliveryServiceImpl"
        method: "getFoodDeliveryOrderById"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-food-delivery-service"
        class: "food_delivery.service.FoodDeliveryServiceImpl"
        method: "getFoodDeliveryOrderByStoreId"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-food-delivery-service"
        class: "food_delivery.service.FoodDeliveryServiceImpl"
        method: "getServiceUrl"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-food-delivery-service"
        class: "food_delivery.service.FoodDeliveryServiceImpl"
        method: "updateDeliveryTime"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-food-delivery-service"
        class: "food_delivery.service.FoodDeliveryServiceImpl"
        method: "updateSeatNo"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-food-delivery-service"
        class: "food_delivery.service.FoodDeliveryServiceImpl"
        method: "updateTripId"
        namespace: "ts"
    - capability: "memory_stress"
      target:
        app: "ts-food-delivery-service"
        container: "ts-food-delivery-service"
        namespace: "ts"
    - capability: "pod_failure"
      target:
        app: "ts-food-delivery-service"
        namespace: "ts"
    - capability: "pod_kill"
      target:
        app: "ts-food-delivery-service"
        namespace: "ts"
    - capability: "time_skew"
      target:
        app: "ts-food-delivery-service"
        container: "ts-food-delivery-service"
        namespace: "ts"
