apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: seed-genesis
  instance: seed
  service: ts-food-service
  system: ts
spec:
  points:
  - capability: jvm_cpu_stress
    target:
      app: ts-food-service
      class: foodsearch.FoodApplication
      method: main
      namespace: ts
  - capability: jvm_cpu_stress
    target:
      app: ts-food-service
      class: foodsearch.config.Queues
      method: emailQueue
      namespace: ts
  - capability: jvm_cpu_stress
    target:
      app: ts-food-service
      class: foodsearch.controller.FoodController
      method: createFoodBatches
      namespace: ts
  - capability: jvm_cpu_stress
    target:
      app: ts-food-service
      class: foodsearch.controller.FoodController
      method: createFoodOrder
      namespace: ts
  - capability: jvm_cpu_stress
    target:
      app: ts-food-service
      class: foodsearch.controller.FoodController
      method: deleteFoodOrder
      namespace: ts
  - capability: jvm_cpu_stress
    target:
      app: ts-food-service
      class: foodsearch.controller.FoodController
      method: findAllFoodOrder
      namespace: ts
  - capability: jvm_cpu_stress
    target:
      app: ts-food-service
      class: foodsearch.controller.FoodController
      method: findFoodOrderByOrderId
      namespace: ts
  - capability: jvm_cpu_stress
    target:
      app: ts-food-service
      class: foodsearch.controller.FoodController
      method: getAllFood
      namespace: ts
  - capability: jvm_cpu_stress
    target:
      app: ts-food-service
      class: foodsearch.controller.FoodController
      method: home
      namespace: ts
  - capability: jvm_cpu_stress
    target:
      app: ts-food-service
      class: foodsearch.controller.FoodController
      method: test_send_delivery
      namespace: ts
  - capability: jvm_cpu_stress
    target:
      app: ts-food-service
      class: foodsearch.controller.FoodController
      method: updateFoodOrder
      namespace: ts
  - capability: jvm_cpu_stress
    target:
      app: ts-food-service
      class: foodsearch.entity.AllTripFood
      method: AllTripFood
      namespace: ts
  - capability: jvm_cpu_stress
    target:
      app: ts-food-service
      class: foodsearch.entity.Delivery
      method: Delivery
      namespace: ts
  - capability: jvm_cpu_stress
    target:
      app: ts-food-service
      class: foodsearch.entity.FoodOrder
      method: FoodOrder
      namespace: ts
  - capability: jvm_cpu_stress
    target:
      app: ts-food-service
      class: foodsearch.mq.RabbitSend
      method: send
      namespace: ts
  - capability: jvm_cpu_stress
    target:
      app: ts-food-service
      class: foodsearch.service.FoodServiceImpl
      method: createFoodOrder
      namespace: ts
  - capability: jvm_cpu_stress
    target:
      app: ts-food-service
      class: foodsearch.service.FoodServiceImpl
      method: createFoodOrdersInBatch
      namespace: ts
  - capability: jvm_cpu_stress
    target:
      app: ts-food-service
      class: foodsearch.service.FoodServiceImpl
      method: deleteFoodOrder
      namespace: ts
  - capability: jvm_cpu_stress
    target:
      app: ts-food-service
      class: foodsearch.service.FoodServiceImpl
      method: findAllFoodOrder
      namespace: ts
  - capability: jvm_cpu_stress
    target:
      app: ts-food-service
      class: foodsearch.service.FoodServiceImpl
      method: findByOrderId
      namespace: ts
  - capability: jvm_cpu_stress
    target:
      app: ts-food-service
      class: foodsearch.service.FoodServiceImpl
      method: getAllFood
      namespace: ts
  - capability: jvm_cpu_stress
    target:
      app: ts-food-service
      class: foodsearch.service.FoodServiceImpl
      method: getServiceUrl
      namespace: ts
  - capability: jvm_cpu_stress
    target:
      app: ts-food-service
      class: foodsearch.service.FoodServiceImpl
      method: updateFoodOrder
      namespace: ts
  - capability: jvm_memory_stress
    target:
      app: ts-food-service
      class: foodsearch.FoodApplication
      method: main
      namespace: ts
  - capability: jvm_memory_stress
    target:
      app: ts-food-service
      class: foodsearch.config.Queues
      method: emailQueue
      namespace: ts
  - capability: jvm_memory_stress
    target:
      app: ts-food-service
      class: foodsearch.controller.FoodController
      method: createFoodBatches
      namespace: ts
  - capability: jvm_memory_stress
    target:
      app: ts-food-service
      class: foodsearch.controller.FoodController
      method: createFoodOrder
      namespace: ts
  - capability: jvm_memory_stress
    target:
      app: ts-food-service
      class: foodsearch.controller.FoodController
      method: deleteFoodOrder
      namespace: ts
  - capability: jvm_memory_stress
    target:
      app: ts-food-service
      class: foodsearch.controller.FoodController
      method: findAllFoodOrder
      namespace: ts
  - capability: jvm_memory_stress
    target:
      app: ts-food-service
      class: foodsearch.controller.FoodController
      method: findFoodOrderByOrderId
      namespace: ts
  - capability: jvm_memory_stress
    target:
      app: ts-food-service
      class: foodsearch.controller.FoodController
      method: getAllFood
      namespace: ts
  - capability: jvm_memory_stress
    target:
      app: ts-food-service
      class: foodsearch.controller.FoodController
      method: home
      namespace: ts
  - capability: jvm_memory_stress
    target:
      app: ts-food-service
      class: foodsearch.controller.FoodController
      method: test_send_delivery
      namespace: ts
  - capability: jvm_memory_stress
    target:
      app: ts-food-service
      class: foodsearch.controller.FoodController
      method: updateFoodOrder
      namespace: ts
  - capability: jvm_memory_stress
    target:
      app: ts-food-service
      class: foodsearch.entity.AllTripFood
      method: AllTripFood
      namespace: ts
  - capability: jvm_memory_stress
    target:
      app: ts-food-service
      class: foodsearch.entity.Delivery
      method: Delivery
      namespace: ts
  - capability: jvm_memory_stress
    target:
      app: ts-food-service
      class: foodsearch.entity.FoodOrder
      method: FoodOrder
      namespace: ts
  - capability: jvm_memory_stress
    target:
      app: ts-food-service
      class: foodsearch.mq.RabbitSend
      method: send
      namespace: ts
  - capability: jvm_memory_stress
    target:
      app: ts-food-service
      class: foodsearch.service.FoodServiceImpl
      method: createFoodOrder
      namespace: ts
  - capability: jvm_memory_stress
    target:
      app: ts-food-service
      class: foodsearch.service.FoodServiceImpl
      method: createFoodOrdersInBatch
      namespace: ts
  - capability: jvm_memory_stress
    target:
      app: ts-food-service
      class: foodsearch.service.FoodServiceImpl
      method: deleteFoodOrder
      namespace: ts
  - capability: jvm_memory_stress
    target:
      app: ts-food-service
      class: foodsearch.service.FoodServiceImpl
      method: findAllFoodOrder
      namespace: ts
  - capability: jvm_memory_stress
    target:
      app: ts-food-service
      class: foodsearch.service.FoodServiceImpl
      method: findByOrderId
      namespace: ts
  - capability: jvm_memory_stress
    target:
      app: ts-food-service
      class: foodsearch.service.FoodServiceImpl
      method: getAllFood
      namespace: ts
  - capability: jvm_memory_stress
    target:
      app: ts-food-service
      class: foodsearch.service.FoodServiceImpl
      method: getServiceUrl
      namespace: ts
  - capability: jvm_memory_stress
    target:
      app: ts-food-service
      class: foodsearch.service.FoodServiceImpl
      method: updateFoodOrder
      namespace: ts
  - capability: jvm_method_exception
    target:
      app: ts-food-service
      class: foodsearch.FoodApplication
      method: main
      namespace: ts
  - capability: jvm_method_exception
    target:
      app: ts-food-service
      class: foodsearch.config.Queues
      method: emailQueue
      namespace: ts
  - capability: jvm_method_exception
    target:
      app: ts-food-service
      class: foodsearch.controller.FoodController
      method: createFoodBatches
      namespace: ts
  - capability: jvm_method_exception
    target:
      app: ts-food-service
      class: foodsearch.controller.FoodController
      method: createFoodOrder
      namespace: ts
  - capability: jvm_method_exception
    target:
      app: ts-food-service
      class: foodsearch.controller.FoodController
      method: deleteFoodOrder
      namespace: ts
  - capability: jvm_method_exception
    target:
      app: ts-food-service
      class: foodsearch.controller.FoodController
      method: findAllFoodOrder
      namespace: ts
  - capability: jvm_method_exception
    target:
      app: ts-food-service
      class: foodsearch.controller.FoodController
      method: findFoodOrderByOrderId
      namespace: ts
  - capability: jvm_method_exception
    target:
      app: ts-food-service
      class: foodsearch.controller.FoodController
      method: getAllFood
      namespace: ts
  - capability: jvm_method_exception
    target:
      app: ts-food-service
      class: foodsearch.controller.FoodController
      method: home
      namespace: ts
  - capability: jvm_method_exception
    target:
      app: ts-food-service
      class: foodsearch.controller.FoodController
      method: test_send_delivery
      namespace: ts
  - capability: jvm_method_exception
    target:
      app: ts-food-service
      class: foodsearch.controller.FoodController
      method: updateFoodOrder
      namespace: ts
  - capability: jvm_method_exception
    target:
      app: ts-food-service
      class: foodsearch.entity.AllTripFood
      method: AllTripFood
      namespace: ts
  - capability: jvm_method_exception
    target:
      app: ts-food-service
      class: foodsearch.entity.Delivery
      method: Delivery
      namespace: ts
  - capability: jvm_method_exception
    target:
      app: ts-food-service
      class: foodsearch.entity.FoodOrder
      method: FoodOrder
      namespace: ts
  - capability: jvm_method_exception
    target:
      app: ts-food-service
      class: foodsearch.mq.RabbitSend
      method: send
      namespace: ts
  - capability: jvm_method_exception
    target:
      app: ts-food-service
      class: foodsearch.service.FoodServiceImpl
      method: createFoodOrder
      namespace: ts
  - capability: jvm_method_exception
    target:
      app: ts-food-service
      class: foodsearch.service.FoodServiceImpl
      method: createFoodOrdersInBatch
      namespace: ts
  - capability: jvm_method_exception
    target:
      app: ts-food-service
      class: foodsearch.service.FoodServiceImpl
      method: deleteFoodOrder
      namespace: ts
  - capability: jvm_method_exception
    target:
      app: ts-food-service
      class: foodsearch.service.FoodServiceImpl
      method: findAllFoodOrder
      namespace: ts
  - capability: jvm_method_exception
    target:
      app: ts-food-service
      class: foodsearch.service.FoodServiceImpl
      method: findByOrderId
      namespace: ts
  - capability: jvm_method_exception
    target:
      app: ts-food-service
      class: foodsearch.service.FoodServiceImpl
      method: getAllFood
      namespace: ts
  - capability: jvm_method_exception
    target:
      app: ts-food-service
      class: foodsearch.service.FoodServiceImpl
      method: getServiceUrl
      namespace: ts
  - capability: jvm_method_exception
    target:
      app: ts-food-service
      class: foodsearch.service.FoodServiceImpl
      method: updateFoodOrder
      namespace: ts
  - capability: jvm_method_return
    target:
      app: ts-food-service
      class: foodsearch.FoodApplication
      method: main
      namespace: ts
  - capability: jvm_method_return
    target:
      app: ts-food-service
      class: foodsearch.config.Queues
      method: emailQueue
      namespace: ts
  - capability: jvm_method_return
    target:
      app: ts-food-service
      class: foodsearch.controller.FoodController
      method: createFoodBatches
      namespace: ts
  - capability: jvm_method_return
    target:
      app: ts-food-service
      class: foodsearch.controller.FoodController
      method: createFoodOrder
      namespace: ts
  - capability: jvm_method_return
    target:
      app: ts-food-service
      class: foodsearch.controller.FoodController
      method: deleteFoodOrder
      namespace: ts
  - capability: jvm_method_return
    target:
      app: ts-food-service
      class: foodsearch.controller.FoodController
      method: findAllFoodOrder
      namespace: ts
  - capability: jvm_method_return
    target:
      app: ts-food-service
      class: foodsearch.controller.FoodController
      method: findFoodOrderByOrderId
      namespace: ts
  - capability: jvm_method_return
    target:
      app: ts-food-service
      class: foodsearch.controller.FoodController
      method: getAllFood
      namespace: ts
  - capability: jvm_method_return
    target:
      app: ts-food-service
      class: foodsearch.controller.FoodController
      method: home
      namespace: ts
  - capability: jvm_method_return
    target:
      app: ts-food-service
      class: foodsearch.controller.FoodController
      method: test_send_delivery
      namespace: ts
  - capability: jvm_method_return
    target:
      app: ts-food-service
      class: foodsearch.controller.FoodController
      method: updateFoodOrder
      namespace: ts
  - capability: jvm_method_return
    target:
      app: ts-food-service
      class: foodsearch.entity.AllTripFood
      method: AllTripFood
      namespace: ts
  - capability: jvm_method_return
    target:
      app: ts-food-service
      class: foodsearch.entity.Delivery
      method: Delivery
      namespace: ts
  - capability: jvm_method_return
    target:
      app: ts-food-service
      class: foodsearch.entity.FoodOrder
      method: FoodOrder
      namespace: ts
  - capability: jvm_method_return
    target:
      app: ts-food-service
      class: foodsearch.mq.RabbitSend
      method: send
      namespace: ts
  - capability: jvm_method_return
    target:
      app: ts-food-service
      class: foodsearch.service.FoodServiceImpl
      method: createFoodOrder
      namespace: ts
  - capability: jvm_method_return
    target:
      app: ts-food-service
      class: foodsearch.service.FoodServiceImpl
      method: createFoodOrdersInBatch
      namespace: ts
  - capability: jvm_method_return
    target:
      app: ts-food-service
      class: foodsearch.service.FoodServiceImpl
      method: deleteFoodOrder
      namespace: ts
  - capability: jvm_method_return
    target:
      app: ts-food-service
      class: foodsearch.service.FoodServiceImpl
      method: findAllFoodOrder
      namespace: ts
  - capability: jvm_method_return
    target:
      app: ts-food-service
      class: foodsearch.service.FoodServiceImpl
      method: findByOrderId
      namespace: ts
  - capability: jvm_method_return
    target:
      app: ts-food-service
      class: foodsearch.service.FoodServiceImpl
      method: getAllFood
      namespace: ts
  - capability: jvm_method_return
    target:
      app: ts-food-service
      class: foodsearch.service.FoodServiceImpl
      method: getServiceUrl
      namespace: ts
  - capability: jvm_method_return
    target:
      app: ts-food-service
      class: foodsearch.service.FoodServiceImpl
      method: updateFoodOrder
      namespace: ts
  replace_scope: service
