apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: "seed-genesis"
  instance: "seed"
  service: "ts-inside-payment-service"
  system: "ts"
spec:
  replace_scope: "service"
  points:
    - capability: "container_kill"
      target:
        app: "ts-inside-payment-service"
        container: "ts-inside-payment-service"
        namespace: "ts"
    - capability: "cpu_stress"
      target:
        app: "ts-inside-payment-service"
        container: "ts-inside-payment-service"
        namespace: "ts"
    - capability: "http_request_abort"
      target:
        app: "ts-inside-payment-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/orderservice/order/*"
        port: 8080
    - capability: "http_request_abort"
      target:
        app: "ts-inside-payment-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/orderservice/order/status/*/*"
        port: 8080
    - capability: "http_request_abort"
      target:
        app: "ts-inside-payment-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/paymentservice/payment"
        port: 8080
    - capability: "http_request_delay"
      target:
        app: "ts-inside-payment-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/orderservice/order/*"
        port: 8080
    - capability: "http_request_delay"
      target:
        app: "ts-inside-payment-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/orderservice/order/status/*/*"
        port: 8080
    - capability: "http_request_delay"
      target:
        app: "ts-inside-payment-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/paymentservice/payment"
        port: 8080
    - capability: "jvm_method_latency"
      target:
        app: "ts-inside-payment-service"
        class: "inside_payment.InsidePaymentApplication"
        method: "main"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-inside-payment-service"
        class: "inside_payment.async.AsyncTask"
        method: "sendAsyncCallToPaymentService"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-inside-payment-service"
        class: "inside_payment.controller.InsidePaymentController"
        method: "addMoney"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-inside-payment-service"
        class: "inside_payment.controller.InsidePaymentController"
        method: "createAccount"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-inside-payment-service"
        class: "inside_payment.controller.InsidePaymentController"
        method: "drawBack"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-inside-payment-service"
        class: "inside_payment.controller.InsidePaymentController"
        method: "home"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-inside-payment-service"
        class: "inside_payment.controller.InsidePaymentController"
        method: "pay"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-inside-payment-service"
        class: "inside_payment.controller.InsidePaymentController"
        method: "payDifference"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-inside-payment-service"
        class: "inside_payment.controller.InsidePaymentController"
        method: "queryAccount"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-inside-payment-service"
        class: "inside_payment.controller.InsidePaymentController"
        method: "queryAddMoney"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-inside-payment-service"
        class: "inside_payment.controller.InsidePaymentController"
        method: "queryPayment"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-inside-payment-service"
        class: "inside_payment.entity.AccountInfo"
        method: "AccountInfo"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-inside-payment-service"
        class: "inside_payment.entity.Balance"
        method: "Balance"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-inside-payment-service"
        class: "inside_payment.entity.Money"
        method: "Money"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-inside-payment-service"
        class: "inside_payment.entity.OutsidePaymentInfo"
        method: "OutsidePaymentInfo"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-inside-payment-service"
        class: "inside_payment.entity.Payment"
        method: "Payment"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-inside-payment-service"
        class: "inside_payment.entity.PaymentInfo"
        method: "PaymentInfo"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-inside-payment-service"
        class: "inside_payment.init.InitData"
        method: "run"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-inside-payment-service"
        class: "inside_payment.service.InsidePaymentServiceImpl"
        method: "addMoney"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-inside-payment-service"
        class: "inside_payment.service.InsidePaymentServiceImpl"
        method: "createAccount"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-inside-payment-service"
        class: "inside_payment.service.InsidePaymentServiceImpl"
        method: "drawBack"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-inside-payment-service"
        class: "inside_payment.service.InsidePaymentServiceImpl"
        method: "getServiceUrl"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-inside-payment-service"
        class: "inside_payment.service.InsidePaymentServiceImpl"
        method: "initPayment"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-inside-payment-service"
        class: "inside_payment.service.InsidePaymentServiceImpl"
        method: "pay"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-inside-payment-service"
        class: "inside_payment.service.InsidePaymentServiceImpl"
        method: "payDifference"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-inside-payment-service"
        class: "inside_payment.service.InsidePaymentServiceImpl"
        method: "queryAccount"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-inside-payment-service"
        class: "inside_payment.service.InsidePaymentServiceImpl"
        method: "queryAddMoney"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-inside-payment-service"
        class: "inside_payment.service.InsidePaymentServiceImpl"
        method: "queryPayment"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-inside-payment-service"
        class: "inside_payment.service.InsidePaymentServiceImpl"
        method: "setOrderStatus"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-inside-payment-service"
        class: "inside_payment.util.CookieUtil"
        method: "CookieUtil"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-inside-payment-service"
        class: "inside_payment.util.CookieUtil"
        method: "addCookie"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-inside-payment-service"
        class: "inside_payment.util.CookieUtil"
        method: "getCookieByName"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-inside-payment-service"
        class: "inside_payment.util.CookieUtil"
        method: "readCookieMap"
        namespace: "ts"
    - capability: "memory_stress"
      target:
        app: "ts-inside-payment-service"
        container: "ts-inside-payment-service"
        namespace: "ts"
    - capability: "pod_failure"
      target:
        app: "ts-inside-payment-service"
        namespace: "ts"
    - capability: "pod_kill"
      target:
        app: "ts-inside-payment-service"
        namespace: "ts"
    - capability: "time_skew"
      target:
        app: "ts-inside-payment-service"
        container: "ts-inside-payment-service"
        namespace: "ts"
