apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: seed-genesis
  instance: seed
  service: ts-inside-payment-service
  system: ts
spec:
  points:
  - capability: network_bandwidth
    target:
      namespace: ts
      source_app: ts-inside-payment-service
      span_names:
      - CREATE table ts
      - INSERT inside_payment
      - INSERT ts.inside_money
      - INSERT ts.inside_payment
      - SELECT ts
      - SELECT ts.inside_money
      - SELECT ts.inside_payment
      - SELECT ts.ts
      target_service: mysql
  - capability: network_bandwidth
    target:
      namespace: ts
      source_app: ts-inside-payment-service
      span_names:
      - GET
      target_service: ts-order-service
  - capability: network_bandwidth
    target:
      namespace: ts
      source_app: ts-inside-payment-service
      span_names:
      - POST
      target_service: ts-payment-service
  - capability: network_corrupt
    target:
      namespace: ts
      source_app: ts-inside-payment-service
      span_names:
      - CREATE table ts
      - INSERT inside_payment
      - INSERT ts.inside_money
      - INSERT ts.inside_payment
      - SELECT ts
      - SELECT ts.inside_money
      - SELECT ts.inside_payment
      - SELECT ts.ts
      target_service: mysql
  - capability: network_corrupt
    target:
      namespace: ts
      source_app: ts-inside-payment-service
      span_names:
      - GET
      target_service: ts-order-service
  - capability: network_corrupt
    target:
      namespace: ts
      source_app: ts-inside-payment-service
      span_names:
      - POST
      target_service: ts-payment-service
  - capability: network_delay
    target:
      namespace: ts
      source_app: ts-inside-payment-service
      span_names:
      - CREATE table ts
      - INSERT inside_payment
      - INSERT ts.inside_money
      - INSERT ts.inside_payment
      - SELECT ts
      - SELECT ts.inside_money
      - SELECT ts.inside_payment
      - SELECT ts.ts
      target_service: mysql
  - capability: network_delay
    target:
      namespace: ts
      source_app: ts-inside-payment-service
      span_names:
      - GET
      target_service: ts-order-service
  - capability: network_delay
    target:
      namespace: ts
      source_app: ts-inside-payment-service
      span_names:
      - POST
      target_service: ts-payment-service
  - capability: network_duplicate
    target:
      namespace: ts
      source_app: ts-inside-payment-service
      span_names:
      - CREATE table ts
      - INSERT inside_payment
      - INSERT ts.inside_money
      - INSERT ts.inside_payment
      - SELECT ts
      - SELECT ts.inside_money
      - SELECT ts.inside_payment
      - SELECT ts.ts
      target_service: mysql
  - capability: network_duplicate
    target:
      namespace: ts
      source_app: ts-inside-payment-service
      span_names:
      - GET
      target_service: ts-order-service
  - capability: network_duplicate
    target:
      namespace: ts
      source_app: ts-inside-payment-service
      span_names:
      - POST
      target_service: ts-payment-service
  - capability: network_loss
    target:
      namespace: ts
      source_app: ts-inside-payment-service
      span_names:
      - CREATE table ts
      - INSERT inside_payment
      - INSERT ts.inside_money
      - INSERT ts.inside_payment
      - SELECT ts
      - SELECT ts.inside_money
      - SELECT ts.inside_payment
      - SELECT ts.ts
      target_service: mysql
  - capability: network_loss
    target:
      namespace: ts
      source_app: ts-inside-payment-service
      span_names:
      - GET
      target_service: ts-order-service
  - capability: network_loss
    target:
      namespace: ts
      source_app: ts-inside-payment-service
      span_names:
      - POST
      target_service: ts-payment-service
  - capability: network_partition
    target:
      namespace: ts
      source_app: ts-inside-payment-service
      span_names:
      - CREATE table ts
      - INSERT inside_payment
      - INSERT ts.inside_money
      - INSERT ts.inside_payment
      - SELECT ts
      - SELECT ts.inside_money
      - SELECT ts.inside_payment
      - SELECT ts.ts
      target_service: mysql
  - capability: network_partition
    target:
      namespace: ts
      source_app: ts-inside-payment-service
      span_names:
      - GET
      target_service: ts-order-service
  - capability: network_partition
    target:
      namespace: ts
      source_app: ts-inside-payment-service
      span_names:
      - POST
      target_service: ts-payment-service
  replace_scope: service
