apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: seed-genesis
  instance: seed
  service: ts-order-other-service
  system: ts
spec:
  points:
  - capability: jvm_mysql_exception
    target:
      app: ts-order-other-service
      db_name: ts
      namespace: ts
      sql_type: delete
      table: orders_other
  - capability: jvm_mysql_exception
    target:
      app: ts-order-other-service
      db_name: ts
      namespace: ts
      sql_type: insert
      table: orders_other
  - capability: jvm_mysql_exception
    target:
      app: ts-order-other-service
      db_name: ts
      namespace: ts
      sql_type: select
      table: information_schema
  - capability: jvm_mysql_exception
    target:
      app: ts-order-other-service
      db_name: ts
      namespace: ts
      sql_type: select
      table: mysql
  - capability: jvm_mysql_exception
    target:
      app: ts-order-other-service
      db_name: ts
      namespace: ts
      sql_type: select
      table: orders_other
  - capability: jvm_mysql_exception
    target:
      app: ts-order-other-service
      db_name: ts
      namespace: ts
      sql_type: select
      table: performance_schema
  - capability: jvm_mysql_exception
    target:
      app: ts-order-other-service
      db_name: ts
      namespace: ts
      sql_type: select
      table: sys
  - capability: jvm_mysql_exception
    target:
      app: ts-order-other-service
      db_name: ts
      namespace: ts
      sql_type: select
      table: ts
  - capability: jvm_mysql_exception
    target:
      app: ts-order-other-service
      db_name: ts
      namespace: ts
      sql_type: update
      table: orders_other
  - capability: jvm_mysql_latency
    target:
      app: ts-order-other-service
      db_name: ts
      namespace: ts
      sql_type: delete
      table: orders_other
  - capability: jvm_mysql_latency
    target:
      app: ts-order-other-service
      db_name: ts
      namespace: ts
      sql_type: insert
      table: orders_other
  - capability: jvm_mysql_latency
    target:
      app: ts-order-other-service
      db_name: ts
      namespace: ts
      sql_type: select
      table: information_schema
  - capability: jvm_mysql_latency
    target:
      app: ts-order-other-service
      db_name: ts
      namespace: ts
      sql_type: select
      table: mysql
  - capability: jvm_mysql_latency
    target:
      app: ts-order-other-service
      db_name: ts
      namespace: ts
      sql_type: select
      table: orders_other
  - capability: jvm_mysql_latency
    target:
      app: ts-order-other-service
      db_name: ts
      namespace: ts
      sql_type: select
      table: performance_schema
  - capability: jvm_mysql_latency
    target:
      app: ts-order-other-service
      db_name: ts
      namespace: ts
      sql_type: select
      table: sys
  - capability: jvm_mysql_latency
    target:
      app: ts-order-other-service
      db_name: ts
      namespace: ts
      sql_type: select
      table: ts
  - capability: jvm_mysql_latency
    target:
      app: ts-order-other-service
      db_name: ts
      namespace: ts
      sql_type: update
      table: orders_other
  replace_scope: service
