apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: "seed-genesis"
  instance: "seed"
  service: "ts-order-other-service"
  system: "ts"
spec:
  replace_scope: "service"
  points:
    - capability: "container_kill"
      target:
        app: "ts-order-other-service"
        container: "ts-order-other-service"
        namespace: "ts"
    - capability: "cpu_stress"
      target:
        app: "ts-order-other-service"
        container: "ts-order-other-service"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-order-other-service"
        class: "other.OrderOtherApplication"
        method: "main"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-order-other-service"
        class: "other.controller.OrderOtherController"
        method: "addcreateNewOrder"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-order-other-service"
        class: "other.controller.OrderOtherController"
        method: "calculateSoldTicket"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-order-other-service"
        class: "other.controller.OrderOtherController"
        method: "createNewOrder"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-order-other-service"
        class: "other.controller.OrderOtherController"
        method: "deleteOrder"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-order-other-service"
        class: "other.controller.OrderOtherController"
        method: "findAllOrder"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-order-other-service"
        class: "other.controller.OrderOtherController"
        method: "getOrderById"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-order-other-service"
        class: "other.controller.OrderOtherController"
        method: "getOrderPrice"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-order-other-service"
        class: "other.controller.OrderOtherController"
        method: "getTicketListByDateAndTripId"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-order-other-service"
        class: "other.controller.OrderOtherController"
        method: "home"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-order-other-service"
        class: "other.controller.OrderOtherController"
        method: "modifyOrder"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-order-other-service"
        class: "other.controller.OrderOtherController"
        method: "payOrder"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-order-other-service"
        class: "other.controller.OrderOtherController"
        method: "queryOrders"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-order-other-service"
        class: "other.controller.OrderOtherController"
        method: "queryOrdersForRefresh"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-order-other-service"
        class: "other.controller.OrderOtherController"
        method: "saveOrderInfo"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-order-other-service"
        class: "other.controller.OrderOtherController"
        method: "securityInfoCheck"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-order-other-service"
        class: "other.controller.OrderOtherController"
        method: "updateOrder"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-order-other-service"
        class: "other.entity.Order"
        method: "Order"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-order-other-service"
        class: "other.entity.Order"
        method: "equals"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-order-other-service"
        class: "other.entity.Order"
        method: "hashCode"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-order-other-service"
        class: "other.entity.OrderAlterInfo"
        method: "OrderAlterInfo"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-order-other-service"
        class: "other.entity.QueryInfo"
        method: "QueryInfo"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-order-other-service"
        class: "other.entity.QueryInfo"
        method: "disableBoughtDateQuery"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-order-other-service"
        class: "other.entity.QueryInfo"
        method: "disableStateQuery"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-order-other-service"
        class: "other.entity.QueryInfo"
        method: "disableTravelDateQuery"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-order-other-service"
        class: "other.entity.QueryInfo"
        method: "enableBoughtDateQuery"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-order-other-service"
        class: "other.entity.QueryInfo"
        method: "enableStateQuery"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-order-other-service"
        class: "other.entity.QueryInfo"
        method: "enableTravelDateQuery"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-order-other-service"
        class: "other.init.InitData"
        method: "run"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-order-other-service"
        class: "other.service.OrderOtherServiceImpl"
        method: "addNewOrder"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-order-other-service"
        class: "other.service.OrderOtherServiceImpl"
        method: "alterOrder"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-order-other-service"
        class: "other.service.OrderOtherServiceImpl"
        method: "cancelOrder"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-order-other-service"
        class: "other.service.OrderOtherServiceImpl"
        method: "checkSecurityAboutOrder"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-order-other-service"
        class: "other.service.OrderOtherServiceImpl"
        method: "create"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-order-other-service"
        class: "other.service.OrderOtherServiceImpl"
        method: "deleteOrder"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-order-other-service"
        class: "other.service.OrderOtherServiceImpl"
        method: "findOrderById"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-order-other-service"
        class: "other.service.OrderOtherServiceImpl"
        method: "getAllOrders"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-order-other-service"
        class: "other.service.OrderOtherServiceImpl"
        method: "getOrderById"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-order-other-service"
        class: "other.service.OrderOtherServiceImpl"
        method: "getOrderPrice"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-order-other-service"
        class: "other.service.OrderOtherServiceImpl"
        method: "getServiceUrl"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-order-other-service"
        class: "other.service.OrderOtherServiceImpl"
        method: "getSoldTickets"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-order-other-service"
        class: "other.service.OrderOtherServiceImpl"
        method: "initOrder"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-order-other-service"
        class: "other.service.OrderOtherServiceImpl"
        method: "modifyOrder"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-order-other-service"
        class: "other.service.OrderOtherServiceImpl"
        method: "payOrder"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-order-other-service"
        class: "other.service.OrderOtherServiceImpl"
        method: "queryAlreadySoldOrders"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-order-other-service"
        class: "other.service.OrderOtherServiceImpl"
        method: "queryForStationId"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-order-other-service"
        class: "other.service.OrderOtherServiceImpl"
        method: "queryOrders"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-order-other-service"
        class: "other.service.OrderOtherServiceImpl"
        method: "queryOrdersForRefresh"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-order-other-service"
        class: "other.service.OrderOtherServiceImpl"
        method: "saveChanges"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-order-other-service"
        class: "other.service.OrderOtherServiceImpl"
        method: "updateOrder"
        namespace: "ts"
    - capability: "memory_stress"
      target:
        app: "ts-order-other-service"
        container: "ts-order-other-service"
        namespace: "ts"
    - capability: "pod_failure"
      target:
        app: "ts-order-other-service"
        namespace: "ts"
    - capability: "pod_kill"
      target:
        app: "ts-order-other-service"
        namespace: "ts"
    - capability: "time_skew"
      target:
        app: "ts-order-other-service"
        container: "ts-order-other-service"
        namespace: "ts"
