apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: seed-genesis
  instance: seed
  service: ts-payment-service
  system: ts
spec:
  points:
  - capability: jvm_cpu_stress
    target:
      app: ts-payment-service
      class: com.trainticket.PaymentApplication
      method: main
      namespace: ts
  - capability: jvm_cpu_stress
    target:
      app: ts-payment-service
      class: com.trainticket.controller.PaymentController
      method: addMoney
      namespace: ts
  - capability: jvm_cpu_stress
    target:
      app: ts-payment-service
      class: com.trainticket.controller.PaymentController
      method: home
      namespace: ts
  - capability: jvm_cpu_stress
    target:
      app: ts-payment-service
      class: com.trainticket.controller.PaymentController
      method: pay
      namespace: ts
  - capability: jvm_cpu_stress
    target:
      app: ts-payment-service
      class: com.trainticket.controller.PaymentController
      method: query
      namespace: ts
  - capability: jvm_cpu_stress
    target:
      app: ts-payment-service
      class: com.trainticket.entity.Payment
      method: Payment
      namespace: ts
  - capability: jvm_cpu_stress
    target:
      app: ts-payment-service
      class: com.trainticket.init.InitData
      method: run
      namespace: ts
  - capability: jvm_cpu_stress
    target:
      app: ts-payment-service
      class: com.trainticket.service.PaymentServiceImpl
      method: addMoney
      namespace: ts
  - capability: jvm_cpu_stress
    target:
      app: ts-payment-service
      class: com.trainticket.service.PaymentServiceImpl
      method: initPayment
      namespace: ts
  - capability: jvm_cpu_stress
    target:
      app: ts-payment-service
      class: com.trainticket.service.PaymentServiceImpl
      method: pay
      namespace: ts
  - capability: jvm_cpu_stress
    target:
      app: ts-payment-service
      class: com.trainticket.service.PaymentServiceImpl
      method: query
      namespace: ts
  - capability: jvm_memory_stress
    target:
      app: ts-payment-service
      class: com.trainticket.PaymentApplication
      method: main
      namespace: ts
  - capability: jvm_memory_stress
    target:
      app: ts-payment-service
      class: com.trainticket.controller.PaymentController
      method: addMoney
      namespace: ts
  - capability: jvm_memory_stress
    target:
      app: ts-payment-service
      class: com.trainticket.controller.PaymentController
      method: home
      namespace: ts
  - capability: jvm_memory_stress
    target:
      app: ts-payment-service
      class: com.trainticket.controller.PaymentController
      method: pay
      namespace: ts
  - capability: jvm_memory_stress
    target:
      app: ts-payment-service
      class: com.trainticket.controller.PaymentController
      method: query
      namespace: ts
  - capability: jvm_memory_stress
    target:
      app: ts-payment-service
      class: com.trainticket.entity.Payment
      method: Payment
      namespace: ts
  - capability: jvm_memory_stress
    target:
      app: ts-payment-service
      class: com.trainticket.init.InitData
      method: run
      namespace: ts
  - capability: jvm_memory_stress
    target:
      app: ts-payment-service
      class: com.trainticket.service.PaymentServiceImpl
      method: addMoney
      namespace: ts
  - capability: jvm_memory_stress
    target:
      app: ts-payment-service
      class: com.trainticket.service.PaymentServiceImpl
      method: initPayment
      namespace: ts
  - capability: jvm_memory_stress
    target:
      app: ts-payment-service
      class: com.trainticket.service.PaymentServiceImpl
      method: pay
      namespace: ts
  - capability: jvm_memory_stress
    target:
      app: ts-payment-service
      class: com.trainticket.service.PaymentServiceImpl
      method: query
      namespace: ts
  - capability: jvm_method_exception
    target:
      app: ts-payment-service
      class: com.trainticket.PaymentApplication
      method: main
      namespace: ts
  - capability: jvm_method_exception
    target:
      app: ts-payment-service
      class: com.trainticket.controller.PaymentController
      method: addMoney
      namespace: ts
  - capability: jvm_method_exception
    target:
      app: ts-payment-service
      class: com.trainticket.controller.PaymentController
      method: home
      namespace: ts
  - capability: jvm_method_exception
    target:
      app: ts-payment-service
      class: com.trainticket.controller.PaymentController
      method: pay
      namespace: ts
  - capability: jvm_method_exception
    target:
      app: ts-payment-service
      class: com.trainticket.controller.PaymentController
      method: query
      namespace: ts
  - capability: jvm_method_exception
    target:
      app: ts-payment-service
      class: com.trainticket.entity.Payment
      method: Payment
      namespace: ts
  - capability: jvm_method_exception
    target:
      app: ts-payment-service
      class: com.trainticket.init.InitData
      method: run
      namespace: ts
  - capability: jvm_method_exception
    target:
      app: ts-payment-service
      class: com.trainticket.service.PaymentServiceImpl
      method: addMoney
      namespace: ts
  - capability: jvm_method_exception
    target:
      app: ts-payment-service
      class: com.trainticket.service.PaymentServiceImpl
      method: initPayment
      namespace: ts
  - capability: jvm_method_exception
    target:
      app: ts-payment-service
      class: com.trainticket.service.PaymentServiceImpl
      method: pay
      namespace: ts
  - capability: jvm_method_exception
    target:
      app: ts-payment-service
      class: com.trainticket.service.PaymentServiceImpl
      method: query
      namespace: ts
  - capability: jvm_method_return
    target:
      app: ts-payment-service
      class: com.trainticket.PaymentApplication
      method: main
      namespace: ts
  - capability: jvm_method_return
    target:
      app: ts-payment-service
      class: com.trainticket.controller.PaymentController
      method: addMoney
      namespace: ts
  - capability: jvm_method_return
    target:
      app: ts-payment-service
      class: com.trainticket.controller.PaymentController
      method: home
      namespace: ts
  - capability: jvm_method_return
    target:
      app: ts-payment-service
      class: com.trainticket.controller.PaymentController
      method: pay
      namespace: ts
  - capability: jvm_method_return
    target:
      app: ts-payment-service
      class: com.trainticket.controller.PaymentController
      method: query
      namespace: ts
  - capability: jvm_method_return
    target:
      app: ts-payment-service
      class: com.trainticket.entity.Payment
      method: Payment
      namespace: ts
  - capability: jvm_method_return
    target:
      app: ts-payment-service
      class: com.trainticket.init.InitData
      method: run
      namespace: ts
  - capability: jvm_method_return
    target:
      app: ts-payment-service
      class: com.trainticket.service.PaymentServiceImpl
      method: addMoney
      namespace: ts
  - capability: jvm_method_return
    target:
      app: ts-payment-service
      class: com.trainticket.service.PaymentServiceImpl
      method: initPayment
      namespace: ts
  - capability: jvm_method_return
    target:
      app: ts-payment-service
      class: com.trainticket.service.PaymentServiceImpl
      method: pay
      namespace: ts
  - capability: jvm_method_return
    target:
      app: ts-payment-service
      class: com.trainticket.service.PaymentServiceImpl
      method: query
      namespace: ts
  replace_scope: service
