apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: "seed-genesis"
  instance: "seed"
  service: "ts-price-service"
  system: "ts"
spec:
  replace_scope: "service"
  points:
    - capability: "container_kill"
      target:
        app: "ts-price-service"
        container: "ts-price-service"
        namespace: "ts"
    - capability: "cpu_stress"
      target:
        app: "ts-price-service"
        container: "ts-price-service"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-price-service"
        class: "price.PriceApplication"
        method: "main"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-price-service"
        class: "price.controller.PriceController"
        method: "create"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-price-service"
        class: "price.controller.PriceController"
        method: "delete"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-price-service"
        class: "price.controller.PriceController"
        method: "home"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-price-service"
        class: "price.controller.PriceController"
        method: "query"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-price-service"
        class: "price.controller.PriceController"
        method: "queryAll"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-price-service"
        class: "price.controller.PriceController"
        method: "update"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-price-service"
        class: "price.init.InitData"
        method: "run"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-price-service"
        class: "price.service.PriceServiceImpl"
        method: "createNewPriceConfig"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-price-service"
        class: "price.service.PriceServiceImpl"
        method: "deletePriceConfig"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-price-service"
        class: "price.service.PriceServiceImpl"
        method: "findAllPriceConfig"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-price-service"
        class: "price.service.PriceServiceImpl"
        method: "findById"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-price-service"
        class: "price.service.PriceServiceImpl"
        method: "findByRouteIdAndTrainType"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-price-service"
        class: "price.service.PriceServiceImpl"
        method: "findByRouteIdsAndTrainTypes"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-price-service"
        class: "price.service.PriceServiceImpl"
        method: "updatePriceConfig"
        namespace: "ts"
    - capability: "memory_stress"
      target:
        app: "ts-price-service"
        container: "ts-price-service"
        namespace: "ts"
    - capability: "pod_failure"
      target:
        app: "ts-price-service"
        namespace: "ts"
    - capability: "pod_kill"
      target:
        app: "ts-price-service"
        namespace: "ts"
    - capability: "time_skew"
      target:
        app: "ts-price-service"
        container: "ts-price-service"
        namespace: "ts"
