apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: "seed-genesis"
  instance: "seed"
  service: "ts-preserve-service"
  system: "ts"
spec:
  replace_scope: "service"
  points:
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-preserve-service"
        class: "preserve.PreserveApplication"
        method: "main"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-preserve-service"
        class: "preserve.config.Queues"
        method: "emailQueue"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-preserve-service"
        class: "preserve.controller.PreserveController"
        method: "home"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-preserve-service"
        class: "preserve.controller.PreserveController"
        method: "preserve"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-preserve-service"
        class: "preserve.mq.RabbitSend"
        method: "send"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-preserve-service"
        class: "preserve.service.PreserveServiceImpl"
        method: "addAssuranceForOrder"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-preserve-service"
        class: "preserve.service.PreserveServiceImpl"
        method: "checkSecurity"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-preserve-service"
        class: "preserve.service.PreserveServiceImpl"
        method: "createConsign"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-preserve-service"
        class: "preserve.service.PreserveServiceImpl"
        method: "createFoodOrder"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-preserve-service"
        class: "preserve.service.PreserveServiceImpl"
        method: "createOrder"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-preserve-service"
        class: "preserve.service.PreserveServiceImpl"
        method: "dipatchSeat"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-preserve-service"
        class: "preserve.service.PreserveServiceImpl"
        method: "getAccount"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-preserve-service"
        class: "preserve.service.PreserveServiceImpl"
        method: "getContactsById"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-preserve-service"
        class: "preserve.service.PreserveServiceImpl"
        method: "getServiceUrl"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-preserve-service"
        class: "preserve.service.PreserveServiceImpl"
        method: "getTripAllDetailInformation"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-preserve-service"
        class: "preserve.service.PreserveServiceImpl"
        method: "preserve"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-preserve-service"
        class: "preserve.service.PreserveServiceImpl"
        method: "queryForStationId"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-preserve-service"
        class: "preserve.service.PreserveServiceImpl"
        method: "sendEmail"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-preserve-service"
        class: "preserve.PreserveApplication"
        method: "main"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-preserve-service"
        class: "preserve.config.Queues"
        method: "emailQueue"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-preserve-service"
        class: "preserve.controller.PreserveController"
        method: "home"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-preserve-service"
        class: "preserve.controller.PreserveController"
        method: "preserve"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-preserve-service"
        class: "preserve.mq.RabbitSend"
        method: "send"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-preserve-service"
        class: "preserve.service.PreserveServiceImpl"
        method: "addAssuranceForOrder"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-preserve-service"
        class: "preserve.service.PreserveServiceImpl"
        method: "checkSecurity"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-preserve-service"
        class: "preserve.service.PreserveServiceImpl"
        method: "createConsign"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-preserve-service"
        class: "preserve.service.PreserveServiceImpl"
        method: "createFoodOrder"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-preserve-service"
        class: "preserve.service.PreserveServiceImpl"
        method: "createOrder"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-preserve-service"
        class: "preserve.service.PreserveServiceImpl"
        method: "dipatchSeat"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-preserve-service"
        class: "preserve.service.PreserveServiceImpl"
        method: "getAccount"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-preserve-service"
        class: "preserve.service.PreserveServiceImpl"
        method: "getContactsById"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-preserve-service"
        class: "preserve.service.PreserveServiceImpl"
        method: "getServiceUrl"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-preserve-service"
        class: "preserve.service.PreserveServiceImpl"
        method: "getTripAllDetailInformation"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-preserve-service"
        class: "preserve.service.PreserveServiceImpl"
        method: "preserve"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-preserve-service"
        class: "preserve.service.PreserveServiceImpl"
        method: "queryForStationId"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-preserve-service"
        class: "preserve.service.PreserveServiceImpl"
        method: "sendEmail"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-preserve-service"
        class: "preserve.PreserveApplication"
        method: "main"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-preserve-service"
        class: "preserve.config.Queues"
        method: "emailQueue"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-preserve-service"
        class: "preserve.controller.PreserveController"
        method: "home"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-preserve-service"
        class: "preserve.controller.PreserveController"
        method: "preserve"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-preserve-service"
        class: "preserve.mq.RabbitSend"
        method: "send"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-preserve-service"
        class: "preserve.service.PreserveServiceImpl"
        method: "addAssuranceForOrder"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-preserve-service"
        class: "preserve.service.PreserveServiceImpl"
        method: "checkSecurity"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-preserve-service"
        class: "preserve.service.PreserveServiceImpl"
        method: "createConsign"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-preserve-service"
        class: "preserve.service.PreserveServiceImpl"
        method: "createFoodOrder"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-preserve-service"
        class: "preserve.service.PreserveServiceImpl"
        method: "createOrder"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-preserve-service"
        class: "preserve.service.PreserveServiceImpl"
        method: "dipatchSeat"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-preserve-service"
        class: "preserve.service.PreserveServiceImpl"
        method: "getAccount"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-preserve-service"
        class: "preserve.service.PreserveServiceImpl"
        method: "getContactsById"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-preserve-service"
        class: "preserve.service.PreserveServiceImpl"
        method: "getServiceUrl"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-preserve-service"
        class: "preserve.service.PreserveServiceImpl"
        method: "getTripAllDetailInformation"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-preserve-service"
        class: "preserve.service.PreserveServiceImpl"
        method: "preserve"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-preserve-service"
        class: "preserve.service.PreserveServiceImpl"
        method: "queryForStationId"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-preserve-service"
        class: "preserve.service.PreserveServiceImpl"
        method: "sendEmail"
        namespace: "ts"
