apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: "seed-genesis"
  instance: "seed"
  service: "ts-route-plan-service"
  system: "ts"
spec:
  replace_scope: "service"
  points:
    - capability: "http_request_replace_method"
      target:
        app: "ts-route-plan-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/routeservice/routes/*/*"
        port: 8080
        server_address: "ts-route-service"
        span_name: "GET"
    - capability: "http_request_replace_method"
      target:
        app: "ts-route-plan-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/routeservice/routes/*"
        port: 8080
        server_address: "ts-route-service"
        span_name: "GET"
    - capability: "http_request_replace_method"
      target:
        app: "ts-route-plan-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/travel2service/routes/*"
        port: 8080
        server_address: "ts-travel2-service"
        span_name: "GET"
    - capability: "http_request_replace_method"
      target:
        app: "ts-route-plan-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/travelservice/routes/*"
        port: 8080
        server_address: "ts-travel-service"
        span_name: "GET"
    - capability: "http_request_replace_method"
      target:
        app: "ts-route-plan-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/travel2service/trip_detail"
        port: 8080
        server_address: "ts-travel2-service"
        span_name: "POST"
    - capability: "http_request_replace_method"
      target:
        app: "ts-route-plan-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/travel2service/trips/left"
        port: 8080
        server_address: "ts-travel2-service"
        span_name: "POST"
    - capability: "http_request_replace_method"
      target:
        app: "ts-route-plan-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/travel2service/trips/routes"
        port: 8080
        server_address: "ts-travel2-service"
        span_name: "POST"
    - capability: "http_request_replace_method"
      target:
        app: "ts-route-plan-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/travelservice/trip_detail"
        port: 8080
        server_address: "ts-travel-service"
        span_name: "POST"
    - capability: "http_request_replace_method"
      target:
        app: "ts-route-plan-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/travelservice/trips/left"
        port: 8080
        server_address: "ts-travel-service"
        span_name: "POST"
    - capability: "http_request_replace_method"
      target:
        app: "ts-route-plan-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/travelservice/trips/routes"
        port: 8080
        server_address: "ts-travel-service"
        span_name: "POST"
    - capability: "http_request_replace_path"
      target:
        app: "ts-route-plan-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/routeservice/routes/*/*"
        port: 8080
        server_address: "ts-route-service"
        span_name: "GET"
    - capability: "http_request_replace_path"
      target:
        app: "ts-route-plan-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/routeservice/routes/*"
        port: 8080
        server_address: "ts-route-service"
        span_name: "GET"
    - capability: "http_request_replace_path"
      target:
        app: "ts-route-plan-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/travel2service/routes/*"
        port: 8080
        server_address: "ts-travel2-service"
        span_name: "GET"
    - capability: "http_request_replace_path"
      target:
        app: "ts-route-plan-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/travelservice/routes/*"
        port: 8080
        server_address: "ts-travel-service"
        span_name: "GET"
    - capability: "http_request_replace_path"
      target:
        app: "ts-route-plan-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/travel2service/trip_detail"
        port: 8080
        server_address: "ts-travel2-service"
        span_name: "POST"
    - capability: "http_request_replace_path"
      target:
        app: "ts-route-plan-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/travel2service/trips/left"
        port: 8080
        server_address: "ts-travel2-service"
        span_name: "POST"
    - capability: "http_request_replace_path"
      target:
        app: "ts-route-plan-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/travel2service/trips/routes"
        port: 8080
        server_address: "ts-travel2-service"
        span_name: "POST"
    - capability: "http_request_replace_path"
      target:
        app: "ts-route-plan-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/travelservice/trip_detail"
        port: 8080
        server_address: "ts-travel-service"
        span_name: "POST"
    - capability: "http_request_replace_path"
      target:
        app: "ts-route-plan-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/travelservice/trips/left"
        port: 8080
        server_address: "ts-travel-service"
        span_name: "POST"
    - capability: "http_request_replace_path"
      target:
        app: "ts-route-plan-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/travelservice/trips/routes"
        port: 8080
        server_address: "ts-travel-service"
        span_name: "POST"
    - capability: "http_response_abort"
      target:
        app: "ts-route-plan-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/routeservice/routes/*/*"
        port: 8080
        server_address: "ts-route-service"
        span_name: "GET"
    - capability: "http_response_abort"
      target:
        app: "ts-route-plan-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/routeservice/routes/*"
        port: 8080
        server_address: "ts-route-service"
        span_name: "GET"
    - capability: "http_response_abort"
      target:
        app: "ts-route-plan-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/travel2service/routes/*"
        port: 8080
        server_address: "ts-travel2-service"
        span_name: "GET"
    - capability: "http_response_abort"
      target:
        app: "ts-route-plan-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/travelservice/routes/*"
        port: 8080
        server_address: "ts-travel-service"
        span_name: "GET"
    - capability: "http_response_abort"
      target:
        app: "ts-route-plan-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/travel2service/trip_detail"
        port: 8080
        server_address: "ts-travel2-service"
        span_name: "POST"
    - capability: "http_response_abort"
      target:
        app: "ts-route-plan-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/travel2service/trips/left"
        port: 8080
        server_address: "ts-travel2-service"
        span_name: "POST"
    - capability: "http_response_abort"
      target:
        app: "ts-route-plan-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/travel2service/trips/routes"
        port: 8080
        server_address: "ts-travel2-service"
        span_name: "POST"
    - capability: "http_response_abort"
      target:
        app: "ts-route-plan-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/travelservice/trip_detail"
        port: 8080
        server_address: "ts-travel-service"
        span_name: "POST"
    - capability: "http_response_abort"
      target:
        app: "ts-route-plan-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/travelservice/trips/left"
        port: 8080
        server_address: "ts-travel-service"
        span_name: "POST"
    - capability: "http_response_abort"
      target:
        app: "ts-route-plan-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/travelservice/trips/routes"
        port: 8080
        server_address: "ts-travel-service"
        span_name: "POST"
    - capability: "http_response_delay"
      target:
        app: "ts-route-plan-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/routeservice/routes/*/*"
        port: 8080
        server_address: "ts-route-service"
        span_name: "GET"
    - capability: "http_response_delay"
      target:
        app: "ts-route-plan-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/routeservice/routes/*"
        port: 8080
        server_address: "ts-route-service"
        span_name: "GET"
    - capability: "http_response_delay"
      target:
        app: "ts-route-plan-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/travel2service/routes/*"
        port: 8080
        server_address: "ts-travel2-service"
        span_name: "GET"
    - capability: "http_response_delay"
      target:
        app: "ts-route-plan-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/travelservice/routes/*"
        port: 8080
        server_address: "ts-travel-service"
        span_name: "GET"
    - capability: "http_response_delay"
      target:
        app: "ts-route-plan-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/travel2service/trip_detail"
        port: 8080
        server_address: "ts-travel2-service"
        span_name: "POST"
    - capability: "http_response_delay"
      target:
        app: "ts-route-plan-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/travel2service/trips/left"
        port: 8080
        server_address: "ts-travel2-service"
        span_name: "POST"
    - capability: "http_response_delay"
      target:
        app: "ts-route-plan-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/travel2service/trips/routes"
        port: 8080
        server_address: "ts-travel2-service"
        span_name: "POST"
    - capability: "http_response_delay"
      target:
        app: "ts-route-plan-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/travelservice/trip_detail"
        port: 8080
        server_address: "ts-travel-service"
        span_name: "POST"
    - capability: "http_response_delay"
      target:
        app: "ts-route-plan-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/travelservice/trips/left"
        port: 8080
        server_address: "ts-travel-service"
        span_name: "POST"
    - capability: "http_response_delay"
      target:
        app: "ts-route-plan-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/travelservice/trips/routes"
        port: 8080
        server_address: "ts-travel-service"
        span_name: "POST"
    - capability: "http_response_patch_body"
      target:
        app: "ts-route-plan-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/routeservice/routes/*/*"
        port: 8080
        server_address: "ts-route-service"
        span_name: "GET"
    - capability: "http_response_patch_body"
      target:
        app: "ts-route-plan-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/routeservice/routes/*"
        port: 8080
        server_address: "ts-route-service"
        span_name: "GET"
    - capability: "http_response_patch_body"
      target:
        app: "ts-route-plan-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/travel2service/routes/*"
        port: 8080
        server_address: "ts-travel2-service"
        span_name: "GET"
    - capability: "http_response_patch_body"
      target:
        app: "ts-route-plan-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/travelservice/routes/*"
        port: 8080
        server_address: "ts-travel-service"
        span_name: "GET"
    - capability: "http_response_patch_body"
      target:
        app: "ts-route-plan-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/travel2service/trip_detail"
        port: 8080
        server_address: "ts-travel2-service"
        span_name: "POST"
    - capability: "http_response_patch_body"
      target:
        app: "ts-route-plan-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/travel2service/trips/left"
        port: 8080
        server_address: "ts-travel2-service"
        span_name: "POST"
    - capability: "http_response_patch_body"
      target:
        app: "ts-route-plan-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/travel2service/trips/routes"
        port: 8080
        server_address: "ts-travel2-service"
        span_name: "POST"
    - capability: "http_response_patch_body"
      target:
        app: "ts-route-plan-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/travelservice/trip_detail"
        port: 8080
        server_address: "ts-travel-service"
        span_name: "POST"
    - capability: "http_response_patch_body"
      target:
        app: "ts-route-plan-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/travelservice/trips/left"
        port: 8080
        server_address: "ts-travel-service"
        span_name: "POST"
    - capability: "http_response_patch_body"
      target:
        app: "ts-route-plan-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/travelservice/trips/routes"
        port: 8080
        server_address: "ts-travel-service"
        span_name: "POST"
    - capability: "http_response_replace_body"
      target:
        app: "ts-route-plan-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/routeservice/routes/*/*"
        port: 8080
        server_address: "ts-route-service"
        span_name: "GET"
    - capability: "http_response_replace_body"
      target:
        app: "ts-route-plan-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/routeservice/routes/*"
        port: 8080
        server_address: "ts-route-service"
        span_name: "GET"
    - capability: "http_response_replace_body"
      target:
        app: "ts-route-plan-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/travel2service/routes/*"
        port: 8080
        server_address: "ts-travel2-service"
        span_name: "GET"
    - capability: "http_response_replace_body"
      target:
        app: "ts-route-plan-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/travelservice/routes/*"
        port: 8080
        server_address: "ts-travel-service"
        span_name: "GET"
    - capability: "http_response_replace_body"
      target:
        app: "ts-route-plan-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/travel2service/trip_detail"
        port: 8080
        server_address: "ts-travel2-service"
        span_name: "POST"
    - capability: "http_response_replace_body"
      target:
        app: "ts-route-plan-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/travel2service/trips/left"
        port: 8080
        server_address: "ts-travel2-service"
        span_name: "POST"
    - capability: "http_response_replace_body"
      target:
        app: "ts-route-plan-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/travel2service/trips/routes"
        port: 8080
        server_address: "ts-travel2-service"
        span_name: "POST"
    - capability: "http_response_replace_body"
      target:
        app: "ts-route-plan-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/travelservice/trip_detail"
        port: 8080
        server_address: "ts-travel-service"
        span_name: "POST"
    - capability: "http_response_replace_body"
      target:
        app: "ts-route-plan-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/travelservice/trips/left"
        port: 8080
        server_address: "ts-travel-service"
        span_name: "POST"
    - capability: "http_response_replace_body"
      target:
        app: "ts-route-plan-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/travelservice/trips/routes"
        port: 8080
        server_address: "ts-travel-service"
        span_name: "POST"
    - capability: "http_response_replace_code"
      target:
        app: "ts-route-plan-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/routeservice/routes/*/*"
        port: 8080
        server_address: "ts-route-service"
        span_name: "GET"
    - capability: "http_response_replace_code"
      target:
        app: "ts-route-plan-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/routeservice/routes/*"
        port: 8080
        server_address: "ts-route-service"
        span_name: "GET"
    - capability: "http_response_replace_code"
      target:
        app: "ts-route-plan-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/travel2service/routes/*"
        port: 8080
        server_address: "ts-travel2-service"
        span_name: "GET"
    - capability: "http_response_replace_code"
      target:
        app: "ts-route-plan-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/travelservice/routes/*"
        port: 8080
        server_address: "ts-travel-service"
        span_name: "GET"
    - capability: "http_response_replace_code"
      target:
        app: "ts-route-plan-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/travel2service/trip_detail"
        port: 8080
        server_address: "ts-travel2-service"
        span_name: "POST"
    - capability: "http_response_replace_code"
      target:
        app: "ts-route-plan-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/travel2service/trips/left"
        port: 8080
        server_address: "ts-travel2-service"
        span_name: "POST"
    - capability: "http_response_replace_code"
      target:
        app: "ts-route-plan-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/travel2service/trips/routes"
        port: 8080
        server_address: "ts-travel2-service"
        span_name: "POST"
    - capability: "http_response_replace_code"
      target:
        app: "ts-route-plan-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/travelservice/trip_detail"
        port: 8080
        server_address: "ts-travel-service"
        span_name: "POST"
    - capability: "http_response_replace_code"
      target:
        app: "ts-route-plan-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/travelservice/trips/left"
        port: 8080
        server_address: "ts-travel-service"
        span_name: "POST"
    - capability: "http_response_replace_code"
      target:
        app: "ts-route-plan-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/travelservice/trips/routes"
        port: 8080
        server_address: "ts-travel-service"
        span_name: "POST"
