apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: "seed-genesis"
  instance: "seed"
  service: "ts-rebook-service"
  system: "ts"
spec:
  replace_scope: "service"
  points:
    - capability: "container_kill"
      target:
        app: "ts-rebook-service"
        container: "ts-rebook-service"
        namespace: "ts"
    - capability: "cpu_stress"
      target:
        app: "ts-rebook-service"
        container: "ts-rebook-service"
        namespace: "ts"
    - capability: "http_request_abort"
      target:
        app: "ts-rebook-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/orderOtherService/orderOther/*"
        port: 8080
    - capability: "http_request_delay"
      target:
        app: "ts-rebook-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/orderOtherService/orderOther/*"
        port: 8080
    - capability: "jvm_method_latency"
      target:
        app: "ts-rebook-service"
        class: "rebook.RebookApplication"
        method: "main"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-rebook-service"
        class: "rebook.controller.RebookController"
        method: "home"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-rebook-service"
        class: "rebook.controller.RebookController"
        method: "payDifference"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-rebook-service"
        class: "rebook.controller.RebookController"
        method: "rebook"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-rebook-service"
        class: "rebook.service.RebookServiceImpl"
        method: "checkTime"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-rebook-service"
        class: "rebook.service.RebookServiceImpl"
        method: "createOrder"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-rebook-service"
        class: "rebook.service.RebookServiceImpl"
        method: "deleteOrder"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-rebook-service"
        class: "rebook.service.RebookServiceImpl"
        method: "dipatchSeat"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-rebook-service"
        class: "rebook.service.RebookServiceImpl"
        method: "drawBackMoney"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-rebook-service"
        class: "rebook.service.RebookServiceImpl"
        method: "getAuthorizationHeadersFrom"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-rebook-service"
        class: "rebook.service.RebookServiceImpl"
        method: "getOrderByRebookInfo"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-rebook-service"
        class: "rebook.service.RebookServiceImpl"
        method: "getRouteByRouteId"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-rebook-service"
        class: "rebook.service.RebookServiceImpl"
        method: "getServiceUrl"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-rebook-service"
        class: "rebook.service.RebookServiceImpl"
        method: "getTripAllDetailInformation"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-rebook-service"
        class: "rebook.service.RebookServiceImpl"
        method: "payDifference"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-rebook-service"
        class: "rebook.service.RebookServiceImpl"
        method: "payDifferentMoney"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-rebook-service"
        class: "rebook.service.RebookServiceImpl"
        method: "queryTrainTypeByName"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-rebook-service"
        class: "rebook.service.RebookServiceImpl"
        method: "rebook"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-rebook-service"
        class: "rebook.service.RebookServiceImpl"
        method: "tripGD"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-rebook-service"
        class: "rebook.service.RebookServiceImpl"
        method: "updateOrder"
        namespace: "ts"
    - capability: "memory_stress"
      target:
        app: "ts-rebook-service"
        container: "ts-rebook-service"
        namespace: "ts"
    - capability: "pod_failure"
      target:
        app: "ts-rebook-service"
        namespace: "ts"
    - capability: "pod_kill"
      target:
        app: "ts-rebook-service"
        namespace: "ts"
    - capability: "time_skew"
      target:
        app: "ts-rebook-service"
        container: "ts-rebook-service"
        namespace: "ts"
