apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: "seed-genesis"
  instance: "seed"
  service: "ts-station-food-service"
  system: "ts"
spec:
  replace_scope: "service"
  points:
    - capability: "dns_error"
      target:
        app: "ts-station-food-service"
        domain_patterns:
          - "mysql"
        namespace: "ts"
    - capability: "dns_random"
      target:
        app: "ts-station-food-service"
        domain_patterns:
          - "mysql"
        namespace: "ts"
