apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: "seed-genesis"
  instance: "seed"
  service: "ts-station-food-service"
  system: "ts"
spec:
  replace_scope: "service"
  points:
    - capability: "container_kill"
      target:
        app: "ts-station-food-service"
        container: "ts-station-food-service"
        namespace: "ts"
    - capability: "cpu_stress"
      target:
        app: "ts-station-food-service"
        container: "ts-station-food-service"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-station-food-service"
        class: "food.StationFoodApplication"
        method: "main"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-station-food-service"
        class: "food.controller.StationFoodController"
        method: "getAllFoodStores"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-station-food-service"
        class: "food.controller.StationFoodController"
        method: "getFoodListByStationFoodStoreId"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-station-food-service"
        class: "food.controller.StationFoodController"
        method: "getFoodStoresByStationNames"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-station-food-service"
        class: "food.controller.StationFoodController"
        method: "getFoodStoresOfStation"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-station-food-service"
        class: "food.controller.StationFoodController"
        method: "home"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-station-food-service"
        class: "food.entity.StationFoodStore"
        method: "StationFoodStore"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-station-food-service"
        class: "food.init.InitData"
        method: "run"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-station-food-service"
        class: "food.init.InitData"
        method: "toFoodList"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-station-food-service"
        class: "food.service.StationFoodServiceImpl"
        method: "createFoodStore"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-station-food-service"
        class: "food.service.StationFoodServiceImpl"
        method: "getFoodStoresByStationNames"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-station-food-service"
        class: "food.service.StationFoodServiceImpl"
        method: "getStaionFoodStoreById"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-station-food-service"
        class: "food.service.StationFoodServiceImpl"
        method: "listFoodStores"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-station-food-service"
        class: "food.service.StationFoodServiceImpl"
        method: "listFoodStoresByStationName"
        namespace: "ts"
    - capability: "pod_failure"
      target:
        app: "ts-station-food-service"
        namespace: "ts"
    - capability: "pod_kill"
      target:
        app: "ts-station-food-service"
        namespace: "ts"
    - capability: "time_skew"
      target:
        app: "ts-station-food-service"
        container: "ts-station-food-service"
        namespace: "ts"
