apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: "seed-genesis"
  instance: "seed"
  service: "ts-seat-service"
  system: "ts"
spec:
  replace_scope: "service"
  points:
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-seat-service"
        class: "seat.SeatApplication"
        method: "main"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-seat-service"
        class: "seat.controller.SeatController"
        method: "create"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-seat-service"
        class: "seat.controller.SeatController"
        method: "getLeftTicketOfInterval"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-seat-service"
        class: "seat.controller.SeatController"
        method: "home"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-seat-service"
        class: "seat.service.SeatServiceImpl"
        method: "distributeSeat"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-seat-service"
        class: "seat.service.SeatServiceImpl"
        method: "getDirectProportion"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-seat-service"
        class: "seat.service.SeatServiceImpl"
        method: "getLeftTicketOfInterval"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-seat-service"
        class: "seat.service.SeatServiceImpl"
        method: "getServiceUrl"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-seat-service"
        class: "seat.service.SeatServiceImpl"
        method: "isContained"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-seat-service"
        class: "seat.SeatApplication"
        method: "main"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-seat-service"
        class: "seat.controller.SeatController"
        method: "create"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-seat-service"
        class: "seat.controller.SeatController"
        method: "getLeftTicketOfInterval"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-seat-service"
        class: "seat.controller.SeatController"
        method: "home"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-seat-service"
        class: "seat.service.SeatServiceImpl"
        method: "distributeSeat"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-seat-service"
        class: "seat.service.SeatServiceImpl"
        method: "getDirectProportion"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-seat-service"
        class: "seat.service.SeatServiceImpl"
        method: "getLeftTicketOfInterval"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-seat-service"
        class: "seat.service.SeatServiceImpl"
        method: "getServiceUrl"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-seat-service"
        class: "seat.service.SeatServiceImpl"
        method: "isContained"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-seat-service"
        class: "seat.SeatApplication"
        method: "main"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-seat-service"
        class: "seat.controller.SeatController"
        method: "create"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-seat-service"
        class: "seat.controller.SeatController"
        method: "getLeftTicketOfInterval"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-seat-service"
        class: "seat.controller.SeatController"
        method: "home"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-seat-service"
        class: "seat.service.SeatServiceImpl"
        method: "distributeSeat"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-seat-service"
        class: "seat.service.SeatServiceImpl"
        method: "getDirectProportion"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-seat-service"
        class: "seat.service.SeatServiceImpl"
        method: "getLeftTicketOfInterval"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-seat-service"
        class: "seat.service.SeatServiceImpl"
        method: "getServiceUrl"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-seat-service"
        class: "seat.service.SeatServiceImpl"
        method: "isContained"
        namespace: "ts"
