apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: "seed-genesis"
  instance: "seed"
  service: "ts-station-service"
  system: "ts"
spec:
  replace_scope: "service"
  points:
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.StationApplication"
        method: "main"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.controller.StationController"
        method: "create"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.controller.StationController"
        method: "delete"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.controller.StationController"
        method: "home"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.controller.StationController"
        method: "query"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.controller.StationController"
        method: "queryById"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.controller.StationController"
        method: "queryForIdBatch"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.controller.StationController"
        method: "queryForNameBatch"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.controller.StationController"
        method: "queryForStationId"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.controller.StationController"
        method: "update"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.entity.Station"
        method: "Station"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.entity.Station"
        method: "setName"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.init.InitData"
        method: "run"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.service.StationServiceImpl"
        method: "create"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.service.StationServiceImpl"
        method: "delete"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.service.StationServiceImpl"
        method: "exist"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.service.StationServiceImpl"
        method: "query"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.service.StationServiceImpl"
        method: "queryById"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.service.StationServiceImpl"
        method: "queryByIdBatch"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.service.StationServiceImpl"
        method: "queryForId"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.service.StationServiceImpl"
        method: "queryForIdBatch"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.service.StationServiceImpl"
        method: "update"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.StationApplication"
        method: "main"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.controller.StationController"
        method: "create"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.controller.StationController"
        method: "delete"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.controller.StationController"
        method: "home"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.controller.StationController"
        method: "query"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.controller.StationController"
        method: "queryById"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.controller.StationController"
        method: "queryForIdBatch"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.controller.StationController"
        method: "queryForNameBatch"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.controller.StationController"
        method: "queryForStationId"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.controller.StationController"
        method: "update"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.entity.Station"
        method: "Station"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.entity.Station"
        method: "setName"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.init.InitData"
        method: "run"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.service.StationServiceImpl"
        method: "create"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.service.StationServiceImpl"
        method: "delete"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.service.StationServiceImpl"
        method: "exist"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.service.StationServiceImpl"
        method: "query"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.service.StationServiceImpl"
        method: "queryById"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.service.StationServiceImpl"
        method: "queryByIdBatch"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.service.StationServiceImpl"
        method: "queryForId"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.service.StationServiceImpl"
        method: "queryForIdBatch"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.service.StationServiceImpl"
        method: "update"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.StationApplication"
        method: "main"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.controller.StationController"
        method: "create"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.controller.StationController"
        method: "delete"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.controller.StationController"
        method: "home"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.controller.StationController"
        method: "query"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.controller.StationController"
        method: "queryById"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.controller.StationController"
        method: "queryForIdBatch"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.controller.StationController"
        method: "queryForNameBatch"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.controller.StationController"
        method: "queryForStationId"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.controller.StationController"
        method: "update"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.entity.Station"
        method: "Station"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.entity.Station"
        method: "setName"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.init.InitData"
        method: "run"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.service.StationServiceImpl"
        method: "create"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.service.StationServiceImpl"
        method: "delete"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.service.StationServiceImpl"
        method: "exist"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.service.StationServiceImpl"
        method: "query"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.service.StationServiceImpl"
        method: "queryById"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.service.StationServiceImpl"
        method: "queryByIdBatch"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.service.StationServiceImpl"
        method: "queryForId"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.service.StationServiceImpl"
        method: "queryForIdBatch"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.service.StationServiceImpl"
        method: "update"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.StationApplication"
        method: "main"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.controller.StationController"
        method: "create"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.controller.StationController"
        method: "delete"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.controller.StationController"
        method: "home"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.controller.StationController"
        method: "query"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.controller.StationController"
        method: "queryById"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.controller.StationController"
        method: "queryForIdBatch"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.controller.StationController"
        method: "queryForNameBatch"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.controller.StationController"
        method: "queryForStationId"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.controller.StationController"
        method: "update"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.entity.Station"
        method: "Station"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.entity.Station"
        method: "setName"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.init.InitData"
        method: "run"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.service.StationServiceImpl"
        method: "create"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.service.StationServiceImpl"
        method: "delete"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.service.StationServiceImpl"
        method: "exist"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.service.StationServiceImpl"
        method: "query"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.service.StationServiceImpl"
        method: "queryById"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.service.StationServiceImpl"
        method: "queryByIdBatch"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.service.StationServiceImpl"
        method: "queryForId"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.service.StationServiceImpl"
        method: "queryForIdBatch"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-station-service"
        class: "fdse.microservice.service.StationServiceImpl"
        method: "update"
        namespace: "ts"
