apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: "seed-genesis"
  instance: "seed"
  service: "ts-station-food-service"
  system: "ts"
spec:
  replace_scope: "service"
  points:
    - capability: "jvm_mysql_exception"
      target:
        app: "ts-station-food-service"
        db_name: "ts"
        namespace: "ts"
        sql_type: "all"
        table: "`ts`.`station_food_list`"
    - capability: "jvm_mysql_exception"
      target:
        app: "ts-station-food-service"
        db_name: "ts"
        namespace: "ts"
        sql_type: "insert"
        table: "station_food_list"
    - capability: "jvm_mysql_exception"
      target:
        app: "ts-station-food-service"
        db_name: "ts"
        namespace: "ts"
        sql_type: "insert"
        table: "station_food_store"
    - capability: "jvm_mysql_exception"
      target:
        app: "ts-station-food-service"
        db_name: "ts"
        namespace: "ts"
        sql_type: "select"
        table: "`ts`.`station_food_store`"
    - capability: "jvm_mysql_exception"
      target:
        app: "ts-station-food-service"
        db_name: "ts"
        namespace: "ts"
        sql_type: "select"
        table: "information_schema"
    - capability: "jvm_mysql_exception"
      target:
        app: "ts-station-food-service"
        db_name: "ts"
        namespace: "ts"
        sql_type: "select"
        table: "mysql"
    - capability: "jvm_mysql_exception"
      target:
        app: "ts-station-food-service"
        db_name: "ts"
        namespace: "ts"
        sql_type: "select"
        table: "performance_schema"
    - capability: "jvm_mysql_exception"
      target:
        app: "ts-station-food-service"
        db_name: "ts"
        namespace: "ts"
        sql_type: "select"
        table: "station_food_list"
    - capability: "jvm_mysql_exception"
      target:
        app: "ts-station-food-service"
        db_name: "ts"
        namespace: "ts"
        sql_type: "select"
        table: "station_food_store"
    - capability: "jvm_mysql_exception"
      target:
        app: "ts-station-food-service"
        db_name: "ts"
        namespace: "ts"
        sql_type: "select"
        table: "sys"
    - capability: "jvm_mysql_exception"
      target:
        app: "ts-station-food-service"
        db_name: "ts"
        namespace: "ts"
        sql_type: "select"
        table: "ts"
    - capability: "jvm_mysql_latency"
      target:
        app: "ts-station-food-service"
        db_name: "ts"
        namespace: "ts"
        sql_type: "all"
        table: "`ts`.`station_food_list`"
    - capability: "jvm_mysql_latency"
      target:
        app: "ts-station-food-service"
        db_name: "ts"
        namespace: "ts"
        sql_type: "insert"
        table: "station_food_list"
    - capability: "jvm_mysql_latency"
      target:
        app: "ts-station-food-service"
        db_name: "ts"
        namespace: "ts"
        sql_type: "insert"
        table: "station_food_store"
    - capability: "jvm_mysql_latency"
      target:
        app: "ts-station-food-service"
        db_name: "ts"
        namespace: "ts"
        sql_type: "select"
        table: "`ts`.`station_food_store`"
    - capability: "jvm_mysql_latency"
      target:
        app: "ts-station-food-service"
        db_name: "ts"
        namespace: "ts"
        sql_type: "select"
        table: "information_schema"
    - capability: "jvm_mysql_latency"
      target:
        app: "ts-station-food-service"
        db_name: "ts"
        namespace: "ts"
        sql_type: "select"
        table: "mysql"
    - capability: "jvm_mysql_latency"
      target:
        app: "ts-station-food-service"
        db_name: "ts"
        namespace: "ts"
        sql_type: "select"
        table: "performance_schema"
    - capability: "jvm_mysql_latency"
      target:
        app: "ts-station-food-service"
        db_name: "ts"
        namespace: "ts"
        sql_type: "select"
        table: "station_food_list"
    - capability: "jvm_mysql_latency"
      target:
        app: "ts-station-food-service"
        db_name: "ts"
        namespace: "ts"
        sql_type: "select"
        table: "station_food_store"
    - capability: "jvm_mysql_latency"
      target:
        app: "ts-station-food-service"
        db_name: "ts"
        namespace: "ts"
        sql_type: "select"
        table: "sys"
    - capability: "jvm_mysql_latency"
      target:
        app: "ts-station-food-service"
        db_name: "ts"
        namespace: "ts"
        sql_type: "select"
        table: "ts"
