apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: seed-genesis
  instance: seed
  service: ts-seat-service
  system: ts
spec:
  points:
  - capability: network_bandwidth
    target:
      namespace: ts
      source_app: ts-seat-service
      target_service: ts-config-service
  - capability: network_bandwidth
    target:
      namespace: ts
      source_app: ts-seat-service
      target_service: ts-order-other-service
  - capability: network_bandwidth
    target:
      namespace: ts
      source_app: ts-seat-service
      target_service: ts-order-service
  - capability: network_corrupt
    target:
      namespace: ts
      source_app: ts-seat-service
      target_service: ts-config-service
  - capability: network_corrupt
    target:
      namespace: ts
      source_app: ts-seat-service
      target_service: ts-order-other-service
  - capability: network_corrupt
    target:
      namespace: ts
      source_app: ts-seat-service
      target_service: ts-order-service
  - capability: network_delay
    target:
      namespace: ts
      source_app: ts-seat-service
      target_service: ts-config-service
  - capability: network_delay
    target:
      namespace: ts
      source_app: ts-seat-service
      target_service: ts-order-other-service
  - capability: network_delay
    target:
      namespace: ts
      source_app: ts-seat-service
      target_service: ts-order-service
  - capability: network_duplicate
    target:
      namespace: ts
      source_app: ts-seat-service
      target_service: ts-config-service
  - capability: network_duplicate
    target:
      namespace: ts
      source_app: ts-seat-service
      target_service: ts-order-other-service
  - capability: network_duplicate
    target:
      namespace: ts
      source_app: ts-seat-service
      target_service: ts-order-service
  - capability: network_loss
    target:
      namespace: ts
      source_app: ts-seat-service
      target_service: ts-config-service
  - capability: network_loss
    target:
      namespace: ts
      source_app: ts-seat-service
      target_service: ts-order-other-service
  - capability: network_loss
    target:
      namespace: ts
      source_app: ts-seat-service
      target_service: ts-order-service
  - capability: network_partition
    target:
      namespace: ts
      source_app: ts-seat-service
      target_service: ts-config-service
  - capability: network_partition
    target:
      namespace: ts
      source_app: ts-seat-service
      target_service: ts-order-other-service
  - capability: network_partition
    target:
      namespace: ts
      source_app: ts-seat-service
      target_service: ts-order-service
  replace_scope: service
