apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: "seed-genesis"
  instance: "seed"
  service: "ts-security-service"
  system: "ts"
spec:
  replace_scope: "service"
  points:
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-security-service"
        class: "security.SecurityApplication"
        method: "main"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-security-service"
        class: "security.controller.SecurityController"
        method: "check"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-security-service"
        class: "security.controller.SecurityController"
        method: "create"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-security-service"
        class: "security.controller.SecurityController"
        method: "delete"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-security-service"
        class: "security.controller.SecurityController"
        method: "findAllSecurityConfig"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-security-service"
        class: "security.controller.SecurityController"
        method: "home"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-security-service"
        class: "security.controller.SecurityController"
        method: "update"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-security-service"
        class: "security.init.InitData"
        method: "run"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-security-service"
        class: "security.service.SecurityServiceImpl"
        method: "addNewSecurityConfig"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-security-service"
        class: "security.service.SecurityServiceImpl"
        method: "check"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-security-service"
        class: "security.service.SecurityServiceImpl"
        method: "deleteSecurityConfig"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-security-service"
        class: "security.service.SecurityServiceImpl"
        method: "findAllSecurityConfig"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-security-service"
        class: "security.service.SecurityServiceImpl"
        method: "getSecurityOrderInfoFromOrder"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-security-service"
        class: "security.service.SecurityServiceImpl"
        method: "getSecurityOrderOtherInfoFromOrder"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-security-service"
        class: "security.service.SecurityServiceImpl"
        method: "getServiceUrl"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-security-service"
        class: "security.service.SecurityServiceImpl"
        method: "modifySecurityConfig"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-security-service"
        class: "security.SecurityApplication"
        method: "main"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-security-service"
        class: "security.controller.SecurityController"
        method: "check"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-security-service"
        class: "security.controller.SecurityController"
        method: "create"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-security-service"
        class: "security.controller.SecurityController"
        method: "delete"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-security-service"
        class: "security.controller.SecurityController"
        method: "findAllSecurityConfig"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-security-service"
        class: "security.controller.SecurityController"
        method: "home"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-security-service"
        class: "security.controller.SecurityController"
        method: "update"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-security-service"
        class: "security.init.InitData"
        method: "run"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-security-service"
        class: "security.service.SecurityServiceImpl"
        method: "addNewSecurityConfig"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-security-service"
        class: "security.service.SecurityServiceImpl"
        method: "check"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-security-service"
        class: "security.service.SecurityServiceImpl"
        method: "deleteSecurityConfig"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-security-service"
        class: "security.service.SecurityServiceImpl"
        method: "findAllSecurityConfig"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-security-service"
        class: "security.service.SecurityServiceImpl"
        method: "getSecurityOrderInfoFromOrder"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-security-service"
        class: "security.service.SecurityServiceImpl"
        method: "getSecurityOrderOtherInfoFromOrder"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-security-service"
        class: "security.service.SecurityServiceImpl"
        method: "getServiceUrl"
        namespace: "ts"
    - capability: "jvm_memory_stress"
      target:
        app: "ts-security-service"
        class: "security.service.SecurityServiceImpl"
        method: "modifySecurityConfig"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-security-service"
        class: "security.SecurityApplication"
        method: "main"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-security-service"
        class: "security.controller.SecurityController"
        method: "check"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-security-service"
        class: "security.controller.SecurityController"
        method: "create"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-security-service"
        class: "security.controller.SecurityController"
        method: "delete"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-security-service"
        class: "security.controller.SecurityController"
        method: "findAllSecurityConfig"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-security-service"
        class: "security.controller.SecurityController"
        method: "home"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-security-service"
        class: "security.controller.SecurityController"
        method: "update"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-security-service"
        class: "security.init.InitData"
        method: "run"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-security-service"
        class: "security.service.SecurityServiceImpl"
        method: "addNewSecurityConfig"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-security-service"
        class: "security.service.SecurityServiceImpl"
        method: "check"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-security-service"
        class: "security.service.SecurityServiceImpl"
        method: "deleteSecurityConfig"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-security-service"
        class: "security.service.SecurityServiceImpl"
        method: "findAllSecurityConfig"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-security-service"
        class: "security.service.SecurityServiceImpl"
        method: "getSecurityOrderInfoFromOrder"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-security-service"
        class: "security.service.SecurityServiceImpl"
        method: "getSecurityOrderOtherInfoFromOrder"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-security-service"
        class: "security.service.SecurityServiceImpl"
        method: "getServiceUrl"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-security-service"
        class: "security.service.SecurityServiceImpl"
        method: "modifySecurityConfig"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-security-service"
        class: "security.SecurityApplication"
        method: "main"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-security-service"
        class: "security.controller.SecurityController"
        method: "check"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-security-service"
        class: "security.controller.SecurityController"
        method: "create"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-security-service"
        class: "security.controller.SecurityController"
        method: "delete"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-security-service"
        class: "security.controller.SecurityController"
        method: "findAllSecurityConfig"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-security-service"
        class: "security.controller.SecurityController"
        method: "home"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-security-service"
        class: "security.controller.SecurityController"
        method: "update"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-security-service"
        class: "security.init.InitData"
        method: "run"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-security-service"
        class: "security.service.SecurityServiceImpl"
        method: "addNewSecurityConfig"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-security-service"
        class: "security.service.SecurityServiceImpl"
        method: "check"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-security-service"
        class: "security.service.SecurityServiceImpl"
        method: "deleteSecurityConfig"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-security-service"
        class: "security.service.SecurityServiceImpl"
        method: "findAllSecurityConfig"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-security-service"
        class: "security.service.SecurityServiceImpl"
        method: "getSecurityOrderInfoFromOrder"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-security-service"
        class: "security.service.SecurityServiceImpl"
        method: "getSecurityOrderOtherInfoFromOrder"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-security-service"
        class: "security.service.SecurityServiceImpl"
        method: "getServiceUrl"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-security-service"
        class: "security.service.SecurityServiceImpl"
        method: "modifySecurityConfig"
        namespace: "ts"
