apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: "seed-genesis"
  instance: "seed"
  service: "ts-travel2-service"
  system: "ts"
spec:
  replace_scope: "service"
  points:
    - capability: "jvm_mysql_exception"
      target:
        app: "ts-travel2-service"
        db_name: "ts"
        namespace: "ts"
        sql_type: "insert"
        table: "trip2"
    - capability: "jvm_mysql_exception"
      target:
        app: "ts-travel2-service"
        db_name: "ts"
        namespace: "ts"
        sql_type: "select"
        table: "trip2"
    - capability: "jvm_mysql_exception"
      target:
        app: "ts-travel2-service"
        db_name: "ts"
        namespace: "ts"
        sql_type: "select"
        table: "ts"
    - capability: "jvm_mysql_latency"
      target:
        app: "ts-travel2-service"
        db_name: "ts"
        namespace: "ts"
        sql_type: "insert"
        table: "trip2"
    - capability: "jvm_mysql_latency"
      target:
        app: "ts-travel2-service"
        db_name: "ts"
        namespace: "ts"
        sql_type: "select"
        table: "trip2"
    - capability: "jvm_mysql_latency"
      target:
        app: "ts-travel2-service"
        db_name: "ts"
        namespace: "ts"
        sql_type: "select"
        table: "ts"
