apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: "seed-genesis"
  instance: "seed"
  service: "ts-train-service"
  system: "ts"
spec:
  replace_scope: "service"
  points:
    - capability: "container_kill"
      target:
        app: "ts-train-service"
        container: "ts-train-service"
        namespace: "ts"
    - capability: "cpu_stress"
      target:
        app: "ts-train-service"
        container: "ts-train-service"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-train-service"
        class: "train.TrainApplication"
        method: "main"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-train-service"
        class: "train.controller.TrainController"
        method: "create"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-train-service"
        class: "train.controller.TrainController"
        method: "delete"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-train-service"
        class: "train.controller.TrainController"
        method: "home"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-train-service"
        class: "train.controller.TrainController"
        method: "query"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-train-service"
        class: "train.controller.TrainController"
        method: "retrieve"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-train-service"
        class: "train.controller.TrainController"
        method: "retrieveByName"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-train-service"
        class: "train.controller.TrainController"
        method: "update"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-train-service"
        class: "train.entity.TrainType"
        method: "TrainType"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-train-service"
        class: "train.init.InitData"
        method: "run"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-train-service"
        class: "train.service.TrainServiceImpl"
        method: "create"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-train-service"
        class: "train.service.TrainServiceImpl"
        method: "delete"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-train-service"
        class: "train.service.TrainServiceImpl"
        method: "query"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-train-service"
        class: "train.service.TrainServiceImpl"
        method: "retrieve"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-train-service"
        class: "train.service.TrainServiceImpl"
        method: "retrieveByName"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-train-service"
        class: "train.service.TrainServiceImpl"
        method: "retrieveByNames"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-train-service"
        class: "train.service.TrainServiceImpl"
        method: "update"
        namespace: "ts"
    - capability: "pod_failure"
      target:
        app: "ts-train-service"
        namespace: "ts"
    - capability: "pod_kill"
      target:
        app: "ts-train-service"
        namespace: "ts"
    - capability: "time_skew"
      target:
        app: "ts-train-service"
        container: "ts-train-service"
        namespace: "ts"
