apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: "seed-genesis"
  instance: "seed"
  service: "ts-travel-plan-service"
  system: "ts"
spec:
  replace_scope: "service"
  points:
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-travel-plan-service"
        class: "travelplan.TravelPlanApplication"
        method: "main"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-travel-plan-service"
        class: "travelplan.controller.TravelPlanController"
        method: "getByCheapest"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-travel-plan-service"
        class: "travelplan.controller.TravelPlanController"
        method: "getByMinStation"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-travel-plan-service"
        class: "travelplan.controller.TravelPlanController"
        method: "getByQuickest"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-travel-plan-service"
        class: "travelplan.controller.TravelPlanController"
        method: "getTransferResult"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-travel-plan-service"
        class: "travelplan.controller.TravelPlanController"
        method: "home"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-travel-plan-service"
        class: "travelplan.entity.TransferTravelInfo"
        method: "TransferTravelInfo"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-travel-plan-service"
        class: "travelplan.entity.TransferTravelInfo"
        method: "getTravelDate"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-travel-plan-service"
        class: "travelplan.entity.TransferTravelResult"
        method: "TransferTravelResult"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-travel-plan-service"
        class: "travelplan.entity.TravelAdvanceResultUnit"
        method: "TravelAdvanceResultUnit"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-travel-plan-service"
        class: "travelplan.service.TravelPlanServiceImpl"
        method: "getCheapest"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-travel-plan-service"
        class: "travelplan.service.TravelPlanServiceImpl"
        method: "getMinStation"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-travel-plan-service"
        class: "travelplan.service.TravelPlanServiceImpl"
        method: "getQuickest"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-travel-plan-service"
        class: "travelplan.service.TravelPlanServiceImpl"
        method: "getRestTicketNumber"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-travel-plan-service"
        class: "travelplan.service.TravelPlanServiceImpl"
        method: "getRoutePlanResultCheapest"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-travel-plan-service"
        class: "travelplan.service.TravelPlanServiceImpl"
        method: "getRoutePlanResultMinStation"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-travel-plan-service"
        class: "travelplan.service.TravelPlanServiceImpl"
        method: "getRoutePlanResultQuickest"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-travel-plan-service"
        class: "travelplan.service.TravelPlanServiceImpl"
        method: "getServiceUrl"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-travel-plan-service"
        class: "travelplan.service.TravelPlanServiceImpl"
        method: "getTransferSearch"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-travel-plan-service"
        class: "travelplan.service.TravelPlanServiceImpl"
        method: "queryTrainTypeByName"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-travel-plan-service"
        class: "travelplan.service.TravelPlanServiceImpl"
        method: "tripsFromHighSpeed"
        namespace: "ts"
    - capability: "jvm_cpu_stress"
      target:
        app: "ts-travel-plan-service"
        class: "travelplan.service.TravelPlanServiceImpl"
        method: "tripsFromNormal"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-travel-plan-service"
        class: "travelplan.TravelPlanApplication"
        method: "main"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-travel-plan-service"
        class: "travelplan.controller.TravelPlanController"
        method: "getByCheapest"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-travel-plan-service"
        class: "travelplan.controller.TravelPlanController"
        method: "getByMinStation"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-travel-plan-service"
        class: "travelplan.controller.TravelPlanController"
        method: "getByQuickest"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-travel-plan-service"
        class: "travelplan.controller.TravelPlanController"
        method: "getTransferResult"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-travel-plan-service"
        class: "travelplan.controller.TravelPlanController"
        method: "home"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-travel-plan-service"
        class: "travelplan.entity.TransferTravelInfo"
        method: "TransferTravelInfo"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-travel-plan-service"
        class: "travelplan.entity.TransferTravelInfo"
        method: "getTravelDate"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-travel-plan-service"
        class: "travelplan.entity.TransferTravelResult"
        method: "TransferTravelResult"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-travel-plan-service"
        class: "travelplan.entity.TravelAdvanceResultUnit"
        method: "TravelAdvanceResultUnit"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-travel-plan-service"
        class: "travelplan.service.TravelPlanServiceImpl"
        method: "getCheapest"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-travel-plan-service"
        class: "travelplan.service.TravelPlanServiceImpl"
        method: "getMinStation"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-travel-plan-service"
        class: "travelplan.service.TravelPlanServiceImpl"
        method: "getQuickest"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-travel-plan-service"
        class: "travelplan.service.TravelPlanServiceImpl"
        method: "getRestTicketNumber"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-travel-plan-service"
        class: "travelplan.service.TravelPlanServiceImpl"
        method: "getRoutePlanResultCheapest"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-travel-plan-service"
        class: "travelplan.service.TravelPlanServiceImpl"
        method: "getRoutePlanResultMinStation"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-travel-plan-service"
        class: "travelplan.service.TravelPlanServiceImpl"
        method: "getRoutePlanResultQuickest"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-travel-plan-service"
        class: "travelplan.service.TravelPlanServiceImpl"
        method: "getServiceUrl"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-travel-plan-service"
        class: "travelplan.service.TravelPlanServiceImpl"
        method: "getTransferSearch"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-travel-plan-service"
        class: "travelplan.service.TravelPlanServiceImpl"
        method: "queryTrainTypeByName"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-travel-plan-service"
        class: "travelplan.service.TravelPlanServiceImpl"
        method: "tripsFromHighSpeed"
        namespace: "ts"
    - capability: "jvm_method_exception"
      target:
        app: "ts-travel-plan-service"
        class: "travelplan.service.TravelPlanServiceImpl"
        method: "tripsFromNormal"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-travel-plan-service"
        class: "travelplan.TravelPlanApplication"
        method: "main"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-travel-plan-service"
        class: "travelplan.controller.TravelPlanController"
        method: "getByCheapest"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-travel-plan-service"
        class: "travelplan.controller.TravelPlanController"
        method: "getByMinStation"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-travel-plan-service"
        class: "travelplan.controller.TravelPlanController"
        method: "getByQuickest"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-travel-plan-service"
        class: "travelplan.controller.TravelPlanController"
        method: "getTransferResult"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-travel-plan-service"
        class: "travelplan.controller.TravelPlanController"
        method: "home"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-travel-plan-service"
        class: "travelplan.entity.TransferTravelInfo"
        method: "TransferTravelInfo"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-travel-plan-service"
        class: "travelplan.entity.TransferTravelInfo"
        method: "getTravelDate"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-travel-plan-service"
        class: "travelplan.entity.TransferTravelResult"
        method: "TransferTravelResult"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-travel-plan-service"
        class: "travelplan.entity.TravelAdvanceResultUnit"
        method: "TravelAdvanceResultUnit"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-travel-plan-service"
        class: "travelplan.service.TravelPlanServiceImpl"
        method: "getCheapest"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-travel-plan-service"
        class: "travelplan.service.TravelPlanServiceImpl"
        method: "getMinStation"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-travel-plan-service"
        class: "travelplan.service.TravelPlanServiceImpl"
        method: "getQuickest"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-travel-plan-service"
        class: "travelplan.service.TravelPlanServiceImpl"
        method: "getRestTicketNumber"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-travel-plan-service"
        class: "travelplan.service.TravelPlanServiceImpl"
        method: "getRoutePlanResultCheapest"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-travel-plan-service"
        class: "travelplan.service.TravelPlanServiceImpl"
        method: "getRoutePlanResultMinStation"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-travel-plan-service"
        class: "travelplan.service.TravelPlanServiceImpl"
        method: "getRoutePlanResultQuickest"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-travel-plan-service"
        class: "travelplan.service.TravelPlanServiceImpl"
        method: "getServiceUrl"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-travel-plan-service"
        class: "travelplan.service.TravelPlanServiceImpl"
        method: "getTransferSearch"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-travel-plan-service"
        class: "travelplan.service.TravelPlanServiceImpl"
        method: "queryTrainTypeByName"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-travel-plan-service"
        class: "travelplan.service.TravelPlanServiceImpl"
        method: "tripsFromHighSpeed"
        namespace: "ts"
    - capability: "jvm_method_return"
      target:
        app: "ts-travel-plan-service"
        class: "travelplan.service.TravelPlanServiceImpl"
        method: "tripsFromNormal"
        namespace: "ts"
