apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: "seed-genesis"
  instance: "seed"
  service: "ts-travel-service"
  system: "ts"
spec:
  replace_scope: "service"
  points:
    - capability: "container_kill"
      target:
        app: "ts-travel-service"
        container: "ts-travel-service"
        namespace: "ts"
    - capability: "cpu_stress"
      target:
        app: "ts-travel-service"
        container: "ts-travel-service"
        namespace: "ts"
    - capability: "http_request_abort"
      target:
        app: "ts-travel-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/routeservice/routes/*"
        port: 8080
        server_address: "ts-route-service"
        span_name: "GET"
    - capability: "http_request_abort"
      target:
        app: "ts-travel-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/trainservice/trains/byName/*"
        port: 8080
        server_address: "ts-train-service"
        span_name: "GET"
    - capability: "http_request_abort"
      target:
        app: "ts-travel-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/basicservice/basic/travel"
        port: 8080
        server_address: "ts-basic-service"
        span_name: "POST"
    - capability: "http_request_abort"
      target:
        app: "ts-travel-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/basicservice/basic/travels"
        port: 8080
        server_address: "ts-basic-service"
        span_name: "POST"
    - capability: "http_request_abort"
      target:
        app: "ts-travel-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/seatservice/seats/left_tickets"
        port: 8080
        server_address: "ts-seat-service"
        span_name: "POST"
    - capability: "http_request_delay"
      target:
        app: "ts-travel-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/routeservice/routes/*"
        port: 8080
        server_address: "ts-route-service"
        span_name: "GET"
    - capability: "http_request_delay"
      target:
        app: "ts-travel-service"
        method: "GET"
        namespace: "ts"
        path: "/api/v1/trainservice/trains/byName/*"
        port: 8080
        server_address: "ts-train-service"
        span_name: "GET"
    - capability: "http_request_delay"
      target:
        app: "ts-travel-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/basicservice/basic/travel"
        port: 8080
        server_address: "ts-basic-service"
        span_name: "POST"
    - capability: "http_request_delay"
      target:
        app: "ts-travel-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/basicservice/basic/travels"
        port: 8080
        server_address: "ts-basic-service"
        span_name: "POST"
    - capability: "http_request_delay"
      target:
        app: "ts-travel-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/seatservice/seats/left_tickets"
        port: 8080
        server_address: "ts-seat-service"
        span_name: "POST"
    - capability: "jvm_method_latency"
      target:
        app: "ts-travel-service"
        class: "travel.TravelApplication"
        method: "main"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-travel-service"
        class: "travel.controller.TravelController"
        method: "adminQueryAll"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-travel-service"
        class: "travel.controller.TravelController"
        method: "createTrip"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-travel-service"
        class: "travel.controller.TravelController"
        method: "deleteTrip"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-travel-service"
        class: "travel.controller.TravelController"
        method: "getRouteByTripId"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-travel-service"
        class: "travel.controller.TravelController"
        method: "getTrainTypeByTripId"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-travel-service"
        class: "travel.controller.TravelController"
        method: "getTripAllDetailInfo"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-travel-service"
        class: "travel.controller.TravelController"
        method: "getTripsByRouteId"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-travel-service"
        class: "travel.controller.TravelController"
        method: "home"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-travel-service"
        class: "travel.controller.TravelController"
        method: "queryAll"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-travel-service"
        class: "travel.controller.TravelController"
        method: "queryInfo"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-travel-service"
        class: "travel.controller.TravelController"
        method: "queryInfoInparallel"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-travel-service"
        class: "travel.controller.TravelController"
        method: "retrieve"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-travel-service"
        class: "travel.controller.TravelController"
        method: "updateTrip"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-travel-service"
        class: "travel.entity.AdminTrip"
        method: "AdminTrip"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-travel-service"
        class: "travel.entity.Travel"
        method: "Travel"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-travel-service"
        class: "travel.entity.Trip"
        method: "Trip"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-travel-service"
        class: "travel.entity.TripAllDetail"
        method: "TripAllDetail"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-travel-service"
        class: "travel.init.InitData"
        method: "run"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-travel-service"
        class: "travel.service.TravelServiceImpl.MyCallable"
        method: "MyCallable"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-travel-service"
        class: "travel.service.TravelServiceImpl.MyCallable"
        method: "call"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-travel-service"
        class: "travel.service.TravelServiceImpl"
        method: "adminQueryAll"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-travel-service"
        class: "travel.service.TravelServiceImpl"
        method: "afterToday"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-travel-service"
        class: "travel.service.TravelServiceImpl"
        method: "create"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-travel-service"
        class: "travel.service.TravelServiceImpl"
        method: "delete"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-travel-service"
        class: "travel.service.TravelServiceImpl"
        method: "getRestTicketNumber"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-travel-service"
        class: "travel.service.TravelServiceImpl"
        method: "getRouteByRouteId"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-travel-service"
        class: "travel.service.TravelServiceImpl"
        method: "getRouteByTripId"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-travel-service"
        class: "travel.service.TravelServiceImpl"
        method: "getServiceUrl"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-travel-service"
        class: "travel.service.TravelServiceImpl"
        method: "getTickets"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-travel-service"
        class: "travel.service.TravelServiceImpl"
        method: "getTicketsByBatch"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-travel-service"
        class: "travel.service.TravelServiceImpl"
        method: "getTrainTypeByName"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-travel-service"
        class: "travel.service.TravelServiceImpl"
        method: "getTrainTypeByTripId"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-travel-service"
        class: "travel.service.TravelServiceImpl"
        method: "getTripAllDetailInfo"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-travel-service"
        class: "travel.service.TravelServiceImpl"
        method: "getTripByRoute"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-travel-service"
        class: "travel.service.TravelServiceImpl"
        method: "query"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-travel-service"
        class: "travel.service.TravelServiceImpl"
        method: "queryAll"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-travel-service"
        class: "travel.service.TravelServiceImpl"
        method: "queryByBatch"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-travel-service"
        class: "travel.service.TravelServiceImpl"
        method: "queryInParallel"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-travel-service"
        class: "travel.service.TravelServiceImpl"
        method: "retrieve"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-travel-service"
        class: "travel.service.TravelServiceImpl"
        method: "setResponse"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-travel-service"
        class: "travel.service.TravelServiceImpl"
        method: "update"
        namespace: "ts"
    - capability: "pod_failure"
      target:
        app: "ts-travel-service"
        namespace: "ts"
    - capability: "pod_kill"
      target:
        app: "ts-travel-service"
        namespace: "ts"
    - capability: "time_skew"
      target:
        app: "ts-travel-service"
        container: "ts-travel-service"
        namespace: "ts"
