apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: "seed-genesis"
  instance: "seed"
  service: "ts-user-service"
  system: "ts"
spec:
  replace_scope: "service"
  points:
    - capability: "container_kill"
      target:
        app: "ts-user-service"
        container: "ts-user-service"
        namespace: "ts"
    - capability: "cpu_stress"
      target:
        app: "ts-user-service"
        container: "ts-user-service"
        namespace: "ts"
    - capability: "http_request_abort"
      target:
        app: "ts-user-service"
        method: "DELETE"
        namespace: "ts"
        path: "/api/v1/users/*"
        port: 8080
        server_address: "ts-auth-service"
        span_name: "DELETE"
    - capability: "http_request_abort"
      target:
        app: "ts-user-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/auth"
        port: 8080
        server_address: "ts-auth-service"
        span_name: "POST"
    - capability: "http_request_delay"
      target:
        app: "ts-user-service"
        method: "DELETE"
        namespace: "ts"
        path: "/api/v1/users/*"
        port: 8080
        server_address: "ts-auth-service"
        span_name: "DELETE"
    - capability: "http_request_delay"
      target:
        app: "ts-user-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/auth"
        port: 8080
        server_address: "ts-auth-service"
        span_name: "POST"
    - capability: "jvm_method_latency"
      target:
        app: "ts-user-service"
        class: "user.UserApplication"
        method: "main"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-user-service"
        class: "user.controller.UserController"
        method: "deleteUserById"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-user-service"
        class: "user.controller.UserController"
        method: "getAllUser"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-user-service"
        class: "user.controller.UserController"
        method: "getUserByUserId"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-user-service"
        class: "user.controller.UserController"
        method: "getUserByUserName"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-user-service"
        class: "user.controller.UserController"
        method: "registerUser"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-user-service"
        class: "user.controller.UserController"
        method: "testHello"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-user-service"
        class: "user.controller.UserController"
        method: "updateUser"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-user-service"
        class: "user.entity.User"
        method: "User"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-user-service"
        class: "user.init.InitUser"
        method: "run"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-user-service"
        class: "user.service.impl.UserServiceImpl"
        method: "createDefaultAuthUser"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-user-service"
        class: "user.service.impl.UserServiceImpl"
        method: "deleteUser"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-user-service"
        class: "user.service.impl.UserServiceImpl"
        method: "deleteUserAuth"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-user-service"
        class: "user.service.impl.UserServiceImpl"
        method: "findByUserId"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-user-service"
        class: "user.service.impl.UserServiceImpl"
        method: "findByUserName"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-user-service"
        class: "user.service.impl.UserServiceImpl"
        method: "getAllUsers"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-user-service"
        class: "user.service.impl.UserServiceImpl"
        method: "getServiceUrl"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-user-service"
        class: "user.service.impl.UserServiceImpl"
        method: "saveUser"
        namespace: "ts"
    - capability: "jvm_method_latency"
      target:
        app: "ts-user-service"
        class: "user.service.impl.UserServiceImpl"
        method: "updateUser"
        namespace: "ts"
    - capability: "pod_failure"
      target:
        app: "ts-user-service"
        namespace: "ts"
    - capability: "pod_kill"
      target:
        app: "ts-user-service"
        namespace: "ts"
    - capability: "time_skew"
      target:
        app: "ts-user-service"
        container: "ts-user-service"
        namespace: "ts"
