apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: seed-genesis
  instance: seed
  service: ts-wait-order-service
  system: ts
spec:
  points:
  - capability: network_bandwidth
    target:
      namespace: ts
      source_app: ts-wait-order-service
      span_names:
      - CREATE table ts
      - SELECT sys
      - SELECT ts
      - SELECT ts.information_schema
      - SELECT ts.mysql
      - SELECT ts.performance_schema
      - SELECT ts.sys
      - SELECT ts.ts
      target_service: mysql
  - capability: network_corrupt
    target:
      namespace: ts
      source_app: ts-wait-order-service
      span_names:
      - CREATE table ts
      - SELECT sys
      - SELECT ts
      - SELECT ts.information_schema
      - SELECT ts.mysql
      - SELECT ts.performance_schema
      - SELECT ts.sys
      - SELECT ts.ts
      target_service: mysql
  - capability: network_delay
    target:
      namespace: ts
      source_app: ts-wait-order-service
      span_names:
      - CREATE table ts
      - SELECT sys
      - SELECT ts
      - SELECT ts.information_schema
      - SELECT ts.mysql
      - SELECT ts.performance_schema
      - SELECT ts.sys
      - SELECT ts.ts
      target_service: mysql
  - capability: network_duplicate
    target:
      namespace: ts
      source_app: ts-wait-order-service
      span_names:
      - CREATE table ts
      - SELECT sys
      - SELECT ts
      - SELECT ts.information_schema
      - SELECT ts.mysql
      - SELECT ts.performance_schema
      - SELECT ts.sys
      - SELECT ts.ts
      target_service: mysql
  - capability: network_loss
    target:
      namespace: ts
      source_app: ts-wait-order-service
      span_names:
      - CREATE table ts
      - SELECT sys
      - SELECT ts
      - SELECT ts.information_schema
      - SELECT ts.mysql
      - SELECT ts.performance_schema
      - SELECT ts.sys
      - SELECT ts.ts
      target_service: mysql
  - capability: network_partition
    target:
      namespace: ts
      source_app: ts-wait-order-service
      span_names:
      - CREATE table ts
      - SELECT sys
      - SELECT ts
      - SELECT ts.information_schema
      - SELECT ts.mysql
      - SELECT ts.performance_schema
      - SELECT ts.sys
      - SELECT ts.ts
      target_service: mysql
  replace_scope: service
