apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: "observed-genesis"
  instance: "observed"
  service: "loadgenerator"
  system: "ts"
spec:
  replace_scope: "service"
  points:
    - capability: "pod_kill"
      target:
        app: "loadgenerator"
        namespace: "ts"
    - capability: "pod_failure"
      target:
        app: "loadgenerator"
        namespace: "ts"
    - capability: "container_kill"
      target:
        app: "loadgenerator"
        container: "loadgenerator"
        namespace: "ts"
    - capability: "cpu_stress"
      target:
        app: "loadgenerator"
        container: "loadgenerator"
        namespace: "ts"
    - capability: "time_skew"
      target:
        app: "loadgenerator"
        container: "loadgenerator"
        namespace: "ts"
    - capability: "dns_error"
      target:
        app: "loadgenerator"
        domain_patterns:
          - "ts-ui-dashboard"
        namespace: "ts"
    - capability: "dns_random"
      target:
        app: "loadgenerator"
        domain_patterns:
          - "ts-ui-dashboard"
        namespace: "ts"
    - capability: "network_delay"
      target:
        namespace: "ts"
        source_app: "loadgenerator"
        span_names:
          - "DELETE /api/v1/adminorderservice/adminorder/*/*"
          - "DELETE /api/v1/adminrouteservice/adminroute/*"
          - "GET /api/v1/adminbasicservice/adminbasic/configs"
          - "GET /api/v1/adminbasicservice/adminbasic/contacts"
          - "GET /api/v1/adminbasicservice/adminbasic/prices"
          - "GET /api/v1/adminbasicservice/adminbasic/stations"
          - "GET /api/v1/adminbasicservice/adminbasic/trains"
          - "GET /api/v1/adminorderservice/adminorder"
          - "GET /api/v1/adminrouteservice/adminroute"
          - "GET /api/v1/admintravelservice/admintravel"
          - "GET /api/v1/adminuserservice/users"
          - "GET /api/v1/assuranceservice/assurances/types"
          - "GET /api/v1/cancelservice/cancel/*/*"
          - "GET /api/v1/cancelservice/cancel/refound/*"
          - "GET /api/v1/consignservice/consigns/account/*"
          - "GET /api/v1/consignservice/consigns/order/*"
          - "GET /api/v1/contactservice/contacts/account/*"
          - "GET /api/v1/executeservice/execute/collected/*"
          - "GET /api/v1/executeservice/execute/execute/*"
          - "GET /api/v1/foodservice/foods/*/jiaxingnan/hangzhou/*"
          - "GET /api/v1/foodservice/foods/*/jinan/beijing/*"
          - "GET /api/v1/foodservice/foods/*/nanjing/beijing/*"
          - "GET /api/v1/foodservice/foods/*/nanjing/jinan/*"
          - "GET /api/v1/foodservice/foods/*/nanjing/shanghai/*"
          - "GET /api/v1/foodservice/foods/*/nanjing/shijiazhuang/*"
          - "GET /api/v1/foodservice/foods/*/nanjing/suzhou/*"
          - "GET /api/v1/foodservice/foods/*/nanjing/taiyuan/*"
          - "GET /api/v1/foodservice/foods/*/nanjing/wuxi/*"
          - "GET /api/v1/foodservice/foods/*/nanjing/xuzhou/*"
          - "GET /api/v1/foodservice/foods/*/nanjing/zhenjiang/*"
        target_service: "ts-ui-dashboard"
    - capability: "network_loss"
      target:
        namespace: "ts"
        source_app: "loadgenerator"
        span_names:
          - "DELETE /api/v1/adminorderservice/adminorder/*/*"
          - "DELETE /api/v1/adminrouteservice/adminroute/*"
          - "GET /api/v1/adminbasicservice/adminbasic/configs"
          - "GET /api/v1/adminbasicservice/adminbasic/contacts"
          - "GET /api/v1/adminbasicservice/adminbasic/prices"
          - "GET /api/v1/adminbasicservice/adminbasic/stations"
          - "GET /api/v1/adminbasicservice/adminbasic/trains"
          - "GET /api/v1/adminorderservice/adminorder"
          - "GET /api/v1/adminrouteservice/adminroute"
          - "GET /api/v1/admintravelservice/admintravel"
          - "GET /api/v1/adminuserservice/users"
          - "GET /api/v1/assuranceservice/assurances/types"
          - "GET /api/v1/cancelservice/cancel/*/*"
          - "GET /api/v1/cancelservice/cancel/refound/*"
          - "GET /api/v1/consignservice/consigns/account/*"
          - "GET /api/v1/consignservice/consigns/order/*"
          - "GET /api/v1/contactservice/contacts/account/*"
          - "GET /api/v1/executeservice/execute/collected/*"
          - "GET /api/v1/executeservice/execute/execute/*"
          - "GET /api/v1/foodservice/foods/*/jiaxingnan/hangzhou/*"
          - "GET /api/v1/foodservice/foods/*/jinan/beijing/*"
          - "GET /api/v1/foodservice/foods/*/nanjing/beijing/*"
          - "GET /api/v1/foodservice/foods/*/nanjing/jinan/*"
          - "GET /api/v1/foodservice/foods/*/nanjing/shanghai/*"
          - "GET /api/v1/foodservice/foods/*/nanjing/shijiazhuang/*"
          - "GET /api/v1/foodservice/foods/*/nanjing/suzhou/*"
          - "GET /api/v1/foodservice/foods/*/nanjing/taiyuan/*"
          - "GET /api/v1/foodservice/foods/*/nanjing/wuxi/*"
          - "GET /api/v1/foodservice/foods/*/nanjing/xuzhou/*"
          - "GET /api/v1/foodservice/foods/*/nanjing/zhenjiang/*"
        target_service: "ts-ui-dashboard"
    - capability: "network_duplicate"
      target:
        namespace: "ts"
        source_app: "loadgenerator"
        span_names:
          - "DELETE /api/v1/adminorderservice/adminorder/*/*"
          - "DELETE /api/v1/adminrouteservice/adminroute/*"
          - "GET /api/v1/adminbasicservice/adminbasic/configs"
          - "GET /api/v1/adminbasicservice/adminbasic/contacts"
          - "GET /api/v1/adminbasicservice/adminbasic/prices"
          - "GET /api/v1/adminbasicservice/adminbasic/stations"
          - "GET /api/v1/adminbasicservice/adminbasic/trains"
          - "GET /api/v1/adminorderservice/adminorder"
          - "GET /api/v1/adminrouteservice/adminroute"
          - "GET /api/v1/admintravelservice/admintravel"
          - "GET /api/v1/adminuserservice/users"
          - "GET /api/v1/assuranceservice/assurances/types"
          - "GET /api/v1/cancelservice/cancel/*/*"
          - "GET /api/v1/cancelservice/cancel/refound/*"
          - "GET /api/v1/consignservice/consigns/account/*"
          - "GET /api/v1/consignservice/consigns/order/*"
          - "GET /api/v1/contactservice/contacts/account/*"
          - "GET /api/v1/executeservice/execute/collected/*"
          - "GET /api/v1/executeservice/execute/execute/*"
          - "GET /api/v1/foodservice/foods/*/jiaxingnan/hangzhou/*"
          - "GET /api/v1/foodservice/foods/*/jinan/beijing/*"
          - "GET /api/v1/foodservice/foods/*/nanjing/beijing/*"
          - "GET /api/v1/foodservice/foods/*/nanjing/jinan/*"
          - "GET /api/v1/foodservice/foods/*/nanjing/shanghai/*"
          - "GET /api/v1/foodservice/foods/*/nanjing/shijiazhuang/*"
          - "GET /api/v1/foodservice/foods/*/nanjing/suzhou/*"
          - "GET /api/v1/foodservice/foods/*/nanjing/taiyuan/*"
          - "GET /api/v1/foodservice/foods/*/nanjing/wuxi/*"
          - "GET /api/v1/foodservice/foods/*/nanjing/xuzhou/*"
          - "GET /api/v1/foodservice/foods/*/nanjing/zhenjiang/*"
        target_service: "ts-ui-dashboard"
    - capability: "network_corrupt"
      target:
        namespace: "ts"
        source_app: "loadgenerator"
        span_names:
          - "DELETE /api/v1/adminorderservice/adminorder/*/*"
          - "DELETE /api/v1/adminrouteservice/adminroute/*"
          - "GET /api/v1/adminbasicservice/adminbasic/configs"
          - "GET /api/v1/adminbasicservice/adminbasic/contacts"
          - "GET /api/v1/adminbasicservice/adminbasic/prices"
          - "GET /api/v1/adminbasicservice/adminbasic/stations"
          - "GET /api/v1/adminbasicservice/adminbasic/trains"
          - "GET /api/v1/adminorderservice/adminorder"
          - "GET /api/v1/adminrouteservice/adminroute"
          - "GET /api/v1/admintravelservice/admintravel"
          - "GET /api/v1/adminuserservice/users"
          - "GET /api/v1/assuranceservice/assurances/types"
          - "GET /api/v1/cancelservice/cancel/*/*"
          - "GET /api/v1/cancelservice/cancel/refound/*"
          - "GET /api/v1/consignservice/consigns/account/*"
          - "GET /api/v1/consignservice/consigns/order/*"
          - "GET /api/v1/contactservice/contacts/account/*"
          - "GET /api/v1/executeservice/execute/collected/*"
          - "GET /api/v1/executeservice/execute/execute/*"
          - "GET /api/v1/foodservice/foods/*/jiaxingnan/hangzhou/*"
          - "GET /api/v1/foodservice/foods/*/jinan/beijing/*"
          - "GET /api/v1/foodservice/foods/*/nanjing/beijing/*"
          - "GET /api/v1/foodservice/foods/*/nanjing/jinan/*"
          - "GET /api/v1/foodservice/foods/*/nanjing/shanghai/*"
          - "GET /api/v1/foodservice/foods/*/nanjing/shijiazhuang/*"
          - "GET /api/v1/foodservice/foods/*/nanjing/suzhou/*"
          - "GET /api/v1/foodservice/foods/*/nanjing/taiyuan/*"
          - "GET /api/v1/foodservice/foods/*/nanjing/wuxi/*"
          - "GET /api/v1/foodservice/foods/*/nanjing/xuzhou/*"
          - "GET /api/v1/foodservice/foods/*/nanjing/zhenjiang/*"
        target_service: "ts-ui-dashboard"
    - capability: "network_bandwidth"
      target:
        namespace: "ts"
        source_app: "loadgenerator"
        span_names:
          - "DELETE /api/v1/adminorderservice/adminorder/*/*"
          - "DELETE /api/v1/adminrouteservice/adminroute/*"
          - "GET /api/v1/adminbasicservice/adminbasic/configs"
          - "GET /api/v1/adminbasicservice/adminbasic/contacts"
          - "GET /api/v1/adminbasicservice/adminbasic/prices"
          - "GET /api/v1/adminbasicservice/adminbasic/stations"
          - "GET /api/v1/adminbasicservice/adminbasic/trains"
          - "GET /api/v1/adminorderservice/adminorder"
          - "GET /api/v1/adminrouteservice/adminroute"
          - "GET /api/v1/admintravelservice/admintravel"
          - "GET /api/v1/adminuserservice/users"
          - "GET /api/v1/assuranceservice/assurances/types"
          - "GET /api/v1/cancelservice/cancel/*/*"
          - "GET /api/v1/cancelservice/cancel/refound/*"
          - "GET /api/v1/consignservice/consigns/account/*"
          - "GET /api/v1/consignservice/consigns/order/*"
          - "GET /api/v1/contactservice/contacts/account/*"
          - "GET /api/v1/executeservice/execute/collected/*"
          - "GET /api/v1/executeservice/execute/execute/*"
          - "GET /api/v1/foodservice/foods/*/jiaxingnan/hangzhou/*"
          - "GET /api/v1/foodservice/foods/*/jinan/beijing/*"
          - "GET /api/v1/foodservice/foods/*/nanjing/beijing/*"
          - "GET /api/v1/foodservice/foods/*/nanjing/jinan/*"
          - "GET /api/v1/foodservice/foods/*/nanjing/shanghai/*"
          - "GET /api/v1/foodservice/foods/*/nanjing/shijiazhuang/*"
          - "GET /api/v1/foodservice/foods/*/nanjing/suzhou/*"
          - "GET /api/v1/foodservice/foods/*/nanjing/taiyuan/*"
          - "GET /api/v1/foodservice/foods/*/nanjing/wuxi/*"
          - "GET /api/v1/foodservice/foods/*/nanjing/xuzhou/*"
          - "GET /api/v1/foodservice/foods/*/nanjing/zhenjiang/*"
        target_service: "ts-ui-dashboard"
    - capability: "network_partition"
      target:
        namespace: "ts"
        source_app: "loadgenerator"
        span_names:
          - "DELETE /api/v1/adminorderservice/adminorder/*/*"
          - "DELETE /api/v1/adminrouteservice/adminroute/*"
          - "GET /api/v1/adminbasicservice/adminbasic/configs"
          - "GET /api/v1/adminbasicservice/adminbasic/contacts"
          - "GET /api/v1/adminbasicservice/adminbasic/prices"
          - "GET /api/v1/adminbasicservice/adminbasic/stations"
          - "GET /api/v1/adminbasicservice/adminbasic/trains"
          - "GET /api/v1/adminorderservice/adminorder"
          - "GET /api/v1/adminrouteservice/adminroute"
          - "GET /api/v1/admintravelservice/admintravel"
          - "GET /api/v1/adminuserservice/users"
          - "GET /api/v1/assuranceservice/assurances/types"
          - "GET /api/v1/cancelservice/cancel/*/*"
          - "GET /api/v1/cancelservice/cancel/refound/*"
          - "GET /api/v1/consignservice/consigns/account/*"
          - "GET /api/v1/consignservice/consigns/order/*"
          - "GET /api/v1/contactservice/contacts/account/*"
          - "GET /api/v1/executeservice/execute/collected/*"
          - "GET /api/v1/executeservice/execute/execute/*"
          - "GET /api/v1/foodservice/foods/*/jiaxingnan/hangzhou/*"
          - "GET /api/v1/foodservice/foods/*/jinan/beijing/*"
          - "GET /api/v1/foodservice/foods/*/nanjing/beijing/*"
          - "GET /api/v1/foodservice/foods/*/nanjing/jinan/*"
          - "GET /api/v1/foodservice/foods/*/nanjing/shanghai/*"
          - "GET /api/v1/foodservice/foods/*/nanjing/shijiazhuang/*"
          - "GET /api/v1/foodservice/foods/*/nanjing/suzhou/*"
          - "GET /api/v1/foodservice/foods/*/nanjing/taiyuan/*"
          - "GET /api/v1/foodservice/foods/*/nanjing/wuxi/*"
          - "GET /api/v1/foodservice/foods/*/nanjing/xuzhou/*"
          - "GET /api/v1/foodservice/foods/*/nanjing/zhenjiang/*"
        target_service: "ts-ui-dashboard"
