apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: "observed-genesis"
  instance: "observed"
  service: "ts-travel-plan-service"
  system: "ts"
spec:
  replace_scope: "service"
  points:
    - capability: "pod_kill"
      target:
        app: "ts-travel-plan-service"
        namespace: "ts"
    - capability: "pod_failure"
      target:
        app: "ts-travel-plan-service"
        namespace: "ts"
    - capability: "container_kill"
      target:
        app: "ts-travel-plan-service"
        container: "ts-travel-plan-service"
        namespace: "ts"
    - capability: "cpu_stress"
      target:
        app: "ts-travel-plan-service"
        container: "ts-travel-plan-service"
        namespace: "ts"
    - capability: "time_skew"
      target:
        app: "ts-travel-plan-service"
        container: "ts-travel-plan-service"
        namespace: "ts"
    - capability: "http_request_delay"
      target:
        app: "ts-travel-plan-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/travelplanservice/travelPlan/cheapest"
        port: 8080
        server_address: "ts-travel-plan-service"
        span_name: "POST /api/v1/travelplanservice/travelPlan/cheapest"
    - capability: "http_request_abort"
      target:
        app: "ts-travel-plan-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/travelplanservice/travelPlan/cheapest"
        port: 8080
        server_address: "ts-travel-plan-service"
        span_name: "POST /api/v1/travelplanservice/travelPlan/cheapest"
    - capability: "http_response_abort"
      target:
        app: "ts-travel-plan-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/travelplanservice/travelPlan/cheapest"
        port: 8080
    - capability: "http_response_delay"
      target:
        app: "ts-travel-plan-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/travelplanservice/travelPlan/cheapest"
        port: 8080
    - capability: "http_response_replace_code"
      target:
        app: "ts-travel-plan-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/travelplanservice/travelPlan/cheapest"
        port: 8080
    - capability: "http_response_patch_body"
      target:
        app: "ts-travel-plan-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/travelplanservice/travelPlan/cheapest"
        port: 8080
    - capability: "http_response_replace_body"
      target:
        app: "ts-travel-plan-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/travelplanservice/travelPlan/cheapest"
        port: 8080
    - capability: "http_request_replace_method"
      target:
        app: "ts-travel-plan-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/travelplanservice/travelPlan/cheapest"
        port: 8080
    - capability: "http_request_replace_path"
      target:
        app: "ts-travel-plan-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/travelplanservice/travelPlan/cheapest"
        port: 8080
    - capability: "http_request_delay"
      target:
        app: "ts-travel-plan-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/travelplanservice/travelPlan/quickest"
        port: 8080
        server_address: "ts-travel-plan-service"
        span_name: "POST /api/v1/travelplanservice/travelPlan/quickest"
    - capability: "http_request_abort"
      target:
        app: "ts-travel-plan-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/travelplanservice/travelPlan/quickest"
        port: 8080
        server_address: "ts-travel-plan-service"
        span_name: "POST /api/v1/travelplanservice/travelPlan/quickest"
    - capability: "http_response_abort"
      target:
        app: "ts-travel-plan-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/travelplanservice/travelPlan/quickest"
        port: 8080
    - capability: "http_response_delay"
      target:
        app: "ts-travel-plan-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/travelplanservice/travelPlan/quickest"
        port: 8080
    - capability: "http_response_replace_code"
      target:
        app: "ts-travel-plan-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/travelplanservice/travelPlan/quickest"
        port: 8080
    - capability: "http_response_patch_body"
      target:
        app: "ts-travel-plan-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/travelplanservice/travelPlan/quickest"
        port: 8080
    - capability: "http_response_replace_body"
      target:
        app: "ts-travel-plan-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/travelplanservice/travelPlan/quickest"
        port: 8080
    - capability: "http_request_replace_method"
      target:
        app: "ts-travel-plan-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/travelplanservice/travelPlan/quickest"
        port: 8080
    - capability: "http_request_replace_path"
      target:
        app: "ts-travel-plan-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/travelplanservice/travelPlan/quickest"
        port: 8080
    - capability: "http_request_delay"
      target:
        app: "ts-travel-plan-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/travelplanservice/travelPlan/minStation"
        port: 8080
        server_address: "ts-travel-plan-service"
        span_name: "POST /api/v1/travelplanservice/travelPlan/minStation"
    - capability: "http_request_abort"
      target:
        app: "ts-travel-plan-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/travelplanservice/travelPlan/minStation"
        port: 8080
        server_address: "ts-travel-plan-service"
        span_name: "POST /api/v1/travelplanservice/travelPlan/minStation"
    - capability: "http_response_abort"
      target:
        app: "ts-travel-plan-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/travelplanservice/travelPlan/minStation"
        port: 8080
    - capability: "http_response_delay"
      target:
        app: "ts-travel-plan-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/travelplanservice/travelPlan/minStation"
        port: 8080
    - capability: "http_response_replace_code"
      target:
        app: "ts-travel-plan-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/travelplanservice/travelPlan/minStation"
        port: 8080
    - capability: "http_response_patch_body"
      target:
        app: "ts-travel-plan-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/travelplanservice/travelPlan/minStation"
        port: 8080
    - capability: "http_response_replace_body"
      target:
        app: "ts-travel-plan-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/travelplanservice/travelPlan/minStation"
        port: 8080
    - capability: "http_request_replace_method"
      target:
        app: "ts-travel-plan-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/travelplanservice/travelPlan/minStation"
        port: 8080
    - capability: "http_request_replace_path"
      target:
        app: "ts-travel-plan-service"
        method: "POST"
        namespace: "ts"
        path: "/api/v1/travelplanservice/travelPlan/minStation"
        port: 8080
    - capability: "dns_error"
      target:
        app: "ts-travel-plan-service"
        domain_patterns:
          - "ts-seat-service"
        namespace: "ts"
    - capability: "dns_random"
      target:
        app: "ts-travel-plan-service"
        domain_patterns:
          - "ts-seat-service"
        namespace: "ts"
    - capability: "network_delay"
      target:
        namespace: "ts"
        source_app: "ts-travel-plan-service"
        span_names:
          - "POST /api/v1/seatservice/seats/left_tickets"
        target_service: "ts-seat-service"
    - capability: "network_loss"
      target:
        namespace: "ts"
        source_app: "ts-travel-plan-service"
        span_names:
          - "POST /api/v1/seatservice/seats/left_tickets"
        target_service: "ts-seat-service"
    - capability: "network_duplicate"
      target:
        namespace: "ts"
        source_app: "ts-travel-plan-service"
        span_names:
          - "POST /api/v1/seatservice/seats/left_tickets"
        target_service: "ts-seat-service"
    - capability: "network_corrupt"
      target:
        namespace: "ts"
        source_app: "ts-travel-plan-service"
        span_names:
          - "POST /api/v1/seatservice/seats/left_tickets"
        target_service: "ts-seat-service"
    - capability: "network_bandwidth"
      target:
        namespace: "ts"
        source_app: "ts-travel-plan-service"
        span_names:
          - "POST /api/v1/seatservice/seats/left_tickets"
        target_service: "ts-seat-service"
    - capability: "network_partition"
      target:
        namespace: "ts"
        source_app: "ts-travel-plan-service"
        span_names:
          - "POST /api/v1/seatservice/seats/left_tickets"
        target_service: "ts-seat-service"
    - capability: "dns_error"
      target:
        app: "ts-travel-plan-service"
        domain_patterns:
          - "ts-route-plan-service"
        namespace: "ts"
    - capability: "dns_random"
      target:
        app: "ts-travel-plan-service"
        domain_patterns:
          - "ts-route-plan-service"
        namespace: "ts"
    - capability: "network_delay"
      target:
        namespace: "ts"
        source_app: "ts-travel-plan-service"
        span_names:
          - "POST /api/v1/routeplanservice/routePlan/cheapestRoute"
          - "POST /api/v1/routeplanservice/routePlan/minStopStations"
          - "POST /api/v1/routeplanservice/routePlan/quickestRoute"
        target_service: "ts-route-plan-service"
    - capability: "network_loss"
      target:
        namespace: "ts"
        source_app: "ts-travel-plan-service"
        span_names:
          - "POST /api/v1/routeplanservice/routePlan/cheapestRoute"
          - "POST /api/v1/routeplanservice/routePlan/minStopStations"
          - "POST /api/v1/routeplanservice/routePlan/quickestRoute"
        target_service: "ts-route-plan-service"
    - capability: "network_duplicate"
      target:
        namespace: "ts"
        source_app: "ts-travel-plan-service"
        span_names:
          - "POST /api/v1/routeplanservice/routePlan/cheapestRoute"
          - "POST /api/v1/routeplanservice/routePlan/minStopStations"
          - "POST /api/v1/routeplanservice/routePlan/quickestRoute"
        target_service: "ts-route-plan-service"
    - capability: "network_corrupt"
      target:
        namespace: "ts"
        source_app: "ts-travel-plan-service"
        span_names:
          - "POST /api/v1/routeplanservice/routePlan/cheapestRoute"
          - "POST /api/v1/routeplanservice/routePlan/minStopStations"
          - "POST /api/v1/routeplanservice/routePlan/quickestRoute"
        target_service: "ts-route-plan-service"
    - capability: "network_bandwidth"
      target:
        namespace: "ts"
        source_app: "ts-travel-plan-service"
        span_names:
          - "POST /api/v1/routeplanservice/routePlan/cheapestRoute"
          - "POST /api/v1/routeplanservice/routePlan/minStopStations"
          - "POST /api/v1/routeplanservice/routePlan/quickestRoute"
        target_service: "ts-route-plan-service"
    - capability: "network_partition"
      target:
        namespace: "ts"
        source_app: "ts-travel-plan-service"
        span_names:
          - "POST /api/v1/routeplanservice/routePlan/cheapestRoute"
          - "POST /api/v1/routeplanservice/routePlan/minStopStations"
          - "POST /api/v1/routeplanservice/routePlan/quickestRoute"
        target_service: "ts-route-plan-service"
    - capability: "dns_error"
      target:
        app: "ts-travel-plan-service"
        domain_patterns:
          - "ts-train-service"
        namespace: "ts"
    - capability: "dns_random"
      target:
        app: "ts-travel-plan-service"
        domain_patterns:
          - "ts-train-service"
        namespace: "ts"
    - capability: "network_delay"
      target:
        namespace: "ts"
        source_app: "ts-travel-plan-service"
        span_names:
          - "GET /api/v1/trainservice/trains/byName/{name}"
        target_service: "ts-train-service"
    - capability: "network_loss"
      target:
        namespace: "ts"
        source_app: "ts-travel-plan-service"
        span_names:
          - "GET /api/v1/trainservice/trains/byName/{name}"
        target_service: "ts-train-service"
    - capability: "network_duplicate"
      target:
        namespace: "ts"
        source_app: "ts-travel-plan-service"
        span_names:
          - "GET /api/v1/trainservice/trains/byName/{name}"
        target_service: "ts-train-service"
    - capability: "network_corrupt"
      target:
        namespace: "ts"
        source_app: "ts-travel-plan-service"
        span_names:
          - "GET /api/v1/trainservice/trains/byName/{name}"
        target_service: "ts-train-service"
    - capability: "network_bandwidth"
      target:
        namespace: "ts"
        source_app: "ts-travel-plan-service"
        span_names:
          - "GET /api/v1/trainservice/trains/byName/{name}"
        target_service: "ts-train-service"
    - capability: "network_partition"
      target:
        namespace: "ts"
        source_app: "ts-travel-plan-service"
        span_names:
          - "GET /api/v1/trainservice/trains/byName/{name}"
        target_service: "ts-train-service"
