apiVersion: aegis-chaos/v1beta
kind: PointManifest
metadata:
  chart_version: "observed-genesis"
  instance: "observed"
  service: "nginx-web-server"
  system: "media"
spec:
  replace_scope: "service"
  points:
    - capability: "pod_kill"
      target:
        app: "nginx-web-server"
        namespace: "media"
    - capability: "pod_failure"
      target:
        app: "nginx-web-server"
        namespace: "media"
    - capability: "container_kill"
      target:
        app: "nginx-web-server"
        container: "nginx-web-server"
        namespace: "media"
    - capability: "cpu_stress"
      target:
        app: "nginx-web-server"
        container: "nginx-web-server"
        namespace: "media"
    - capability: "time_skew"
      target:
        app: "nginx-web-server"
        container: "nginx-web-server"
        namespace: "media"
    - capability: "http_request_delay"
      target:
        app: "nginx-web-server"
        method: "GET"
        namespace: "media"
        path: "/wrk2-api/movie/read-page"
        port: 8080
        server_address: "nginx-web-server"
        span_name: "/wrk2-api/movie/read-page"
    - capability: "http_request_abort"
      target:
        app: "nginx-web-server"
        method: "GET"
        namespace: "media"
        path: "/wrk2-api/movie/read-page"
        port: 8080
        server_address: "nginx-web-server"
        span_name: "/wrk2-api/movie/read-page"
    - capability: "http_response_abort"
      target:
        app: "nginx-web-server"
        method: "GET"
        namespace: "media"
        path: "/wrk2-api/movie/read-page"
        port: 8080
    - capability: "http_response_delay"
      target:
        app: "nginx-web-server"
        method: "GET"
        namespace: "media"
        path: "/wrk2-api/movie/read-page"
        port: 8080
    - capability: "http_response_replace_code"
      target:
        app: "nginx-web-server"
        method: "GET"
        namespace: "media"
        path: "/wrk2-api/movie/read-page"
        port: 8080
    - capability: "http_response_patch_body"
      target:
        app: "nginx-web-server"
        method: "GET"
        namespace: "media"
        path: "/wrk2-api/movie/read-page"
        port: 8080
    - capability: "http_response_replace_body"
      target:
        app: "nginx-web-server"
        method: "GET"
        namespace: "media"
        path: "/wrk2-api/movie/read-page"
        port: 8080
    - capability: "http_request_replace_method"
      target:
        app: "nginx-web-server"
        method: "GET"
        namespace: "media"
        path: "/wrk2-api/movie/read-page"
        port: 8080
    - capability: "http_request_replace_path"
      target:
        app: "nginx-web-server"
        method: "GET"
        namespace: "media"
        path: "/wrk2-api/movie/read-page"
        port: 8080
    - capability: "http_request_delay"
      target:
        app: "nginx-web-server"
        method: "GET"
        namespace: "media"
        path: "/wrk2-api/movie/read-info"
        port: 8080
        server_address: "nginx-web-server"
        span_name: "/wrk2-api/movie/read-info"
    - capability: "http_request_abort"
      target:
        app: "nginx-web-server"
        method: "GET"
        namespace: "media"
        path: "/wrk2-api/movie/read-info"
        port: 8080
        server_address: "nginx-web-server"
        span_name: "/wrk2-api/movie/read-info"
    - capability: "http_response_abort"
      target:
        app: "nginx-web-server"
        method: "GET"
        namespace: "media"
        path: "/wrk2-api/movie/read-info"
        port: 8080
    - capability: "http_response_delay"
      target:
        app: "nginx-web-server"
        method: "GET"
        namespace: "media"
        path: "/wrk2-api/movie/read-info"
        port: 8080
    - capability: "http_response_replace_code"
      target:
        app: "nginx-web-server"
        method: "GET"
        namespace: "media"
        path: "/wrk2-api/movie/read-info"
        port: 8080
    - capability: "http_response_patch_body"
      target:
        app: "nginx-web-server"
        method: "GET"
        namespace: "media"
        path: "/wrk2-api/movie/read-info"
        port: 8080
    - capability: "http_response_replace_body"
      target:
        app: "nginx-web-server"
        method: "GET"
        namespace: "media"
        path: "/wrk2-api/movie/read-info"
        port: 8080
    - capability: "http_request_replace_method"
      target:
        app: "nginx-web-server"
        method: "GET"
        namespace: "media"
        path: "/wrk2-api/movie/read-info"
        port: 8080
    - capability: "http_request_replace_path"
      target:
        app: "nginx-web-server"
        method: "GET"
        namespace: "media"
        path: "/wrk2-api/movie/read-info"
        port: 8080
    - capability: "http_request_delay"
      target:
        app: "nginx-web-server"
        method: "POST"
        namespace: "media"
        path: "/wrk2-api/review/compose"
        port: 8080
        server_address: "nginx-web-server"
        span_name: "/wrk2-api/review/compose"
    - capability: "http_request_abort"
      target:
        app: "nginx-web-server"
        method: "POST"
        namespace: "media"
        path: "/wrk2-api/review/compose"
        port: 8080
        server_address: "nginx-web-server"
        span_name: "/wrk2-api/review/compose"
    - capability: "http_response_abort"
      target:
        app: "nginx-web-server"
        method: "POST"
        namespace: "media"
        path: "/wrk2-api/review/compose"
        port: 8080
    - capability: "http_response_delay"
      target:
        app: "nginx-web-server"
        method: "POST"
        namespace: "media"
        path: "/wrk2-api/review/compose"
        port: 8080
    - capability: "http_response_replace_code"
      target:
        app: "nginx-web-server"
        method: "POST"
        namespace: "media"
        path: "/wrk2-api/review/compose"
        port: 8080
    - capability: "http_response_patch_body"
      target:
        app: "nginx-web-server"
        method: "POST"
        namespace: "media"
        path: "/wrk2-api/review/compose"
        port: 8080
    - capability: "http_response_replace_body"
      target:
        app: "nginx-web-server"
        method: "POST"
        namespace: "media"
        path: "/wrk2-api/review/compose"
        port: 8080
    - capability: "http_request_replace_method"
      target:
        app: "nginx-web-server"
        method: "POST"
        namespace: "media"
        path: "/wrk2-api/review/compose"
        port: 8080
    - capability: "http_request_replace_path"
      target:
        app: "nginx-web-server"
        method: "POST"
        namespace: "media"
        path: "/wrk2-api/review/compose"
        port: 8080
    - capability: "dns_error"
      target:
        app: "nginx-web-server"
        domain_patterns:
          - "cast-info-service"
        namespace: "media"
    - capability: "dns_random"
      target:
        app: "nginx-web-server"
        domain_patterns:
          - "cast-info-service"
        namespace: "media"
    - capability: "network_delay"
      target:
        namespace: "media"
        source_app: "nginx-web-server"
        span_names:
          - "ReadPage"
        target_service: "cast-info-service"
    - capability: "network_loss"
      target:
        namespace: "media"
        source_app: "nginx-web-server"
        span_names:
          - "ReadPage"
        target_service: "cast-info-service"
    - capability: "network_duplicate"
      target:
        namespace: "media"
        source_app: "nginx-web-server"
        span_names:
          - "ReadPage"
        target_service: "cast-info-service"
    - capability: "network_corrupt"
      target:
        namespace: "media"
        source_app: "nginx-web-server"
        span_names:
          - "ReadPage"
        target_service: "cast-info-service"
    - capability: "network_bandwidth"
      target:
        namespace: "media"
        source_app: "nginx-web-server"
        span_names:
          - "ReadPage"
        target_service: "cast-info-service"
    - capability: "network_partition"
      target:
        namespace: "media"
        source_app: "nginx-web-server"
        span_names:
          - "ReadPage"
        target_service: "cast-info-service"
    - capability: "dns_error"
      target:
        app: "nginx-web-server"
        domain_patterns:
          - "movie-info-service"
        namespace: "media"
    - capability: "dns_random"
      target:
        app: "nginx-web-server"
        domain_patterns:
          - "movie-info-service"
        namespace: "media"
    - capability: "network_delay"
      target:
        namespace: "media"
        source_app: "nginx-web-server"
        span_names:
          - "ReadMovieInfo"
        target_service: "movie-info-service"
    - capability: "network_loss"
      target:
        namespace: "media"
        source_app: "nginx-web-server"
        span_names:
          - "ReadMovieInfo"
        target_service: "movie-info-service"
    - capability: "network_duplicate"
      target:
        namespace: "media"
        source_app: "nginx-web-server"
        span_names:
          - "ReadMovieInfo"
        target_service: "movie-info-service"
    - capability: "network_corrupt"
      target:
        namespace: "media"
        source_app: "nginx-web-server"
        span_names:
          - "ReadMovieInfo"
        target_service: "movie-info-service"
    - capability: "network_bandwidth"
      target:
        namespace: "media"
        source_app: "nginx-web-server"
        span_names:
          - "ReadMovieInfo"
        target_service: "movie-info-service"
    - capability: "network_partition"
      target:
        namespace: "media"
        source_app: "nginx-web-server"
        span_names:
          - "ReadMovieInfo"
        target_service: "movie-info-service"
    - capability: "dns_error"
      target:
        app: "nginx-web-server"
        domain_patterns:
          - "movie-id-service"
        namespace: "media"
    - capability: "dns_random"
      target:
        app: "nginx-web-server"
        domain_patterns:
          - "movie-id-service"
        namespace: "media"
    - capability: "network_delay"
      target:
        namespace: "media"
        source_app: "nginx-web-server"
        span_names:
          - "UploadMovieId"
        target_service: "movie-id-service"
    - capability: "network_loss"
      target:
        namespace: "media"
        source_app: "nginx-web-server"
        span_names:
          - "UploadMovieId"
        target_service: "movie-id-service"
    - capability: "network_duplicate"
      target:
        namespace: "media"
        source_app: "nginx-web-server"
        span_names:
          - "UploadMovieId"
        target_service: "movie-id-service"
    - capability: "network_corrupt"
      target:
        namespace: "media"
        source_app: "nginx-web-server"
        span_names:
          - "UploadMovieId"
        target_service: "movie-id-service"
    - capability: "network_bandwidth"
      target:
        namespace: "media"
        source_app: "nginx-web-server"
        span_names:
          - "UploadMovieId"
        target_service: "movie-id-service"
    - capability: "network_partition"
      target:
        namespace: "media"
        source_app: "nginx-web-server"
        span_names:
          - "UploadMovieId"
        target_service: "movie-id-service"
    - capability: "dns_error"
      target:
        app: "nginx-web-server"
        domain_patterns:
          - "text-service"
        namespace: "media"
    - capability: "dns_random"
      target:
        app: "nginx-web-server"
        domain_patterns:
          - "text-service"
        namespace: "media"
    - capability: "network_delay"
      target:
        namespace: "media"
        source_app: "nginx-web-server"
        span_names:
          - "UploadText"
        target_service: "text-service"
    - capability: "network_loss"
      target:
        namespace: "media"
        source_app: "nginx-web-server"
        span_names:
          - "UploadText"
        target_service: "text-service"
    - capability: "network_duplicate"
      target:
        namespace: "media"
        source_app: "nginx-web-server"
        span_names:
          - "UploadText"
        target_service: "text-service"
    - capability: "network_corrupt"
      target:
        namespace: "media"
        source_app: "nginx-web-server"
        span_names:
          - "UploadText"
        target_service: "text-service"
    - capability: "network_bandwidth"
      target:
        namespace: "media"
        source_app: "nginx-web-server"
        span_names:
          - "UploadText"
        target_service: "text-service"
    - capability: "network_partition"
      target:
        namespace: "media"
        source_app: "nginx-web-server"
        span_names:
          - "UploadText"
        target_service: "text-service"
    - capability: "dns_error"
      target:
        app: "nginx-web-server"
        domain_patterns:
          - "unique-id-service"
        namespace: "media"
    - capability: "dns_random"
      target:
        app: "nginx-web-server"
        domain_patterns:
          - "unique-id-service"
        namespace: "media"
    - capability: "network_delay"
      target:
        namespace: "media"
        source_app: "nginx-web-server"
        span_names:
          - "UploadUniqueId"
        target_service: "unique-id-service"
    - capability: "network_loss"
      target:
        namespace: "media"
        source_app: "nginx-web-server"
        span_names:
          - "UploadUniqueId"
        target_service: "unique-id-service"
    - capability: "network_duplicate"
      target:
        namespace: "media"
        source_app: "nginx-web-server"
        span_names:
          - "UploadUniqueId"
        target_service: "unique-id-service"
    - capability: "network_corrupt"
      target:
        namespace: "media"
        source_app: "nginx-web-server"
        span_names:
          - "UploadUniqueId"
        target_service: "unique-id-service"
    - capability: "network_bandwidth"
      target:
        namespace: "media"
        source_app: "nginx-web-server"
        span_names:
          - "UploadUniqueId"
        target_service: "unique-id-service"
    - capability: "network_partition"
      target:
        namespace: "media"
        source_app: "nginx-web-server"
        span_names:
          - "UploadUniqueId"
        target_service: "unique-id-service"
