apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aegis-sso.fullname" . }}-config
  labels:
    {{- include "aegis-sso.labels" . | nindent 4 }}
data:
  config.toml: |
    name = "aegis-sso"
    port = {{ .Values.config.port }}

    [database.mysql]
    host = "{{ .Values.config.database.mysql.host }}"
    port = "{{ .Values.config.database.mysql.port }}"
    user = "{{ .Values.config.database.mysql.user }}"
    password = "{{ .Values.config.database.mysql.password }}"
    db = "{{ .Values.config.database.mysql.db }}"

    [redis]
    host = "{{ .Values.config.redis.host }}"

    [sso]
    issuer = "{{ .Values.config.sso.issuer }}"
    base_url = "{{ .Values.config.sso.baseURL }}"
    jwks_url = "{{ .Values.config.sso.jwksURL }}"
    kid = "{{ .Values.config.sso.kid }}"
    client_id = "{{ .Values.config.sso.clientID }}"
    backend_redirect_uri = "{{ .Values.config.sso.backendRedirectURI }}"
    private_key_path = "{{ .Values.config.sso.privateKeyPath }}"
    seed_secret_dump_path = "{{ .Values.config.sso.seedSecretDumpPath }}"
