apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aegis-sso.fullname" . }}
  labels:
    {{- include "aegis-sso.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "aegis-sso.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        rollout-timestamp: {{ now | quote }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "aegis-sso.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: aegis-sso
          image: {{ include "aegis-sso.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - aegis-sso
            - sso
            - --conf
            - /etc/aegis/config.toml
            - --port
            - {{ .Values.service.port | quote }}
          ports:
            - containerPort: {{ .Values.service.port }}
              name: http
          readinessProbe:
            httpGet:
              path: /.well-known/jwks.json
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /.well-known/jwks.json
              port: http
            initialDelaySeconds: 30
            periodSeconds: 15
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/aegis/config.toml
              subPath: config.toml
            - name: private-key
              mountPath: {{ .Values.config.sso.privateKeyPath }}
              subPath: sso-private.pem
              readOnly: true
            {{- if .Values.persistence.enabled }}
            - name: secrets
              mountPath: {{ .Values.persistence.mountPath }}
            {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "aegis-sso.fullname" . }}-config
        - name: private-key
          secret:
            secretName: {{ include "aegis-sso.secretName" . }}
            items:
              - key: sso-private.pem
                path: sso-private.pem
        {{- if .Values.persistence.enabled }}
        - name: secrets
          persistentVolumeClaim:
            claimName: {{ include "aegis-sso.fullname" . }}-secrets
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
