{{- if .Values.enabled }}
# Redis Service
{{- $envMode := ((.Values.global | default dict).envMode) | default .Values.envMode | default "" -}}
{{- if eq $envMode "staging" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis.fullname" . }}
spec:
  type: NodePort
  selector:
    app: {{ include "redis.fullname" . }}
  ports:
    - port: {{ .Values.service.port | default 6379 }}
      nodePort: {{ .Values.service.nodePort | default 32279 }}
{{- else }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis.fullname" . }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    app: {{ include "redis.fullname" . }}
  ports:
    - port: {{ .Values.service.port | default 6379 }}
{{- end }}
{{- end }}
