{{- if .Values.enabled }}
# redis
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "redis.fullname" . }}
spec:
  serviceName: {{ include "redis.fullname" . }}
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ include "redis.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "redis.fullname" . }}
    spec:
      {{- with .Values.serviceAccount.name }}
      serviceAccountName: {{ . }}
      {{- end }}
      containers:
        - name: redis
          image: {{ include "redis.image" . }}
          imagePullPolicy: "{{ include "redis.imagePullPolicy" . }}"
          ports:
            - containerPort: {{ .Values.service.port | default 6379 }}
          {{- with .Values.extraEnv }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if not .Values.persistence.enabled }}
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          {{- end }}
          volumeMounts:
            - name: redis-data
              mountPath: /data
      {{- if not .Values.persistence.enabled }}
      volumes:
        - name: redis-data
          emptyDir:
            medium: "Memory"
            sizeLimit: "512Mi"
      {{- end }}
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes:
          - {{ .Values.persistence.accessMode }}
        {{- if .Values.persistence.storageClass }}
        storageClassName: {{ .Values.persistence.storageClass | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
  {{- end }}
{{- end }}
